### ISSUE TITLE
Serialize / Deserialize with a list of points ?

### ISSUE THREAD

**Issue by Antho2407** [szimek/signature_pad#102]
Hello, I just would like to know if it would be possible to save the signature, not as an image, but as an array of point ? 

Thank you for your help !

**Comment by szimek** [comment]
Currently to make it use less memory, only up to 4 points are kept in `points` array. After calculating Bezier curve, the oldest point is removed (https://github.com/szimek/signature_pad/blob/master/src/signature_pad.js#L185). This optimization is probably not that necessary and if the line just mentioned was removed, you probably could access all points simply via `signaturePad.points`.

**Comment by Antho2407** [comment]
Ok, thank you for your help !
