### ISSUE TITLE
Signature pad is blank

### ISSUE THREAD

**Issue by dan-rigby32** [szimek/signature_pad#103]
The pad is still working. IsEmpty returns true and false appropriately, but the text is never visible. 

Thanks for your help!

**Comment by szimek** [comment]
I'm not really sure what's the issue here. Could you try to reproduce it e.g. on http://jsfiddle.net?

**Comment by dan-rigby32** [comment]
Sorry. I figured it out. It turned out to be a javascript resizing issue on our end.

Thanks!
