### ISSUE TITLE
iPhone ratio and window.resize problems

### ISSUE THREAD

**Issue by razvanphp** [szimek/signature_pad#104]
Hello,

First of all, thanks for this great library, I implemented it in my application.

The way I'm using it, is to save the data into a hidden input from the database, and redraw it on every page load with fromDataURL.

The first problem is your demo code with `window.onresize = resizeCanvas; resizeCanvas();` it behaves really strange on iPhone 6 Safari, any scroll clears the canvas, ads some white space, it looks few times bigger than it should and I cannot draw anything on the canvas. 

Also this code snippet clears the canvas when the tablet is rotated, something really unexpected for all users. Having to redraw it myself from the data I have seems really hacky.

Anyway, I removed the code snippet and it seems to work ok, but the problem is, the same image saved on desktop, looks smaller on iPhone.

Any ideas? Or do you need more debug information?

Thanks!

**Comment by jnylund** [comment]
I have the same issue, did you figure it out?

**Comment by travelingwilly** [comment]
Anyone figure this out...
I opened a separate window (window.open) so this would kind of self in-closed , But Everything is Small . And when I Close the Tab with the signature it seems to corrupt the original page
 
Any Idea

**Comment by ohdotoh** [comment]
I don't know if this is related, but when the signature pad scrolls even partly off screen and then scrolls back into view on an iPad mini or iPad Air 1, it is clearing the canvas. Doesn't do it on my iPhone 6. All on iOS 9.2.1, all using safari and I'm using the latest version of signature pad and still seeing this effect.

**Comment by Shadoh702** [comment]
I found that on android the scrollbar at the top appearing and disappearing calls a resize event, which seems to blank the canvas

**Comment by shawe** [comment]
Maybe this helps: https://github.com/szimek/signature_pad/issues/33#issuecomment-298242020

**Comment by UziTech** [comment]
closing as stale
