### ISSUE TITLE
FromDataURL reducing image size

### ISSUE THREAD

**Issue by rmmackay** [szimek/signature_pad#105]
Hello,

If I save a signature to a database using the toDataURL() function, and then I load that string back into the canvas using the fromDataURL() function, then the resulting image appears in the canvas but is noticeably smaller than the original image. 

To test, draw in the canvas along all 4 edges. Save and then reload. You will see that the right-side and bottom-sides of the image now have space between the image and the border because the image was made slightly smaller.

Since I re-save images over and over for a good reason, they keep shrinking with each save!!!

Help!

**Comment by razvanphp** [comment]
Hmm, this happens only on Retina Display, I just reproduced it. You must deal with it yourself somehow, the creator said already multiple times that the library should not take care of this.

**Comment by razvanphp** [comment]
It seems that this solves the problem:
http://jsfiddle.net/4JH75/19/

**Comment by Mottoweb** [comment]
I am experiencing the same issue with device pixel ratio 1. Any help?

**Comment by durasj** [comment]
Related to https://github.com/szimek/signature_pad/issues/153

**Comment by demo-igor** [comment]
To make the same image size you can add options
`signaturePad.fromDataURL(data, {width: 100, height: 100})`
width, height should be the same as canvas size
More details:
https://github.com/szimek/signature_pad/blob/master/src/signature_pad.ts

**Comment by iDevIt007** [comment]
Thanks to your last answer, we can now fix the problem with fromDataURL scaling issues, should close this issue.

**Comment by pavankumar0425** [comment]
Thanks a lot for the response "demo-igor"
