### ISSUE TITLE
Signature_pad doesn't work properly when is inside ScrollView

### ISSUE THREAD

**Issue by joanebrown** [szimek/signature_pad#109]
Hi,

I tried your plugin inside a long ScrollView, but the scroll doesn´t work, it is blocked.

Device: Samsumg Note 3.

Thanks for your amazing work!

**Comment by szimek** [comment]
Unfortunately, I'm not sure if it's possible to fix it. How a browser will know if you want to scroll or draw when you swipe over a canvas? What I usually did was to have a link/button in a form that opened a new non-scrollable view with signature pad and some buttons (clear/save/cancel).

**Comment by szimek** [comment]
If it's still a problem, please reopen this ticket.
