### ISSUE TITLE
Using sign data in form

### ISSUE THREAD

**Issue by rjong** [szimek/signature_pad#110]
Hi,

For a website, I use Laravel. I want to integrate your signature pad in it, so that I can use the signing pas in a form.

How can I get the signature in Laravel like "Input::get('sign')"?

Thanks.

**Comment by szimek** [comment]
I've never used Laravel, but it should be enough to make an ajax call to the server with a value returned from the `signaturePad. toDataURL()` call or assign this value to a hidden input field in a form and submit this form.

**Comment by rjong** [comment]
Ah. Do you have example code for assigning the value to an input field?

**Comment by szimek** [comment]
Haven't tried it, but it should be rather simple. Assuming that you have an element `<input type="hidden" />` you can do something like this:

```
var value = signaturePad.toDataURL();
input.value = value; // if you're not using jQuery
input.val(value); // if you're using jQuery

**Comment by charlesfries** [comment]
Late to this, but a hack-ey workaround I did was use the onEnd method to get signaturePad.toDataURL(), and then I used that string as a the value of an input in my form.

**Comment by szimek** [comment]
You could listen to `submit` event on form element, which should be triggered when user clicks the submit button, and assign result of `signaturePad.toDataURL()` to a hidden field there. Please reopen this issue if it's still a problem.
