### ISSUE TITLE
Making signature-pad stay put?

### ISSUE THREAD

**Issue by lsces** [szimek/signature_pad#111]
Am I missing something? I know I will need to create a pop-up on mobile devices to enter the signature in, but how do I stop it sliding around ...
AH it's dependent on the browser being used. Seems I can't use 'Dolphin' and have to switch back to the generic browser and all is good ... 
SO the question becomes what browsers work best on android when trying to use signature_pad?

**Comment by szimek** [comment]
I have never used Dolphin browser before, but if you create a popup that takes up the whole screen then it shouldn't be scrollable... If it's still a problem, please reopen it. Some demo on jsfiddle, jsbin, etc. that shows this issue together with a version of Dolphin browser you're using would be really helpful.
