### ISSUE TITLE
fromDataUrl failing on FireFox

### ISSUE THREAD

**Issue by WattyRev** [szimek/signature_pad#112]
fromDataUrl works fine in Chrome, but when I try it on OSX FireFox, it is not working. The image.onerror event fires, and the image never appears in the canvas. Happened with both PNG and JPG images.

Error:
`"SignaturePad fromDtaURL" error { target: <img>, isTrusted: true, currentTarget: <img>, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1436549330124359, originalTarget: <img>, explicitOriginalTarget: <img>, NONE: 0 }`

**Comment by WattyRev** [comment]
Commenting out line 65 in the fromDataUrl function got everything working for me.

    SignaturePad.prototype.fromDataURL = function (dataUrl) {
		var self = this,
			image = new Image(),
			width = this._canvas.width,
			height = this._canvas.height;

		//image.crossOrigin = '';

		this._reset();
		image.onload = function () {
			self._ctx.drawImage(image, 0, 0, width, height);
		};
		image.onerror = function(e) {
			console.log("SignaturePad fromDtaURL", e);
		};
		image.src = dataUrl;
		this._isEmpty = false;
	};

**Comment by szimek** [comment]
@WattyRev Do you still have this issue with the latest version of the library and Firefox? I've just tried the demo page in Firefox 42 and didn't have this issue.

**Comment by WattyRev** [comment]
Sorry, can't say. I don't have access to that code base any more. New job.

**Comment by szimek** [comment]
Thanks for the reply. I'll close it then.
