### ISSUE TITLE
Type name option and draw 

### ISSUE THREAD

**Issue by zebamba** [szimek/signature_pad#114]
This is a question for future feature.

Would you consider to add option to type the name and draw?

ex http://thomasjbradley.ca/lab/signature-pad/accept/

**Comment by szimek** [comment]
Not sure really. It looks like it should be [rather simple](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_text) though and one could use e.g this font: [Give You Glory](https://www.google.com/fonts/specimen/Give+You+Glory).

It should be easy to add it yourself - have 2 canvas elements and you can draw a text on the first one using `context.fillText` and use `SignaturePad` on the second one.
