### ISSUE TITLE
Issue in jelly bean

### ISSUE THREAD

**Issue by padmakurup123** [szimek/signature_pad#117]
Hi,

I am facing an issue with the signature pad in the android Jelly Bean version of my application. nothing can be drawn on the signature pad, only ambiguous lines appear. 

There is a known issue with Jelly Bean that, if an overflow attribute is present in any of the parent HTML then the signature pad does not behave as expected. I tested this scenario by removing all other HTML except for the canvas tag. The signature pad worked fine then. But I cannot confirm anything based on that.

Is there any fix available for the issue?? Any help would be appreciated.

Thanks in advance.

**Comment by aflames** [comment]
I have the same problem. Have you fixed tis problem?

**Comment by padmakurup123** [comment]
Hi,
We fixed the issue by using crosswalk in our application. Another fix would be switch to the coordinates canvas(an older version of canvas that uses coordinates for drawing) in case of jelly bean device.

Hope this helps!

**Comment by silentFred** [comment]
Hi @padmakurup123 would you mind elaborating on your answer? I'm also stuck with the same issue on a hybrid app mostly used in web.

**Comment by ChrisSmeets** [comment]
Most likely it has something to do with triggering both mouse and touch events in older versions of Android. At least in my case. Perhaps, a framework like crosswalk solves the most known/common problems, but for me shooting a mosquito with a tank is a little bit overkill and crosswalk is not maintained anymore.

I ran a test with an additional condition testing for touch support in _handleMouseEvents. 

```
if (!('ontouchstart' in document.documentElement)) {
  this._canvas.addEventListener('mousedown', this._handleMouseDown);
  this._canvas.addEventListener('mousemove', this._handleMouseMove);
  document.addEventListener('mouseup', this._handleMouseUp);
}
```

The behaviour looks good for me now, even with scrolling. So, hopefully, this solution can help others as well.
