### ISSUE TITLE
when trying to dot the proverbial i the dots almost always result in two dots

### ISSUE THREAD

**Issue by matthiasg** [szimek/signature_pad#120]
it seems the library always tries to create two points when trying to make a dot... 

![tempfileforshare_2015-09-21-11-27-53](https://cloud.githubusercontent.com/assets/231889/9988809/fa319b0c-6053-11e5-8de1-12f7ababe617.jpg)

Device: Samsung Galaxy Note 4 (5.1.1)

**Comment by szimek** [comment]
Thanks for reporting it. Something is broken with the code that handles touch events, as I can reproduce it on iOS, but can't on desktop with a mouse. I won't have much time to look into it this week, so unless somebody comes up with a fix sooner, I'll try to fix it next week.

**Comment by mnkpailsorathiya** [comment]
required only Web


On Mon, Sep 21, 2015 at 2:41 AM, Szymon Nowak <notifications@github.com>
wrote:

> Thanks for reporting it. Something is broken with the code that handles
> touch events, as I can reproduce it on iOS, but can't on desktop with a
> mouse. I won't have much time to look into it this week, so unless somebody
> comes up with a fix sooner, I'll try to fix it next week.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/szimek/signature_pad/issues/120#issuecomment-141925631>
> .
>



-- 



*imperious.in <http://imperious.in>*

*MN Kapil Sorathiya*

*Mo:- 74055 33198*
:mnkapilsorathiya

**Comment by mnkpailsorathiya** [comment]
not ios

On Mon, Sep 21, 2015 at 2:44 AM, kapil sorathiya <mnkapilsorathiya@gmail.com
> wrote:

> required only Web
>
>
> On Mon, Sep 21, 2015 at 2:41 AM, Szymon Nowak <notifications@github.com>
> wrote:
>
>> Thanks for reporting it. Something is broken with the code that handles
>> touch events, as I can reproduce it on iOS, but can't on desktop with a
>> mouse. I won't have much time to look into it this week, so unless somebody
>> comes up with a fix sooner, I'll try to fix it next week.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/szimek/signature_pad/issues/120#issuecomment-141925631>
>> .
>>
>
>
>
> --
>
>
>
> *imperious.in <http://imperious.in>*
>
> *MN Kapil Sorathiya*
>
> *Mo:- 74055 33198*
> :mnkapilsorathiya
>



-- 



*imperious.in <http://imperious.in>*

*MN Kapil Sorathiya*

*Mo:- 74055 33198*
:mnkapilsorathiya

**Comment by PerfectPixel** [comment]
The cause of this problem is that mobile devices seem to fire a touch start and touch end event followed by a mouse down and mouse up event. This behavior is probably there to simulate mouse events while just tapping. In this case it is messing things up.
