### ISSUE TITLE
chrome iphone 5&6 emulation doesnt work

### ISSUE THREAD

**Issue by jnylund** [szimek/signature_pad#121]
Hi, I have the pad working fine on chrome and fine on regular iphones, but iphone emulation on chrome doesn't allow usage of the pad  . When I turn on chrome iphone 5 or 6 emulation it doesn't work, if I double click I get dots,  but there is no normal click and draw behavior I see everywhere else.

Any ideas, would be nice to be able to test on chrome.

**Comment by szimek** [comment]
Just tried it in Chrome 47 and it works for me. Please reopen this ticket if it's still a problem.
