### ISSUE TITLE
Erase?

### ISSUE THREAD

**Issue by alexiskattan** [szimek/signature_pad#122]
Is there any way to erase part of a line?  I'm trying to make it into a simple drawing program.

**Comment by szimek** [comment]
It depends on what you mean by "erase". You can paint over it, which would effectively erase it. Though, if you're talking about "undo" feature, then it's not possible at the moment. It only keeps the last few points in the memory and uses them to draw the next line.

**Comment by alexiskattan** [comment]
OK thanks for the help

**Comment by szimek** [comment]
I'm closing it, but if you got any more questions or issues, feel free to reopen it.

**Comment by giuliogatto** [comment]
Hi, I'd like to erase some previously painted lines, the lines are placed over a transparent background.. how to do that?
Cheers

**Comment by giuliogatto** [comment]
(I have tried to change signaturePad.penColor = "transparent" at runtime, but it doesn't erase)

**Comment by szimek** [comment]
@giuliogatto Again, it depends on what you mean by "erase". It's possible now to do "undo" feature, by using `#toData` and `#fromData` methods. Let me know, if that's what you want.

**Comment by giuliogatto** [comment]
Hi Szimek, thank you for the quick reply!!
Well what I'd like to implement is an 'eraser' feature: something that you can use to partially delete lines that are already been painted.. I hope I am explaining myself clearly.
For example: first the user would trace an 'X' on the screen, the he'd decide that he wants to delete/erase one of the 2 lines of the 'X'. To do so, he'd click onto an 'eraser' button. When the button is clicked the pen doesn't draw lines anymore, but remove the lines/pixels that that clicked.

**Comment by szimek** [comment]
I'm not sure if it's possible if you have a transparent background, though I'm not saying it's not. If the background was opaque, then it should be rather simple - just set pen color to be the same as background color and use it to draw over previously drawn lines.

**Comment by giuliogatto** [comment]
Thank you, 'source-out' seems to be what I am looking for.. is there a way to implement it with your library?
Cheers

**Comment by giuliogatto** [comment]
OK, done it by adding a public method like this:

`// Public methods
SignaturePad.prototype.eraser = function () {
  var ctx = this._ctx;
  ctx.globalCompositeOperation = 'destination-out'
  console.log('eraser');
}`

**Comment by szimek** [comment]
@giuliogatto Thanks! I've added links to 2 demos to README for future reference, one based on your code:
* erase feature: https://jsfiddle.net/szimek/jq9cyzuc/
* undo feature: https://jsfiddle.net/szimek/osenxvjc/
