### ISSUE TITLE
Can only sign when resized

### ISSUE THREAD

**Issue by Geoffry304** [szimek/signature_pad#125]
Hello,

First of all I wanna thank you for this library, but I have a problem.

When I want to sign in the field, i first need to resize my window before I can sign it.

Do you know what the problem is? My Sign field pop's open when pushing a button. My code is the same as the source code.

Regards
Geoffry

**Comment by coryasilva** [comment]
I ran into this too, most likely you have css transitions right?  You can listen for the transitionend event.  I am using this in the Angular framework and I decided it was just easier to $watch the element.width() for changes.
````js
                function whichTransitionEvent() {
                    var ele = document.createElement('div');
                    var transitions = {
                        'transition': 'transitionend',
                        'OTransition': 'oTransitionEnd',
                        'MozTransition': 'transitionend',
                        'WebkitTransition': 'webkitTransitionEnd'
                    };
                    for (var t in transitions) {
                        if (ele.style[t] !== undefined) {
                            return transitions[t];
                        }
                    }
                }
                var transitionEvent = whichTransitionEvent();

                element.on(transitionEvent, resizeSignaturePad);
````

**Comment by Geoffry304** [comment]
Hello, I just used the example from the library so I didn't change anything. I don't understand what you mean.

var wrapper = document.getElementById("signature-pad"),
            clearButton = wrapper.querySelector("[data-action=clear]"),
            saveButton = wrapper.querySelector("[data-action=save]"),
            closeButton =wrapper.querySelector("[data-action=close]"),
            canvas = wrapper.querySelector("canvas"),
            signaturePad;
// Adjust canvas coordinate space taking into account pixel ratio,
// to make it look crisp on mobile devices.
// This also causes canvas to be cleared.
function resizeCanvas() {
    // When zoomed out to less than 100%, for some very strange reason,
    // some browsers report devicePixelRatio as less than 1
    // and only part of the canvas is cleared then.
    var ratio =  Math.max(window.devicePixelRatio || 1, 1);
    canvas.width = canvas.offsetWidth * ratio;
    canvas.height = canvas.offsetHeight * ratio;
    canvas.getContext("2d").scale(ratio, ratio);
}

window.onresize = resizeCanvas;
resizeCanvas();

**Comment by coryasilva** [comment]
Oh I see; the I have *not* experienced that issue.  The CSS transition problem that I was speaking of was specifically found while putting the signature pad in a bootstrap modal.  Does the demo work for you?

**Comment by szimek** [comment]
Please reopen this ticket if it's still a problem.

**Comment by rodrigovallades** [comment]
Hi, I'm having the exact problema described by the original poster.

If I open the signature pad inside a bootstrap modal, it doesn't work until I resize the window. It's driving me insane, lol.

**Comment by coryasilva** [comment]
I am still confident that the problem you guys are experiencing is because of css transitions.  As a test try initialing the signature in a timeout of 1 second (by then the css animation should have played through and the pad should get the correct size)

**Comment by farr433** [comment]
Yeah @coryasilva is correct... I have my signature box inside of a modal which sounds like the same setup as you. When the button is clicked it has an onclick property that fires the initSignature function. You may be using the data-target and data-toggle to call your modal but use an onclick function like this and then you can add the re-size as it pops up. If you inspect your code as it is now you will probably see that your canvas has a size of 0.

**Button**
`<button class="btn btn-info btn-block" onclick="initSignature()">
                                        Add Performance Report
                                    </button>`

**Javascript**
`function initSignature()
{
                $("#writeupModal").modal("show");
                window.setTimeout(resizeCanvas, 1000);
}`
