### ISSUE TITLE
Any plans to bump the NPM version to 1.5

### ISSUE THREAD

**Issue by jusopi** [szimek/signature_pad#126]
I see that you have your release versions at 1.5.* however the NPM version is still on 1.4.0.

**Comment by szimek** [comment]
Thanks for noticing! I totally forgot that it doesn't happen automatically. I'll need to add release script to handle all this stuff... Anyway, I just published 1.5.1 to npm.

**Comment by jusopi** [comment]
Thanks!  And thanks for the awesome API.  I downloaded and had a working implementation with Angular in less than 30 minutes.
