### ISSUE TITLE
Is there a setup to achieve smooth curves ?

### ISSUE THREAD

**Issue by bartes** [szimek/signature_pad#127]
Something like Bezier Curves in that example:
http://www.jqueryscript.net/demo/Smooth-Signature-Pad-Plugin-with-jQuery-Html5-Canvas/examples/

**Comment by szimek** [comment]
Not at the moment. 

This would most likely require recalculating control points for already drawn curves and redrawing them again which would cause them to  flicker. It might also be possible to take into account more points when calculating new control points, but that would on the other hand increase the delay when drawing curves.

**Comment by bartes** [comment]
Thanks for the quick reply.
I managed to do that with onBegin and onEnd callbacks but I lacked some functionalities in the lib which are currently here
https://github.com/szimek/signature_pad/compare/master...bartes:master
