### ISSUE TITLE
dotSize property only works on click/tap

### ISSUE THREAD

**Issue by hugohil** [szimek/signature_pad#128]
Hey there.
First of all, thanks for the awesome work !

I just noticed a strange behavior with the `dotSize` property. In the following gif, I set it to 10, and as you can see, on a click event, it creates a dot with the correct radius, but when I drag the cursor around, radius is still the default one.

![signaturepad-dotsize](https://cloud.githubusercontent.com/assets/4352715/10449826/61618ece-7196-11e5-81f5-340a53802519.gif)

**Comment by szimek** [comment]
For line width you got separate settings: `minWidth` and `maxWidth`.

**Comment by hugohil** [comment]
My bad, I should have RTFM ... -_-
Thank you !
