### ISSUE TITLE
Dynamic offset depending on mouse position

### ISSUE THREAD

**Issue by skr0tm** [szimek/signature_pad#131]
I am using parts of your demo css and your demo app.js. 
The further the mouse is on the right side of the canvas, the bigger the offset between actual mouse position and painted dot get. Tried it in most recent Firefox and Chrome.

**Comment by szimek** [comment]
@skr0tm Does it happen for you in the demo as well?

**Comment by skr0tm** [comment]
No, just in my project. Modified the css of your demo to fit. But even with the standard settings the issue maintains. Any ideas?

**Comment by szimek** [comment]
Any chances you could post it somewhere (jsfiddle, jsbin or something similar)?

**Comment by skr0tm** [comment]
Went away for the weekend, but gladly on Monday.

**Comment by skr0tm** [comment]
The wrappers of the app,js are returning null. HTML is a 1:1 copy of your demo. 
"Uncaught TypeError: Cannot read property 'querySelector' of null". 
That seems only to affect the clearing and saving. 

The offset is caused by the 100% width, or any width given to the canvas.

**Comment by szimek** [comment]
@skr0tm Could you post your code somewhere anyway? It might help find out what's wrong either with the library or your code.

**Comment by lilo346** [comment]
Seems I'm having the same problem

**Comment by szimek** [comment]
I'm closing it. If it's still an issue, please reopen it and try provide some code e.g. on http://jsfiddle.net that reproduces it.

**Comment by owalerys** [comment]
See my jsfiddle for the reproduced issue: [https://jsfiddle.net/yy7Lc74y/](https://jsfiddle.net/yy7Lc74y/)

**Comment by owalerys** [comment]
Here's a non-Vuejs version: [https://jsfiddle.net/0w7eq5sn/](https://jsfiddle.net/0w7eq5sn/)

**Comment by GaetanoH** [comment]
I'm also having the same problem on Mac and iPad

**Comment by capyash** [comment]
Don't set width and height via css for a canvas. Seems to break the way signature pad works.

**Comment by chandrarishabh** [comment]
I am having the same issue. It happens only when we set width and height via CSS. Any other way to resize the canvas?

**Comment by senyaak** [comment]
If someone have this issue - check canvas scaling
