### ISSUE TITLE
feature request: using the pen to highlight parts of the canvas

### ISSUE THREAD

**Issue by bedros** [szimek/signature_pad#132]
first, thanks for a great and easy to use signature util.

I'm trying to use it to annotate a text image; writing on the image, signing it, which works fine, but I tried to highlight a line of text and it did not work, I tried to change the color transparency of penColor and I got bunch of circular spray patterns.

Thanks,

**Comment by szimek** [comment]
The problem is that because there's no native way of drawing curves with variable width, the lines are actually drawn using circles. The circles sometimes overlap, which is not visible when you use an opaque color, but is apparent when you use non-opaque one. I'll have to check if it's possible either to avoid this overlapping or if there's some blend mode that would not add up transparency values...

**Comment by bedros** [comment]
Thanks for quick reply, I found some other signature apps that try to make small lines instead of points, like this one https://www.youtube.com/watch?v=8KV1o9hPF5E using swift for iOS

**Comment by szimek** [comment]
Thanks, but I don't see anywhere that he shows how to draw a curve with variable width. Anyway, this library uses circles and it's probably not that easy to do make sure that nothing is overlapping, so unless there's some setting on canvas element that allows transparency values not to add up, it's going to be hard to fix it. Though I'd really like to make it work...

**Comment by bedros** [comment]
thanks, that's fine, I started to learn javascript, and wondering what's the purpose of first line of app.js which is "var wrapper = ... multiple values"

**Comment by szimek** [comment]
[This part](https://github.com/szimek/signature_pad/blob/master/example/js/app.js#L1-L5) just defines some variables used later in the script - signature pad wrapper element, clear and save buttons etc.

**Comment by UziTech** [comment]
closing this as stale. If this is still needed we can reopen it.
