### ISSUE TITLE
Line and Text inside canvas

### ISSUE THREAD

**Issue by Bambicruz** [szimek/signature_pad#136]
Is it possible to add a line inside the canvas with some text under it (preferable a dynamic php text)?

Similar to this : http://core0.staticworld.net/images/article/2013/04/echosign-signing-100033776-large.jpg

Thank you!!

**Comment by BoKu** [comment]
You can add text to a canvas using something like this

    var canvas = document.getElementById("myCanvas");
    var ctx = canvas.getContext("2d");
    ctx.font = "30px Arial";
    ctx.fillText("Hello World",10,50);

and lines can be drawn on a canvas using code like this

    var c=document.getElementById("myCanvas");
    var ctx=c.getContext("2d");
    ctx.beginPath();
    ctx.moveTo(0,0);
    ctx.lineTo(300,150);
    ctx.stroke();

**Comment by Bambicruz** [comment]
Thank you, where / which files should I insert the code above in?

**Comment by szimek** [comment]
@Bambicruz the first snippet posted by @BoKu should work. You can create two canvases - one for signature pad and one for drawing text and add some button to switch between them.

I'm closing it, as it's not really an issue. If you're still having issues with the code, please ask on e.g. http://stackoverflow.com.
