### ISSUE TITLE
when I useing Jquery mobile JS, signature can't work

### ISSUE THREAD

**Issue by panda112** [szimek/signature_pad#138]
I met a issue, when I useing Jquery mobile JS, signature can't work, How I can fix it?

**Comment by wulfsolter** [comment]
I use jQuery Mobile fine with signature_pad. It's not jQuery Mobile :p

**Comment by panda112** [comment]
signature is conflict with jquery mobile js, how to fix it?

**Comment by szimek** [comment]
@panda112 Could you prepare a demo that shows this issue using e.g. https://jsfiddle.net or a similar service?

**Comment by panda112** [comment]
I'm sorry, that is my mistake, I'm include the app.js,signature_pad.js in my sign.html, when jquery mobile load my html, the app.js,signature_pad.js haven't excuted.
