### ISSUE TITLE
Initial canvas width/height is 0

### ISSUE THREAD

**Issue by Mekimuraosu** [szimek/signature_pad#139]
Hey Szimek. 
Great work on the library.
I do have an issue though.
I got the NPM (version 1.5 I believe it was), and started testing with the source code from the demo.

wrapper and this part:

  function resizeCanvas() {
        // When zoomed out to less than 100%, for some very strange reason,
        // some browsers report devicePixelRatio as less than 1
        // and only part of the canvas is cleared then.
        var ratio = Math.max(window.devicePixelRatio || 1, 1);
        canvas.width = canvas.offsetWidth \* ratio;
        canvas.height = canvas.offsetHeight \* ratio;
        canvas.getContext("2d").scale(ratio, ratio);
    }

```
window.onresize = resizeCanvas;
resizeCanvas();
```

I've also tried with the similar but updated code in the "Usage" section on this page.
And in both cases the canvas width and height is both set to 0, even if it visually is displayed alot bigger, and I am unable to draw on the canvas, but I can save it if I've tried to draw, even with no result.

I've tried testing the values, and it seems the two "canvas.offsetXX" values is zero on the initial load even if trying to call resizeCanvas() manually.

However, if I adjust the window size manually or even start zooming, then the canvas works perfectly, and it is updated with values dynamically as I adjust the window.

Clearly I must have overlooked something?

So far I've only tested it on a laptop using Chrome Version. 47.0.2526.80 m

**Comment by Mekimuraosu** [comment]
After some more testing, I can see that it's due to the fact that my resizeCanvas calls is being called while the canvas is hidden with `display:none` (or rather the div that it is all inside, is display:none, the canvas itself is just showing with height/width values of 0 as mentioned)
This also goes for resizing the window manually.

But the dev tools in Chrome still shows shows the canvas when it is display none, so should it not be possible to set the height and width, even though it's not currently displayed?

**Comment by szimek** [comment]
Please reopen this issue if it's still a problem.

**Comment by jealvin** [comment]
same here

**Comment by Chintan-Techcronus** [comment]
@szimek : Have you got any solution for above matter signature pad not working in pop up unless window is resized. We are using Signature Pad v4.1.4 with app.js file available in project.

**Comment by szimek** [comment]
@Chintan-Techcronus Please ensure that the canvas element has non-zero width and height before you initialize SignaturePad.
