### ISSUE TITLE
Multiple Signature boxes on the same page.

### ISSUE THREAD

**Issue by nmakwana** [szimek/signature_pad#141]
I want to add more than 1 signature box in to a single HTML page.

So how can I accomplish this?

I will have 2 signature pad divs with ID 15685 and 14962. And I don't want to write following line of code 2 times.

var wrapper = document.getElementById("signature-pad"),

Like:

var wrapper = document.getElementById("signature-pad_15685"),
and 
var wrapper = document.getElementById("signature-pad_14962"),

But I want to pass value of ID dynamically into app.js because value of ID comes from the database and app.js use that ID value to refer 2 signature box DIVS.

Example:
var wrapper = document.getElementById("signature-pad_"+ ID),

Your help to get this job done would be highly appreciated.

**Comment by szimek** [comment]
You can put these IDs in an array and map them to signature pad elements.

**Comment by nmakwana** [comment]
Can you please have me an example (source code) to do this?

**Comment by nmakwana** [comment]
Can you please have me an example (source code) to do this?

**Comment by szimek** [comment]
```javascript
[14962,15685].map(function (id) {
  var wrapper = document.getElementById("signature-pad_" + id);
  ...
});
```
This way you don't have to repeat the code for each id.

**Comment by nmakwana** [comment]
But as you know that line:
var wrapper = document.getElementById("signature-pad"),

is written in the app.js file.

So how to pass or how to use values 14962,15685 in the app.js so that we can write the code like:

 [14962,15685].map(function (id) {
  var wrapper = document.getElementById("signature-pad_" + id);
  ...
});

**Comment by nmakwana** [comment]
I meant to say how to pass values of 14962,15685 from asp file to .js file because 14962,15685 comes from database.

**Comment by szimek** [comment]
I have no idea. I've never written anything in ASP.

**Comment by szimek** [comment]
Could you ask this question at http://stackoverflow.com? There might be some ASP users that can help you. As far as I understand it, it's not really related to this library.

**Comment by nmakwana** [comment]
Thanks for your help so far.

I tried editing code of app.js file as per my requirements and it worked well.
