### ISSUE TITLE
Scaling a signature_pad to draw closer- Question (Not an issue)

### ISSUE THREAD

**Issue by ajohnsonRH** [szimek/signature_pad#142]
We are trying to scale the signature pad to allow for a user who cannot see very well, but still keep the work they have done on a signature pad. We do not want to clear the canvas, so we cannot resize it. My question is, how do we scale it so that the pencil will draw within the zoomed window?

**Comment by rookiec14** [comment]
+1

**Comment by szimek** [comment]
There's a PR and a demo that would allow one to do it: https://github.com/szimek/signature_pad/pull/100#issuecomment-168779144. Both canvases are 300x300, but have different CSS sizes. Unfortunately, there's an issue (shown in the demo) when one tries to copy data from one scaled canvas to another.

**Comment by UziTech** [comment]
closing as stale
