### ISSUE TITLE
Is it compatible with Android? I really need this plugin :)

### ISSUE THREAD

**Issue by JesusMurF** [szimek/signature_pad#143]
Is it compatible with Android? I really need this plugin :)

**Comment by wulfsolter** [comment]
Works with every browser that supports canvas, so yes http://caniuse.com/#feat=canvas

**Comment by szimek** [comment]
It's compatible with Android browser on Android 3.x and up. On devices with Android 2.3 and earlier you need to provide your own `HTMLCanvasElement#toDataURL` implementation. There are some examples how to do it, e.g. [here](http://jimdoescode.blogspot.co.uk/2011/11/trials-and-tribulations-with-html5.html).
