### ISSUE TITLE
onchange save signature to hidden field

### ISSUE THREAD

**Issue by osoz** [szimek/signature_pad#144]
First of all, thanks for making this plugin, it works really well! We have it working on one website, and are really happy with it. We want to implement it in an other website, but have a question about the way we want to implement it.

If it possible we would like to make it work without the save button. The signature field is part of a bigger form, with its own save button. We want the signature field data to post along the rest of the input fields. The way we had this in mind was to use some sort of onChange function. So that if the signature fields changes, it would save its data to an hidden input field.

We thought we would have to use "signaturePad.toDataURL()" and "onEnd", but couldn't get it working together. We were hoping you could help us. 

Thanks in advance!

**Comment by szimek** [comment]
If possible, one simple way would be to handle the whole submit via JS. Then you'd only need to read the value once, when the save button for the whole form is clicked. 

It should probably also work with `onEnd` function - what issues you had exactly?

**Comment by osoz** [comment]
Thanks for the fast reply!

We could submit via JS indeed, but if possible we would like to not to. But it is definitely an option.

My issue with the `onEnd` is that I don't exacty know how to use it in this case. Could you maybe provide an example?

**Comment by szimek** [comment]
Here's an example of using `onEnd`: https://jsfiddle.net/szimek/taunyyf5. 

You could also try to add `onSubmit` function to the form or listen for its `submit` event and just assign signature pad data to hidden input there.

**Comment by osoz** [comment]
Thanks for the example, I got it working! 
And thanks for your fast reply, really appreciated!
