### ISSUE TITLE
Difference between Pen and Pad draw line

### ISSUE THREAD

**Issue by HardikPatel88** [szimek/signature_pad#145]
Hey Szimek. 

Great work on the library. 

I have one small issue when i am trying to draw signature on pad at that time there is a difference between pen and pad draw line. 
Please help me i have already spend 5 hours to solve this issue.

Send me feedback in : hardik.patel@imobdevtech.com 

Thanks 
Hardik Patel

**Comment by szimek** [comment]
Please reopen this issue if it's still a problem.
