### ISSUE TITLE
not able to write unless i resize the window.

### ISSUE THREAD

**Issue by ralanyo** [szimek/signature_pad#146]
I have this installed but cannot write on the canvas unless i resize the window. Then it let me write.

**Comment by szimek** [comment]
Does the [demo](http://szimek.github.io/signature_pad/) work for you? If it does, can paste your code to something like jsfiddle or jsbin?

**Comment by ralanyo** [comment]
Thank for the response. I actually got it working now. For some reason it wouldn't work if i was performing a hide/show on a div. So i just used it's own route and page and it works. The only thing i'm having trouble now with is the css to make the box height shorter. When i change it, it offesets the writing marks. I have the canvas at the end of our form page instead of using a modal like your example. Is there a better way to make the box 200px?

**Comment by ralanyo** [comment]
Okay, never mind on the css. I have it figured out. Made the m-signature-pad relative and the inner divs absolute. Thank

**Comment by dperezq** [comment]
I have the same problem, this happens when I try to hide/show the div clicking on a button. When I resize the windows, the signaturepad works. This is because I want to implement the div inside a site clicking on a button
