### ISSUE TITLE
error on image type jpeg

### ISSUE THREAD

**Issue by talha-malik** [szimek/signature_pad#147]
Hi,
when I change image type to jpeg, it gives me black image. How can it be fixed?

Thanks

**Comment by szimek** [comment]
@talha-malik Check description for [backgroundColor](https://github.com/szimek/signature_pad#options) option.

**Comment by talha-malik** [comment]
@szimek thanks. yes I checked it, it is still not working on my web site but when I use the example code it works fine. I am still wondering what is wrong in when I use it for my site, it keeps on creating black image.

**Comment by talha-malik** [comment]
I changed canvas color to black and penColor to white for the time being but backgroundColor property is not working.
here is my code
`signaturePad = new SignaturePad(canvas,{
	backgroundColor:"rgba(255,255,255,0)",
	penColor:"rgb(255,255,255 )"
});`

**Comment by talha-malik** [comment]
I have closed it but if you can guide me about the problem then please.

**Comment by szimek** [comment]
Does it work if you set background color to just `rgb(255,255,255)`?

**Comment by talha-malik** [comment]
no it does not work. yes it should give white text on white background but it gives black on white.

**Comment by szimek** [comment]
Can you try:
```javascript
const sig = new SignaturePad(canvas, { 
  backgroundColor: 'rgb(255, 255, 255)', 
  penColor: 'rgb(0, 0, 0)',
});
window.open(sig.toDataURL("image/jpeg"));
```
I've just tried it on the demo page and it works fine.

**Comment by talha-malik** [comment]
Did not work. penColor works fine but not backgroundColor. Can you tell me if there are any dependencies?

**Comment by talha-malik** [comment]
I can share my whole code with you if you want to see.

**Comment by szimek** [comment]
Here's a demo that generates jpeg image with white background and black pen color and opens it in a new window when you stop drawing: https://jsfiddle.net/szimek/20z8zbuh. Let me know if it works for you.

**Comment by talha-malik** [comment]
No it did not work. I get this
data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD/wAARCADIAjkDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD8qqKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooA//Z

**Comment by talha-malik** [comment]
Just for the note it works fine if I use this on the example code with this library. It is just my application. I also logged in values of background color it gives what are given in the options array. But for some reason it ignores it.

**Comment by szimek** [comment]
Can you reproduce your issue in jsfiddle, jsbin, or any other similar service, so that it's easy for me to run?

**Comment by talha-malik** [comment]
I have sent an email to szimek@gmail.com with my code. I am not able to reporduce at jsfiddle. Please check
Thanks

**Comment by pieterMZ** [comment]
I have the same problem. @talha-malik  have you managed to resolve the issue?

**Comment by szimek** [comment]
@pieterMZ Can you reproduce this issue and post it on jsfiddle, jsbin etc.?

**Comment by talha-malik** [comment]
@pieterMZ in my case it was actually saving an image with black backgroundColor and black penColor. Changing backgroundColor property did not work for me so I changed penColor to white and left background as black. check following code

    signaturePad = new SignaturePad(canvas,{
        backgroundColor:"rgb(255,255,255)", // white background not working
        penColor:"rgb(255,255,255 )" // So changed penColor to white
    });

After this I also faced problem on RESET event. Had to change the function to this
    
    SignaturePad.prototype._reset = function () {
        this.points = [];
        this._lastVelocity = 0;
        this._lastWidth = (this.minWidth + this.maxWidth) / 2;
        this._isEmpty = true;
        this.penColor= 'white'; // Added this line
        this.backgroundColor='black'; // Added this line
        this._ctx.fillStyle = this.penColor;
    };

Hope it helps.

**Comment by pieterMZ** [comment]
Thank you @talha-malik for the reply. Unfortunately the background needs to be white in my scenario.

@szimek Please see this Fiddle: [Fiddle](https://jsfiddle.net/y5mnv9gj/ )
You'll notice that after the first stroke, I immediately open the image. But all of a sudden the background is completely white.

I'll really appreciate it if you're able to assist me in generating JPG with a white background.

Thanks for the time

**Comment by szimek** [comment]
@pieterMZ I can replicate the issue. If I remove `resizeCanvas()` call, it works fine though. I'll check it out when I have some free time.

**Comment by szimek** [comment]
@pieterMZ There's an easy fix though, which might be necessary anyway: just call `signaturePad.clear();` at the end of `resizeCanvas()`.

**Comment by pieterMZ** [comment]
@szimek the `signaturePad.clear();` rectified my problem. Thank you for the assistance.

**Comment by fsboehme** [comment]
Just reporting that I had the same issue only on mobile – desktop was working fine. On mobile, it was saving a black image. Adding `signaturePad.clear();` at the end of `resizeCanvas()` did the trick. 

Thanks for this awesome project!
