### ISSUE TITLE
Question - Signature doesn't work when comes from a hidden div

### ISSUE THREAD

**Issue by dperezq** [szimek/signature_pad#148]
When I try it inside a single page it works fine, but the problem comes when I try to put inside a div, which is hidden at the beginning, then the pad doesn't work. I think is a canvas problem with the resizing, but I don't know how to solve it.

This is my code:

```
<div class="col-sm-9 col-md-10 message-list">
  This is the first div, which I hidde when click on a row
</div>
<div class="col-sm-9 col-md-10 view-message" style="display:none" >
 <div id="signature-pad" class="m-signature-pad">
    <div class="m-signature-pad--body">
       <canvas></canvas>
    </div>
    <div class="m-signature-pad--footer">
       <div class="description">Sign above</div>
          <button type="button" class="button clear sign_btn" data-action="clear">Clear</button>
          <button type="button" class="button save sign_btn" data-action="save">Save</button>
    </div>
</div>
```
and this is the js part:

```
$(document).ready(function() {
$(".list-group-item").each(function() {
    $(this).click(function() {
            $(".message-list").fadeOut('slow').css('display','none');
            $(".view-message").fadeIn('slow').css('display','block');
    });
});
```

**Comment by mcblum** [comment]
Same problem for me! Any idea how to fix it?

**Comment by Ngpriddy** [comment]
Was this ever figured out?

**Comment by kingsbu7** [comment]
For what it's worth (I know this is an old thread), I just ran into this problem myself and I found a simple solution.  I added the following code to my javscript file:

jQuery(document).ready(function(){ 
   setTimeout(function(){
     $("#signature-pad").hide();
   }, 10)
});

For some reason, if you set it to display initially, and hide it later, it will work.  So, I have my page load with it showing, but then run the function above and it hides it after 10 milliseconds (not noticeable for the user).  I then click my button and it works.

Hope it helps!

**Comment by sofiiahitlan** [comment]
Another option Instead of using display: none; you could position your form way off the screen (-5000px). When ready to display it, change the margin to the positive value.
CSS manipulations didn't work for me. Instead of playing with CSS, I didn't render the signature pad until the user was ready to sign. I.e. wrap the signature pad component with the condition that listens to some event.
