### ISSUE TITLE
When using signature_pad with PhoneGap/Cordova touchend event not firing

### ISSUE THREAD

**Issue by AlexPashley** [szimek/signature_pad#149]
First of all thanks for taking the time to make the signature_pad it's great and helped me a lot.

It appears that the touchend event is not firing when using phonegap (5.4.1), from a previous pull request #88 it appears @mtomic fixed it, however this was signature_pad version 1.3.4 there has been several improvements/fixes since then.

Would it be possible to merge this fix into the latest version?

**Comment by szimek** [comment]
Sure. I'll try to find some free time to do it over the weekend and release a new version.

**Comment by mtomic** [comment]
@AlexPashley thanks for the nudge. I've been using my patched version ever since the PR #88 
It would be great to merge it in, it's a simple fix.

**Comment by szimek** [comment]
@mtomic Could you rebase your PR against the current master and fix indentation? It would be easier for me to merge it then.

**Comment by mtomic** [comment]
@szimek thanks - https://github.com/szimek/signature_pad/pull/150
