### ISSUE TITLE
Use of signature_pad with an asp.net form

### ISSUE THREAD

**Issue by DarkSDragon** [szimek/signature_pad#154]
Im attempting to integrate the Signature_Pad with an asp form. I was using the one made by Thomas J Bradley but it has a few issues with re-sizing. Ive had a look around but no one has an example of an asp form and/or the code behind for the signature to appear.

The end result is the signature will be added to an interactive PDF document for further processing but unfortunately due to my own limitations with C# im not sure how to properly incorporate it.

Any help here would be appreciated greatly.

**Comment by marc0ch** [comment]
Had similar issue in .NET. Got sizing to work by getting rid of outer div & form. Currently having issues with the signature not appearing, though

**Comment by multinerd** [comment]
Since this issue is still open, and i just had to implement something similar, I thought I'd offer some links. 

https://www.thewebflash.com/using-signature-pad-with-asp-net-mvc/

**Comment by JuergenGutsch** [comment]
I also did a post about using it in ASP.NET:
[https://asp.net-hacker.rocks/2018/06/05/signature-pad.html](https://asp.net-hacker.rocks/2018/06/05/signature-pad.html)
And I did a PR (#367) to add an ASP.NET/C# example to the readme as well

**Comment by szimek** [comment]
I've just merged @JuergenGutsch's PR, so I'm closing this issue.
