### ISSUE TITLE
empty image on mobile devices 

### ISSUE THREAD

**Issue by riskid** [szimek/signature_pad#155]
I must be doing something wrong as I can't find anyone else with this problem.
I made a custom content type in D7 and added the sigpad field. This works perfectly with chrome and IE/edge on Win7 and Win10. When using my smartphone (android 5) or iPad it stores an empty image instead of the signature.

I do get a notice and warning:
Notice: Undefined index: uri in sigpad_field_widget_form() (line 59 of /var/www/sites/mydomain/sites/all/modules/sigpad/sigpad.module).
Warning: file_get_contents(): Filename cannot be empty in sigpad_field_widget_form() (line 59 of /var/www/sites/mydomain/sites/all/modules/sigpad/sigpad.module).

Thanks for any advise or help.

**Comment by jbnv** [comment]
I'm observing a similar problem. Works fine in Chrome on the desktop. On an Android tablet and on my iPhone, I'm having issues with the content of the pad disappearing spontaneously. The disappearance usually occurs some time after I have drawn in the box and have shifted the focus elsewhere on the page. On the Android device, I can consistently lose my signature by trying to scroll past the bottom of the page. 

The best theory that I have at this point involves a "Clear" control that we have just above the signature box. This control has a click event that calls SignaturePad.clear(). The theory is that somehow the control is registering a click event. We are going to try removing the Clear control and see if we can still reproduce the problem in that situation.

(An observation on @riskid's post: The error messages you have posted appear to be from your server-side code, not from JavaScript.)
