### ISSUE TITLE
Signature is 'wavy' when signed with touch screen

### ISSUE THREAD

**Issue by huntmj01** [szimek/signature_pad#158]
When I sign my signature with my mouse the signature looks great.

![signature drawn with mouse](https://cloud.githubusercontent.com/assets/10147954/14214590/c1e9c832-f7f2-11e5-8229-ea87913cf07d.PNG)

However when I sign my signature with a touch screen the signature is wavy.

![signature drawn with touch screen](https://cloud.githubusercontent.com/assets/10147954/14214593/c1ee0370-f7f2-11e5-8f53-dec9d5a44ab7.PNG)

Here are straight lines drawn with both a mouse and touch screen:

![straight line drawn with mouse](https://cloud.githubusercontent.com/assets/10147954/14214592/c1ec7d98-f7f2-11e5-9fcd-28cca9aa97df.PNG)
![straight line drawn with touch screen](https://cloud.githubusercontent.com/assets/10147954/14214591/c1eb62f0-f7f2-11e5-9872-3e695648e241.PNG)

**Comment by AnnieCyl** [comment]
I have the same problem. #157

**Comment by szimek** [comment]
@2015HuntMJ @AnnieCyl Is there any chance one of you could try it out with some older versions of this library on Android 4.2.2? You can get one e.g. from https://cdnjs.com/libraries/signature_pad. I don't have access to a device with Android 4.2 and I don't know if it was always broken like this or if I broke it in some recent release.

**Comment by 2015HuntMJ** [comment]
@szimek My apologies for the late reply.  I was not using Android.  My app was on a windows tablet.  However, my work switched to an iPad and the signature is no longer wavy.  Might  have just been the windows tablet.
