### ISSUE TITLE
Bootstrap 3 modal issue.

### ISSUE THREAD

**Issue by Emmark** [szimek/signature_pad#160]
I'm using the signature pad in a modal. The signature won't draw until you either rotate or resize your window then you can draw. 

A link to source and a demo of the issue [http://xeroharm.com.au/SignTest/modal.html](http://xeroharm.com.au/SignTest/modal.html)

**Comment by Emmark** [comment]
Fixed by adding:

$('#myModal').on('shown.bs.modal', function (e) {
    resizeCanvas()
    drawSignature()
})

**Comment by crissacandler** [comment]
is the drawSignature a method you created?

**Comment by eldoncar** [comment]
> Fixed by adding:
> 
> $('#myModal').on('shown.bs.modal', function (e) {
> resizeCanvas()
> drawSignature()
> })

You saved my day man. Thank you very much for sharing!

**Comment by aasalshehhi** [comment]
> Fixed by adding:
> 
> $('#myModal').on('shown.bs.modal', function (e) {
> resizeCanvas()
> drawSignature()
> })

Adding it where? please
