### ISSUE TITLE
On resize lost draw

### ISSUE THREAD

**Issue by socieboy** [szimek/signature_pad#161]
When you resize browser the signature is lost, but the empty method is false... it should be false again no?

**Comment by szimek** [comment]
Yeah, it's a known issue. I don't want to add any code to the library that listens to resize event, as it might make more sense to use some kind of throttling or maybe listen only to orientation change on mobile devices etc.

The easiest solution is to call `signaturePad.clear()` in your resize handler - this will correctly set `isEmpty` flag.

**Comment by taschetto** [comment]
I don't want to clear the canvas on resize (or orientation chance on phones). Is this possible?

**Comment by szimek** [comment]
@taschetto No, if you really resize the canvas (i.e. change its `width` or `height` properties) - it's just how canvas works. However, you could listen to resize/orientation change event and redraw the image.

**Comment by shawe** [comment]
Maybe this helps: https://github.com/szimek/signature_pad/issues/33#issuecomment-298242020
