### ISSUE TITLE
Signature vertical offset

### ISSUE THREAD

**Issue by ralph-fuechtenkort** [szimek/signature_pad#170]
Hi,
i am using (or try to) use signaturePad in an IONIC2 application.
Everything works fine except:
there is a vertical offset between the pen position (or finger) and the actual drawing.
Actually the drawing shows up always around 50px above the pen.
Its the same on browser and Android device.
Anyone had/has the same problem and can help me with a solution/workaraound/hint what i am doing wrong?

Thanks in advance

Ralph

**Comment by Adrian-Sevan** [comment]
Same problem. It seems that this is happening when working with touch event.
The issue can be reproduced easily in Chrome in responsive view (dev tools)

**Comment by jetwitaussi** [comment]
Add this:
```
var ratio = Math.max(window.devicePixelRatio || 1, 1);
canvas.width = canvas.offsetWidth * ratio;
canvas.height = canvas.offsetHeight * ratio;
canvas.getContext("2d").scale(ratio, ratio);
```

**Comment by ustincameron** [comment]
> var ratio = Math.max(window.devicePixelRatio || 1, 1);
> canvas.width = canvas.offsetWidth * ratio;
> canvas.height = canvas.offsetHeight * ratio;
> canvas.getContext("2d").scale(ratio, ratio);

Where did you add this? I'm experiencing this on HDPI/Retina screens only.

**Comment by himat** [comment]
@ustincameron add it where you get the canvas element in your JS
