### ISSUE TITLE
Add text to the canvas (New Feature)

### ISSUE THREAD

**Issue by Cinezaster** [szimek/signature_pad#174]
We like to add the name of the signer to the background.

**Comment by tuanbs** [comment]
Same here. I can draw and save image into file using signature-pad but I don't know how to add a textfield allowing user input full name and drag it below their signature. I've been searching for this feature but no luck. Any suggestion be much appreciate. Thanks.

**Comment by szimek** [comment]
This feature has nothing to do with this library and thus won't be added to it.

It can be done with [`strokeText`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/strokeText) method. Here's a simple [demo](https://jsfiddle.net/szimek/rs72ghLj/3/) that does not use signature_pad library at all.

If you have any more questions, feel free to ask.
