### ISSUE TITLE
Save background image also

### ISSUE THREAD

**Issue by hasnainali786** [szimek/signature_pad#177]
I want to save the background image also so how to add background image and save it instead of background color

**Comment by sajan45** [comment]
Try a `fromDataUrl` like below:
```
var signaturePad = new SignaturePad(angular.element('#signature-pad')[0], {
      backgroundColor: 'rgba(255, 255, 255, 0)',
      penColor: 'rgb(0, 0, 0)'
    });
signaturePad.fromDataURL('assets/images/background.jpg');
var saveButton = angular.element('#save');
var cancelButton = angular.element('#clear');
```
I did not read any documentation about it so this is my personal opinion. There might be any other way.

**Comment by hasnainali786** [comment]
.controller('firstimagecntrl',function($scope, $cordovaCamera){
     var canvas = document.getElementById('signatureid');
     var ratio =  Math.max(window.devicePixelRatio || 1, 1);
    canvas.width = canvas.offsetWidth * ratio;
    canvas.height = canvas.offsetHeight * ratio;
    canvas.getContext("2d").scale(ratio, ratio);
     var signaturePad = new SignaturePad(canvas);
    $scope.clearCanvas = function(){
        signaturePad.clear();
    };
    
    $scope.saveCanvas= function(){
        
        var sigimg= signaturePad.toDataURL("image/jpeg");
        $scope.signature= sigimg;
        signaturePad.fromDataURL("data:image/png;base64,iVBORw0K...");
        //give image background 
       $scope.signature.style.backgroundImage = "url('../img/1.jpg')";
    };
I wrote my code like this so what type of changes I have to do

**Comment by makhele** [comment]
@hasnainali786 Here is my implementation:

Create an in Memory Canvas:

    const inMemoryCanvas = document.createElement('canvas');

Write the background image to the `inMemoryCanvas `:

    const ctx = inMemoryCanvas.getContext('2d');
    var backgroundImage= document.querySelector('img') ;
    ctx.drawImage(backgroundImage, 0, 0, 400, 200);

Then write the signature to the canvas and get the DataURL of the `inMemoryCanvas`:

    const signatureImage = new Image();
    signatureImage.onload = () => {
       ctx.drawImage(signatureImage, 0, 0, width, height); // Or at whatever offset you like
       this.backgroundAndSignatureDataURI = inMemoryCanvas.toDataURL();
       console.log('background and and signatureDataURI', this.backgroundAndSignatureDataURI);
    };
    signatureImage.src = this.signaturePad.toDataURL();

**Comment by UziTech** [comment]
closing as stale
