### ISSUE TITLE
Read wrong position when zooming by <ion-scroll> 

### ISSUE THREAD

**Issue by sebastianor** [szimek/signature_pad#179]
I use this signature_pad in Ionic Framework application. Everythings works fine until I use zoom in <ion-scroll> tag, then plug draws a line in a completely different place than I move my finger. Here is my HTML code with canvas: 
`<ion-scroll zooming="true" id="myCanvas" min-zoom="0.5" max-zoom="2" direction="xy" delegate-handle="canvas" overflow-scroll="false" >
       <canvas height="1754" width="1240" id='signatureCanvas'></canvas>
    </ion-scroll>`

**Comment by szimek** [comment]
Hey, without any code that I can run and debug, it's really hard to figure out what's wrong. I guess it gets invalid coordinates from touch event, but I'm not sure how we can access the correct ones. Any chances you could provide the full code and some instructions how to run it? I'm not sure if Ionic allows its apps to be deployed as normal web apps :/

**Comment by sebastianor** [comment]
Hey, i've created simply Ionic project with this problem. You can see it here: https://bitbucket.org/Sebastianor/signaturepad . Unfortunately, it is necessary to install ionic by **npm install -g cordova ionic**, then go to the root directory of the project and run **ionic serve** command. Then you can normally test in a browser.

**Comment by UziTech** [comment]
closing as stale
