### ISSUE TITLE
Cannot set property 'SignaturePad' of undefined

### ISSUE THREAD

**Issue by nicktc** [szimek/signature_pad#181]
Hi,

When I load the signature_pad.js inside my app.js (this files contains more js libraries that work succesfully, like jquery, etc) without actually making any calls to the signature api I am getting the following errror message:

`
signature_pad.js:13 Uncaught TypeError: Cannot set property 'SignaturePad' of undefined
`

That's this line:

`
root['SignaturePad'] = factory();
`

I am doing something wrong?

**Comment by szimek** [comment]
Hey, are you using any module library? If not, then `root` should be equal to the `window` object, which shouldn't be undefined. Any chances you could provide an example somewhere (e.g. jsfiddle/jsbin...) that replicates your issue?

**Comment by MmtBkn** [comment]
I have same issue. Trying to use it w/ng2/ionic2. Did you solve it @nicktc ?

    ```
commonjs({
      include: [
        'node_modules/rxjs/**',
        'node_modules/angular2-signaturepad/**'
      ],
      namedExports: {
        'node_modules/angular2-signaturepad/signature-pad.js':['SignaturePadModule']
      }
    })


```

**Comment by szimek** [comment]
@MmtBkn Can you try to replicate it somewhere using e.g. https://jsfiddle.net, or, if it's not possible, create a separate repo?

**Comment by Tarekajaj** [comment]
Facing same issue in 2020

**Comment by kopes** [comment]
same here

**Comment by mdookie4** [comment]
try to set the signature-pad version back to 2.8.0 in package.json and npm install again
    "angular2-signaturepad": "2.8.0",
