### ISSUE TITLE
miniature image of the signature is being repeated when used on phone (android) 

### ISSUE THREAD

**Issue by pandaster** [szimek/signature_pad#182]
Hey there,

I used your code inside a form and everything that i draw upon the canvas reapears on the top left quadrant of the canvas 
![canvas example](https://cloud.githubusercontent.com/assets/22026186/18271190/93ff19e0-7439-11e6-9fe1-0972eabe693d.png)

Anyone had the same problem? or have an idea how to solve this?

**Comment by szimek** [comment]
Could you provide an example that replicates this issue in e.g. jsfiddle or jsbin?

**Comment by oglem** [comment]
szimek this is caused, at least in my case due to a library angular-signature.

It created a feedback loop writing data back into the url. 

I don't know why its scaling but a workaround at least in my case was to comment out:

          $scope.$watch("dataurl", function (dataUrl) {
            if (dataUrl) {
              **//$scope.signaturePad.fromDataURL(dataUrl);**
            }
          });

Strangely it only happens on mobiles.

**Comment by pandaster** [comment]
It seems to solve the problem - thanks ! :)

**Comment by szimek** [comment]
@oglem Thanks for posting the workaround. 

I'm closing it, because it's not really an issue with this library, but rather its angular wrapper.
