### ISSUE TITLE
Creating smoother lines by using sampling rate?

### ISSUE THREAD

**Issue by kunukn** [szimek/signature_pad#183]
Would it make sense to use a sampling rate to collect data points to create smoother lines?

The article
https://medium.com/square-corner-blog/smoother-signatures-be64515adb33#.vib1pfjh4
Shows data are picked from a sampled touch points.

I could not see any sampling algorithm in the code. Every touch events seems to be used to draw a line.

I created his demo with Underscore library, where the sampling rate is every x-milliseconds, this is set to 20 at the bottom of the JS code.
http://codepen.io/kunukn/pen/kkbNvx

**Comment by szimek** [comment]
I'm not sure I understand it correctly. Throttling causes the function to be called less often, so how does it result in smoother lines, if we have less points? The more points we have from touch/mouse move events, the smoother the lines should be. Of course I may be wrong 😉

**Comment by kunukn** [comment]
I forgot to explain my motivation/intent.
You are right, with more points we get it more accurate.
But I dont want it more accurate, I want it more natural looking.

What I want is better looking signatures which looks as if you were signing with a pen on paper.

My experience when using a mouse or finger is that the drawings gets shaky or edgy because my hand/finger is slightly shaking. 

My idea is what if we sampled the points to ensure some distance between every point. Then we can use the smoothening algorithm to force a natural looking curvy line. 

I might be wrong, this is just an idea.

**Comment by kunukn** [comment]
Maybe this explains it better

Reduce mouse "noise"
From this stackoverflow
http://stackoverflow.com/q/5829437/815507

"Right now, (1) is problematic because I get thousands of mouse movements within a few seconds. Due to (1) the line can look jaggy. What current idea: when the user finishes drawing the line, i store all movements in a Array and reduce them (median threshold) and then use a spline algorithm to recreate a line."

The jaggy is solved because signature_pad uses a smoothening algorithm. Then the mentions reduce the points.

"store all movements in a Array and reduce them (median threshold)"

There are some interesting answers also.

**Comment by kunukn** [comment]
I am reading and learning.
I think what I am looking for is de-noising.

From the article
http://willowsystems.github.io/jSignature/#/about/linesmoothing/
De-noising (simplifying) the stroke before smoothing

"One worthy addition to this algorithm is real-time de-noising of the curve endpoint data. Before the above algorithm is invoked, a filter may be introduced between the "pointer moved to point X" event generator and the above-mentioned curve fitting algorithm. In our current case, we do not convey the "pointer moved to point X" events to the rendering logic until the distance from prior curve's end-point exceeds 2 units (i.e. "browser pixels") of movement."


I think that must be better than my throttling idea.

**Comment by szimek** [comment]
Now I get it. There are some really good ideas in this article - I guess we could copy some of them e.g. better interpolation (I'll need to read more carefully this part) and skipping points that are too close to the previous one (I'll need to add some debugging to see how often it occurs). 

Any PRs or test versions that show the difference between the current version and the (hopefully) improved one are welcome :) One thing that is currently missing is the possibility to feed the library with an array of points (with their times) - this would allow to easily compare drawing speed and the overall result.

**Comment by kunukn** [comment]
Here's an example
Using a mouse to draw letters.

![demo-using-mouse](https://cloud.githubusercontent.com/assets/3199603/18541324/c2a20e64-7b24-11e6-93c0-639a17587904.png)
http://szimek.github.io/signature_pad/

Some custom coded added trying to reduce the "mouse noise"

![custom-using-mouse](https://cloud.githubusercontent.com/assets/3199603/18541327/c86ad2ae-7b24-11e6-896b-921da6afc6ad.png)

http://codepen.io/kunukn/full/kkbNvx/

**Comment by szimek** [comment]
Thanks! I'm currently working on a version that stores all points (`x`, `y`, `time`) in an array (of arrays of points ;)) and provides a method to draw a signature using this data (it just iterates over these points and calls `addPoint()`, which takes care of the rest). This way we could prepare a few signatures (e.g. one drawn slowly, one drawn fast etc.) and compare results by feeding exactly the same data to a modified version of this library.

It's actually working, but I need to refactor and clean it up a bit. I should have it ready at the beginning of the next week.

**Comment by szimek** [comment]
@kunukn I've just pushed a version that stores all drawn points in `_data` variable. This data can then be loaded using `_fromRawData` method. This way we can prepare some signatures and put their data e.g. into a gist and then easily load it and compare results of the current and improved implementations. The new version is at https://github.com/szimek/signature_pad/tree/draw-signature-from-point-data.

**Comment by kunukn** [comment]
That was quick. I see, a method to save and load data points to compare drawing based on same dataset. I will play with it next week where I have time.

**Comment by kunukn** [comment]
I like the raw data idea and to save the x,y,time. 

This enables testing on draw result by modifying the configuration on same dataset.
I believe the current api supports color configuration and line-width related configuration.

Here are some of my ideas reflecting on how to use the raw data.
--------------------

The configuration could also in the future support dataset filter options or algorithm selection.

A real-time filter component could be added.
That component decides whether to use the point based on (x,y,time) and current drawing dataset.

F.x. as an idea to minimize "mouse noise" or other type of enhancement techniques where the x,y values gets modified in the filter component.

I could imagine the API to support a callback method to include a custom implemented real-time filter component.

There is this approach with code example which I also find interesting.
That algorithms seems to be more "mouse noise" friendly, but might look as good as Signature Pad on touch devices.
http://perfectionkills.com/exploring-canvas-drawing-techniques/

"Bezier curves: One interesting concept I came across was using bezier lines instead of straight ones. This allows for curves of a free-drawn path to be naturally smoother. 
The idea is to replace straight-line stroke with quadraticCurveTo, using middle point between two consecutive points as quadratic curve control points." 

I am not sure whether that algorithm is the same as this one. I don't think so. 
"using middle point between two consecutive points as quadratic curve control points" seems to be a simpler calculation than used in Signature Pad, I might be wrong.

I think it could be interesting to add that algorithm and compare it to the current smoothening algorithm using the same raw dataset.

----

I will play with the raw data thing and modify my Codepen. 
Thanks for the raw data idea.

**Comment by szimek** [comment]
Thanks for the link - I remember commenting this article long time ago on Hacker News :) Anyway, it's possible that the algorithm to calculate control points is too complex and could be simplified and optimized. I remember I had a lot of issues making it work, so once I got a version that worked I stopped looking further ;)

The first thing I'd like to do is to refactor the library to separate functions that calculate and draw. This way it should be easy to allow to draw e.g. SVG as the output using these raw points - all calculations would stay the same, only the drawing functions would be different.

Regarding passing functions with custom algorithms - I'm totally ok with it if it doesn't require tons of changes to the library itself. However, I also think that almost nobody will use it, so I'd prefer to have as good default algorithm as possible 😉

**Comment by szimek** [comment]
@kunukn I've just release 1.6.0-beta.1 with 2 new methods: `toData` and `fromData`. This version is already used by https://szimek.github.io/signature_pad. Now you can draw a signature, save it as a JSON object using `toData` method, modify the drawing algorithm and compare updated and original version using `fromData`.

I'll try to go over your suggestions and see if they improve performance or look of drawn signatures.

**Comment by szimek** [comment]
@kunukn I just saw your demo again and it really works much smoother than the current version. Any chances you could create a PR for this feature? It would be great if it didn't have a dependency on underscore library though and if it was possible to disable both distance checking and event throttling.

**Comment by kunukn** [comment]
Hi Szymon

The demo was a quick prototype demo. It simple uses throttling to slowing
down sampling rate. But it also creates "lag", because it does it by
slowing down FPS. It slows down the mouse/touch movement events. So this is
not quite the right code, but the idea is to have a configuration where you
can set the sampling rate. F.eks. maximum collect n dots per second.

For mouse drawing I was thinking that it collected to many dots per second
for the implemented algorithm which creates the "mouse noise". So the idea
is to tweak the drawing result by having a configuration to set the dot
sampling rate. But creating lag as with the prototype is probably not the
best approach.

I don't have some code to set a sampling rate, I might make one when I have
some time. Other projects, family and job are currently making me too busy
at the moment.

The throttle function can be extracted from underscore, here's a code
snippet from 2014 i think  http://stackoverflow.com/a/27078401/815507

**Comment by kunukn** [comment]
Hi Szimek

I made a quick prototype throttling without lagging.
Small code modification

http://codepen.io/kunukn/pen/90c49e2ac8886bc17512bf4beb33b5a9

signaturePad = new SignaturePad(canvas, {
  throttle: 16 // x milli seconds
});


And


SignaturePad.prototype._strokeUpdate = function (event, isStrokeMove) {
  var x = event.clientX;
  var y = event.clientY;

  var diff;
  if (isStrokeMove && this.throttle) {
    // are we are throttling ?
    diff = event.timeStamp - this.lastUpdateTimeStamp;
    if (diff <= this.throttle) {
      return; // skip this update
    }
  }
  this.lastUpdateTimeStamp = event.timeStamp; // update
...



Github code at
https://github.com/kunukn/signature_pad/tree/throttling



I have also another idea where we skipped points if they are to close to
each other (de-noising strategy) but I will look at that in another time.




- Kunuk

**Comment by kunukn** [comment]
Hi Szimek

I was to quick with my previous email.
I implemented a pseudo throttle function, might be ok but I would prefer a
true throttle function.


I have updated the code with a real throttle example.
I have added a draw points button in the prototype.

throttle value set to 16 milliseconds (60 FPS, no lagging)
http://codepen.io/kunukn/full/bgjzpb/

no throttling version
http://codepen.io/kunukn/full/83d852292e80ba33f3ec9db3f5ab7de8/


You can compare what ponts are used in those two codepens by clicking the
draw points button.

Code is in Github
https://github.com/kunukn/signature_pad/tree/throttling


- Kunuk

**Comment by szimek** [comment]
This looks really cool. I need to fix all the issues with SVG for 1.6.0 release and hope to release your changes as 1.7.0.

**Comment by szimek** [comment]
@kunukn Hey, now that 1.6.0 is released, could you prepare a PR with your code from http://codepen.io/kunukn/full/bgjzpb/? I'd merge it and release as 1.7.0. I guess the throttle function could be simplified a bit, because we won't be using `leading/trailing` options.

**Comment by kunukn** [comment]
@szimek I will look into this

**Comment by szimek** [comment]
Closed by #237

**Comment by jyt1902** [comment]
this.minWidth = 1.0;
this.maxWidth = 1.0;
this.throttle = 'throttle' in opts ? opts.throttle : 1; // in miliseconds
this.minDistance = 'minDistance' in opts ? opts.minDistance : 0;
After Change signature_pad.js above line look like this. 

![signaturepad writing](https://user-images.githubusercontent.com/42262012/43941545-2c24024e-9c92-11e8-8f2e-143aa0f373c4.png)
----------------------------------
I want smooth line like below image(Sketchpads windows app).

![other2](https://user-images.githubusercontent.com/42262012/43941671-a209d1d2-9c92-11e8-9417-9e24b549a88d.png)
