### ISSUE TITLE
signature pad doesn't seem to work with *ngIf in Angular 2

### ISSUE THREAD

**Issue by cenjennifer** [szimek/signature_pad#184]
Hi - 

I'm trying to display the signature pad only when a user checks off a checkbox, using *ngIf. It doesn't seem to be working if I initiate the this.signaturePad in ngAfterViewChecked(), as the signature is technically not part of the DOM when the user first gets to the page. Do you have any suggestions as to how I can implement this? 

Thanks!

**Comment by kunukn** [comment]
This is likely an Angular 2 issue than a Signature pad issue. 

I am actually playing with Angular 2 at the moment and I can get the checkbox thing to work but I use the ngAfterViewInit lifecycle. I created a Pad component where I added the html , css and custom script from Signature Pad demo page. 

In the Pad component's ngAfterViewInit lifecycle i run the custom initialization script. 

I simply added the Signature pad js library in the html header and used the global window.SignaturePad to create a new signature object (quick and dirty example code)

This is with Webpack and Typescript based on this guide
https://angular.io/docs/ts/latest/guide/webpack.html
and the forms from this guide
https://scotch.io/tutorials/how-to-deal-with-different-form-controls-in-angular-2

pad.component.ts
```
import {Component} from '@angular/core';

@Component({
    selector: 'pad',
    template: `
        <div id="signature-pad" class="m-signature-pad">
            <div class="m-signature-pad--body">
                <canvas></canvas>
            </div>
            <div class="m-signature-pad--footer">
                <div class="description">Sign above</div>
                <button type="button" class="button clear" data-action="clear">Clear</button>
                <button type="button" class="button save" data-action="save">Save</button>
            </div>
        </div>
    `,
    styles: [`
		.m-signature-pad {			
			font-size: 10px;			
		}
		/* And the rest ...*/
	`]
})

export class PadComponent {
   // this is quick demo code
    _init = function () {
        var wrapper = document.getElementById("signature-pad");
        var
            clearButton = wrapper.querySelector("[data-action=clear]"),
            saveButton = wrapper.querySelector("[data-action=save]"),
            canvas = wrapper.querySelector("canvas"),
            signaturePad;
        function resizeCanvas(canvas) {
            canvas = canvas || this;
            var ratio = Math.max(window.devicePixelRatio || 1, 1);
            canvas.width = canvas.offsetWidth * ratio;
            canvas.height = canvas.offsetHeight * ratio;
            canvas.getContext("2d").scale(ratio, ratio);
        }
        window.onresize = resizeCanvas.bind(canvas);
        resizeCanvas(canvas);

        //noinspection TypeScriptUnresolvedFunction
        signaturePad = new window.SignaturePad(canvas);

        clearButton.addEventListener("click", function (event) {
            signaturePad.clear();
        });
        saveButton.addEventListener("click", function (event) {
            if (signaturePad.isEmpty()) {
                alert("Please provide signature first.");
            } else {
                window.open(signaturePad.toDataURL());
            }
        });
    };

    ngAfterViewInit() {        
        this._init();
    }
}
```

app.component.ts
```
import {
    Component,
    Input, 
} from '@angular/core';


import { PadComponent } from '../pad';

@Component({
  selector: 'my-app',
  directives: [PadComponent],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  @Input() pad = {
    isActive: false
  };
}
```


app.component.html
```
  <label>
    <input type="checkbox" name="isActive"  [(ngModel)]="pad.isActive">
    Is Active?
  </label>
  <pad *ngIf="pad.isActive">loading pad...</pad>
```

**Comment by cenjennifer** [comment]
Oh, I see! Thank you so much for the sample code.

**Comment by luben-gonsalves-au1** [comment]
You can use **[hidden]** instead of ***ngIf**. These are two ways to show/hide an element. The only difference is: *ngIf will remove the element from DOM while [hidden] will tell the browser to show/hide an element using CSS display property by keeping the element in DOM.
