### ISSUE TITLE
Can't get signature pad to resize

### ISSUE THREAD

**Issue by quaestorial** [szimek/signature_pad#185]
I have tried to implement signature pad in a ruby project as per the suggestions in drifting ruby screencast https://www.driftingruby.com/episodes/capturing-signatures-with-signature-pad

Everything works beautifully, except the resizing of the canvas.

I get a javascript error in the browser console: `canvas.getContext is not a function. (In 'canvas.getContext("2d")', 'canvas.getContext' is undefined)`

I tried to wrap the javascript in a call to `$(function () {   [...]   });`to make sure the DOM is loaded, to no avail.
Also, placing the javascript code on the page just before the closing `/body`tag didn't help.

``` javascript
function resizeCanvas(canvas) {
    var ratio =  Math.max(window.devicePixelRatio || 1, 1);
    canvas.width = canvas.offsetWidth * ratio;
    canvas.height = canvas.offsetHeight * ratio;
    canvas.getContext("2d").scale(ratio, ratio);
}

$(document).on('turbolinks:load', function() {
  var canvas = document.querySelector("canvas");
  if (canvas){
    canvas.height = canvas.offsetHeight;
    canvas.width = canvas.offsetWidth;
    window.addEventListener("resize", resizeCanvas);
    resizeCanvas(canvas);
    signature_pad = new SignaturePad(canvas);
    $('.signature_pad_clear').click(function() { signature_pad.clear() });
    $('.signature_pad_save').click(function(event) {
      if (signature_pad.isEmpty()){
        alert('You must sign to accept the Terms and Conditions');
        event.preventDefault();
      } else {
        $('.signature_pad_input').val(signature_pad.toDataURL());
      }
    });
  }
});
```

``` haml
.container
    #id.row
        = form_for @document do |f|
            .col-md-10.col-md-offset-1
                .panel.panel-default
                    .panel-heading
                        %h2.panel-title
                            %span.glyphicon.glyphicon-ok(aria-hidden="true")
                            Your Signature
                    .panel-body
                        = f.hidden_field :signature, class: "signature_pad_input"
                        .signature_pad.text-center
                            .signature_pad_body
                                %canvas
                            .signature_pad_footer
                                .text-muted Sign above
                                %button.btn.btn-default.signature_pad_clear(type="button") Clear

            .col-md-10.col-md-offset-1
                = f.submit "Sign digitally", class: "btn btn-success btn-lg btn-block signature_pad_save", id: "sign-doc"
```

``` css
.signature_pad {
  width: 700px;
  height: 400px;
  margin: 0 auto;
}

.signature_pad_body canvas {
  width: 100%;
  height: 100%;
  border: dotted #444;
  background: #CCCCCC;
}
```

If I change the dimensions in the css from 700px and 400px respectively to just 100% each, the resizing works for the containing div but the canvas is not resized properly, which leads to touch/point being out of focus (i touch somewhere and the resulting draw is half an inch to the upper left)

Any suggestion what might be wrong?

**Comment by kunukn** [comment]
There seems to be something wrong with the event binding for resizing with the code example.
You could console log the canvas inside the resize function. 

I am thinking something like this.

`function resizeCanvas() {
		console.log(this); // I should always be the canvas element
		var ratio =  Math.max(window.devicePixelRatio || 1, 1);
		this.width = this.offsetWidth * ratio;
		this.height = this.offsetHeight * ratio;
		this.getContext("2d").scale(ratio, ratio);
}	
window.onresize = resizeCanvas.bind(document.querySelector('canvas'));`

----

There is a difference between using width/height styling and setting width/height attribute values on the canvas elements.
http://stackoverflow.com/q/331052/5707008

**Comment by shawe** [comment]
Maybe this helps: https://github.com/szimek/signature_pad/issues/33#issuecomment-298242020
