### ISSUE TITLE
Signature-pad not working for angular 2 in PROD, but works in DEV

### ISSUE THREAD

**Issue by cenjennifer** [szimek/signature_pad#186]
Hey! 

I can't seem to figure out why the signature-pad isn't working in the PROD environment, but works find in the DEV environment. 

I get the following error in the prod version:
`Can't bind to 'options' since it isn't a known property of 'signature-pad'.`

Any insights?

Thanks!

**Comment by balaabhinav** [comment]
@cenjennifer  I am facing the same issue.. Were you able to find any solutions ?

**Comment by cenjennifer** [comment]
@balaabhinav  - Yes, the issue was solved when I update to the latest version of the angular2-webpack starter. Perhaps, you can try updating the angular 2 version you are currently using to the latest one.

**Comment by balaabhinav** [comment]
Ah ok thanks. Will see if it solves the issue :-)

**Comment by kashban** [comment]
Typically this is an error showing up if AOT (Ahead of Time compiling) is not supported by a component.
