### ISSUE TITLE
Hi szimek

### ISSUE THREAD

**Issue by kaioramos** [szimek/signature_pad#187]
Man, you're brilhant!

I try to use ur signature pad, and works very fine!
But now i'm try to save the images with:

assinatura.save = function(sigImg)
    {
        $cordovaFile.writeFile(cordova.file.externalApplicationStorageDirectory, "assinatura.jpg", sigImg, true).then
        (
          function(result){
              console.log("sucesso");
          },
          function(err){
              console.log("erro", err);
          }
        )
    }

The file is write in app folder, but when i try open (i use ubuntu) shows me that msg:

Error interpreting JPEG image file (Not a JPEG file: starts with 0x64 0x61)

U can help me?

Your job is amazing, thanks.

Hugs from Brasil!

**Comment by kaioramos** [comment]
Hi man, sorry for bad inglish (again). To everyone else that has my problem, heres the solution:

.controller('SignatureCtrl', function($scope, $cordovaFile) {
    var canvas = document.getElementById('signatureCanvas');
    //var signaturePad = new SignaturePad(canvas);
    var signaturePad = new SignaturePad(canvas);
    var assinatura = {};
    $scope.clearCanvas = function() {
        signaturePad.clear();
    }
    $scope.saveCanvas = function() {
        var sigImg = signaturePad.toDataURL();
        $scope.signature = sigImg;
    var myBaseString = sigImg;
    console.log(sigImg);
    console.log(myBaseString);
    // Split the base64 string in data and contentType
    var block = myBaseString.split(";");
    // Get the content type
    var dataType = block[0].split(":")[1];// In this case "image/png"
    // get the real base64 content of the file
    var realData = block[1].split(",")[1];// In this case "iVBORw0KGg...."
    // The path where the file will be created
    var folderpath = "file:///storage/emulated/0/";
    // The name of your file, note that you need to know if is .png,.jpeg etc
    var filename = "myimage.png";
    savebase64AsImageFile(folderpath,filename,realData,dataType);
    function b64toBlob(b64Data, contentType, sliceSize) {
        contentType = contentType || '';
        sliceSize = sliceSize || 512;
        var byteCharacters = atob(b64Data);
        var byteArrays = [];
        for (var offset = 0; offset < byteCharacters.length; offset += sliceSize) {
            var slice = byteCharacters.slice(offset, offset + sliceSize);
            var byteNumbers = new Array(slice.length);
            for (var i = 0; i < slice.length; i++) {
                byteNumbers[i] = slice.charCodeAt(i);
            }
            var byteArray = new Uint8Array(byteNumbers);
            byteArrays.push(byteArray);
        }
      var blob = new Blob(byteArrays, {type: contentType});
      return blob;
}
function savebase64AsImageFile(folderpath,filename,content,contentType){
    // Convert the base64 string in a Blob
    var DataBlob = b64toBlob(content,contentType);

    console.log("Starting to write the file :3");

    window.resolveLocalFileSystemURL(folderpath, function(dir) {
        console.log("Access to the directory granted succesfully");
    dir.getFile(filename, {create:true}, function(file) {
            console.log("File created succesfully.");
            file.createWriter(function(fileWriter) {
                console.log("Writing content to file");
                fileWriter.write(DataBlob);
            }, function(){
                alert('Unable to save file in path '+ folderpath);
            });
    });
    });
}
}
})

I'm very proud of me, lol, make less then a month when i start with ionic.
Thanks for u API, helps me a lot.
To some how want more information about this solution just ask me.

**Comment by szimek** [comment]
It's great that you've figured it out!
