### ISSUE TITLE
Signature Pen not stop when canvas is used inside bootstrap modal in desktop

### ISSUE THREAD

**Issue by nilulande05** [szimek/signature_pad#188]
It is working properly for Ipad if you used signature canvas inside modal. But for desktop it does not allow to stop pen when signature canvas is used inside bootstrap modal

**Comment by qayyumabro** [comment]
Hi did you able to fix it? It works when I inspect it but not otherwise.

**Comment by jesusquev3311** [comment]
the problem is the resize, when the signature is inside a modal or collapse the canvas width and height are = nan or null afeter resizing the draw shows off
