### ISSUE TITLE
validate that the signature contains more than one point

### ISSUE THREAD

**Issue by cnerio** [szimek/signature_pad#192]
Hello szimek i think this signature pad is awesome,i want to ask you how i can validate that the signature drawing, shouldn't be a simple dot only in the pad, i need the users drawing a real signature not only a dot , you can help me please ?!!

**Comment by szimek** [comment]
I'm working on a version that provides access to all points that were drawn - this way you can easily write your own validation. I was planning on making it a private variable (it was supposed to be used only to export images in SVG format), but it looks like making it public could solve other problems, like this one.

Unfortunately, I'm really busy now, so I don't think I'll manage to release a new version before the end of the year :/ If you really need it earlier, you can try out the version on [this](https://github.com/szimek/signature_pad/tree/draw-signature-from-point-data) branch. You can access the point data (it's an array of arrays - each "inner" array represents a single dot or a line) via `SignaturePad#_data` property.

**Comment by szimek** [comment]
@cnerio There's a new unreleased version that provides `#toData` method that will return an array of point arrays (each "inner" array represents a line or a single dot). This way you could check if the first array has more than one point (i.e. it's a line) or, if it doesn't (i.e. it's a dot), if there's more than 1 array.

This version is available [here](https://github.com/szimek/signature_pad/tree/draw-signature-from-point-data). I'll release it as a beta version probably next week.

**Comment by szimek** [comment]
@cnerio I've just released 1.6.0-beta.1 with this feature. This version is already used by https://szimek.github.io/signature_pad. Let me know if you find any issues.
