### ISSUE TITLE
Signature pad doesn't work on a touch device where the page containing the signature zone is scrollable

### ISSUE THREAD

**Issue by carbontracking** [szimek/signature_pad#197]
This is similar to the issue : **Signature_pad doesn't work properly when is inside ScrollView #109**

In my case, I'm trying to include the signature pad on a webpage that has up/down scrolling and left/right swipe actions.

I'm wondering if you have an example of the code you mentioned, i.e. as you say " What I usually did was to have a "click/tap here to sign" link/button in a form that opened a new non-scrollable view with signature pad and some buttons (clear/save/cancel)."

Best regards / Colm OGAIRBHITH

P.S. Your work on this has been immensely helpful to me, many thanks

**Comment by mirrikat45** [comment]
I also ran into this problem on an Android Tablet with Chrome browser. It does work so long as the screen isn't scrolled. Once the screen scrolls, the contents of the signature pad are erased. Curious what can be done, as a new window popup is a bit out of the flow for me.

**Comment by oscaramidasoft** [comment]
Hello,
I have a solution for this problem consisting in detecting the start and stop of the scroll event. At start, simply get canvas data with the "toDataURL()" method. At scroll stop, put that data again with "fromDataURL()" method.
I'm going to make a pull request so this solution can be reviewed and tested.

**Comment by szimek** [comment]
@mirrikat45 @oscaramidasoft Quick question - do you handle `window.resize` or listen for `orientationchange` event? If scrolling causes resize to be triggered, maybe you could simply use `orientationchange` instead?

**Comment by oscaramidasoft** [comment]
Hi Szymon,

I'm not calling any of these events. Are you suggesting to call
'orientationchange' just after setting Signature_pad's value back?

--
---------------------------------------------------
Òscar Pérez del Campo

Amidasoft Sistemes d'Informació, SL
c./ Emili Grahit, 59, entresol 1ª
17002 Girona
616 664 373 | 872 032 326
oscar.perez@amidasoft.com <oscar@amidasoft.com>
http://www.amidasoft.com
---------------------------------------------------

2017-01-18 21:57 GMT+01:00 Szymon Nowak <notifications@github.com>:

**Comment by oscaramidasoft** [comment]
I just made a request pull with my solution...

**Comment by szimek** [comment]
Thanks for the PR, but could you prepare a demo page that shows the issue? I'd like to check why it's happening first, instead of implementing a workaround.

**Comment by oscaramidasoft** [comment]
Hi,

the error happens on iPad, not on the browser. So, please, open this link on an iPad (tested with Safari on iPad):
https://jsfiddle.net/297nt83r/

**Comment by szimek** [comment]
Thanks! Unfortunately, I can't replicate it using iPad Simulator from Xcode, so I'll have to find someone with a real device to debug it.

**Comment by oscaramidasoft** [comment]
Hi Szimek,

I'm reviewing it and I see that the jsfiddle I prepared works correctly on iPad... How strange...
It seems the problem is not with the library, but some interaction with other libraries I have in my project...
Please, could you reject the pull request?
And excuseme for any inconvenience...

**Comment by szimek** [comment]
No problem. Cheers!

**Comment by szimek** [comment]
@carbontracking @mirrikat45 Is it still an issue? I accidentally closed this issue, instead of PR and I'm not sure if it should be reopened.

**Comment by transcendtient** [comment]
I'm having this issue too. On a Asus MeMo Pad 7 in Chrome.
I tried the fix branch, but eventually, if you scroll enough, it will delete the signature.

**Comment by sujathay** [comment]
Am facing the same issue.. Did anyone get solution for this? please share

**Comment by VamMeejS** [comment]
This package works great on Desktop but not on iPhone. The error I get is: "Safari cannot open the page. The operation couldn't be completed. (WebKitBlobResource error 1.)"

Someone on Stackoverflow told me that this error is due to the way that iOS and some versions of Android (don't) handle the blob created by dataUrlToBlob. 

Have you discovered another option for iOS and Android devices, please?

**Comment by szimek** [comment]
@VamMeejS The demo code for the "app" is just an example, but I agree that it could work better on Safari. Something like this would probably work better:

```js
function download(dataURL, filename) {
  if (navigator.userAgent.indexOf("Safari") > -1 && navigator.userAgent.indexOf("Chrome") === -1) {
    window.open(dataURL);
  } else {
    var blob = dataURLToBlob(dataURL);
    var url = window.URL.createObjectURL(blob);

    // ... the rest of the current code
  }
}
```
I'm not sure what's the best way to detect if it's Safari or not. PRs are welcome ;)

**Comment by VamMeejS** [comment]
Thank you, Szymon. That is helpful. It avoids the error and opens a window of the final signed image. My goal is to save to the database but I guess if it downloaded to the Photos app on the iPhone that would be acceptable. Do you know how to cause it to download the image to the Photos app on an iPhone, please?
