### ISSUE TITLE
Doesn't seem to support Webpack

### ISSUE THREAD

**Issue by szh** [szimek/signature_pad#199]
I'm using Webpack to bundle my app and I'm trying to integrate SignaturePad. I tried using
`import { SignaturePad } from "signature_pad"`, `import "signature_pad"`, `require("signature_pad")` and many other variations, with "signature_pad/signature_pad", and even "signature_pad/src/signature_pad", but it seems that Webpack doesn't support the module types that SignaturePad uses.

The only way I got it to work is using [exports-loader](https://github.com/webpack/exports-loader):
`var SignaturePad = require("exports?SignaturePad!signature_pad/src/signature_pad");`

Any plans to add Webpack support? Or am I missing something?

**Comment by bbashy** [comment]
In the same boat too! Webpack :(

**Comment by JD-Robbs** [comment]
Personally, I have set it up in the `webpack.config.js` as follows (using the `expose` loader):

    module: { 
        loaders: [
            {test: require.resolve('signature_pad'), loader: 'expose?SignaturePad'},
            [...]
        ]
    }

And then in my code simply:

    let SignaturePad = require("signature_pad");

So, this is essentially what you are already doing, just that you can instead set it up once and then import the usual way.

**Comment by szimek** [comment]
In theory it should work - the production build uses Universal Module Definition (UMD) and has the `main` field in `package.json` file. 

Anyone wants to investigate why it doesn't actually work and create a PR that fixes this issue?

**Comment by szimek** [comment]
Can you check if beta version (`1.6.0-beta.1`, can be installed using `npm i signature_pad@beta`) works?

**Comment by szh** [comment]
Yes, now I can use `var SignaturePad = require("signature_pad");` or `import "signature_pad"`, though I still can't do `import { SignaturePad } from "signature_pad".

**Comment by szimek** [comment]
@szh Thanks for the info! It sucks that ES6 import doesn't work. I don't think that UMD is supposed to support ES6 export/import :/

I'll see if I have to provide 2 different builds - ES6 (that uses `export default` and is exposed using `jsnext:main` in `package.json` file) and UMD or if there's a simpler way. 

If anyone knows anything about it already, it would be awesome!

**Comment by szh** [comment]
I just tried `import * as SignaturePad from "signature_pad";` and it works. It might not be worth the effort to create separate builds, maybe just add this to the readme instead.

**Comment by szimek** [comment]
@szh I still want to try it out and fix it (or at least document how it can be used with Webpack) before releasing 1.6.0 (or 2.0.0, because I'm also considering removing Bower support). I've noticed that I'm exporting `SignaturePad` class using `module.exports = SignaturePad;` instead of `export default SignaturePad`, but I have no idea if it changes anything.

**Comment by collinforrester** [comment]
So both `import * as SignaturePad from "signature_pad";` and `require('signature_pad')` worked for me.

However, I had to add `"plugins": ["transform-exponentiation-operator"]` to my `.babelrc` file.  It seemed that babel was picking that plugin definition up from the `.babelrc` file in `node_modules/signature_pad`.

Once I installed and added that I was good to go.

**Comment by szimek** [comment]
Uh, I forgot about `transform-exponentiation-operator`. I'll remove it, because it doesn't really do much and everyone would need to add it.

**Comment by collinforrester** [comment]
Any luck figure out what type of builds you have to support to allow `import {}` syntax as well as `require`?

We're struggling with that internally as well.

**Comment by szimek** [comment]
Nope, not yet :/

**Comment by szimek** [comment]
I've just published a new beta version that hopefully fixes loading it with webpack. I tried it locally with webpack 2 and both `import SignaturePad from 'signature_pad'` and `const SignaturePad = require('signature_pad')` worked fine. 

However, publishing UMD/ES6 library is new to me, so it's very possible that I broke something 😉 Let me know if it works for you. If you're using browserify, requirejs it would be awesome to confirm it still works there.

**Comment by szimek** [comment]
@collinforrester ☝️

**Comment by szh** [comment]
It works! Visual Studio 2015 doesn't seem to like it, but it does work fine.

**Comment by szimek** [comment]
@szh What does exactly Visual Studio 2015 doesn't like about it?

**Comment by szh** [comment]
![image](https://cloud.githubusercontent.com/assets/546965/22667212/72f5e7ea-ec81-11e6-9f4f-ccb65cb447c8.png)

**Comment by szimek** [comment]
@szh Are you sure you have it in package.json dependencies or devDependencies? BTW. Do you have to use `import { SignaturePad } from 'signature_pad'`? `import SignaturePad from 'signature_pad' doesn't work?

**Comment by szh** [comment]
I double checked, I do have it in package.json in dependencies: `"signature_pad": "1.6.0-beta.6",`. You're right, I don't need to use curly braces, I just did out of habit. I should note that VS had the same problem on 1.6.0-beta.1 as well - I don't remember if it did before that.

Also, before I only tested that it would transpile (I'm using TypeScript) w/o errors or warnings. I just tested a page which uses the component and I see that, whereas when using `import * as SignaturePad from "signature_pad";`, calling `new SignaturePad(canvas, opts)` would call the constructor correctly, now webpack converts it to `var signature_pad_1 = __webpack_require__(335); ... new signature_pad_1.default(canvas, opts)`, or when importing with braces, `signature_pad_1.SignaturePad`, both of which fail.

**Comment by szimek** [comment]
@szh And what happens if instead of `import * as SignaturePad from "signature_pad"` you simply do `import SignaturePad from "signature_pad"`?

**Comment by szh** [comment]
Sorry I wasn't so clear. That's what I'm doing now, and it compiles to `var signature_pad_1 = __webpack_require__(335);` at the top of the file, and then `new signature_pad_1.default(canvas, opts)`. When I do `import { SignaturePad } from 'signature_pad'` with braces, then it's `new signature_pad_1.SignaturePad(canvas, opts)`

**Comment by szimek** [comment]
@szh I'm lost. Does it work with `import SignaturePad from 'signature_pad'`? I don't plan to support every possible version of import syntax 😉

**Comment by szh** [comment]
`import SignaturePad from 'signature_pad'; new SignaturePad(canvas, opts)` generates `var signature_pad_1 = __webpack_require__(335); new signature_pad_1.default(canvas, opts)`

`import { SignaturePad } from 'signature_pad'; new SignaturePad(canvas, opts)` generates `var signature_pad_1 = __webpack_require__(335); new signature_pad_1.SignaturePad(canvas, opts)`

Both of those fail. The only thing that works is `import * as SignaturePad from "signature_pad";`

**Comment by szimek** [comment]
This will never end 😉 @szh Which version of webpack are you using? I thought I tried it with the latest webpack 1.x (though I was using my local version of this library via `npm link`) and it worked...

**Comment by szh** [comment]
I'm using Webpack 1.14.0

**Comment by szimek** [comment]
@szh It works fine for me 😕 

I created a repo I'm using to test it: https://github.com/szimek/signature_pad-webpack-1-test. It's basically the demo app, just with webpack 1.14.0. Run:
```
yarn && yarn run build && open index.html
```
to try it out.

**Comment by szh** [comment]
I was able to reproduce the issue in your demo repo by using TypeScript...

**Comment by szimek** [comment]
@szh Could you make a PR to this repo I created that adds typescript and causes this error to show up?

**Comment by szh** [comment]
https://github.com/szimek/signature_pad-webpack-1-test/pull/1

**Comment by szimek** [comment]
@szh This is probably the issue you're having: https://github.com/Microsoft/TypeScript/issues/13017 and https://github.com/rollup/rollup/issues/1156.

**Comment by szh** [comment]
Aha. Good job tracking that down

**Comment by szimek** [comment]
Looks like it might get solved soon :/ The fastest fix would probably be to switch to webpack 2.x and use the es6 version of the library ;)

**Comment by szh** [comment]
I think until it's fixed I'll continue using `import * as SignaturePad from "signature_pad";`
;)

**Comment by szimek** [comment]
I'll probably release `1.6.0-beta.6` as `1.6.0` then and just add info in the README file about this issue with TS. Thanks!

**Comment by szh** [comment]
Sounds good to me! Thanks for the help!

**Comment by dlombardi** [comment]
I'm unable to import signature_pad with the syntax ```import SignaturePad from 'signature_pad'```

**Comment by szimek** [comment]
@dlombardi Could you create a new issue with error message etc.?

**Comment by sugiserv** [comment]
I had this issue and what worked for me was directly importing the JS file as per [this comment](https://github.com/szimek/signature_pad/issues/257#issuecomment-305973105). I'm on webpack 2.2.1.

**Comment by divdax** [comment]
Same here... cannot import / require with webpack!

**Comment by szimek** [comment]
@divdax Are you using JS or TS? Which version of webpack?

**Comment by szimek** [comment]
@calvinfroedge Could you try version `3.0.0-beta.1` and see if you have the same problem?

**Comment by ibrokemypie** [comment]
I am in the same boat, is 3.0.0-beta.1 yard add-able?

**Comment by bcasci** [comment]
I don't mean to re-open this issue, but I too ran into this while migrating an application that uses signature_pad to webpack. 

The issue turned out to be a problem in the application code, not webpack or some interaction between webpack and signature_pad. Specifically a missing variable assignment keyword (var, let, const), which produced an error similar to the one @dlombardi had.

```
// Produces a SignaturePad undefined error without using var, let or const
signaturePad = new SignaturePad(document.querySelector('canvas'))
```

```
// works
let signaturePad = new SignaturePad(document.querySelector('canvas'))
```

So if you're new to ES6 and Webpack, don't forget about little things like this and maybe consider using a javascript linter to help spot similar issues.
