### ISSUE TITLE
Image size on mobile device

### ISSUE THREAD

**Issue by zazics** [szimek/signature_pad#200]
"fromDataURL()" incorrectly resize image data on Android device.
Image data is saved correctly into a local file using "toDataURL()" but when I reload it, image is half its original size.
This is due to pixel ratio. I made a quick fix in file "signature_pad.js" in "fromDataURL" function line 124.
I remove the divide by pixel ratio and now image size is correct:
width = this._canvas.width /*/ ratio*/,
height = this._canvas.height /*/ ratio*/;

**Comment by kashban** [comment]
I would rather recommend to enhance signaturePad to keep aspect ratio of a given image and fit it into a canvas of a given size.

**Comment by lexon0011** [comment]
I have the same problem. Is there already a solution for this problem?

**Comment by UziTech** [comment]
fixed in #253
