### ISSUE TITLE
How to set the width of the pen?

### ISSUE THREAD

**Issue by badongdyc** [szimek/signature_pad#201]
I tried to set the width of the pen Like this:
`canvas.getContext("2d").lineWidth=10`
But  not work
So how to set the width of the pen?

**Comment by blairanderson** [comment]
you have to use:
`minWidth` and `maxWidth`

**Comment by Poojatilekar** [comment]
I have set minwidth  and maxwidth at runtime but still not getting updated on Draw buttol click
