### ISSUE TITLE
resizing the dotSize doesn't seem to change anything.

### ISSUE THREAD

**Issue by dfunkd** [szimek/signature_pad#203]
I am trying to resize the image after signing. This makes the signature pen so small, it is nearly impossible to see. My thought was to increase the dotSize so that the signature shows up better after being shrunk, but changing the dotSize doesn't seem to do anything. Is there a max size that I am perhaps breaking or is it just not working properly?

**Comment by szimek** [comment]
Maybe it's not described clearly enough in the README, but `dotSize` defines a size of a single dot that you get when you tap or click just *once*. What you're looking for are most likely `minWidth` and `maxWidth` options.

Feel free to reopen this issue, if something still doesn't work correctly.
