### ISSUE TITLE
Sometimes it stops working properly

### ISSUE THREAD

**Issue by sourcer18** [szimek/signature_pad#206]
Sometimes it stops working correctly and shows points. I can not paint properly. Any idea why it might be?
I pass the image of what happens.
I am using it within ionic Framework.

![image](https://cloud.githubusercontent.com/assets/6040292/21808600/4296038e-d744-11e6-8d81-6aa4352f4063.png)

**Comment by grouser** [comment]
I have exactly the same problem. If I open the same page twice, it works again. I am using Chrome.

**Comment by szimek** [comment]
Related ticket: https://github.com/szimek/signature_pad/issues/211.

**Comment by szimek** [comment]
@sourcer18 Could you check (as described in #211) what events are triggered when you're trying to draw a signature?

**Comment by sourcer18** [comment]
I have noticed that the error only happens when I have connected the mobile to the chrome debug tool, so I have given it resolved. A greeting.

**Comment by szimek** [comment]
Thanks! Unfortunately, I can't replicate it using iPad Simulator from Xcode, so I'll have to find someone with a real device to debug it.

**Comment by szimek** [comment]
@sourcer18 Can this ticket be closed then?

**Comment by sourcer18** [comment]
yes! Thanks for all!
