### ISSUE TITLE
Won't be responsive

### ISSUE THREAD

**Issue by Feronax** [szimek/signature_pad#207]
I put signature_pad with the JSs, it works perfectly on the web browser with the PC but when I try it into responsive mode, the canvas get giant, out of the screen and it doesn't draw where I click, I don't find why
Can someone help me please ?
Thank you

**Comment by szimek** [comment]
Does it work correctly for you on the [demo page](https://szimek.github.io/signature_pad/)?

**Comment by Feronax** [comment]
Yes it works with my phone and and also the computer in responsive mode

Le 10 janv. 2017 6:40 PM, "Szymon Nowak" <notifications@github.com> a
écrit :

**Comment by szimek** [comment]
What you're most likely missing is this part from the demo: https://github.com/szimek/signature_pad/blob/master/example/js/app.js#L7-L21. You need to listen for window resize or orientation change and adjust canvas accordingly.

**Comment by Feronax** [comment]
Yes I saw it but don't really know what I should do with this, can you help
me please?

**Comment by szimek** [comment]
You could just copy this code and it should work ;) Otherwise it's hard for me to help you, unless you can show your code e.g. using jsfiddle, jsbin or something similar.

**Comment by Feronax** [comment]
But I already linked the app.js on my html page, shouldn't it read this
code itself? I should but it before calling the canvas so? (I'm sorry I'm
not really good with Javascript)

Yes I can show it to you but only tomorrow at work (it's 9pm where I live)


Le 10 janv. 2017 20:54, "Szymon Nowak" <notifications@github.com> a écrit :

You could just copy this code and it should work ;) Otherwise it's hard for
me to help you, unless you can show your code e.g. using jsfiddle, jsbin or
something similar.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/szimek/signature_pad/issues/207#issuecomment-271679907>,
or mute the thread

**Comment by Feronax** [comment]
I tried to put it on jsfiddle but it won't work so I'll try to explain to
you as clear as possible

• I put the canvas on a page (with a lot of other things), and in the
<head> I put the script you gave me yesterday (with also a script that is a
the top your example page on github but I don't know what is it used for)
• I linked app.js and signature_pad.js on my HTML page

But I still have the ratio problem and the size problem too, what should I
do ?

Thank you for your work, it's awesome !



2017-01-10 20:57 GMT+01:00 Guillyan Chapput <guillyan.chapput@gmail.com>:

**Comment by Feronax** [comment]
Okay sorry for the 3 post, I finnaly made it ! I had to put the app.js in 2nd like this (to keep it drawing) : 

        
        <script src="../js/signature_pad.js" type="text/javascript"></script>
        <script src="../js/app.js" type="text/javascript"></script>

And then the script and it works ! I still don't know why it wouldn't work the first time I did the same but no matter :)

Thanks again for this !

**Comment by szimek** [comment]
Can you create a demo (using jsfiddle or jsbin etc.) that shows your issue(s)?

**Comment by Feronax** [comment]
I finally made it, it's responsive and working by adding some CSS rules to
make it okay with my app
Because of your CSS with the background etc... Il totally forgot some
important rules, that's my bad sorry for the post
Thank you for this awesome work you did! ;)

**Comment by NathanCH** [comment]
I think the "resizeCanvas" documentation is incomplete. It implies by implementing the function the canvas will be responsive, but it needs to be accompanied by CSS properties. This is what @Feronax is talking about.

For example, on the demo, remove the width/height CSS properties on the canvas element and you will be able to reproduce his problem. Resizing the browser will double the canvas height and width indefinitely.

If you run into this issue, make sure you have width/height CSS properties on your canvas element else resize will not work!
