### ISSUE TITLE
It works sometimes on touch PCs

### ISSUE THREAD

**Issue by grouser** [szimek/signature_pad#211]
I am using Ubuntu 16.04 with Google Chrome. I have copied the demo page into my machine. If I start the Google Chrome in full-screen mode after restarting, it doesn't work at all. It just draws some points, however, with the mouse works fine.

If I open Google Chrome manually, it doesn't work until I open the inspector and I draw with the inspector open. Once I close it, it can work or not, it depends on it. If I open the page in two tabs, it will work in the second one straightaway but  not in the first one.

I have recorded a video where you can see what I mean.

https://youtu.be/O-00i6JpGgo

**Comment by szimek** [comment]
Hey, thanks for reporting this issue. Unfortunately, I don't have access to a device that can use mouse and touch events at the same time, so I you'd have to debug it yourself :/

As a start there are `_handleMouseDown/_handleTouchStart` and `_handleMouseMove/_handleTouchMove ` functions where you could add a simple `console.log` call to see which one is called when and with what data.

**Comment by grouser** [comment]
Those are the events that are triggered when it fails. As you can see _handleTouchMove is not triggered at all.

_handleMouseMove
_handleTouchStart
_handleTouchEnd

**Comment by szimek** [comment]
That's really strange, because start and end events come from touch, but move events come from mouse :/ Could you check if it also works like this in other browsers, e.g. Firefox?

**Comment by grouser** [comment]
I have added these lines and now it always works fine....
```
$(document).ready(function () {
    // Bind touch event listeners.
    var elem = $('html').get(0);
    elem.addEventListener('touchmove', function (e) { console.info('"touchmove" detected. Coordinates."');             });
});
```

**Comment by szimek** [comment]
I have no idea why it helps :)

**Comment by disier** [comment]
Hi. I have the same problem with Ubuntu 15.01 + Chrome 54 on Toshiba laptop with touch screen: The touchmove event doesn't trigger.

I checked that the touchcancel or touchleave events are not fired by Chrome (maybe they where interfiering). 

BUT on the online demo at sizmek.github.io/signature_pad works properly, so I suppose the error is related to that mi SignaturePad and canvas are created dynamically.

I'll try to apply the solution proposed on issue #40 or forcing a resize and I'll give feedback.

Thanks for this amazins script!

**Comment by disier** [comment]
Problem partially solved:

In my case the problem is located on Chrome (Firefox works ok) + Ubuntu:
- Go to Settings
- Go to Advanced settings
- Disable the "Protect you and your device from dangerous sites" option.
- Restart browser

Solves the problem. Don't know the reason (my app does not use window.location.replace method)

I hope it helps.

**Comment by Araeis** [comment]
Hi and thx for this great project !

I'm having a similar issue using FF 53 or Edge, no touch screen, mouse only: 
When i open the browser in full screen by default, log into my app to make a signature, nothing works, not even a point is drawed. If i resize the screen it works perfectly and immediatly. I'm using the same script as in the demo page. Same thing, if i open the FF console and perform no action, i can start drawing again.

this is strange :D

Any test i could make or try?  

Thx

Araeis

**Comment by Araeis** [comment]
Ok found it in closed queries : was a bootstrap panel problem, needed to force a rezise of the canva when tab is shown.

**Comment by UziTech** [comment]
closing as stale
