### ISSUE TITLE
How to save on server-side?

### ISSUE THREAD

**Issue by coda-apps** [szimek/signature_pad#214]
Hi folks
I just came across this, it looks amazing.
This isn't an "issue" per-se, but hopefully someone will be able to comment on this.

I want to save the signature on the server side - how would i use the signature as part of a form field i can request on the server side?

The server side technology/type i guess is less relevant - i think the missing piece is how to have the signature saved in a field value?

Thanks!

**Comment by kalihos** [comment]
Hi.

I don't think it were hard to get. The component already is converting your signature into BASE64, which you can handle with a normal JSON property inside an object, or wherever you like. I'm currently taking the signature into a JSON object property directly; biometrics into another property (with JSON.stringify), and other data. I send that object to my Express backend and, after hasing checks, I store it into my SQL Server database.

**Comment by szimek** [comment]
@coda-apps There are a few options. If you already have a form, you can add a hidden field to it and handle submit event:
```js
form.addEventListener("submit", function (event) {
  hiddenField.value =  signaturePad. toDataURL();
});
```

**Comment by szimek** [comment]
@coda-apps If you still have any issues specific to this library, please reopen this ticket. Otherwise ask a question on https://stackoverflow.com. Cheers!
