### ISSUE TITLE
Firefox svg lacking info output

### ISSUE THREAD

**Issue by chitgoks** [szimek/signature_pad#221]
Firefox requires the width and height attribute in the svg tag. Currently it does not include these so the signature will not be visible when used in the canvas.

This is just a suggestion as we can easily append our own width and height attributes to the output svg.

**Comment by szimek** [comment]
@chitgoks What do you mean exactly by "_used in a canvas_"? If I simply do 
```js
window.open(signaturePad.toDataURL('image/svg+xml'))
``` 
it works fine in FF 51, so I'm assuming you're talking about something else, right?

**Comment by chitgoks** [comment]
hi szimek. i meant when i use the signaturepad.toDataURL(svg)  as an image to be drawn in the canvas it will not be displayed unless the svg returned has a width and height attribute

**Comment by szimek** [comment]
Does it work fine in Chrome without these attributes? Could you check if it works with `width: 100%; height: auto;`?

**Comment by chitgoks** [comment]
hi szimek it is not a problem in chrome without those attributes. only in firefox. what i did was to manually add width and height attribute. to make it visibile in canvas under firefox

its not a problem really just thought you might want to know about it since not many probably know these are required in firefox when loading svg images in canvas

**Comment by szimek** [comment]
@chitgoks Hey, I've just released 1.6.0-beta.8, which should fix it - I've just added `width` and `height` to match `viewport` attribute. Could you check it out?

**Comment by chitgoks** [comment]
This is confirmed working. the generated svg can be rendered in canvas in IE, FireFox and Chrome.

By the way will there be a .min.js for this?

**Comment by szimek** [comment]
That's awesome. I think I figured out scaling issue on HiDPI as well, so the final 1.6 release might be coming soon ;)

You should have minified ES5 version in `./node_modules/signature_pad/dist/signature_pad.min.js`.
