### ISSUE TITLE
multiple signature box of multiple sizes

### ISSUE THREAD

**Issue by seetpal-smartshore** [szimek/signature_pad#226]
Hi, I have created multiple signboxes, but 

now I need to create a new signature box of diffrent size,

if disturbs the previous boxes,  or itself work disturbed.

any solution please

**Comment by szimek** [comment]
Please provide a demo showing this issue using https://jsfiddle.net, https://jsbin.com or similar service.

**Comment by seetpal-smartshore** [comment]
Thanks for your considration.

But, I have resolved it , by giving every canvas element their inline width and height rather than stylesheet

:D
