### ISSUE TITLE
const data = signaturePad.toData(); not || Not working

### ISSUE THREAD

**Issue by arbo38** [szimek/signature_pad#227]
Hello,

I have been using your super signature_pad for a project but sadly i have to report a bug concerning  the saving of the signature using the toData() method of signaturePad.

I used this method after copy pasting your exemple code and using CDN (tryed with both of them), simply changing the saving method in the saveButton event listener's else statement.

The error provided is : Uncaught TypeError: signaturePad.toData is not a function
    at HTMLButtonElement.<anonymous> (testing.js:30)

`saveButton.addEventListener("click", function (event) {
	    if (signaturePad.isEmpty()) {
	        alert("Please provide signature first.");
	    } else {
	    	const data = signaturePad.toData();
	    	console.log(data);
	        //window.open(signaturePad.toDataURL());
	    }
	});`

**Comment by szimek** [comment]
This method is only available in version 1.6.0 which is currently in beta and it not available yet on CDN. You can install it with `npm i signature_pad@beta` or `yarn add signature_pad@beta`.

If you check out the [demo page](https://szimek.github.io/signature_pad/), it works fine there.
