### ISSUE TITLE
Base64 is too Long

### ISSUE THREAD

**Issue by naveen305** [szimek/signature_pad#229]
Thanks for the Plugin!

I would like to know is there any way to reduce or decode output Base64? My Character limit DB is 4000. So, What is the best way to store?

Thanks Again!

**Comment by szimek** [comment]
Not really, unless you want to have really tiny canvas. Base64 encodes three bytes into four bytes, so you could decode it to save some space, but in this case it would be best to simply decode base64 image on the server, store it as a file (you could store it e.g. on S3 if you can't create files on your server) and only keep urls or paths to them in your DB.

**Comment by naveen305** [comment]
Thank You So Much (@szimek) for your reply. Will do that

**Comment by magalyJesus** [comment]
Hola existe la posibilidad de guardar la firma(signature_pad) en un folder estoy usando laravel

**Comment by hherrera** [comment]
Enviala por AJAX



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=hherrera@araujoysegovia.com&idSignature=22>

*Hernando Enrique Herrera Guerra*
*Director TIC*
hherrera@araujoysegovia.com <csola@araujoysegovia.com>
PBX: +57 (5) 6501190 Ext.1103
Cartagena - Colombia
www.araujoysegovia.com
________________________



2017-03-16 17:36 GMT-05:00 magalyJesus <notifications@github.com>:
