### ISSUE TITLE
signaturePad.toData(); is not a function

### ISSUE THREAD

**Issue by AmirHMousavi** [szimek/signature_pad#231]
```
const data = signaturePad.toData();
TypeError: signaturePad.toData is not a function
```
toData() is not a function and also in not included in signature_pad.js
I have installed signature_pad by `Bower`. 
how should I get the drawn signature as an array of points?
as I understood till the latest version available by npm and bower (v 1.5.x) this function is not included

**Comment by szimek** [comment]
This function is only available in 1.6.0 beta version, which has not been and most likely won't be released to Bower. If you need this feature, you can install it using `npm i signature_pad@beta` or `yarn add signature_pad@beta`. Keep in mind that it's still beta and some things might (and most likely will) change in the final version.
