### ISSUE TITLE
How to use signature pad with multiple instance of it on same page

### ISSUE THREAD

**Issue by simran66** [szimek/signature_pad#233]
I like onBeginEvent and onEndEvemt and do not want to go the general JS way with onClick event that you have in your sample using canvas element.

      <signature-pad [options]="signaturePadOptions" (onBeginEvent)="drawStart()" (onEndEvent)="drawComplete('shipperSignature')"></signature-pad>

How do I create multiple instance of signature pad (3 in my case) using ionic 2 and angularJS 2

**Comment by natcohen** [comment]
I don't know Ionic but with angular 2, simply use [directives](https://angular.io/guide/attribute-directives)

**Comment by bplogan** [comment]
`@ViewChild('sigpad1') signaturePad: SignaturePad; `
`@ViewChild('sigpad2') signaturePad2: SignaturePad;`

HTML:
` <signature-pad #sigpad1  [options]="signaturePadOptions" (onBeginEvent)="drawStart()" (onEndEvent)="drawComplete()"></signature-pad>`

`<signature-pad #sigpad2 style="border:1px solid #6995ab" [options]="signaturePadOptions2" (onBeginEvent)="drawStart2()" (onEndEvent)="drawComplete2()"></signature-pad>`

In the drawComplete() and drawComplete2() you can get the image from this.signaturePad.toDataURL() and this.signaturePad2.toDataURL()

**Comment by IngLuisCastro** [comment]
How resolve the clear()? 
![image](https://user-images.githubusercontent.com/28106554/110041817-c0a73900-7d12-11eb-8d5d-55bb64aa0dde.png)

**Comment by IngLuisCastro** [comment]
How resolve the this.signaturePad2.clear()?

![image](https://user-images.githubusercontent.com/28106554/110041921-e3395200-7d12-11eb-8ea2-6d48f643e5b7.png)
