### ISSUE TITLE
Saving image on server

### ISSUE THREAD

**Issue by lowe493** [szimek/signature_pad#234]
Hello, do you know the best way to do this? i noticed somebody else asked the question but i cannot tell the best way to include their solution, can you help?

I have resized the canvas and ideally would like a button that saves the image back to my server hosting the site with either a random name or a name from a field somewhere on the page

Thanks
Steve

**Comment by szimek** [comment]
@lowe493 Please ask this question on https://stackoverflow.com? You'll most likely get more answers there.

Anyway, it's really up to you how you want to do it and depends on what language you're using on the server. You could save them directly on the disk, send them to S3 etc., there are many options.

The easiest way is to either send content of the image to the server using XHR (Ajax) or simply create a form with a hidden field and set the value of this hidden field to the data you get from the library.

**Comment by abhiyan52** [comment]
I tried it all.I am using PHP to send the image to the server but the url exceeds the limit of the URL length.

**Comment by ryanrupp** [comment]
You should be sending the data via a POST with the payload in the body of the request rather than sounds like you're putting it in a URL parameter on a GET.

**Comment by abhiyan52** [comment]
Thank you

**Comment by h4de5** [comment]
I made something hopefully useful for users:

https://jsfiddle.net/d7ejkz1v/1/

I just added an upload javascript function to the signature pad example. It should upload the signature via ajax to the target url. on the server side you can handle those signatures as normal file uploads.
