### ISSUE TITLE
Open Signature Pad in Bootstrap Modal fails on second attempt

### ISSUE THREAD

**Issue by kourvoisier** [szimek/signature_pad#235]
Hello,

When i open signature pad within a boostrap modal like so:
$('#signaturemodal').modal('toggle');
$("#content").html(signaturehtmlcontent);
InitializeSignaturePad();

This logic works perfectly fine. However if i call the $('#signaturemodal').modal('toggle'); again to close the bootstrap modal and then reopen the boostrap modal again signaturepad javascript no longer recognizes that the canvas has content. I can draw the signature but i no longer can clear the canvas or create the signature. It acts as if the content is blank even thought i have drawn a new signature.

Any help will be appreciated.
Thanks

**Comment by szimek** [comment]
@kourvoisier Could you prepare a demo that replicates this issue using e.g. jsfiddle/jsbin/etc?
