### ISSUE TITLE
All bower based installs are broken with 1.6.0

### ISSUE THREAD

**Issue by travist** [szimek/signature_pad#238]
The issue is that with Bower, it is referencing the ```dist``` folder for the main package, but this folder is not included with bower.

**Comment by szimek** [comment]
@travist Sorry about it. If you still need Bower support, please use 1.5.3 release. I've just re-released 1.6.0 as 2.0.0 and added info about dropping support for Bower. 

Though I've just noticed that I forgot to remove `bower.json` file in 2.0.0 release...
