### ISSUE TITLE
dataurl not updated when leaving drawing area

### ISSUE THREAD

**Issue by KevinVG** [szimek/signature_pad#239]
If you use the demo in Google Chrome and start drawing in de canvas but leave the canvas area while still holding the mouse down, the dataurl is not updated so when you click the "sign" button the image is empty. Any solutions for this?

**Comment by delpierrem** [comment]
same for me

**Comment by szimek** [comment]
I can't reproduce it. I mean at some point I need to release mouse button to actually click the "Save" button.
