### ISSUE TITLE
jquery deferred with signaturepad.js

### ISSUE THREAD

**Issue by richitorres** [szimek/signature_pad#242]
![errorfirma](https://cloud.githubusercontent.com/assets/7819928/24812564/3c152446-1b90-11e7-84a1-65c7fa4eea90.PNG)

this is my code and example with the issue

Signature:
![git1](https://cloud.githubusercontent.com/assets/7819928/24814891/f9d5cabe-1b98-11e7-97bc-5c1b54327973.PNG)
DataURL:
![git2](https://cloud.githubusercontent.com/assets/7819928/24814907/01402e52-1b99-11e7-9535-8343f5215512.PNG)

output:
![git3](https://cloud.githubusercontent.com/assets/7819928/24814917/0b1e4972-1b99-11e7-9d10-43509e11ca77.PNG)

Code JS signature canvas:

![git4](https://cloud.githubusercontent.com/assets/7819928/24814936/17526b2e-1b99-11e7-86a8-5dc52b24cd7e.PNG)

Code php image decoder:

![git5](https://cloud.githubusercontent.com/assets/7819928/24814959/1ff37534-1b99-11e7-932f-73e85d7c51ea.PNG)

I have that issue with mi canvas signature, i use signature pad.js

and my signatures does not come out with background white and pencilcolor: dark, when i make the convertions with php encoder, i can send de image code: data/image-jpeg base_64., my signature come out with only background.color dark, and not show the signature.

my image signature dont does npt come out with that features, i need help about that problem

**Comment by szimek** [comment]
Could you replicate this issue using jsfiddle/jsbin/something similar and describe steps to reproduce it?

**Comment by richitorres** [comment]
steps, how i get the signature?

**Comment by szimek** [comment]
@richitorres I created a template at https://jsfiddle.net/szimek/h80phxyr/. Please try to use it to replicate your issue.
