### ISSUE TITLE
Signature is not visible until after resize

### ISSUE THREAD

**Issue by jpa57** [szimek/signature_pad#243]
Great work - very helpful to me.   Thanks.   It has a behavior I haven't root caused.   I put the signature-pad  in a modal
```html
            <div id="signature-pad" class="modal-body m-signature-pad">
```
and it works great with one caveat.   When the modal appears and I start to sign, it is entering data but it is not visible.   You can tell because the save button is permitted and sends data.   If you resize the screen before you draw, drawing is then visible.   If you resize after you've initially drawn, it seems to still have data, but only the new drawing is visible.

If I force it to call resize canvas after the modal is displayed, it works fine:
```javascript
    $(window).on('shown.bs.modal', function() {
        resizeCanvas();  
    });
```
The workaround is fine for me but thought I'd share in case there is a less hacky way to do it.

**Comment by szimek** [comment]
Thanks for reporting it. Could you create a demo of this issue in jsfiddle/jsbin/etc?

**Comment by jpa57** [comment]
Thanks Szymon, I tried here: https://jsfiddle.net/jpa57/0g1jpd8t/

It’s my first.   The real solution is buried in a rails app, so I think I must be missing something when I converted to js/html because the signature panel is small and resizing doesn’t fix the ability to sign.   But I also don’t get the warning when save is clicked with no data.. so I think it’s a bad fiddle :-)

**Comment by szimek** [comment]
@jpa57 I think you're not loading signature pad library anywhere in this demo. If you check the dev console, it says that SignaturePad is not defined.

**Comment by jpa57** [comment]
I think I fixed the module references in an updated fiddle here: https://jsfiddle.net/acthmntt/.   But it gets  a syntax error on the "export" statements in chrome and Firefox in the library references.

**Comment by szimek** [comment]
I've just created a template for reporting issues:  https://jsfiddle.net/szimek/h80phxyr/. Maybe try to modify this one.

**Comment by jpa57** [comment]
That works.   I forked it and ended up several versions later here https://jsfiddle.net/jpa57/ane764wn/3/  which exhibits the behavior

**Comment by szimek** [comment]
Uh, somehow I lost my previous comment. 

Anyway, here's a somewhat fixed version: https://jsfiddle.net/szimek/ane764wn/5/. The issue is that before you open the modal, the canvas inside it has size of 0x0 pixels, so you have to wait with resizing and the initializing the library till the modal is opened.

**Comment by jpa57** [comment]
Ah, makes sense.   So you deferred calling the constructor until the modal is open. resizeCanvas() doesn't depend on the constructor so it sets it up properly.   Thanks for looking at it!

**Comment by szimek** [comment]
@jpa57 I'm not sure what bootstrap does with modals when it closes them, but you might need to call `signaturePad.off()` to disable listening to input events.
