### ISSUE TITLE
iOS Firefox Mobile Scrolling problem

### ISSUE THREAD

**Issue by dereklim12** [szimek/signature_pad#244]
I tried this great plugin on iOS 8 firefox mobile. When I append a signature and scroll up or down quickly, the signature will be gone. I just scrolled quickly but a little, although the signature  pad is within the viewport while scrolling, it disappears.

**Comment by szimek** [comment]
Can you use e.g. jsfiddle to show what code you're using? You could check if scrolling doesn't cause `resize` event to be fired for some reason. If it's the case you could listen to [`orientationchange`](https://developer.mozilla.org/en-US/docs/Web/Events/orientationchange) event instead.

**Comment by dereklim12** [comment]
where do I use it?

**Comment by dereklim12** [comment]
Yeah I figured it out. Just add the following code below and it worked. Thanks alot @szimek  .

//window.onresize = resizeCanvas;
var orientationChange = function() {
    var dataURL = signaturePad.toDataURL();
    resizeCanvas();
    if (!signaturePad.isEmpty()) {
      // If you don't check that the pad is empty then writing data (even if that data is a blank image) will make it think you have data in there!
      signaturePad.fromDataURL(dataURL);
    }
};
window.addEventListener('orientationchange', function () { orientationChange(); });

**Comment by szimek** [comment]
You're welcome!
