### ISSUE TITLE
Question about signature size vs canvas size

### ISSUE THREAD

**Issue by shawe** [szimek/signature_pad#248]
I'm using this function https://github.com/szimek/signature_pad/issues/49#issuecomment-260976909 shared by @jaredatch that crop the user signature without whitespace.

My code now is like this, for always resize and draw, that in my opinion is not correctly explained on your example: https://github.com/szimek/signature_pad/issues/33#issuecomment-298242020 and this caused a lot of issues reported here.

I based my code in your example code but I'm using BootStrap for responsiveness and the canvas size can be set different width/height for any device, and signature is always set with canvas size, without respecting the stored canvas size and aspect ratio. Is there a way to change this behavior? In other words, I prefer to get a scaled signatured inside of canvas used by signature_pad.

For example, this can help me: https://github.com/szimek/signature_pad/issues/153#issuecomment-226755595 ?

**Comment by shawe** [comment]
Yes, it worked for me before some changes, and I think is the better way for responsive designs:

      /**
       * All credits to @jaredatch: https://github.com/szimek/signature_pad/issues/49#issuecomment-260976909
       * 
       * Crop signature canvas to only contain the signature and no whitespace.
       *
       * @since 1.0.0
       */
      function cropSignatureCanvas(canvas) {
         ...
      }

      function resizeCanvas() {
         var ratio = Math.max(window.devicePixelRatio || 1, 1);
         signatureCanvas.width = signatureCanvas.offsetWidth * ratio;
         signatureCanvas.height = signatureCanvas.offsetHeight * ratio;
         signatureCanvas.getContext("2d").scale(ratio, ratio);
      }

      function drawCanvas() {
         resizeCanvas();
         signaturePad = new SignaturePad(signatureCanvas);
         dataURL = "{$fsc->signature}";
         if (dataURL !== "") {
            var image = new Image();
            var xIniCanvas = 25;
            var yIniCanvas = 25;
            var scaleFactor = 0.85;
            signaturePad.clear();
            image.src = dataURL;
            width = image.width;
            height = image.height;
            image.onload = function () {
               signatureCanvas = document.getElementById("signature");
               if ((width / scaleFactor) > signatureCanvas.width) {
                  width = scaleFactor * signatureCanvas.width;
                  height = scaleFactor * height * (signatureCanvas.width / image.width);
               }
               if ((height / scaleFactor) > signatureCanvas.height) {
                  height = scaleFactor * signatureCanvas.height;
                  width = scaleFactor * width * (signatureCanvas.height / image.height);
               }
               signatureCanvas.getContext("2d").drawImage(image, xIniCanvas, yIniCanvas, width, height);
            };
            signaturePad._isEmpty = false;
         }
      }

      window.addEventListener("resize", drawCanvas);
      drawCanvas();

And before submiting the data to database I do this:
      $("#input_signature").val(cropSignatureCanvas(signatureCanvas));

**Comment by RajuKottedi** [comment]
i have tried your method but its not working may be i am using it differently. could you please make plunker how you have done it ?

**Comment by shawe** [comment]
@RajuKottedi yes, and I'm interested if you find a better way also. I'm using FacturaScripts and it uses RainTPL, all mentions to {$fsc->vars} are equivalent to $this->vars on the controller side.

This is my full script block on view:

`<script>
   $(document).ready(function () {
      var signatureCanvas = document.getElementById("signature");
      var clearButton = document.getElementById("clear-signature");
      var saveButton = document.getElementById("save-signature");
      var deleteButton = document.getElementById("delete-signature");
      var signaturePad;
      var PIXEL_RATIO = (function () {
         var ctx = document.createElement("canvas").getContext("2d"),
                 dpr = window.devicePixelRatio || 1,
                 bsr = ctx.webkitBackingStorePixelRatio ||
                 ctx.mozBackingStorePixelRatio ||
                 ctx.msBackingStorePixelRatio ||
                 ctx.oBackingStorePixelRatio ||
                 ctx.backingStorePixelRatio || 1;

         return dpr / bsr;
      })();
      var ratio = PIXEL_RATIO;

      /**
       * Resize canvas size to available space
       */
      function resizeCanvas() {
         signatureCanvas.width = signatureCanvas.offsetWidth * ratio;
         signatureCanvas.height = signatureCanvas.offsetHeight * ratio;
         signatureCanvas.style.width = signatureCanvas.width;
         signatureCanvas.style.height= signatureCanvas.height;
         signatureCanvas.getContext("2d").scale(ratio, ratio);
         signatureCanvas.getContext("2d").setTransform(ratio, 0, 0, ratio, 0, 0);
      }

      /**
       * Draw the signature respecting the aspect ratio and adding some whitespace padding
       */
      function drawCanvas() {
         var XPosCanvas;
         var YPosCanvas;

         resizeCanvas();
         
         signaturePad = new SignaturePad(signatureCanvas);
         
         {if condition="$fsc->firma!=''"}
         signaturePad.off();
         {/if}

         dataURL = "{$fsc->firma}";

         if (dataURL !== "") {
            var image = new Image();
            var xIniCanvas = 0;
            var yIniCanvas = 0;
            var scaleFactor = 0.80;

            signaturePad.clear();
            image.src = dataURL;
            image.onload = function () {
               width = image.naturalWidth;
               height = image.naturalHeight;
               
               // Resize the original image respecting original aspect ratio
               if (width > signatureCanvas.offsetWidth || height > signatureCanvas.offsetHeight) {
                  if (width > signatureCanvas.offsetWidth) {
                     width = signatureCanvas.offsetWidth;
                     height = (width * image.naturalHeight / image.naturalWidth);
                  }
                  if (height > signatureCanvas.offsetHeight) {
                     height = signatureCanvas.offsetHeight;
                     width = (height * image.naturalWidth / image.naturalHeight);
                  }
               }
                  
               if (ratio == 1) {
                  XPosCanvas = ((signatureCanvas.offsetWidth / 2) - ((width * scaleFactor) / 2)) * ratio;
                  YPosCanvas = ((signatureCanvas.offsetHeight / 2) - ((height * scaleFactor) / 2)) * ratio;
                  widthImageCanvas = image.naturalWidth;
                  heightImageCanvas = image.naturalHeight;
               } else {
                  //XPosCanvas = (((signatureCanvas.width / 2) - ((image.width * scaleFactor) / 2)) * ratio);
                  //YPosCanvas = (((signatureCanvas.height / 2) - ((image.height * scaleFactor) / 2)) * ratio);
                  XPosCanvas = 25;
                  YPosCanvas = 25;
                  widthImageCanvas = image.width;
                  heightImageCanvas = image.height;
               }

               ctxCanvas = signatureCanvas.getContext("2d");
               ctxCanvas.drawImage(image, xIniCanvas, yIniCanvas, widthImageCanvas, heightImageCanvas, XPosCanvas, YPosCanvas, width * scaleFactor, height * scaleFactor);
            };

            signaturePad._isEmpty = false;
         }
      }

      window.addEventListener("resize", drawCanvas);
      drawCanvas();

      {if condition="$fsc->user->admin || $fsc->firma=='' || $fsc->allow_delete"}
      clearButton.addEventListener("click", function (event) {
         signaturePad.on();
         signaturePad.clear();
         $("#input_firma").val("");
         $("#input_datos_firma").val("");
      });

      saveButton.addEventListener("click", function (event) {
         if (signaturePad.isEmpty()) {
            bootbox.alert({
               size: "medium",
               title: "<b>Atención:</b>",
               message: "El documento debe firmarse para poder guardarlo."
            });
         } else {
            this.disabled = true;
            var arrayData = [];
            arrayData.push(signaturePad.toData());
            var signatureData = JSON.stringify(arrayData);
            var signatureSVG = signaturePad.toDataURL("image/svg+xml");
            
            // RemoveBlanks: https://github.com/szimek/signature_pad/issues/49
            
            $("#input_firma").val(signatureSVG);
            $("#input_datos_firma").val(signatureData);
            this.form.submit();
         }
      });
      
      deleteButton.addEventListener("click", function (event) {
         this.disabled = true;
         signaturePad.on();
         signaturePad.clear();
         var arrayData = [];
         arrayData.push(signaturePad.toData());
         var signatureData = "";
         var signatureSVG = "";

         $("#input_firma").val(signatureSVG);
         $("#input_datos_firma").val(signatureData);
         this.form.submit();
      });
      {/if}
   });
</script>`

Using this way, works great on all devices, but the saved image was scaled on redraw , and I'm interested to only scale it when was loaded on a different device with different aspect ratio that require it. Has no sense for me obtain a different aspect ratio before and after save, but at least, is working.

**Comment by RajuKottedi** [comment]
@shawe thanks for the code. Will let you know if there is any progress :)
