### ISSUE TITLE
Feature Request: add option to handle simple clicks as paths not as circles

### ISSUE THREAD

**Issue by laDanz** [szimek/signature_pad#250]
**Do you want to request a feature or report a bug?**
Feature Request.

**What is the current behavior?**
Single clicks in SignaturePad generate svg:circle instead of svg:path on method SignaturePad.prototype._toSVG.

```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
	<circle r="1.5" cx="38" cy="67" fill="rgb(22, 90, 175)"/>
</svg>
```
This would lead me to implement also svg:circle in an other component on my project. The signature component we used prior just rendered a simple path:
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
	<path d="M 38 67 l 1 1" stroke-width="2" stroke="rgb(22, 90, 175)" fill="none" stroke-linecap="round"/>
</svg>
```
**What is the expected behavior?**
Could you change the general behaviour (or add an option) to use svg:path instead of svg:circle?
It would simplify my further processing of the signature/svg.

This code would be sufficient, in method SignaturePad.prototype._toSVG:
```
function (rawPoint) {
	      var path = document.createElement('path');
	      var attr = 'M ' + rawPoint.x.toFixed(3) + ' ' + rawPoint.y.toFixed(3) + ' l 1 1';

	      path.setAttribute('d', attr);
	      path.setAttribute('stroke-width', '2');
	      path.setAttribute('stroke', _this2.penColor);
	      path.setAttribute('fill', 'none');
	      path.setAttribute('stroke-linecap', 'round');

	      svg.appendChild(path);
  }
```

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**
SignaturePad: current
browser/os: all

**Comment by UziTech** [comment]
closing as stale

**Comment by ofiroha** [comment]
Hi,
I know it's an old request, but can it please be implemented?
I'm working on a project where I can only use svg paths.
So I converted the signature's svg base64 to paths by doing a DOMParser, and because dots created as circles, they are not showing up in the final result.

this is what i'm trying to do, it works fine for the paths, but it won't include the circles.

```
var svgurl = signaturePad.toDataURL('image/svg+xml');

var svgbase64 = svgurl.split(",")[1]
let svg = atob(svgbase64)
let parser = new DOMParser();
let xmlDoc = parser.parseFromString(svg, 'image/svg+xml');
let d = xmlDoc.getElementsByTagName('path');
for (i = 0; i < d.length; i++) {
      let text = d[i].getAttribute('d');
      console.log(text)
    }
```

thanks.
