### ISSUE TITLE
Improve drawing quality

### ISSUE THREAD

**Issue by szimek** [szimek/signature_pad#251]
### Issue
Drawn lines are not very smooth, especially when drawing slowly. Skipping points too close to each other and throttling was supposed to improve it and it did, but not very much.

#### Chrome Canvas app
https://canvas.apps.chrome 
Doesn't draw lines with variable width, but the lines are very smooth. Seems to be using [Ink library](https://chromium.googlesource.com/chromium/src/third_party/+/5c5cea33ebab6046cd2dfc381faeb2d2d52c1486/ink).

#### iMessage
Looks like iMessage uses some dark magic and gives much better results than this library. It might be a good idea to experiment a bit to try to achieve similar results.

iMessage (iPhone 5):
![imessage](https://cloud.githubusercontent.com/assets/9873/25785574/8bb5cb7a-3384-11e7-84f2-a0ba6654be5b.jpg)

SignaturePad (iPhone 5):
![signature-pad](https://cloud.githubusercontent.com/assets/9873/25785575/9a879c82-3384-11e7-9455-113b238b485c.jpg)

#### ezl/signature-pad
In https://github.com/szimek/signature_pad/issues/319 it has been reported that https://github.com/ezl/signature-pad plugin generates smoother lines; it might be worth looking into it as well

### Some interesting ideas:
* make width changes smoother, by interpolating velocity along more than just the previous point (?)
* use more steps to draw a curve to get rid of visible circles (?)
* check if faster device produces smoother lines (EDIT: it doesn't)
* try to skip points too close to each other (EDIT: implemented!)
* https://www.youtube.com/watch?v=H79iUsai6uc / https://github.com/eur00t/Effective-Curve-Fitting
* https://www.particleincell.com/2012/bezier-splines/

One of the problems is that changing already drawn curve (even if it's just the last few points), would most likely require to redraw the whole thing...

Any ideas, suggestions and PRs are welcome ;)

**Comment by claudiorivetti** [comment]
This is a quick and dirty experiment I made last summer. The idea is to smooth the path with a function over a moving window. The window is set in the code but could be adjusted based on speed. For simplicity I used a fixed pen width.
http://scvsa-servizi.campusnet.unipr.it/tools/signature/signature_pad/example/

cl.

**Comment by szimek** [comment]
@claudiorivetti That's really awesome! I remember one of Google drawing apps using the same solution. I'll check it out. However, the strange thing about iMessage that the lag is no larger than in this library...

If you use a finger to draw, instead of a stylus, the touch point is pretty wide (for sure wider than one pixel) and I'm not really sure how mobile apps or browsers actually figure out the exact coordinates of touch events in such case. Maybe it would be possible to somehow adjust the coordinates received by the browser based on coordinates of the previous points and current speed and not only interpolate paths between them. I'm not sure if it makes any sense or if I'll have time to experiment with it. I'd have to make the points visible to see if the curves themselves could be improved or if points are not along the "ideal" lines.

**Comment by halo** [comment]
@claudiorivetti How can I obtain such magic? :) Admittedly it would have to be a little bit more realistic, either entirely dynamically, or just maybe just a thicker line would maybe suffice. 

Most people I observed write rather slow for some reason and it looks rather like from the 90s:

![screen shot 2017-05-15 at 19 58 45](https://cloud.githubusercontent.com/assets/11441/26071598/f45d6a6e-39a8-11e7-9f10-64e2afad974b.jpg)

**Comment by halo** [comment]
What strikes me is that other libraries don't have dynamic width at all, but generally appear "cleaner" to me. E.g compared to the image I posted above.

such as [this](http://www.supersignature.com/) and [this](https://willowsystems.github.io/jSignature/#/demo/))
![screen shot 2017-06-20 at 16 44 32](https://user-images.githubusercontent.com/11441/27339332-ce346c02-55d7-11e7-837c-b80016c39940.jpg)

![screen shot 2017-06-20 at 16 44 48](https://user-images.githubusercontent.com/11441/27339335-cff33a96-55d7-11e7-9a5b-fcb498ee691b.jpg)

**Comment by szimek** [comment]
@halo I'd like to avoid post-processing/auto-fixing, though I agree that the results are usually much nicer. The thing is that, at least in iMessage, it is possible to have smooth lines without any post-processing. There are a few things I'd like to try, e.g. skip points that are too close to the each other. Throttling has been added recently, but if someone draws really slowly, it won't help a lot.

Another thing is that I don't use this library anymore, so unless I find some example how to provide smoother lines (just like I did with [posts by Square](https://medium.com/square-corner-blog/smoother-signatures-be64515adb33)) I don't think I'll have a lot of time to investigate it myself.

**Comment by szimek** [comment]
@halo I did a quick experiment, where I'm skipping a point if it's too close to the previous one. It seems to improve drawing quality when one is drawing very slow, but introduces a noticeable lag. Still pretty far from what's possible in iOS iMessage or Notes apps though :/ The demo is available at http://signature-pad.surge.sh/ and you can try to change `signaturePad.minDistance` value to see how it impacts the drawing. The default value is 5, which means that if the previous point is closer than 5px to the new one, the new one is skipped.

Also, I added a timing using `performance.now` to `#_updateStroke` function (not present in the demo) and, unless there's something async going on or I messed something up, it looks like it takes less than 1 millisecond to add a point and draw a curve. It means there's plenty of time to do more fancy processing.

**Comment by halo** [comment]
I will very gratefully try this out in production with real users and give you feedback. Do you have a branch on Github or a dist file I can use?

I like the approach, thank you very much for giving it a try.

**Comment by szimek** [comment]
@halo If you'd like to build your own version (e.g. minified), I just pushed it to https://github.com/szimek/signature_pad/tree/improve-drawing-quality branch.

**Comment by halo** [comment]
Thank you, I just took the compiled one from the demo page and deployed it to production. Will let you know how it's being received in the next 1-3 weeks.

**Comment by fa-at-pulsit** [comment]
@halo & @szimek  - take a look on this two links, it can be helpful 
- http://paperjs.org/examples/path-simplification/
- http://thejosephturner.com/simpleline/

**Comment by szimek** [comment]
@fa-at-pulsit Thanks! However, both examples simplify the path *after* user stops drawing it, which I'd like to avoid. Maybe I'll give up at some point and just go with this solution, but I hope it's possible to get better results without noticeable latency.

**Comment by halo** [comment]
> I'd like to avoid post-processing/auto-fixing

Just out of curiosity, why is that?

- [ ] Keeping the code simple and robust, avoiding bugs
- [ ] Not messing up end-user experience with visual glitches
- [ ] Lock-in that prevents e. g. exposing drawing stream while writing 
- [ ] Existing post-procesisng solutions are not mature enough

By the way, from the subjective feedback I received from end-users over the past week, I can tell that drawing quality has immediately been apprehended as "has clearly improved" (by regularly recurring signers). I'll see if I can get some more meat to the bone, yet I will not be able to expose real-world signatures here for comparison.

All I can say is that most people write ridiculously slow and small, now matter how much you tell them. ;) Also, I suspect the device (Surface Pro) to be a major culprit. At some point using an iPad with one of those fancy new pens may give me more insight into that.

**Comment by fa-at-pulsit** [comment]
@szimek this other example simplified the path on the fly (i think so) 
take a look on this video https://www.youtube.com/watch?v=H79iUsai6uc
sources -> https://github.com/eur00t/Effective-Curve-Fitting
and i get much better effect on retina with canvas resizing  like
`<canvas  width="1000" height="200" style="width: 500px; height: 100px;"/> `

**Comment by szimek** [comment]
@fa-at-pulsit Thanks! I played a bit more with iMessage app and (probably thanks to my super slow iPhone 5) it seems that it does post-processing on the fly as well, but it's barely noticeable.

I have to release a new version with some bug fixes first, but then I'll try to release a new version with optional skipping points that are too close to each other and then look into this on the fly post-processing - it looks really promising.

**Comment by halo** [comment]
So, after 1.5 months in production, I can confidently say that the quality has greatly improved by this PR. Several dozen people have signed again and again and it looks much better compared to what their signatures looked like before.

![](http://www.reactiongifs.com/wp-content/uploads/2013/01/yes-awesome-oldschool.gif)

**Comment by halo** [comment]
> I have to release a new version with some bug fixes first, but then I'll try to release a new version with optional skipping points that are too close to each other

Hi! Are you going to need backwards compatibility? Or is it just [this commit](https://github.com/szimek/signature_pad/commit/88a9946ef64c666a79b9ef433502ed399fdf4b75) as it is?

**Comment by Hanzofm** [comment]
Is there any way to improve the draw speed?

**Comment by UziTech** [comment]
closing as stale
