### ISSUE TITLE
Issue with _fromData

### ISSUE THREAD

**Issue by jsg006** [szimek/signature_pad#252]
I am implementing this after upgrading from an old version of a signature pad and I ran across a minor annoyance. When you run fromData on a series of points it will draw it as normal, but it will not add them to the _data variable. It was a simple fix and I've fixed it on my local site, but it might be worth adding an update so that the issue is avoided in the future.

In short, for every pointGroup found in the parameter pointGroups, it pushes an empty array onto _data, just like in _strokeBegin and for every point in that group it adds it to the last possible group in _data just like in _strokeUpdate. 

```
SignaturePad.prototype._fromData = function (pointGroups, drawCurve, drawDot) {
  for (var i = 0; i < pointGroups.length; i += 1) {
    var group = pointGroups[i];
// like _strokeBegin
    this._data.push([]); 
    if (group.length > 1) {
      for (var j = 0; j < group.length; j += 1) {
        var rawPoint = group[j];
        var point = new Point(rawPoint.x, rawPoint.y, rawPoint.time);
// start like _strokeUpdate
        this._data[this._data.length - 1].push({ 
            x: point.x,
            y: point.y,
            time: point.time
        }); 
// end like _strokeUpdate

// . . .
```

**Comment by UziTech** [comment]
closing this as stale
