### ISSUE TITLE
Signature on Mobile Device Missing on Scroll

### ISSUE THREAD

**Issue by asithade** [szimek/signature_pad#254]
On mobile phones, after you draw your signature and scroll down a little, if you go back up, it vanishes from the canvas. The data is still there, but the signature goes missing. 

Anyone else able to replicate this issue?

**Comment by bat020** [comment]
We're getting exactly the same problem.

**Comment by szimek** [comment]
Could you check if resize event is triggered during scroll?

**Comment by asithade** [comment]
@szimek You mean in our customized code? I have disabled any code that triggers the resize to happen to test it as well and the issue still persists.

**Comment by szimek** [comment]
I mean that the library itself doesn't set canvas width or height, which would result in clearing the canvas. I'm just wondering if you have any code that does it, like [these lines](https://github.com/szimek/signature_pad/blob/master/example/js/app.js#L16-L17) in the demo app.

**Comment by asithade** [comment]
This was in the code previously but commented out:

```
	if($('div').hasClass('consent-signature')){
		var canvas, signaturePad; 
		// var canvas_width = $('.consent-signature .col-md-8 .row').width();
		// $('canvas').attr('width', canvas_width);

		canvas = document.querySelector("canvas");
		signaturePad = new SignaturePad(canvas);

		$('.clear-signature').click(function(ev){
			ev.preventDefault();
			signaturePad.clear();
		});
	}
```

**Comment by szimek** [comment]
@asithade So you don't handle `window.resize` or `orientationchange` event anywhere?

**Comment by asithade** [comment]
This is the only other code that I can see that has window.resize

```
	$(window).on('resize', function() {
		$('.modal:visible').each(reposition);
		// if($('div').hasClass('consent-signature')){
		// 	var canvas_width = $('.consent-signature .col-md-8 .row').width();
		// 	$('canvas').attr('width', canvas_width);
		// }
	});
```
But again, I've commented out that section too but the issue still persists.

**Comment by bat020** [comment]
just FYI we got around this problem by storing the canvas width & height locally and altering the resize event handler to only set canvas.width and canvas.height if the new dimensions differ from the old ones. so the signature box clears on an actual resize (eg if the device orientation changes) but not on scrolls etc. we figured this was slicker than stashing and redrawing the signature.

**Comment by andreiiovan** [comment]
Hi guys,

I have the same problem with the scrolling. The signature disappears if I scroll fast (normal scroll). If I scroll very slow, the signature will stay. There is no issue on Chrome browser on PC (even in emulation mode on mobile devices). The problem encounters only on mobile device browsers.

Any fix that came out? It will be greatly appreciated! Thanks!

**Comment by szimek** [comment]
Could you create a demo page that shows this issue using codepen, jsfiddle or anything that works fine on mobile devices? Then I could check if there are any strange resize events being fired during scroll.

**Comment by andreiiovan** [comment]
@szimek - The problem for me is indeed window.onresize action.

```
      function resizeCanvas() {
        var ratio = Math.max(window.devicePixelRatio || 1, 1);
        canvas.height = canvas.offsetHeight * ratio;
        canvas.width = canvas.offsetWidth * ratio;
        canvas.getContext("2d").scale(ratio, ratio);
      }

      //window.onresize = resizeCanvas;
      resizeCanvas();
```

To have fixed it by take window.onresize action out. I still have a problem when changing the orientation (there's a bit of delay between the touch point and where the line is drawn), but only on the far right of the canvas.

In my case I scale the canvas only when loading the page and that's it.

**Comment by Eioxin** [comment]
> @szimek - The problem for me is indeed window.onresize action.
> 
> ```
>       function resizeCanvas() {
>         var ratio = Math.max(window.devicePixelRatio || 1, 1);
>         canvas.height = canvas.offsetHeight * ratio;
>         canvas.width = canvas.offsetWidth * ratio;
>         canvas.getContext("2d").scale(ratio, ratio);
>       }
> 
>       //window.onresize = resizeCanvas;
>       resizeCanvas();
> ```
> I fixed it by taking window.onresize action out. I still have a problem when changing the orientation (there's a bit of delay between the touch point and where the line is drawn), but only on the far right of the canvas.
> 
> In my case I scale the canvas only when loading the page and that's it.

Thanks mate. That was the solutions for me.

**Comment by tcmgroup** [comment]
> @szimek - The problem for me is indeed window.onresize action.
> 
> ```
>       function resizeCanvas() {
>         var ratio = Math.max(window.devicePixelRatio || 1, 1);
>         canvas.height = canvas.offsetHeight * ratio;
>         canvas.width = canvas.offsetWidth * ratio;
>         canvas.getContext("2d").scale(ratio, ratio);
>       }
> 
>       //window.onresize = resizeCanvas;
>       resizeCanvas();
> ```
> 
> I fixed it by taking window.onresize action out. I still have a problem when changing the orientation (there's a bit of delay between the touch point and where the line is drawn), but only on the far right of the canvas.
> 
> In my case I scale the canvas only when loading the page and that's it.

Works for me.
