### ISSUE TITLE
devicePixelRatio used on fromDataURL but not on toDataURL on 2.2.1 & 1.5.3

### ISSUE THREAD

**Issue by danielocdh** [szimek/signature_pad#255]
I found size inconsistencies when saving/loading images as DataURL on mobile, I checked the code and it seems like toDataURL is missing the devicePixelRatio calculation

**Comment by akz92** [comment]
I'm facing this on 1.5.3 too, when loading a saved image it takes only half of the canvas dimensions.

**Comment by UziTech** [comment]
closing as stale
