### ISSUE TITLE
Signature pad requires window resize before pen strokes will display

### ISSUE THREAD

**Issue by oshihirii** [szimek/signature_pad#259]
Signature Pad v2.1.1
Chrome Version 58.0.3029.110
PC (Windows 7)

I have a successful implementation running in a barebones html scenario, but when I have transferred it into a large application, the signature pad requires a resize before any strokes will appear.  

I'm just wondering if this is a "known issue" under certain circumstances?

Unfortunately, I cannot post code from the large application I have transferred it to in order to give more context, but I was just wondering if this sort of behaviour had come up before and if so what the solution was.  

The only anomalies I can discern from the demo are:

- the `<body>` tag does not have `onselectstart="return false"`

- the `app.js` content resides within a function that is called when a certain item is clicked

Thank you.  

**Edit:**  Hmm, in Developer Tools, I can see the canvas width and height are 0 when the page loads, i'm not sure why.  The resize function rectifies this by changing those values.  Does it matter that the fieldset that the signature pad is within is initially set to display none (it is a stepped form, where only one step is displayed at a time)?  

**Edit:**  Just read this re:  [HTMLElement.offsetWidth](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetWidth):

> In compliance with the specification, this property will return null on Webkit if the element is hidden (the style.display of this element or any ancestor is "none") or if the style.position of the element itself is set to "fixed".

So perhaps having the fieldset containing the signature pad as display none, will prevent the initial `resizeCanvas()` function from running properly:

```
function resizeCanvas() {
var ratio =  Math.max(window.devicePixelRatio || 1, 1);
canvas_left.width = canvas_left.offsetWidth * ratio;
canvas_left.height = canvas_left.offsetHeight * ratio;
canvas_left.getContext("2d").scale(ratio, ratio);

canvas_right.width = canvas_right.offsetWidth * ratio;
canvas_right.height = canvas_right.offsetHeight * ratio;
canvas_right.getContext("2d").scale(ratio, ratio);
}
```

Is there an alternative way to get the values that `offsetWidth`  and `offsetHeight` provides?

**Comment by szimek** [comment]
I don't know about any alternatives for `offsetWidth` and `offsetHeight` (I'm not saying there aren't any), but it seems like a very similar problem to the one people are having when they are using it with some UI libraries like Bootstrap, where canvas is e.g. inside a modal, which is initially hidden (and has size of 0x0px) and then shown only once a button or sth happens. In case of Bootstrap, there are events you can listen to to call `resize` function. Maybe you have a similar option?

**Comment by oshihirii** [comment]
FYI, I deployed a jQuery `show()` / `hide()` fieldset logic where I re-initalised signaturePad each time fieldset 03 (the fieldset with the signature pad) was clicked (as i had to initialise signaturePad when the fieldset was in a "shown" state for the canvas to have the right height and width), but it became problematic for users - they didn't want to lose the signature when going back to a previous step.  

My main user scenario is tablets, so my goals were:

- Persistent signature across steps
- (Possibly preventing window resize, to prevent signaturePad clear)  
- (Possibly preventing screen orientation change, to prevent signaturePad clear)
- (Retain quality and accuracy of exported image data)  

Here is [work in progress jsFiddle](https://jsfiddle.net/rwone/zkfkdy6h/) which effectively achieves the first two of these goals.

**Comment by UziTech** [comment]
closing as stale
