### ISSUE TITLE
Can .toDataURL value be used in .fromDataURL?  

### ISSUE THREAD

**Issue by oshihirii** [szimek/signature_pad#265]
I am trying to capture signature at resize event and then redraw signature afterwards.

Readme states:

```
// Draws signature image from data URL.
// NOTE: This method does not populate internal data structure that represents drawn signature. 
// Thus, after using #fromDataURL, #toData won't work properly.
signaturePad.fromDataURL("data:image/png;base64,iVBORw0K...");
```

But also states:

> This clearing of the canvas by the browser can be annoying, especially on mobile devices e.g. when screen orientation is changed. There are a few workarounds though, e.g. you can lock screen orientation,  or read an image from the canvas before resizing it and write the image back after.

How do you do this last part:

> read an image from the canvas before resizing it and write the image back after.

if you cannot use data from `.toDataURL` in `.fromDataURL`?  

I tried the following but the lines gets increasingly blurrier:

```
  $(window).resize(function() {
    var left_flag = 0;
    var right_flag = 0;
    if (signaturePad_left.isEmpty() === false) {
      var temp_left_sig = signaturePad_left.toDataURL();
      signaturePad_left.clear();
      left_flag = 1;
    }
    if (signaturePad_right.isEmpty() === false) {
      var temp_right_sig = signaturePad_right.toDataURL();
      signaturePad_right.clear();
      right_flag = 1;
    }
    resizeCanvas();
    if (left_flag === 1) {
      signaturePad_left.fromDataURL(temp_left_sig);
    }
    if (right_flag === 1) {
      signaturePad_right.fromDataURL(temp_right_sig);
    }
  });
```

Edit:  Actually, after re-reading this, I think it means that you cannot use `.toDataURL()` on an image that was created from `.fromDataURL()` - but this still creates problems after resizing once, if using the above method, and image is still blurry.

**Comment by szimek** [comment]
In theory this:
```js
const data = signaturePad.toDataURL();
signaturePad.clear();
signaturePad.fromDataURL(data);
```
shouldn't change anything. If you're getting more and more blurred version then it's either a bug in the library or your code.

Another thing you can try is to use is:
```js
data = signaturePad.toData()
signaturePad.clear();
signaturePad.fromData(data);
```

**Comment by oshihirii** [comment]
[jsFiddle](https://jsfiddle.net/rwone/o86gm47h/) - you can see blurriness by drawing signature, then resizing jsFiddle result window several times. 

I am responding to resize event like this:

```
$(window).resize(function() {

  var left_flag = 0;
  var right_flag = 0;

  // only capture left signature if there is one
  if (signaturePad_left.isEmpty() === false) {
    var temp_left_sig = signaturePad_left.toDataURL();
    signaturePad_left.clear();
    left_flag = 1;
  }

  // only capture right signature if there is one
  if (signaturePad_right.isEmpty() === false) {
    var temp_right_sig = signaturePad_right.toDataURL();
    signaturePad_right.clear();
    right_flag = 1;
  }

  resizeCanvas();

  // if there was a left signature, redraw it
  if (left_flag === 1) {
    signaturePad_left.fromDataURL(temp_left_sig);
  }

  //  if there was a right signature, redraw it
  if (right_flag === 1) {
    signaturePad_right.fromDataURL(temp_right_sig);
  }

});
```

**Comment by vidhya5** [comment]
var data = $("#DrawnSignatureData").val();

            if (data) {
                $("#Type").hide();
                $("#Draw").show();
                alert(data);signaturePad.clear();
                signaturePad.fromData(data);
            }
My scenario is little different. I am trying to redraw the image when I revisit the page. I have stored the value toData on a hidden text field . The value is available. But the canvas is still blank. 
Am I doing anything wrong?

**Comment by UziTech** [comment]
closing as stale

**Comment by joelatkins23** [comment]
I have the same issues.
If anyone has a result, let me know.
Thank you
