### ISSUE TITLE
Send to php POST method. 

### ISSUE THREAD

**Issue by fumson** [szimek/signature_pad#267]
How can I send a signature to a php file by POST method?

**Comment by tusharkhatri29** [comment]
@fumson 

You can get the dataurl using var data = signaturePad.toDataURL("image/jpeg");

**Comment by mariusares** [comment]
I have the same issue here. Can anyone make it obvious how we can send the dataUrl using post ?
var dataUrl = signaturePad.toDataURL("image/jpeg");
I have the following :+1:
<script type="script">

var signaturePad = new SignaturePad(document.getElementById('myCanvas'), {
  backgroundColor: 'rgba(255, 255, 255, 0)',
  penColor: 'rgb(0, 0, 0)'
});


function getSignaturePad() {
var imageData = signaturePad.toDataURL();
 document.getElementsByName("image")[0].setAttribute("value", imageData);
}

$('#form-submit').submit(function() {
  getSignaturePad();
  return true;
 });

  </script>

PHP :
echo '<img src="' . $_POST['image'] . '">';

$upload_dir = "upload/";  //implement this function yourself
$img = $_POST['image'];
$img = str_replace('data:image/png;base64,', '', $img);
$img = str_replace(' ', '+', $img);
$data = base64_decode($img);
$file = $upload_dir."image_name.png";
$success = file_put_contents($file, $data);
//header('Location: '.$_POST['return_url']);
    echo "Signature Uploaded Successfully.";
    echo $file;

}
and HTML side

<form method="POST" action="" enctype="multipart/form-data" id="form-submit" name="myform">
    <section>
        <div class="container">
          <div class="boxarea">
            <div class="signature-pad" id="signature-pad">
              <div class="m-signature-pad">
                <div class="m-signature-pad-body">
                  <canvas id="myCanvas" width="625" height="318" style="border: 1px solid black"></canvas>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    <input type="hidden" id='image' name="image" value="">
    <input type="submit" name="submit" value="submit">
  </form>


is not working. The post is blank
what do I do wrong?
Thank you
