### ISSUE TITLE
Canvas size responsive

### ISSUE THREAD

**Issue by 50l3r** [szimek/signature_pad#268]
Hi,

I need to create a responsive signature pad with 100% width and specific height (300px)

How can i do this?

**Comment by meorfi** [comment]
@50l3r was you able to do that ? 
@szimek any suggestions please ? :) I see a PullRequest exist for that, and is old old :) 
https://github.com/szimek/signature_pad/pull/100

**Comment by Amsvartner** [comment]
Afaik you can't set canvas width to a percentage, but you can read the width of the parent element with jQuery, and use regular javascript to set the width. Do this before you intialize SignaturePad.

`var canvas = document.querySelector("canvas");`
`var canvasWidth = $("#myCanvas").parent().outerWidth();`

`canvas.setAttribute("width", canvasWidth);`

` this.signaturePad = new SignaturePad(canvas);`

**Comment by 50l3r** [comment]
Sorry for delay.

It works :)

**Comment by mark1828** [comment]
When I change the width, the coordinates of my cursor doesn't match my drawing. Anyone has the same problem?

**Comment by yokean1605** [comment]
Thanks, it works to for me.
