### ISSUE TITLE
Wierd incremental draws

### ISSUE THREAD

**Issue by vmexia** [szimek/signature_pad#269]
Hello,

I'm having a kinda wierd behaviour on my mobile app. When I draw something on the canvas, on stoke finish, the previous state of the current draw gets incrementally drawn on the canvas. 

[First iteration](http://imgur.com/a/TZpL5)
[Second iteration](http://imgur.com/a/OBWu5)
[Third iteration](http://imgur.com/a/o2YxC)

note: the red areas indicate the new element.

This is a cordova app with react. The version 1.5. of signature pad was working flowlessly, today I decided to update to the newest version (2.2.0) and this started to happen. Any idea of what might be the cause? I find it wierd because this doesn't happen when I'm debugging the app on chrome.

Best regards

**Comment by szimek** [comment]
No idea. Can you try to replicate it e.g. in https://jsfiddle.net/szimek/h80phxyr ?

**Comment by vmexia** [comment]
I don't know how to replicate it, but I do know that it only happens on the devices, when I test it on the computer it works well.
