### ISSUE TITLE
i use fromData after toData, and the draw is not completely the same .

### ISSUE THREAD

**Issue by c4cat** [szimek/signature_pad#270]
I don't know why i get data and set data will make the draw different.(the line will become shorter)

I make a demo here https://jsfiddle.net/h80phxyr/7/

**There is the pic compare.**
https://i.stack.imgur.com/fLNmM.png
https://i.stack.imgur.com/bleJn.png

I use  v2.2.0 and chrome 58

Many thanks!

**Comment by szimek** [comment]
Most likely it's a bug - probably not all data points are stored (the ones at the end of each stroke) and thus when recreating image from these points, each line is a bit shorter.

**Comment by c4cat** [comment]
@szimek thanks for reply. I will take some time try to fix the bug. By the way, signature pad is a wonderful JavaScript library.

**Comment by c4cat** [comment]
@szimek 
I think i found the question.
we should push the end point to this._data when _strokeEnd.

```
SignaturePad.prototype._strokeEnd = function (event) {
  var canDrawCurve = this.points.length > 2;
  var point = this.points[0];

  if (!canDrawCurve && point) {
    this._drawDot(point);
  }

  if (typeof this.onEnd === 'function') {
    this.onEnd(event);
  }
 // ************* new add ************
  this._data[this._data.length - 1].push({
    x: point.x,
    y: point.y,
    time: point.time,
    color: this.penColor
  });
 // ************* new add ************
};
```

**Comment by tempbing** [comment]
I also met for this problem.
I'll try it later...

**Comment by tempbing** [comment]
@szimek   It seems that , this bug is not fixed . 


---------------------------------
html dom:
  <canvas id="signature_container" width="400" height="500"></canvas>
js:
  var signatureId = '#signature_container'; 
  signaturePad = new SignaturePad($(signatureId)[0], {
                backgroundColor: 'rgb(255,255,255)',  
                //penColor: 'green',
                minWidth: 3, 
                maxWidth: 3, 
            });
 
---------------------------------

I see this bug again .

**Comment by szimek** [comment]
@tempbing I don't - check out the jsfiddle (https://jsfiddle.net/h80phxyr/7/) posted by @c4cat. It works fine now. Are you sure that you're using version 2.2.1?

**Comment by tempbing** [comment]
# @szimek   I'm sure , and my step like these :

**Comment by tempbing** [comment]
@szimek I'm sure , and my step like these ..

**Comment by tempbing** [comment]
@szimek I'm sure , and my step like these ..
1.  Draw some curves(like letter ‘J’ ) (js code use  signaturePad.fromData() +  signaturePad.toData())
2. js code use  signaturePad.fromDataURL()  + signaturePad.toDataURL())
-----------------
You can see the bug.
-----------------
Others:
 I also see anther problem . When change the setting ,` signaturePad.minWidth = 5;
            signaturePad.maxWidth = 10;
            signaturePad.penColor = "rgb(66, 133, 244)";`
  use  signaturePad.fromData() +  signaturePad.toData()  . The problem is distinct .

**Comment by tempbing** [comment]
@szimek    A new Demo (https://jsfiddle.net/h80phxyr/10/)

**Comment by szimek** [comment]
Here's a fixed version: https://jsfiddle.net/szimek/h80phxyr/11/ You need to set canvas size in CSS and adjust its size in JS as well. The canvas size adjustment code is based on the code from the demo (https://github.com/szimek/signature_pad/blob/master/example/js/app.js#L11-L19).

**Comment by tempbing** [comment]
Thanks very much for reply. 
On this fixed version: (https://jsfiddle.net/szimek/h80phxyr/11/) 
I see the problem again.
You can draw some curves (like six letters "jjJJjj") ,then click "undo" button six times .
On this online demo.: (https://jsfiddle.net/szimek/h80phxyr/11/) 
I have a try ,maybe i don't  understand ...
The picture compare.
()

**Comment by szimek** [comment]
@tempbing Nah, you're right. It's much less noticeable now, but something is still off. I'll check it out.

**Comment by amolumesh12** [comment]
@szimek , am displaying image on signature-pad...when i draw only  on signature-pad and do undo() operation it  perform correctly..but when am displaying image on signature-pad and  then perform undo then it clear entire image first and then other data..i want to undo only data on image..not an image
my takephoto function()
public  takePicture(sourceType, DestinationType) {
    var options = {
      quality: 100,
      
      //sourceType: sourceType,
      // destinationType: DestinationType,
      destinationType: this.camera.DestinationType.DATA_URL,
      saveToPhotoAlbum: true,
      correctOrientation: true,
      //mediaType: 2,
      encodingType: this.camera.EncodingType.JPEG,
     mediaType: this.camera.MediaType.PICTURE,
     // allowEdit : true,
      //height:100,
      //width:200,
     
      targetWidth :1000,
      targetHeight:1000,
      // width: window.screen.width,
      // height: window.screen.height,
     
    };


    this.camera.getPicture(options).then((imagePath) => {
      if (this.platform.is('android') && sourceType === this.camera.PictureSourceType.PHOTOLIBRARY) {
        this.filePath.resolveNativePath(imagePath)
          .then(filePath => {            
            this.lastImage = this.createFileName();           
            this.tempPath = "data:image/jpeg;base64," + imagePath;
            this.selectedImagePath = imagePath;
           
           //this.signaturePad.fromDataURL(this.tempPath);
          //this.tempPath = this.signaturePad.toDataURL(this.tempPath);
          });

      } else {
       
        this.lastImage = this.createFileName();
       this.tempPath = "data:image/jpeg;base64," + imagePath;
      
     this.selectedImagePath = imagePath;
     this.signaturePad.fromDataURL(this.tempPath);
      // this.selectedImagePath
        this.tempPath = this.signaturePad.toDataURL(this.tempPath);
        // let canvas = document.querySelector('canvas');

        // this.signaturePad.set('canvasWidth', canvas.this.tempath);
        // this.signaturePad.set('canvasHeight', canvas.this.tempath);
        // let tempPathheight =500; 
        // this.signaturePad.set('temPath', tempPathheight);
        //this.tempPath.Height = CanvasHeight;
      }
    }, (err) => {
     // this.presentToast(err);
     console.log(err);
    });
    
  }

  private createFileName() {
    var d = new Date(),
      n = d.getTime(),
      newFileName = n + ".jpg";
    return newFileName;
  }
  

and my perform()-undo function 
 perform()
      {
        var data = this.signaturePad.toData(); 
        if (data) {
        
          data.pop(); // remove the last dot or line
         this.signaturePad.fromData(data);
      }
       }
     
please help me to correct my perform() function

**Comment by szimek** [comment]
@amolumesh12 I'm not sure if there's an easy way to do it at the moment, because `SignaturePad#fromData` clears the canvas before it redraws everything. If you draw your image after calling this method, it would overwrite the signature.

Currently, you could modify the library to remove `this.clear()` call from `SignaturePad#fromData` method. I could change this method to not call `SignaturePad#clear`, but that would be a breaking change and would require releasing a new major version.

**Comment by amolumesh12** [comment]
can you please make changes in my code for undo operation because..sorry , but  am not getting what you trying to say ??

**Comment by RahulRathodGitHub** [comment]
> 
> 
> @szimek , am displaying image on signature-pad...when i draw only on signature-pad and do undo() operation it perform correctly..but when am displaying image on signature-pad and then perform undo then it clear entire image first and then other data..i want to undo only data on image..not an image

There is one working solution for what you are desiring.

1. Copy the data Object (Obtained from "toData()") to a local variable
2. Pop from the local object
3. Use fromData(localVariable)
4. You need to create another hidden canvas
5. Draw the background Image
6. Draw the actual canvas 
7. Replace the actual canvas with the state of the hidden canvas
8. For future "undos" modify the data object that you are updating and repeat (2-7).

**Comment by RahulRathodGitHub** [comment]
> @amolumesh12 I'm not sure if there's an easy way to do it at the moment, because `SignaturePad#fromData` clears the canvas before it redraws everything. If you draw your image after calling this method, it would overwrite the signature.
> 
> Currently, you could modify the library to remove `this.clear()` call from `SignaturePad#fromData` method. I could change this method to not call `SignaturePad#clear`, but that would be a breaking change and would require releasing a new major version.

How about we add an optional parameter to fromData() like "doNotClear?:Boolean". It wont break the existing code and will be more flexible.
