### ISSUE TITLE
signaturePad.fromData(data) is not setting internal _data variable. (v 2.2.0)

### ISSUE THREAD

**Issue by inf0rm4tik3r** [szimek/signature_pad#271]
Hello,

i do not know if it is intended bahaviour, but using signaturePad.fromData(data) always leaves the _data variable of the SignaturePad object empty.
This results into an empty array being returned if signaturePad.toData() gets called afterwards.

Setting _data manually has fixed the problem for me however.

`sig_pad.fromData(data);`
`sig_pad._data = data;`

**Comment by szimek** [comment]
@inf0rm4tik3r Hey, could you create a PR for this issue?
