### ISSUE TITLE
onEnd event not firing when using Javascript to draw inside canvas

### ISSUE THREAD

**Issue by ibarczewski** [szimek/signature_pad#273]
I'm trying to write an automation test with Protractor that signs the signature pad, which would trigger the onEnd event to fire. Currently, the automated signing looks like this:

```
var canvas = document.getElementsByTagName('canvas')[0];
var ctx = canvas.getContext("2d");
ctx.moveTo(0,0);
ctx.lineTo(200,100);
ctx.stroke();
```

My signature_pad declaration looks like this:
```
var signaturePad = new SignaturePad(canvas, {
          backgroundColor: '#FFF',
          minWidth: 1,
          maxWidth: 1.5,
          dotSize: 3,
          penColor: 'rgb(68, 68, 68)',
          onEnd: function () {
            ngModel.$setViewValue(signaturePad.toDataURL());
          }
        });
```

By using the function up above where it strokes a line across the canvas, the onEnd event does not fire. If I use a mouse or my finger on the signature-pad, it fires the onEnd event, so I am pretty confident I have it wired correctly. Am I doing something wrong, or is this a bug? Is there a way I can manually get this event to fire?

**Comment by szimek** [comment]
The library listens for mouse/touch events, it has no idea that you're drawing something on the canvas. So it's not a bug, but it won't work the way you want it. The `onEnd` function will be available on the instance of the `signaturePad`, so you can do:
```js
var canvas = document.getElementsByTagName('canvas')[0];
var signaturePad = new SignaturePad(canvas, {...});

var ctx = canvas.getContext("2d");
ctx.moveTo(0,0);
ctx.lineTo(200,100);
ctx.stroke();

signaturePad.onEnd();
```

**Comment by GaintVlad** [comment]
`signaturePad.onEnd = function(){
	$scope.$apply(function() {
		console.log('end');
	});
};`
