### ISSUE TITLE
build problem with new angular

### ISSUE THREAD

**Issue by deinega** [szimek/signature_pad#275]
Hi. I just updated my angular-cli to the latest version.
Now I cant run my project:

ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in node_modules/@angular/core/core.d.ts, resolving symbol SignaturePadModule in /node_modules/angular2-signaturepad/index.d.ts, resolving symbol SignaturePadModule in node_modules/angular2-signaturepad/index.d.ts

Can you please help?

**Comment by szimek** [comment]
@deinega You'll have to ask in [angular2-signaturepad](https://github.com/wulfsolter/angular2-signaturepad) project. I do not maintain it.
