### ISSUE TITLE
How to use fromDataURL

### ISSUE THREAD

**Issue by sahaB-shock** [szimek/signature_pad#276]
Thanks much for providing such a nice api. Need some help to achieve my need.

I can successfully save the string what I get from toDataURL() in server.
But when I give the same data to signaturePad.fromDataURL(data from server) doesn't draw the image in canvas.

Any idea on this, I will really appreciate.

**Comment by szimek** [comment]
@sahaB-shock Are you sure the string is really the same? 

If you go to the [demo page](https://szimek.github.io/signature_pad/), draw something and then run:
```js
data = signaturePad.toDataURL()
signaturePad.clear()
signaturePad.fromDataURL(data)
```
it should draw the same image.

**Comment by sahaB-shock** [comment]
Thanks szimek.

**Comment by gregakaoz** [comment]
I believe your problem is that the fromDataURL is in base64 and you need to convert it to binary before you as it on you server.

**Comment by demo-igor** [comment]
To make the same image size you can add options
`signaturePad.fromDataURL(data, {width: 100, height: 100})`
width, height should be the same as canvas size

**Comment by git102347501** [comment]
> 要使图像大小相同，可以添加
> `signaturePad.fromDataURL(data, {width: 100, height: 100})`
> 宽度，高度与画布大小相同的选项。
> 更多详细信息：[https](https://github.com/szimek/signature_pad/blob/master/src/signature_pad.ts) :
> [//github.com/szimek/signature_pad/blob/master/src/signature_pad.ts](https://github.com/szimek/signature_pad/blob/master/src/signature_pad.ts)

What if {width: 100, height: 100} is 100% size? Do I think there should be a typescript model for options of fromdataurl?
