### ISSUE TITLE
set dotSize

### ISSUE THREAD

**Issue by wp56610** [szimek/signature_pad#277]
Hey there.
First of all, thanks for the awesome work !
signature_pad it great !   

but today i find a little question about dotSize.  I need let users to set dot,so I get the value from a range, 
As we all know ,the value is String ,but I ignore it,when i find in the source code,i understand i Make mistakes,the dot return  a Unexpectedly value.(not waring ,no error ,so i Spend some time to find why)
`this.dotSize = opts.dotSize || function () {
            return (this.minWidth + this.maxWidth) / 2;
        };`
maybe it's better
`        this.dotSize = opts.dotSize || function () {
            return (parseFloat(this.minWidth) + parseFloat(this.maxWidth)) / 2;
        };`

**Comment by wp56610** [comment]
I need let users to set minWidth,maxWidth ,not dot

**Comment by gregakaoz** [comment]
First, dotSize is not set at dotSize but at "_strokeWidth";
Finally, you can alter it by the passed in object: see code below:

        var signaturePad = new SignaturePad(document.getElementById('signature-pad'), {
            backgroundColor: 'rgba(255, 255, 255, 255)',
            penColor: 'rgb(0, 0, 0)',
            maxWidth: 20 /* this makes it fatter!!! */
        });
