### ISSUE TITLE
Can I use this module to MARK on Human Body ??

### ISSUE THREAD

**Issue by udara86** [szimek/signature_pad#279]
Hi,

I am developing a  OPD Patient Data management system. Doctors want to mark injuries on a virtual human body. (I attached a sample screen shot seen at a another site for your reference
![screenshot from 2017-06-30 09_04_12](https://user-images.githubusercontent.com/1080985/28955236-b100f8dc-7902-11e7-8ae6-8f0f7598b8ce.png)
)

Then save the marked injuries on human body should be able to SAVE as image in server folder and put path into a mysql table..

I searched lot.. Could you please advice me whther I can uitilite this for my requirement as well ?

Thanks

**Comment by wulfsolter** [comment]
I don't feel that "doing your homework" is an issue that other people need to solve for you. 👎

**Comment by szimek** [comment]
Here's an example how to draw over an image: https://jsfiddle.net/szimek/d6a78gwq/.

**Comment by udara86** [comment]
What is the code if I need to save this modified images into a folder and
update certain mysql table record ?
Just illustrate me via a sample code...

[image: Inline image 1]

I stucked at this place since around 2 weeks.. Highly appreciate your
positive feedback.

Thanks
Bye









*Have a Nice Day...>>Best Regards From  Capt Udara Pathirage        Master
of IT, UCSC, Colombo | BSc in ENCM, Kelaniya | Dip. IT, NIBM | (CSSL)
        Software Engineer (IT OFFICER)*
*              Directorate of Information Technology*
*              SRI LANKA ARMY*

*Email: udara86@gmail.com <udara86@gmail.com> | **SkypeID: udara1986 | **Phone:
071 8110497, 0776021042*
