### ISSUE TITLE
Layout issue in iPad Pro 10.5

### ISSUE THREAD

**Issue by bfleishman** [szimek/signature_pad#285]
When clicking your demo link while using an iPad Pro 10.5, the layout is not right. I attached a screen shot of the issue. You can see everything is shifted down and to the right. It works fine with all other browsers.

Is this an issue that is just related to these devices and is there a fix for that?

![img_0113](https://user-images.githubusercontent.com/360187/29391849-22171bf4-82c8-11e7-8fb4-f5ae313ae2d9.PNG)

**Comment by bfleishman** [comment]
Let me know if I can assist in any way in testing of any bug fixes.

**Comment by szimek** [comment]
@bfleishman Good news is that I can reproduce this issue in iPad simulator. Bad news is that I have no idea when I'll have enough free time to fix it. PRs are welcome :)

**Comment by bfleishman** [comment]
Okay, I'm happy and I'm sad at the same time :) Is it a java script issue you think? Or something with the CSS?

**Comment by szimek** [comment]
Fixed by https://github.com/szimek/signature_pad/commit/30197238214390f73924b3690948b6fb28037d03.
