### ISSUE TITLE
onBegin and onEnd functionality

### ISSUE THREAD

**Issue by dwardrian** [szimek/signature_pad#286]
According to the API, onBegin() is called at the start of a stroke, however it seems to only get called on page load.

Example:

`var pad = new SignaturePad (canvas, {  
   backgroundColor: 'rgb(255,255,255)',  
   velocityFilterWeight:0.4,  
   onBegin: console.log('hello')  
   //onBegin: startWritingTimer()
 });`

The above code logs 'hello' when the page is loaded, rather than at the start of each stroke. 
Have I misinterpreted the API? It's also the same for onEnd() ... neither methods are firing at the start/end of strokes. What am I missing? 
Thank you

**Comment by szimek** [comment]
@dwardrian You need to pass a function as `onBegin` value. `console.log('hello')` is not a function, but a function call.

```js
var startWritingTimer = function () { ... };
var pad = new SignaturePad (canvas, { 
  backgroundColor: 'rgb(255,255,255)', 
  velocityFilterWeight:0.4, 
  onBegin: startWritingTimer // notice lack of ()
});
```

Hope this helps.

**Comment by dwardrian** [comment]
Thanks so much, removing the () worked. Sorry for the noob question!

**Comment by szimek** [comment]
No problem. Cheers!
