### ISSUE TITLE
OnUpdate callback implementation

### ISSUE THREAD

**Issue by BioPhoton** [szimek/signature_pad#287]
**Do you want to request a feature or report a bug?**
Feature request

**What is the current behavior?**
OnBegin and OnEnd callbacks exist. No OnUpdate callback

**What is the expected behavior?**
Would be cool to have OnUpdate callback too.

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**
v2.2.1

**Comment by UziTech** [comment]
should be fixed by #567
