### ISSUE TITLE
es5 support in

### ISSUE THREAD

**Issue by BioPhoton** [szimek/signature_pad#288]
**Do you want to request a feature or report a bug?**
feature

**What is the current behavior?**
want to use the es5 version of this lib.

**What is the expected behavior?**
would need 1 bundle file as es5 like here => https://github.com/szimek/signature_pad/blob/master/example/js/signature_pad.js

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**
2.2.1

**Comment by szimek** [comment]
@BioPhoton Hey, are the files in the current npm package not enough? There's an umd version (`signature_pad.js`) and es module (`signature_pad.mjs`) version.

**Comment by BioPhoton** [comment]
Ah ok i c. I used the direct bower install over the git url. (yes I have to use bower... :-( )

**Comment by szimek** [comment]
@BioPhoton Yeah, bower is not supported since 1.6, because I'd have to keep built files in the repo and it was really inconvenient.
