### ISSUE TITLE
Scale signature data to fit canvas

### ISSUE THREAD

**Issue by BioPhoton** [szimek/signature_pad#289]
**Do you want to request a feature or report a bug?**
A Feature

**What is the current behavior?**
if the canvas gets resized i cache the signature and rerender it after resize. My proble is, if the signature is too long (the width) and a resize to smaller width parts of the signature are invisible
https://jsfiddle.net/amLm6u4h/

**What is the expected behavior?**
I want to scale the signature down so it always fits the size after rescaling

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**
2.2.1

**Comment by BioPhoton** [comment]
Another thing that would help is if i could get the width and height from the result of` toData()`

**Comment by mymattcarroll** [comment]
@BioPhoton, we had similar requirements for which we wrote this library: https://github.com/blinkmobile/canvas-manipulation

Here is a example of usage with an AngularJS component we wrote as well: https://github.com/blinkmobile/angular-signature-pad

**Comment by UziTech** [comment]
closing as stale
