### ISSUE TITLE
CDN for 2.x versions

### ISSUE THREAD

**Issue by Waexu** [szimek/signature_pad#290]
Can you please add new 2.x versions to CDN? Thank you.

**Comment by szimek** [comment]
Do you mean cdnjs.com? I think it stopped working when I removed built .js files from the git repo. Do you know if it can fetch files from npm packages?

**Comment by Waexu** [comment]
Yes, I meant cdnjs. And they probably don't support npm

**Comment by MartinKolarik** [comment]
You can use https://www.jsdelivr.com/package/npm/signature_pad

**Comment by szimek** [comment]
@MartinKolarik Thanks! I completely forgot about this CDN.
