### ISSUE TITLE
SignaturePad on Ionic/Angular does not work correctly

### ISSUE THREAD

**Issue by CedricNomentsoa** [szimek/signature_pad#291]
Hello everyone, I have some troubles in using SignaturePad in my application. I don't have any problem when I launch the application in Ubuntu (VirtualBox), but when I launch it on my Surface (where I really need it), I have a problem.

The problem is when I put a canvas in my application with an image in the background with the fonction "fromDataUrl()" : 
```javascript
  ngAfterViewInit() {
    if (this.record.new_signature_base64) {
      this.signaturePad.fromDataURL('data:image/jpeg;base64,' + this.record.new_signature_base64);
    } else {
      this.clear();
    }
  }
```

```html
<ion-content >
  <ion-badge color="subtle" padding style="width:100%;height:100%;text-align:center;vertical-align: middle;" >
    <ion-badge color="white" padding style="position: relative; top: 50%; margin-top:-200px">
       <signature-pad [options]="signaturePadOptions" (onBeginEvent)="drawStart()" (onEndEvent)="drawComplete()"></signature-pad>
    </ion-badge>
  </ion-badge>
</ion-content>
```
And this is what I get : 
![first](https://image.noelshack.com/fichiers/2017/35/3/1504105214-sc.png)

My background is truncate while it's supposed to fill the white space. But I solve the problem by adding that : 

```javascript
  ngAfterViewInit() {
    this.signaturePad.resizeCanvas(); //that line
    if (this.record.new_signature_base64) {
      this.signaturePad.fromDataURL('data:image/jpeg;base64,' + this.record.new_signature_base64);
    } else {
      this.clear();
    }
  }
```
![second](https://image.noelshack.com/fichiers/2017/35/3/1504105704-sc.png)

But there is another probleme here that I can't solve though my background is good.
The problem is when I draw, my black line doesn't appear where my pen is, but a few pixels on the right.
Here a quick video to demonstrate it : 

![video](https://media.giphy.com/media/3ohhwMScMZN63B0jrW/giphy.gif)

As you can see there is an offset and I don't really know how to fix it.
FYI : it works very well on large screen, no offset, but not on my Surface

I hope you can help me, thanks a lot.

**Comment by wulfsolter** [comment]
https://github.com/wulfsolter/angular2-signaturepad/issues/42
