### ISSUE TITLE
Save just opens a blank page in Chrome - works fine in other browsers

### ISSUE THREAD

**Issue by DanielKYantis** [szimek/signature_pad#293]
Apparently Google Chrome has removed support for top-frame navigation, you can see more informations here: https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/GbVcuwg_QjM

Chrome 60.0.3112.113 (64-bit)
macOS 10.12.6 (16G29)
Signature-Pad 2.3.0 Demo Page: (http://szimek.github.io/signature_pad)

Signature-Pad used to work when I looked at it several months ago. So I'm actually ready to try it but found it does not work now.

works fine in Safari and Firefox.

I cleared all cache and reset to defaults but still produces just a blank page on save. Any ideas how to fix?

console error says: http://szimek.github.io/signature_pad/js/app.js:33 Not allowed to navigate top frame to data URL: ...

**Comment by szimek** [comment]
Yeah, I'm not sure what's the best way to fix it is, as I want to keep the demo as simple as possible. I could replace the whole content of the page with image data, or just show it in the console.

However, it's just an issue with the demo and doesn't really have any impact on the library itself.

**Comment by szimek** [comment]
The code in the repo and the demo were updated and now clicking any of the "save" buttons will download the image (https://github.com/szimek/signature_pad/commit/02428b353a4ae4c2e7cb8650a26135b4ab3bc848). Thanks for reporting it!
