### ISSUE TITLE
Suggested real saving example!

### ISSUE THREAD

**Issue by sposmen** [szimek/signature_pad#296]
Based on the jsfiddle, there is a way to generate a real saving behavior. This is the updated one...
https://jsfiddle.net/d6a78gwq/1356/

Tks four your great job!

**Comment by szimek** [comment]
@sposmen Thanks! I'll update the demo as soon as I have some free time.

**Comment by szimek** [comment]
@sposmen I've just updated the demo with your (slightly modified) code. Huge thanks for this idea!

**Comment by sposmen** [comment]
👍
