### ISSUE TITLE
Internet Explorer version

### ISSUE THREAD

**Issue by tejashapani** [szimek/signature_pad#297]
I would like to know what browsers are supported by Signature pad. And what is the minimum version of browsers are supported.

**Comment by szimek** [comment]
@tejashapani It should support every browser that has basic support for canvas: https://caniuse.com/#feat=canvas. It won't work on IE8, which doesn't support canvas at all and in Android 2.3 `Canvas#toDataURL` is not supported, though it's possible to add a polyfill for that if you need. If it doesn't work properly in any other more recent browser, then it's most likely a bug.

The demo page has been rewritten recently using flexbox, so it might not look correctly in older browsers, but the library itself should work.

**Comment by tejashapani** [comment]
Hi @szimek 

Thanks for the info.
I will check for polyfill.
