### ISSUE TITLE
Specify Folder to Save PNG

### ISSUE THREAD

**Issue by LuigiMdg** [szimek/signature_pad#301]
Hi,
I've inserted your JS and the code to my website, but I haven't understand how to save the PNG to a specific folder..
I've inserted this JS, but they open an empty page.. Without signature..
And on the FTP I haven't find the signature file..!
```
<h4 style=\"clear:left;margin-top:30px\">Firma:&nbsp;<canvas id='signature-pad' class='signature-pad' width=400 height=125 style='border:1px solid black'></canvas></h4>
<button id='save-png'>Save as PNG</button>
```
```
document.getElementById('save-png').addEventListener('click', function () {
  if (signaturePad.isEmpty()) {
    return alert("Please provide a signature first.");
  }
  
  var data = signaturePad.toDataURL('image/png');
  console.log(data);
  window.open(data);
});
```

**Comment by szimek** [comment]
The code you pasted only opens a new tab that displays the signature image. You can check the updated code of the demo app to see how to actually download the image: https://github.com/szimek/signature_pad/blob/master/example/js/app.js#L35-L48

However, you can't select a folder to save it to, this is handled natively by your browser and most likely all files will end up in somewhere in a `Downloads` folder, which location depends on your OS.

**Comment by LuigiMdg** [comment]
How to use the _download_ function?
I've try this but not work..! :-(
```
          document.getElementById('save-png').addEventListener('click', function () {
            download('firme', 'firma1.png');
          });
```
Scuse me for my noobity

**Comment by szimek** [comment]
@LuigiMdg Just use the whole code from `example` folder - it works. Then modify it according to your needs and occasionally check if it still works ;)

If you check the code, you'll notice that the first parameter to the `download` function is data url that you get from `SignaturePad#toDataURL()` and the second is the name of the file.

If you have any questions related to JS language itself, please ask them e.g. at https://stackoverflow.com/.

Good luck! :)
