### ISSUE TITLE
Dynamic Color goes to default on undo

### ISSUE THREAD

**Issue by RahibAly** [szimek/signature_pad#302]
I'm creating a page where I have added 4-5 dynamic color boxes to choose from, and it works very well..
But the problem is when I use undo functionality, if I select color red and draw a line, then I change color to green and draw 2nd line, then I choose color Red and draw 3rd line, then when I click undo it works but all lines color changes back to the current selected color..

**Comment by szimek** [comment]
Unfortunately, it's a bug :/ I created a demo to replicate it: https://jsfiddle.net/szimek/js6u2L27/.

Fortunately, it's easy to fix ;) I'll try to find some time during the weekend to release a new version, but in the meantime, you can just add:
```js
this.penColor = color;
```
right before this line: https://github.com/szimek/signature_pad/blob/master/example/js/signature_pad.js#L496 to fix it.

**Comment by RahibAly** [comment]
Great! it fixed the issue, Thanks a lot

**Comment by szimek** [comment]
Fixed in 2.3.2!
