### ISSUE TITLE
JPG can not be stored in version Signature Pad v2.3.1

### ISSUE THREAD

**Issue by Hamburgo58** [szimek/signature_pad#303]
In my last used version 1.6.0-beta.1 it was possible to store a signatur as JPG.

With the current version I got a black picture.

What can be the reason ?

**Comment by szimek** [comment]
As mentioned in the README.md - you need to use an opaque color for `backgroundColor` option when saving image as JPEG:
> Use a non-transparent color e.g. "rgb(255,255,255)" (opaque white) if you'd like to save signatures as JPEG images.
This should solve your problem.

**Comment by szimek** [comment]
Please reopen this issue if the suggestion above doesn't solve your problem.

**Comment by Hamburgo58** [comment]
Yes, this solved my problem. Many thanks for your quick response.
