### ISSUE TITLE
Drawing over image does not save the whole image with the signature

### ISSUE THREAD

**Issue by thesourav123** [szimek/signature_pad#304]
Hi,
The Drawing over image functionality does not save the background image, but only the signature.

here is my fiddle copied from the original one:
https://jsfiddle.net/thesourav/Ltzq3bLx/

**Comment by szimek** [comment]
It's not really a problem with the demo - it's supposed to work like this. It just places an image over the canvas, but doesn't actually draw the image to it. You can easily change the demo to:
* store the signature and then draw the image and then the signature over it to an offscreen/hidden canvas
* draw the image to the visible canvas and draw signature over it

You might want to look into [globalCompositeOperation](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation) as well.

**Comment by thesourav123** [comment]
@szimek Thanks for the reply. I understand your point. But, how do i place the signature at the exact same position on the top of the image.

**Comment by szimek** [comment]
You can probably put both the image and canvas in a container that has `position: relative`.

Here's also a demo that saves an image, but it kind of sucks, because you'd have to redraw the image every time the canvas is cleared, either by user or by resize/screen orientation change.

**Comment by thesourav123** [comment]
@szimek Thanks a Lot. That works. I just need it to be sent to the database once user confirms.
