### ISSUE TITLE
Can't resize canvas without it breaking

### ISSUE THREAD

**Issue by robbiemilejczak** [szimek/signature_pad#305]
_If you have a question, please ask it on [StackOverflow](https://stackoverflow.com/questions/ask?tags=javascript+signature-pad) and use `signature-pad` tag instead of creating an issue._

**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**

Just to be clear I'm not currently concerned with resizing it dynamically, I just want it to be statically larger for mobile screens. Anytime I resize it with any method it stops working, including the code provided by you to handle high DPI screens. I'm not sure what to do, everything I introduce to resize the canvas makes it stop working but gives me no console errors. I suspect it is because the pen becomes so offset when I resize my screen manually, but I'm not sure how to handle that on my end.

**What is the expected behavior?**
I can set the canvas to a static size (ex 800x600) and comfortably draw inside of it.

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**
Most current, and both my mobile phone, chrome, and firefox are having this issue.

**Comment by szimek** [comment]
Could you provide a demo that allows me to replicate this issue? Or provide a link to this "how to handle high DPI screens" demo and steps to replicate it?

**Comment by robbiemilejczak** [comment]
I can't reproduce it unfortunately. I've taken your code from the resize button in your example and it works well enough. The signature pad feels a little off after resizing though, but if I do anything with the offsetHeight/offsetWidth the signature pad breaks. If I use the resizeCanvas() function you wrote I end up with a tiny black square. Still, this is acceptable enough. Thanks for your help

**Comment by szimek** [comment]
Good luck ;)

**Comment by caub** [comment]
Hey, here's an example with resizing problems: https://jsfiddle.net/caub/gn9oqe0m/

You can see that the pen drawing is not under the mouse cursor, there's an offset

I know we are not supposed to use width: 100% on the canvas, but is there a way yo have signature_pad still working with resizing?

**Comment by caub** [comment]
I found a fix by listening resize changes and updating canvas width: https://jsfiddle.net/caub/gn9oqe0m/1/
