### ISSUE TITLE
Draw Signature Android App

### ISSUE THREAD

**Issue by RahibAly** [szimek/signature_pad#307]
Hello, I have made an Android app by using your library, so I would like to say Thank u for making this library.
Now the problem is that when we draw signature and move finger very fast then it has little bit of delay, the pointer does not follow your finger instantly I hope you understand what I'm trying to explain.. if not, just install my app on your android and test it, app is available on Play Store: [Draw Signature](https://play.google.com/store/apps/details?id=com.diytech.drawsignature)

**Comment by szimek** [comment]
I've recently added `minDistance` option that rejects points that are closer than this distance. The default value is 5. It does introduce a noticeable lag, but it draws smoother lines, especially if someone draws really slowly. You can try to reduce this number or even set it to `0` to disable it completely.

**Comment by szh** [comment]
I have the same issue, and even with minDistance set to 0 there's appreciable lag.

**Comment by szh** [comment]
Never mind, it was an issue caused by Angular. I needed to setup SignaturePad outside of NgZone, or all events would be handled by Angular which caused the lag.
