### ISSUE TITLE
Including Signature_pad in an html form save and download

### ISSUE THREAD

**Issue by etiks3** [szimek/signature_pad#314]
Hi,
I've created an HTML form. 
This form needs to be signed up before been sent to a server. Signature_pad is opening in a modal when customer click on "sign" button. I would like to save the signature in the form and then send the "wrapped" element to the server signature_pad + form in a single file.

Do I need to wrap my html form in a canvas? Do I need to include my form in the signature_pad canvas?

I'm a bit lost here. Thanks fro your help.

Best regards.

Sylvain

**Comment by szimek** [comment]
@etiks3 In general it's better to ask such questions on https://stackoverflow.com/.

You can add a hidden field to your form, e.g. `<input type="hidden" name="signature-pad" />` and when signature is ready (e.g. when user clicks "sign" button) you can call `hiddenInput.value = signaturePad.toDataURL();` to assign signature data to your hidden field. Additionally, you can now automatically submit the form or wait for the user to click a submit button to do it.

**Comment by etiks3** [comment]
@szimek Thanks for your prompt reply, I'm sorry, but stackoverflow didn't allowed me to send you a question...
That sounds like a good idea!! I'll investigate this way and get back to you.

**Comment by szimek** [comment]
Please reopen this issue if you have any further questions.
