### ISSUE TITLE
Thanks Szymon 

### ISSUE THREAD

**Issue by bulksign** [szimek/signature_pad#316]
Hey Szymon ,

Just wanted to say thanks for this wonderful library. We have integrated it into our electronic signature platform and we were pleasantly surprised on how simple and straightforward was to integrate (and how trouble free was to integrate into a large TypeScript project).

Thank you for this great work.

[How it looks in action, gif link](https://i.imgur.com/wv6cI00.gif)

**Comment by szimek** [comment]
That's great to hear. Thank you so much!
