### ISSUE TITLE
Randomly missing SVG and XY points output from .toDataURL('image/svg+xml') and .toData()

### ISSUE THREAD

**Issue by arnoldmanzano** [szimek/signature_pad#317]
**Do you want to request a feature or report a bug?**
Possible bug. Unfortunately, we are unable to re-create it, but we wanted to check if other users are experiencing it to gather more data and help with debugging.

**What is the current behavior?**
We export user-inputted signature in PNG, SVG and XY points and save it in the backend.
Randomly, SVG and XY points will be empty, but PNG is still generated correctly. It's happening for about 3 out of every 100 signatures we collect.
SVG output from `.toDataURL('image/svg+xml')` is empty except for the svg headers.
XY Points output from `.toData()` is only an empty array.

_If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via <https://jsfiddle.net> or similar (template: <https://jsfiddle.net/szimek/h80phxyr/>)._
Unfortunately, we are unable to re-create it, but we wanted to check if other users are experiencing it or have stumbled upon it.

**What is the expected behavior?**
SVG and XY points are consistently exported together with the PNG.

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**
SignaturePad version 2.3.2
SignaturePad version 2.1.0
Not tied to specific browser or device based on the failures we have reviewed.

**Comment by szimek** [comment]
That's strange :/

When `.toDataURL` is used to generate PNG or JPEG image, it simply delegates to canvas element to generate this image - it's not using collected point data at all. `.toDataURL('image/svg+xml')` on the other hand uses the same data that is returned from `.toData` method to generate SVG, that's one if `.toData` returns an empty array, `.toDataURL('image/svg+xml')` generates an empty SVG.

This internal data structure (`SignaturePad#_data`) is (or rather should be) only cleared when `SignaturePad#clear` is called.

**Comment by patrickdk77** [comment]
This is due to the SVG generation code and HiDPI devices.
The ratio will be >1, and it makes the resulting maxX and maxY smaller than the generated SVG it created using the canvis width and height.
Editing the code to remove the ratio makes it work as expected. I imagine also using the ratio adjusted maxX and maxY values when you create the SVG would also fix the problem.

There is no function options passed into SVG, so currently you cannot override any of this like you can for the other image formats.

**Comment by junardoclarit** [comment]
I think this issue still not fix. We just experience missing svg attributes also svg end tag from the .toDataURL('image/svg+xml'). any work around for this issue? I hope this get fixed.

**Comment by UziTech** [comment]
@junardoclarit are you able to reproduce this and provide steps to reproduce the issue?

**Comment by UziTech** [comment]
closing as stale
