### ISSUE TITLE
Signature_pad Problem in Mobile

### ISSUE THREAD

**Issue by amine-damani** [szimek/signature_pad#318]
Hello, I have made an Web site by using your library, so I would like to say Thank u for making this library.
Now the problem is that when we draw signature and move finger up or down, out of pad  the signature is 
removed

**Comment by szimek** [comment]
I'm not 100% sure why it happens, but most likely you're listening to `resize` event, right? You can add some logging there to see if it's fired when you scroll the screen.

If it is fired on scroll, then you can listen to other events like `orientationchange`, which won't be triggered when scrolling.

Let me know if it helps.

**Comment by zoldek** [comment]
not in resize, i draw signature and move finger up or down, out of pad the signature is removed.
Look this : https://youtu.be/k-W2Y4KKU04

**Comment by szimek** [comment]
But the code in the demo page is listening to `resize` event and when it happens it resizes the canvas, which causes it be cleared.

You can fix it in these 2 ways I mentioned:
- listen to `orientationchange` event instead of `resize`
- check if width has actually changed when `resize` even is fired and don't do anything if it hasn't

**Comment by zoldek** [comment]
Thank you @szimek  for your help
 it's work fine. 👍

**Comment by santosh-btc** [comment]
@zoldek As I understand, as per the docs browser will clear the canvas on resize event automatically. Now even i have replaced the `resize` with `orientationchange` it is still not working. I doubt that when we scroll up in mobile it actually move the address bar in and which could fire the resize event, is it possible?

It's not working for me on iPhone 7+, can you please put some more light what steps you followed to fix this?

**Comment by szimek** [comment]
@santosh-btc Could you add a simple `console.log` to your `resize` or `orientationchange` event handler and see to see if it's triggered when scrolling? This should tell you when your handler is executed.

**Comment by santosh-btc** [comment]
@szimek "resize" event execute when scrolling.

**Comment by szimek** [comment]
@santosh-btc So if `orientationchange` event is not fired on scrolling, move your canvas resize logic there. It should fix your problem.

**Comment by ParthBarot-BoTreeConsulting** [comment]
@szimek I think what @santosh-btc is mentioning is related to the other library which we are using for ReactJS frontend. It is mentioned there that `A signature pad implementation for react.`, but when we reviewed the internal code we found it is not using your library.

Though, if you have any suggestions on it, would be great. I have raised an issue in there.

**Comment by zoldek** [comment]
Hi @santosh-btc 
Try this : 

var windowWidth = $(window).width();
$(window).resize(function(){    
    if ($(window).width() != windowWidth) {
      window.onresize = resizeCanvas;
      resizeCanvas();
    }
});
window.orientation = resizeCanvas;
resizeCanvas();

It works for me
when you in the phone listen to orientationchange
when you in the desktop listen to onresize

**Comment by ParthBarot-BoTreeConsulting** [comment]
@zoldek Yep, got the same thing, updated the other issue as well. Basically now we need to identify if the device is mobile or not. Can we do that just by `window.width` and comparing it against actual device sizes?

**Comment by zoldek** [comment]
@ParthBarot-BoTreeConsulting  what's your problem exactly ?

**Comment by ParthBarot-BoTreeConsulting** [comment]
@zoldek The problem is, I need my ReactJS app to work diff. in Web vs Mobile - As you mentioned it needs to register for diff. events. I am thinking of doing it by checking the window width, like,

``` javascript
...
if(window.width() > 300){ //This will be compared with multiple screen width/height sizes to ensure its web.
  window.addEventListener('resize', function(){ ... });
} else {
    window.addEventListener('orientationchange', function(){ ... });
}
```

Any ideas?

**Comment by zoldek** [comment]
`if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {
   window.addEventListener('orientationchange', function(){ ... });
} else {
     window.addEventListener('resize', function(){ ... });
}`

**Comment by karan4364** [comment]
@zoldek  Thanks. Your solution is worked for me. You saved my day.

**Comment by thienban** [comment]
Hi, I'm using React JS for a Mobile App,
My issue is to display the Image from _toDataURL_.
I trigger the addEventListener in _componentDidMount_ and Remove event listener in _componentWillUnmount_
But, it doesn't change anything.

`componentDidMount() {
		if(canvas != null){
			window.addEventListener('orientationchange', resizeCanvas(canvas));
		}
	}
	componentWillUnmount() {
		if(canvas != null){
			window.addEventListener('orientationchange', resizeCanvas(canvas));
		}
	}`

My images
![signature1](https://user-images.githubusercontent.com/28274942/45556764-50538700-b83c-11e8-927b-d71be3842ece.PNG)
![signature2](https://user-images.githubusercontent.com/28274942/45556777-56e1fe80-b83c-11e8-9e62-b3679702bda8.PNG)

Can you explain how to trigger the _addEventListener_ ? please

**Comment by Satya3999** [comment]
Hello there! 

I'm using your library to create a signature on my website and retrieving the data in CRM. Everything works fine except for signature pad JavaScript is creating too many characters when I sign the form using my mobile application, which is in turn causing some performance issues when submitting the form, is there any way that I can reduce/restrict the number of character created by signature pad when using it in mobile application. 

Thanks,
Satya
