### ISSUE TITLE
Bad quality of signature (signature isn't smooth)?

### ISSUE THREAD

**Issue by din-gi** [szimek/signature_pad#319]
I have tried posting on StackOverflow before sending a question here (https://stackoverflow.com/questions/47267164/signaturepad-isnt-so-smooth)

I have tried looking for a signature pad to allow signature drawing in my website,

The SignaturePads that I looked at are these:

- https://github.com/szimek/signature_pad (Demo: http://szimek.github.io/signature_pad/)

- https://github.com/ezl/signature-pad (Demo: https://www.jqueryscript.net/demo/Smooth-Signature-Pad-Plugin-with-jQuery-Html5-Canvas/examples/)

In the past I have used Szimek signature pad and everything works fine but when comparing the demo to the second demo of Ezl signature pad the smoothness of Ezl supersedes Szimek in the smoothness.

Ezl Signature Pad:

[![Ezl Signature Pad][1]][1]

Szimek Signature Pad:
[![Szimek Signature Pad][2]][2]

I have tried modifying the throttling setting of the Szimek plugin and also in general I prefer using the Szimek plugin because there is better support, contributions and community to it.

Does anyone knows why do I get such a bad quality in comparison to the Ezl plugin?

  [1]: https://i.stack.imgur.com/6WULw.png
  [2]: https://i.stack.imgur.com/1y73a.png

**Comment by szimek** [comment]
Thanks for reporting this issue. There already is a ticket for it https://github.com/szimek/signature_pad/issues/251 and if anyone is willing to investigate the differences between these plugins, they are very welcome ;) I'll add info about your finding there as well.

I want to rewrite this plugin to TypeScript first (I already started working on it) and then look into other similar libraries and some papers to figure out how to make it smoother.

**Comment by szimek** [comment]
@din-gi There are a few other options besides `throttle` that you can try out. One would be to define the same min and max widths (`minWidth` and `maxWidth`). You can also try to adjust `minDistance` - increasing this value will make lag more noticeable, but might result in smoother lines.
