### ISSUE TITLE
Usability problem with orientationchange

### ISSUE THREAD

**Issue by marcorinck** [szimek/signature_pad#32]
Hi, 

this is a very nice library and I'm (almost) 100% happy with it. Many thanks for your effort!

My only problem is a usability problem with orientationchange on mobile devices.

To have a consistent styling one has to change the size of canvas when user changes the orientation of his device (your demo does it too). Unfortunately that clears whole canvas. 

The usability problem I see is, that the person who owns the device hands it to another person to sign something and then the device is handed back its very likely that the orientation will change unintentionally. And thus the signature gets lost .

I think I know why you delete the canvas on resize as you don't want to scale the image, right? 

But maybe there is another solution for orientationchange so you don't have to delete the image and preserve it? 

Maybe add pixels dynamically when width gets bigger? 

This would lead to a square image when starting with portrait format and switching to landscape. So toDataUrl() should return only the image that is visible in current canvas size, so you can always change back to landscape format when an unintentional orientationchange event happened. 

Or is something like that maybe already possible with current version?

Thanks for your time.

**Comment by nikonov91-dev** [comment]
I have found a solution to handle orientation change or window resize, here is it
https://stackoverflow.com/a/60057521/9277453
Tied with react

**Comment by plocket** [comment]
Though it doesn't solve all the criteria I have for resizing (because it has to maintain the same aspect ratio the whole time), I made a non-React version of @nikonov91-dev 's solution in the same issue. Look at the "Resize" section at https://stackoverflow.com/a/75261364/14144258.

The code is as follows, though it doesn't have a button to clear the canvas:

```html
<div id="wrapper">
  <canvas id="pad" width="200" height="100"></canvas>
</div>
```

```css
canvas {
  border: red 1px solid;
}
```

```js
// Inspiration: https://stackoverflow.com/a/60057521
// Version with no React

const canvas = document.querySelector('#pad');
const signPad = new SignaturePad(canvas);
// Doesn't work without the #wrapper. Probably because #pad
// needs it to be able to be 100% of it. Not sure exactly
// why that makes a difference when #wrapper doesn't have
// a width set on it. Though #pad alone does work after the
// first resize.
let prevWidth = $('#wrapper').width();
let lines = [];


setTimeout(resizeSignatureAndCanvas, 0);
window.addEventListener("resize", () => setTimeout(resizeSignatureAndCanvas, 0));
window.addEventListener("orientationchange", () => setTimeout(resizeSignatureAndCanvas, 0));


function resizeSignatureAndCanvas () {
  // Get the current canvas contents
  lines = signPad.toData();
  
  // if there are no lines drawn, don't need to scale them
  if ( signPad.isEmpty() ) {
    // Set initial size
    resizeCanvas();
  } else {
    
    // Calculate new size
    let currentWidth = $('#wrapper').width();
    let scale = currentWidth / prevWidth;
    prevWidth = currentWidth;  // Prepare for next time
    // Scale the contents along with the width
    setRescaledSignature(lines, scale);
    // Match canvas to window size/device change
    resizeCanvas();
    // Load the adjusted canvas contents
    signPad.fromData(lines);
  }
};


// This is really the key to keeping the contents
// inside the canvas. Getting the scale right is important.
function setRescaledSignature (lines, scale) {
  lines.forEach(line => {
    line.points.forEach(point => {
      // Same scale to avoid warping
      point.x *= scale;
      point.y *= scale;
    });
  });
};


function resizeCanvas () {
  /** Have to resize manually to keep the canvas the width of the
  *   window without distorting the location of the "pen". */
  
  // I'm not completely sure of everything in here
  const canvas = $('#pad')[0];

  // Not sure why we need both styles and props
  canvas.style.width = '100%';
  canvas.style.height = (canvas.offsetWidth / 1.75) + 'px';
  
  // When zoomed out to less than 100%, for some very strange reason,
  // some browsers report devicePixelRatio as less than 1
  // and only part of the canvas is cleared then.
  let ratio = Math.max(window.devicePixelRatio || 1, 1);
  // This part causes the canvas to be cleared
  canvas.width = canvas.offsetWidth * ratio;
  canvas.height = canvas.offsetHeight * ratio;
  canvas.getContext("2d").scale(ratio, ratio);
};
```

As you can see from my notes, I'm not completely sure why every part works, but from what I can tell it does preserve the behavior of the [version](https://stackoverflow.com/a/60057521/14144258) that [@Alexey Nikonov](https://stackoverflow.com/users/9277453/alexey-nikonov) made.

Future compatibility could be helped by adding a `.scale()` to signature_pad itself. If I have time I'll make an issue and a PR.
