### ISSUE TITLE
signature_pad under bootstrap always returns height 0 not working

### ISSUE THREAD

**Issue by apaulcb** [szimek/signature_pad#320]
when ever i try to put the signature_pad under a bootstrap container, row, or even a column the signature pad collapses into a height of 0.  I´m not using, any hide, or modals, or tabs, I have posted the example on https://jsfiddle.net/qjw18qsb/ hope some one can help

I think its still something to do with bootstrap.css not letting the signature_pad have any height. 

using signatrue_pad 2.3.2 i have tried it on safari and firefox mainly

**Comment by szimek** [comment]
It works fine if I set `height` and `width` in px instead of 100% for `.signature-pad`. 

BTW. It's a better idea to use https://www.jsdelivr.com/ (e.g. https://cdn.jsdelivr.net/npm/signature_pad@2.3.2/dist/signature_pad.min.js) than to link directly to github, because Chrome and Firefox won't load such scripts.

**Comment by apaulcb** [comment]
thank you so much for this development, and its true it works fine with px instead of %, but then the size of the signature pad is lock to that size only and I loose the responsiveness that I get with bootstrap. If I change the window size to be smaller then the signature pad with and height set in px the signature pad gets "cut" out of frame of the window instead of resizing to a smaller size.  

and yes, I actually use signature_pad_min.js from local source in my actual project, i used the github for the jsfiddle test.

**Comment by szimek** [comment]
@apaulcb I guess you could leave the `height` and `width` at 100%, but then its parent element would need to have non-zero size, either using px or flexbox or grid or sth else.

**Comment by mfoote** [comment]
@apaulcb The best option is to use @medis and set up the different sizes you need in your css, see [here](https://getbootstrap.com/docs/4.1/layout/overview/#responsive-breakpoints)
