### ISSUE TITLE
getting error in prod release in ionic 3 and angular 5

### ISSUE THREAD

**Issue by meni88** [szimek/signature_pad#321]
In browser mode or in normal build the drawing works properly.
But when you build in --prod or --prod --release does not succeed in drawing and gives the following error
vendor.js:1 ERROR ReferenceError: a198254 is not defined
at a._calculateCurveControlPoints (10.js:1)
at a._addPoint (10.js:1)
at a._strokeUpdate (10.js:1)
at a._strokeMoveUpdate (10.js:1)
at HTMLCanvasElement._handleTouchMove (10.js:1)
at t.invokeTask (polyfills.js:3)
at Object.onInvokeTask (vendor.js:1)
at t.invokeTask (polyfills.js:3)
at r.runTask (polyfills.js:3)
at e.invokeTask [as invoke] (polyfills.js:3)

Thank you very much to anyone who helps

**Comment by rpanadero** [comment]
I'm having the same issue.

**Comment by szimek** [comment]
Hey, you'll have to figure out what this `a198254` variable is in your minified code. You can probably beautify this code in any editor and compare minified code with the source code and see what it is. It most likely is some issue with JS minification, but without seeing the minified code it's hard for me to tell what's wrong.

**Comment by meni88** [comment]
There is probably a problem with the ionic build
this the line from the build code 10.js
"m=n.x-(a198257.x+(r-d)*v),g=n.y-(a198257.y+(u-c)*v);"
and i search in all build pages and not define var like this : a198257

**Comment by KevinSchiffmann** [comment]
Hello,
First, thank you very much for the lib :)
We have the same minified issue without ionic (with angular 5.0.3 and CLI 1.5.4). It seems to come from these two const (m1 & m2) badly minified:
https://github.com/szimek/signature_pad/blob/master/src/signature_pad.js#L280
https://github.com/szimek/signature_pad/blob/master/src/signature_pad.js#L281

Here is my minified version (with var a3075 undefined):

```
u.prototype._calculateCurveControlPoints = function(n,l,e) {
  var o = n.x-l.x,
      u = n.y-l.y,
      i = l.x-e.x,
      a = l.y-e.y,
      r = (n.x+l.x)/2,
      d = (n.y+l.y)/2,
      s = (l.x+e.x)/2,
      c = (l.y+e.y)/2,
      m = Math.sqrt(o*o+u*u),
      f = Math.sqrt(i*i+a*a),
      p = f/(m+f),
      h = l.x-(a3075.x+(r-s)*p),
      v = l.y-(a3075.y+(d-c)*p);
      return {
        c1: new t(r+h,d+v),
        c2: new t(s+h,c+v)
      }
    }
```

**Comment by szimek** [comment]
Could you report it to ionic? I'm not sure if I can do anything about it, if the minifier they're using produces broken code.

**Comment by meni88** [comment]
I've already reported to ionic but I got out of it in the meantime because I had to release a version of the application
https://forum.ionicframework.com/t/angular2-signaturepad-unable-to-paint-in-prod-mode-on-device/113782/14?u=meni_oz

**Comment by anilchinnu21** [comment]
I am having the same issue while using it with Angular 4 and Angular cli 1.5.5. Works fine in dev environment but throws this exception in Prod mode (with minification). Any idea if this is to do with CLI or with Signature pad itself.
`a463752 is not defined
main.b211f109c1c078f73dca.bundle.js:formatted:14182 ReferenceError: a463752 is not defined
    at i.G7vL.i._calculateCurveControlPoints (vendor.c2e3bd2e6d7de550cf94.bundle.js:1)
    at i.G7vL.i._addPoint (vendor.c2e3bd2e6d7de550cf94.bundle.js:1)
    at i.G7vL.i._strokeUpdate (vendor.c2e3bd2e6d7de550cf94.bundle.js:1)
    at i._strokeMoveUpdate (vendor.c2e3bd2e6d7de550cf94.bundle.js:1)
    at HTMLCanvasElement._handleMouseMove (vendor.c2e3bd2e6d7de550cf94.bundle.js:1)
    at t.invokeTask (polyfills.db7e1d510e23dd22e788.bundle.js:1)
    at Object.onInvokeTask (vendor.c2e3bd2e6d7de550cf94.bundle.js:1)
    at t.invokeTask (polyfills.db7e1d510e23dd22e788.bundle.js:1)
    at r.runTask (polyfills.db7e1d510e23dd22e788.bundle.js:1)
    at e.invokeTask [as invoke] (polyfills.db7e1d510e23dd22e788.bundle.js:1)`

**Comment by szimek** [comment]
@anilchinnu21 Can you check which version of uglifyjs you're using?

**Comment by anilchinnu21** [comment]
@szimek it's 2.8.29

**Comment by stevebauman** [comment]
Getting same issue with only prod releases using Laravel's elixir. Keep in mind I'm using over 28 JS packages and only this one causes issues.

Generates the exception:

> app.js?id=70e9ec4ef31356e4b661:formatted:11459 Uncaught ReferenceError: a6039 is not defined

Here is where it fails (compiled code):

```js
o.prototype._calculateCurveControlPoints = function(t, e, n) {
    var i = t.x - e.x
    , o = t.y - e.y
    , a = e.x - n.x
    , s = e.y - n.y
    , u = (t.x + e.x) / 2
    , l = (t.y + e.y) / 2
    , c = (e.x + n.x) / 2
    , d = (e.y + n.y) / 2
    , f = Math.sqrt(i * i + o * o)
    , h = Math.sqrt(a * a + s * s)
    , p = h / (f + h)
    , m = a6039.x + (u - c) * p // <-- Fails here
    , v = a6039.y + (l - d) * p
    , g = e.x - m
    , _ = e.y - v;
    return {
        c1: new r(u + g,l + _),
        c2: new r(c + g,d + _)
    }
}
```

**Comment by stevebauman** [comment]
Just for some more information, if I run `npm run dev` it compiles fine and works great in all browsers, but as soon as I run `npm run prod` and compiles for production, as soon as I touch the canvas this error gets generated as I move my mouse through it. I can click the canvas and place dots without error.

**Comment by stevebauman** [comment]
Sorry for the spam! Downgraded to `v2.2.1` and it compiles fine and works without issue. :smile:

**Comment by urbanjaklin** [comment]
Encountering the same issue using yarn (webpack).

**Comment by DmGolovchenko** [comment]
I use angular-cli and build project by forward command: ng build --prod --env=prod
I have the same issue. But if update _calculateCurveControlPoints function inside of signature_pad.mjs file to forward:
SignaturePad.prototype._calculateCurveControlPoints = function (s1, s2, s3) {
  var dx1 = s1.x - s2.x;
  var dy1 = s1.y - s2.y;
  var dx2 = s2.x - s3.x;
  var dy2 = s2.y - s3.y;

  var m1 = { x: (s1.x + s2.x) / 2.0, y: (s1.y + s2.y) / 2.0 };
  var m2 = { x: (s2.x + s3.x) / 2.0, y: (s2.y + s3.y) / 2.0 };
  
  var test = m2; // <- Add this line

  var l1 = Math.sqrt(dx1 * dx1 + dy1 * dy1);
  var l2 = Math.sqrt(dx2 * dx2 + dy2 * dy2);

  var dxm = m1.x - m2.x;
  var dym = m1.y - m2.y;

  var k = l2 / (l1 + l2);
  var cm = { x: m2.x + dxm * k, y: m2.y + dym * k };

  var tx = s2.x - cm.x;
  var ty = s2.y - cm.y;

  return {
    c1: new Point(m1.x + tx, m1.y + ty),
    c2: new Point(m2.x + tx, m2.y + ty)
  };
};

Then ng build --prod --env=prod command works fine. 
This solution works for me.
