### ISSUE TITLE
[Feature Request] Signature complexity validation

### ISSUE THREAD

**Issue by natezerk** [szimek/signature_pad#322]
Is there a way to validate the complexity of the signature to stop simple signatures being validated (example a single dot).

Is there some way to perhaps validate using the number of points of the signature on the canvas?

**Comment by szimek** [comment]
You can use `SignaturePad#toData` method to get raw data and use it to do any kind of validation you might need.

It returns an array of arrays of points, something like:
```
[
  [point, point, point],       // a line
  [point],                     // a dot
  [point, point, point, point] // another line
]
```
So you can do validations like:
```
const groups = signaturePad.toData();

// same as isEmpty
groups.length === 0 

// check if there's at least one group with more than 5 points
groups.some(group => group.length > 5)
```

Hope this helps.

**Comment by natezerk** [comment]
Great response thanks.
