### ISSUE TITLE
Embed Into Standard HTML Page

### ISSUE THREAD

**Issue by RossMarlow** [szimek/signature_pad#323]
Hi, I'm struggling to add this to a HTML page. I was wondering if someone could talk me through embedding it from beginning to end as I've tried many things but don't seem to be getting anywhere.

Thanks,
Ross

**Comment by RossMarlow** [comment]
Thanks very much, I did try using this yesterday but I now realize I must've had the HTML file in a different location to the js and css folders so it wasn't finding them.

Thank you. I'll have to have a mess tomorrow now about embedding just the signature pad to the bottom of my form without the background and also attaching the signature into an email sent from the website. I will probably end up returning to this page. I have the form set up which makes a full mailto link with all the details so I'll just have to get this attached somehow and then get it to send through the website rather than opening the mail program but I will return as and when.

Thanks again,
Ross

**Comment by RossMarlow** [comment]
Hi,

I've just attempted to embed this pad again but when I open the webpage the outline, buttons and "sign above" is there but the canvas is not.

Could you advise?

Thanks,
Ross

**Comment by RossMarlow** [comment]
By removing the CSS you provided it works but the pad is very small so I guess I just need to tweak the CSS so I will try this and then come back.

**Comment by RossMarlow** [comment]
Just to let you know, I managed to edit the CSS and get my webpage displaying properly again with the signature pad still fully working. I just need to figure out how to attach the signature into the mail to link. This webpage will be accessed on an iPad to take people's details. Have you any ideas how I could implement this?

**Comment by szimek** [comment]
You could probably use `onEnd` callback that is called at the end of every stroke.

```js
signaturePad.onEnd(() => {
  const data = signaturePad.toDataURL();
  // update your link with new data
});
```

If you have any more questions, please reopen this issue.
