### ISSUE TITLE
Module not found: Error: Can't resolve 'signature_pad

### ISSUE THREAD

**Issue by tabishsoh** [szimek/signature_pad#325]
I am getting below error while compiling. signature-pad is available in node modules.

> Error: ./node_modules/angular2-signaturepad/signature-pad.js
> Module not found: Error: Can't resolve 'signature_pad' in '/Users/TabishSohail/Desktop/devdactic-pad/node_modules/angular2-signaturepad'
> resolve 'signature_pad' in '/Users/TabishSohail/Desktop/devdactic-pad/node_modules/angular2-signaturepad'
>   Parsed request is a module
>   using description file: /Users/TabishSohail/Desktop/devdactic-pad/node_modules/angular2-signaturepad/package.json (relative path: .)
>     Field 'browser' doesn't contain a valid alias configuration
>   after using description file: /Users/TabishSohail/Desktop/devdactic-pad/node_modules/angular2-signaturepad/package.json (relative path: .)
>     resolve as module
>       looking for modules in /Users/TabishSohail/Desktop/devdactic-pad/node_modules
>         using description file: /Users/TabishSohail/Desktop/devdactic-pad/package.json (relative path: ./node_modules)
>           Field 'browser' doesn't contain a valid alias configuration
>         after using description file: /Users/TabishSohail/Desktop/devdactic-pad/package.json (relative path: ./node_modules)
>           using description file: /Users/TabishSohail/Desktop/devdactic-pad/package.json (relative path: ./node_modules/signature_pad)
>             no extension
>               Field 'browser' doesn't contain a valid alias configuration
>               /Users/TabishSohail/Desktop/devdactic-pad/node_modules/signature_pad doesn't exist
>

**Comment by Chumillas** [comment]
Same here
Using Ionic 3 and angular2-signaturepad 2.6.1

Please update your post with more info of your environment
