### ISSUE TITLE
Size initialization failure when initial size of canvas (width and height) are specified on CSS

### ISSUE THREAD

**Issue by liguori** [szimek/signature_pad#326]
This jsfiddle show-up the actual issue
https://jsfiddle.net/gianluigiliguori/h0cg3s8u/
I expect that using CSS instead of HTML Attributes for define the canvas size the signature-pad would be fine.
I am using the last version of signature-pad on Chrome v63.0.3239.84

**Comment by weotch** [comment]
I'm experiencing same behavior, Chrome 64 and Firefox 60.

**Comment by liguori** [comment]
Hi @weotch, I resolved with this initialization on the constructor of the SignaturePad (look just the modified code):
https://github.com/liguori/signature_pad/commit/1dba267be9e4fd7c4850887cdc128e805ac51253

I made also a PR to the @szimek original repository and He accepted it. I noticed now that the whole codebase of the repository has been written in TypeScript and maybe these changes are not "rewritted".

I went deeply to this problem at the time and I remember that the problem is due to the fact that the CSS sizes are note "propagated" to the JS property of the Canvas object and as reported here:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/width
It assume the the default value of '300'.

Let me know if you need more explenation.

**Comment by liguori** [comment]
Let's wait for a @szimek  comment

**Comment by lukeliasi** [comment]
What about just doing this?
```
signaturePad.canvas.setAttribute("width", "350");
signaturePad.canvas.setAttribute("height", "200");
```

**Comment by UziTech** [comment]
closing as stale
