### ISSUE TITLE
Restore signature from localstorage from different page where canvas is shown

### ISSUE THREAD

**Issue by Tumke** [szimek/signature_pad#328]
Hi,

I try to restore a signature into the canavas from a base64 file. This works only when i'm visiting the page where the canvas is placed. 
Let's say i have 2 pages. If page 1 is loaded i want to restore the signature, which is in de local storage, the canvas is on page2. If i visit the second page were the canvas is, the signature is not shown. 

If i restore the signature when visiting page2, everythings works. 

I made i fidde as example http://jsfiddle.net/g5vAN/252/

**Comment by UziTech** [comment]
closing as stale
