### ISSUE TITLE
undefined is not an object (evaluating 'this._data[this._data.length-1].push')

### ISSUE THREAD

**Issue by lathonez** [szimek/signature_pad#329]
Hey,

I'm just raising this for your visibility / in case you have any ideas. I don't have a repro and am not expecting you to be able to do anything to solve this.

We're getting this error thrown on one of our production apps. We have lots of apps running out there and only one has ever had this issue, which suggests to me it might be device related.

The error

```
undefined is not an object (evaluating 'this._data[this._data.length-1].push')
```

Is being thrown from here:

https://github.com/szimek/signature_pad/blob/master/src/signature_pad.js#L173-L178

That's pretty much all the info I have. The client using the app hasn't reported anything to us from a behaviour perspective.

Other info:

* Ionic 3 / Angular 4 app deployed via the AppStore
* iPad Model: iPad6,11
* UA: UA: Mozilla/5.0 (iPad; CPU OS 11_0_1 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Mobile/15A402

I am tracking the issue and will update you if I get further information.

Thanks for all your hard work on this repo,

Stephen

**Comment by lathonez** [comment]
Just seen again on another instance of the app:

* iOS 11.2.5
* iPad6,11

**Comment by stefankunze** [comment]
I also can see that Issue on Chrome Mobile v.56.0.2924/64.0.3282 on Android v.7.0

**Comment by timbru31** [comment]
I'm joining the club with the error messages:
`TypeError: Cannot read property 'push' of undefined` and `TypeError: Cannot read property 'length' of undefined`

Our tracking said it's a Samsung SM-T5851 with Chrome 64.0.01 and running Android 7.0.01

---
Minified stack trace:
```
Cannot read property 'push' of undefined
at i._strokeUpdate (scripts.09258a303eed71dcb9ac.bundle.js:1)
at i._strokeMoveUpdate (scripts.09258a303eed71dcb9ac.bundle.js:1)
at HTMLCanvasElement._handleTouchMove (scripts.09258a303eed71dcb9ac.bundle.js:1)
at e.invokeTask (polyfills.395920b077ebea14c462.bundle.js:1)
at Object.onInvokeTask (main.4f4970c93c661f275c5d.bundle.js:1)
at e.invokeTask (polyfills.395920b077ebea14c462.bundle.js:1)
at t.runTask (polyfills.395920b077ebea14c462.bundle.js:1)
at t.invokeTask [as invoke] (polyfills.395920b077ebea14c462.bundle.js:1)
at _ (polyfills.395920b077ebea14c462.bundle.js:1)
at HTMLCanvasElement.m (polyfills.395920b077ebea14c462.bundle.js:1)
```

**Comment by bbialas** [comment]
+1

**Comment by sp53519** [comment]
+1

**Comment by jmeinke** [comment]
Maybe the TypeScript rewrite (-> version 3) from @szimek will remove this error. We also have got a report about it via Sentry for Mobile Safari 12.0 on iPad with iOS 12.1.1. We are currently using Signature Pad version 2.3.2.

**Comment by busiweb** [comment]
I think I've found the solution: Add the following line inside the _o.prototype.clear_ function (above everything else):
`this._data = [];`

**Comment by rafaelgrilli92** [comment]
@busiweb did it work? If so, do a pull request with the fix, plz

**Comment by dphrag** [comment]
Saw this reported on a Safari 12.1 / iOS 12.2 device :(

**Comment by JosNun** [comment]
Also experiencing this issue. iPad with iOS 12.2

**Comment by lewisloofis** [comment]
Also experiencing this issue, Samsung SM-J730G with Android 7.0

**Comment by webfletch** [comment]
Also experiencing this issue on iPhone 11 Pro with iOS 13.4.1. It doesn't seem to cause a problem for the end-user but now that my App has error logging it is rather annoying receiving alerts about this.

**Comment by JosNun** [comment]
@UziTech As far as I'm aware, this issue hasn't been resolved. I'm assuming it's been closed to clean up issues that are stale?

**Comment by UziTech** [comment]
If this is still an issue you can open another issue with more information. As far as I know this issue has been resolved in the latest beta release.

**Comment by JosNun** [comment]
Ah, my bad. I looked at the tags and didn't see a beta 4 tag. I didn't realize that beta 4 had only been pushed to NPM.

**Comment by agilgur5** [comment]
Looking at #481, I believe it should have fixed this as well. The [early return](https://github.com/szimek/signature_pad/blob/878786ef6ef38bf317d1cf674b3455d39e98d270/src/signature_pad.ts#L309) for the race condition there is in the same method as this issue. So, if I understand correctly, if `this._data.length === 0` this line won't be hit either and so this error shouldn't occur if it happens due to the same race condition evaluating to `this.data[-1].push`
