### ISSUE TITLE
Add info to README about different ways of handling orientationchange event.

### ISSUE THREAD

**Issue by szimek** [szimek/signature_pad#33]
Some solutions: https://github.com/szimek/signature_pad/issues/32

**Comment by shawe** [comment]
In my opinion the issues 33, 94, 104, 161 and maybe others, have the same related issue.

I solved with this change, explained here: https://github.com/szimek/signature_pad#handling-high-dpi-screens

`function resizeCanvas() {
    var ratio =  Math.max(window.devicePixelRatio || 1, 1);
    canvas.width = canvas.offsetWidth * ratio;
    canvas.height = canvas.offsetHeight * ratio;
    canvas.getContext("2d").scale(ratio, ratio);
    signaturePad.clear(); // otherwise isEmpty() might return incorrect value
}

window.addEventListener("resize", resizeCanvas);
resizeCanvas();`

and my change is this:

`      function resizeCanvas() {
         var ratio = Math.max(window.devicePixelRatio || 1, 1);
         canvas.width = canvas.offsetWidth * ratio;
         canvas.height = canvas.offsetHeight * ratio;
         canvas.getContext("2d").scale(ratio, ratio);
      }

      function drawCanvas() {
         resizeCanvas();
         signaturePad = new SignaturePad(canvas);
         if ("{$fsc->firma}" !== "") {
            signaturePad.fromDataURL("{$fsc->firma}");
         }
      }
      
      window.addEventListener("resize", drawCanvas);
      drawCanvas();`

If you try to resize without drawing, you lose your drawing, but if you resize and before draw on canvas, the image is always here.

For me, the problem that still persist is that canvas don't respect the original aspect ratio if you use a dynamic width for the canvas. I prefer respect the original image aspect ratio, stored without blank data and put it centered on any canvas size, resizing the image but respecting the original, like people are saying on issue number 200.

**Comment by oshihirii** [comment]
What is:

    {$fsc->firma}

**Comment by shawe** [comment]
@oshihirii sorry for my delay to reply you, I'm putting signature_pad on a plugin of FacturaScripts (an Eneboo alternative based on web) to add signature in documents, this is a value from the controller that contains the signature value stored in the database, this is the way that use RainTPL, and $fsc are $this on the controller that is extended from fs_controller and store the value in $fsc, and for this reason we use this var name on the view.

On next major version it will be re-writted to use some Symfony components and RainTPL must be replaced with Twig, and support multi-language that isn't actually supported.

**Comment by shawe** [comment]
I "solved" this problem, but image results scaled in aspect ratio from original size created from user, but at least works and it's usable.

**Comment by UziTech** [comment]
closing as stale
