### ISSUE TITLE
Signature is much larger than canvas when I use fromDataURL

### ISSUE THREAD

**Issue by Zuldra** [szimek/signature_pad#332]
Hello.

When I save a signature and then reload it using fromDataURL, the signature is multiplied in size and larger than the canvas. I am using the simplest implementation of a signature_pad in my app, so it seems there is an issue with signature_pad not allowing this behavior to be predictable and simple.

Can anyone please suggest me how to reload the image using fromDataURL with the same size as the original? And without complex canvas manipulation?

Thank you.

**Comment by psychochicken** [comment]
Having the exact opposite problem as Zuldra. When reading a signature fromDataURL, the signature on the canvas is about 25% smaller. I've also got a very simple Signature Pad set up, be happy to give more details if needed.

**Comment by n3b** [comment]
@psychochicken `.fromDataURL(url, {ratio: 1})`

**Comment by wdmtech** [comment]
@n3b You rock, my friend. Thanks!

**Comment by nikola1970** [comment]
@n3b thanks!
