### ISSUE TITLE
reduce Point.color data

### ISSUE THREAD

**Issue by lukescott** [szimek/signature_pad#333]
**Do you want to request a feature or report a bug?**

Feature and "Bug"

**What is the current behavior?**

Every single point stores `color: black`.

**What is the expected behavior?**

Feature:

As stated by this comment in the code:

```js
// All points in the group have the same color, so it's enough to set
// penColor just at the beginning.
this.penColor = color;
```

Only the first `color` property of the first point is used for each stroke. Since the rest is not used, only the first point should store the color.

I would also suggest omitting color from the first point if the color is `black`, or if the color is the same from the previous stroke.

"Bug":

If I remove `color: black` for storage, and then attempt to load it back into signature_pad nothing is drawn. So it appears to be not loading any defaults. The TypeScript definition of Point on DefinitelyTyped lists `color` as an optional property. Also the point.js file does not contain `color`. 

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**

2.3.0
Chrome 63
Mac OS X

**Comment by szimek** [comment]
It's been a while, but I just released 3.0.0-beta.1 version that changes the structure of data returned from `SignaturePad#toData` method. It returns an array of point groups, where each point group has 2 fields: `color` and `points`.
