### ISSUE TITLE
signaturePad.toDataBlob()

### ISSUE THREAD

**Issue by Gruski** [szimek/signature_pad#334]
I need to POST the signature from signature_pad to a server as a binary blob (.png). I see examples on getting the base64 encoded data url but not how to get the .PNG binary blob.

Need a signaturePad.toDataBlob("image/png"); function unless one already exists.

**Comment by szimek** [comment]
You can convert image in base64 to blob yourself: https://stackoverflow.com/questions/16245767/creating-a-blob-from-a-base64-string-in-javascript.

From the post linked above:
```js
var byteCharacters = atob(b64Data);
var byteNumbers = new Array(byteCharacters.length);
for (var i = 0; i < byteCharacters.length; i++) {
    byteNumbers[i] = byteCharacters.charCodeAt(i);
}
var byteArray = new Uint8Array(byteNumbers);
var blob = new Blob([byteArray], {type: contentType});
```

Hope that helps!

**Comment by Gruski** [comment]
Yes but why does the signature_pad convert it to base64 in the first place only to have us decoded back when this format is not needed for every scenario. It seems like the default format should be raw binary which takes less space and doesn't require signature_pad to encode it. Then there could be a function to encode it for those who need that extra step. But for signature_pad to assume we want it encoded and do this needless task only for us to undo it seems like a waste.

**Comment by szimek** [comment]
You still got access to `canvas` element, so you can also simply do `Canvas#toBlob` ;) At the time of writing this library `canvas.toBlob` was not supported by most browsers (even `Canvas#toDataURI` was not supported by then still popular Android 2.3), so it was not added.

I'm just not sure if it makes sense to add a wrapper for every possible canvas method that allows you to get data back from it, if you still got access to the canvas itself and can call methods on it directly.

**Comment by Gruski** [comment]
Good point. I'll use canvas.toBlob(). It seems to be well supported now.
By this thought then maybe signaturePad.toDataURL() should no longer exist either when canvas.toDataURL() is widely supported.

**Comment by szimek** [comment]
`SignaturePad#toDataURL` accepts custom `'image/svg+xml' option that is not supported by `Canvas#toDataURL`. I could remove `toDataURL` and add `SignaturePad#toSVG`, but I think it's simpler to have one method for that.

Please reopen this ticket if you have more questions.
