### ISSUE TITLE
No "onClear" event

### ISSUE THREAD

**Issue by v1rich** [szimek/signature_pad#336]
Need an onClear event like the onEnd event.  I am using these events to populate a hidden field with the toDataUrl value.  It's easy enough to add it so I added it in my local copy.  

I've never contributed to open source software so hence I am submitting it as an issue rather than trying to submit the fix for it myself.  It's just not something I have gotten into yet.

//in setup
this.onClear = opts.onClear;

//at end of clear event
if (typeof this.onClear === 'function') {
      this.onClear(event);
}

**Comment by UziTech** [comment]
closing as stale. It seems like this could be easily done without changes to this library. When ever you call `clear()` run the function. No need for an event to fire.
