### ISSUE TITLE
In android > 6 not work?

### ISSUE THREAD

**Issue by algp** [szimek/signature_pad#337]
Hello,

It is possible that from version 6 of android the package does not work?

I have tried the same implementation in the version of android 6 and it works. But in versions 7 and 8 of Android does not work.

Do you know if it can be a bug and you know how to fix it?

Thank you very much. A greeting.

**Comment by szimek** [comment]
Could you elaborate a bit on what you mean exactly by "does not work"? The demo page works fine for me on a phone with Android 6.

**Comment by algp** [comment]
Hello,

Thank you very much for answering.

When I try to make a signature on an android version 7, the trace that should appear while I am signing does not appear.

However, if I capture the signature, the signature has been generated correctly.

**Comment by szimek** [comment]
Does it happen on the [demo page](http://szimek.github.io/signature_pad/) as well?

You can connect your phone to your computer and use [Chrome remote debugging](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/) to see if you get any errors in dev tools console.
