### ISSUE TITLE
Touch tracking

### ISSUE THREAD

**Issue by Gruski** [szimek/signature_pad#338]
I have a canvas that is 300 width by 100 height. When I start drawing on the canvas from top to bottom vertically the ink is drawn right under the touch point at the top but as the touch point is moved downward the drawn line lags behind proportional to the distance from the top so that by the time the touch point reaches the bottom of the canvas the line being draw is well above the touch point. 

So in other words the line being drawn is not synchronized with the tough position. Noticed this behavior changes with the size of the canvas. For example if I increase the height of the canvas to 150 this problem goes away and if I increase it even more the problem comes back lagging in the other direction. 

Same issue with horizontal tracking if the canvas is narrow.

This seems like some kind of ratio calculation problem.

**Comment by Safi87** [comment]
Hi Gruski,

I had the same problem. It was happening because I wasn't applying resizeCanvas function, when I added it, my problem disappeared.

**Comment by Gruski** [comment]
Yes, thanks. I found that in the Wiki.
