### ISSUE TITLE
New version doesn't work with IE11.

### ISSUE THREAD

**Issue by sigoofballde** [szimek/signature_pad#339]
Newest signature_pad.js file is not compatible with IE11. Works with Chrome, Firefox, and Opera. All the examples work on IE11 but they are not using the newest code. The below is the results of my research.

Code from examples that work in IE11:
![image](https://user-images.githubusercontent.com/18445648/36283762-8cec52bc-1249-11e8-8a08-7eec58e6265c.png)

Doesn't work in IE11:
![image](https://user-images.githubusercontent.com/18445648/36283688-4bc533a8-1249-11e8-9663-23215072ebf1.png)

**Comment by szimek** [comment]
Which file are you loading exactly? If you check [signature_pad.js](https://cdn.jsdelivr.net/npm/signature_pad@2.3.2/dist/signature_pad.js) or [signature_pad.min.js](https://cdn.jsdelivr.net/npm/signature_pad@2.3.2/dist/signature_pad.min.js), you'll notice that there's no such code.

**Comment by sigoofballde** [comment]
https://github.com/szimek/signature_pad/blob/master/src/signature_pad.js

**Comment by szimek** [comment]
How are you loading it? Using `<script>` tag or webpack or ...? 

If you're using `<script>` tag, then you should load this file: https://cdn.jsdelivr.net/npm/signature_pad@2.3.2/dist/signature_pad.min.js

If you use e.g. webpack and install this package using `npm install signature_pad` or `yarn add signature_pad`, you can simply use `import SignaturePad from 'signature_pad'`. It will use built files from `dist` folder then, not source files from `src` folder.

**Comment by sigoofballde** [comment]
I was loading all the files using script tag. I downloaded the .min file from jsdelivr.net and it worked. Thanks for the quick feedback.

**Comment by TulsiramJat** [comment]
@szimek  I'm using it throw yarn install, It is not working in IE11, It is using build files but it's breaking some where in IE11.

**Comment by TulsiramJat** [comment]
how to downgrade it to stable version???
