### ISSUE TITLE
am not able to resize image on signature-pad( ionic 3)

### ISSUE THREAD

**Issue by amolumesh12** [szimek/signature_pad#346]
am trying to draw on image..which is placed on signature-pad..am able to display image on signature-pad and drawing on image..but that image is displaying in one corner of signature-pad so it occupying only 1 corner of signature-pad..i want to display that image on entire canvas of signature-pad

please find below attach output of my project(ionic 3 )[my output screen shot of image][1]

[1]: https://i.stack.imgur.com/4KMxq.jpg i tried this in my canvasResize() function ..but its not work see my below

canvasResize() {
    let canvas = document.querySelector('canvas');
    var ratio =  window.devicePixelRatio || 1;
    canvas.getContext("2d").scale(ratio, ratio);
   this.signaturePad.set('minWidth', 1);
   this.signaturePad.set('canvasWidth', canvas.offsetWidth);
    this.signaturePad.set('canvasHeight', canvas.offsetHeight);
 }

i add this Ionic2 Signature Pad resize image in my function but still it not work

**Comment by amolumesh12** [comment]
help me plase

**Comment by cabaird** [comment]
+1

**Comment by ForAFuture** [comment]
Me too
