### ISSUE TITLE
onEnd is not actually end.

### ISSUE THREAD

**Issue by vincent-cm** [szimek/signature_pad#349]
The throttle function takes updateStroke a default 16ms delay after it arrives onEnd event. (there is the last dot to be drawn asynchronously with the onEnd event)
Consider running onEnd synchronously after the final stroke update

**Comment by PieterVanPoyer** [comment]
Hello, I made a pull request for this a while ago. https://github.com/szimek/signature_pad/pull/313

**Comment by vincent-cm** [comment]
Thanks @PieterVanPoyer

**Comment by PieterVanPoyer** [comment]
It is not yet merged in the master. And I don't know if it will ever be merged.
That's up to szimek.

**Comment by vincent-cm** [comment]
@PieterVanPoyer yep, I have to steal your code from the pull lol
