### ISSUE TITLE
Needs "change" event / callback.

### ISSUE THREAD

**Issue by coolaj86** [szimek/signature_pad#35]
In order for this to work properly in the context of angular (data-binding and such), there needs to be an "change" event that fires whenever a draw action is complete. I think it would be generally useful in many cases.

``` javascript
var token;
signaturePad.onchange = function () {
  clearTimeout(token);
  token = setTimeout(function () {
      signaturePad.toDataURL()
      // update ng-model
      // trigger ng-change
  }, 500);
};
```

Is that something you'd be willing to add?

**Comment by ParagShinde** [comment]
can I use this event like this from dom?
 <signature-pad  
   [options]="signaturePadOptions" (onEnd)="captureImage()" class="signatureCanvas">
  </signature-pad>
