### ISSUE TITLE
Allow multiple touch

### ISSUE THREAD

**Issue by renatodolza** [szimek/signature_pad#352]
**Do you want to request a feature or report a bug?**
Hello everyone, everything good? Taking a look at the repository I found a topic asking to disable, but I did not find anything that would allow. I know it does not have much to do for a 'signature', but it is that it was very good to put this tool in my project and now I need to enable this feature, I would really appreciate some help from you. Thank you!

**What is the expected behavior?**
Allow multiple touch

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**
SignaturePad: 2.3.2
Chrome: 65.0.3325.124

**Comment by UziTech** [comment]
closing as stale

**Comment by renatodolza** [comment]
> closing as stale

Why? This is a cool feature and I am in need.

**Comment by UziTech** [comment]
Multi touch is tricky. If someone touches the screen with their hand then trys to draw a signature nothing will be drawn since their hand was the first touch point. I don't think it is possible to create an accurate multi touch experience.
