### ISSUE TITLE
Canvas freeze when using S-pen

### ISSUE THREAD

**Issue by martijn189** [szimek/signature_pad#354]
Could anyone confirm that when using this project in combination with a Samsung S-pen (on samsung device) the browser (sometimes) freezes after placing the first dot. When using mouse cursor or finger there is no issue.

When browser freezes, it gives this error in log: ANR input dispatching timed out (waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago. Wait queue length: 121. Wait queue head age: 20512.9ms.)

**Comment by dariobednarski** [comment]
Yes, same issue here. Any solutions for that?

**Comment by UziTech** [comment]
closing as stale
