### ISSUE TITLE
Send background image + signature to server side?

### ISSUE THREAD

**Issue by hitmacreed** [szimek/signature_pad#358]
i have a background added +  the signature but it only send the signature , any idiea how to make this works?

```
html
<div class="wrapper_ass">
  <img src="images/main/various/paper.jpg" width=400 height=200 class="yolo" />
   <canvas id="signature-pad" class="signature-pad " width=400 height=200  ></canvas>
  </div>
js
$scope.signaturePad = new SignaturePad(document.getElementById('signature-pad'), {
               backgroundColor: 'rgba(255, 255, 255,0)',
                penColor: 'rgb(0,0,0)'
            }); 
$scope.file = $scope.signaturePad.toDataURL('image/jpeg',100);
```
then i send the file to server whit $scope.file...

**Comment by belamov** [comment]
@hitmacreed hey, did you figure it out?

**Comment by hitmacreed** [comment]
> @hitmacreed hey, did you figure it out?

yes , its possible check this [commit](https://github.com/szimek/signature_pad/pull/350/commits/d62e32666f72fc10509c988a75177bd76ebba7e7)
