### ISSUE TITLE
iPhone 6s Safari cannot open the page. "WebKitBlobResource error1". 

### ISSUE THREAD

**Issue by VamMeejS** [szimek/signature_pad#360]
_If you have a question, please ask it on [StackOverflow](https://stackoverflow.com/questions/ask?tags=javascript+signature-pad) and use `signature-pad` tag instead of creating an issue._

**Do you want to request a feature or report a bug?**

**What is the current behavior?**

_If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via <https://jsfiddle.net> or similar (template: <https://jsfiddle.net/szimek/h80phxyr/>)._

**What is the expected behavior?**

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**

**Comment by VamMeejS** [comment]
According to StackOverflow commenter this error is due to the way that iOS and some versions of Android (don't) handle the blob created by dataUrlToBlob. Have not been able to find a solution online and hope you can help please. Your app works great on Desktop but not on mobile devices. (I posted a question on StackOverflow as suggested. The person referred me back to GitHub.)

**Comment by rieg-ec** [comment]
Same issue here, users on old versions of Android and IOS cannot even open the site where the library is installed, has anyone found a workaround?

**Comment by ivangomes** [comment]
@rieg-ec did you try using a different browser such as Google Chrome or Firefox? (It would be nice to know the version of the iOS and Safari of the device.)

**Comment by ivangomes** [comment]
Not working on iPod touch (6th generation) Software Version: 12.5.7 using Safari.

![IMG_49F72EE1DE77-1](https://github.com/szimek/signature_pad/assets/6374624/df799abc-e7d1-41af-b2fc-3214b8c9b7ae)

**Comment by rieg-ec** [comment]
![PHOTO-2024-01-18-18-00-23](https://github.com/szimek/signature_pad/assets/58893812/acff54f7-1a90-439b-b18b-81e6c93730f1)

i don't know the version of Safari, but seems to be a bug with ios 12? it also happens on old Android versions though
