### ISSUE TITLE
Small Fix in README Examples + Angular2 wrapper

### ISSUE THREAD

**Issue by mariohmol** [szimek/signature_pad#363]
Hi,

thanks for this module.

Some points i found:

## Code Examples

The 2 examples in readme is not working because the js link has change to https://szimek.github.io/signature_pad/js/signature_pad.js

The links that are wrong: 
```
Other demos
Erase feature: https://jsfiddle.net/szimek/jq9cyzuc/
Undo feature: https://jsfiddle.net/szimek/osenxvjc/
```

## Smooth

In the main demo, when i draw i can see some smooth in the line thickness.

But using this wrapper it does not work like that.. any ideas how this can be fixed? 
https://github.com/wulfsolter/angular2-signaturepad/issues/61

Thanks!

**Comment by szimek** [comment]
Thanks for reporting these issues! I've already fixed both examples.

Regarding the Angular wrapper - I'm not really sure. The demo at http://lathonez.com/angular2-signaturepad-demo/ seems to work fine. You can play with values of `minWidth` and `maxWidth` and see if changing them makes any difference.

**Comment by mariohmol** [comment]
Awesome!!

Well.. i used the vanillajs and have the smooth behaviour.. so its something related with the wrapper.. 
thanks!
