### ISSUE TITLE
Signature Pad canvas is 0,0 even when resizing

### ISSUE THREAD

**Issue by donpedro0914** [szimek/signature_pad#370]
i don't know if there is a solution for this, my canvas width and height is automatically 0,0 even when resizing. but when i changed the value of height and width on the inspect element, i can use the signature pad.

here is my js
`  var wrapper1 = document.getElementById("signature-pad_boiler1"),
      canvas1 = wrapper1.querySelector("canvas"),
      signaturePad1;

  var wrapper2 = document.getElementById("signature-pad_boiler2"),
      canvas2 = wrapper2.querySelector("canvas"),
      signaturePad2;

  var wrapper3 = document.getElementById("signature-pad_boiler3"),
      canvas3 = wrapper3.querySelector("canvas"),
      signaturePad3;

  var wrapper4 = document.getElementById("signature-pad_boiler4"),
      canvas4 = wrapper4.querySelector("canvas"),
      signaturePad4;

  function resizeCanvas(canvas) {
      var ratio =  window.devicePixelRatio || 1;
      canvas.width = canvas.offsetWidth * ratio;
      canvas.height = canvas.offsetHeight * ratio;
      canvas.getContext("2d").scale(ratio, ratio);
  }

  resizeCanvas(canvas1);
  signaturePad1 = new SignaturePad(canvas1);

  resizeCanvas(canvas2);
  signaturePad2 = new SignaturePad(canvas2);

  resizeCanvas(canvas3);
  signaturePad3 = new SignaturePad(canvas3);

  resizeCanvas(canvas4);
  signaturePad4 = new SignaturePad(canvas4);`

**Comment by miladkardgar** [comment]
i get parent element div width and height and resize canvas.
this code fix my problem:

`  canvas.width = 500;
  canvas.height = 290;
  canvas.getContext("2d").scale(ratio, ratio);`

**Comment by ForAFuture** [comment]
The canvas size can be set. The drawn picture is also the canvas size, but the drawn content only shows the upper half
