### ISSUE TITLE
toDataURL not working properly on rotated canvas

### ISSUE THREAD

**Issue by guestisp** [szimek/signature_pad#371]
Hi to all.
I'm trying to use a rotated signature pad. Signature pad is drawn properly, i'm able to sign on a rotated canvas, but when calling `toDataURLl`, the resulting image is cut where the original, unrotated, canvas where placed initially, seems that `toDataURL` doesn't honor the rotation.

This is the code that I'm using to rotate the canvas:
```
var canvas = document.querySelector("canvas");

canvas.setAttribute("width", $$(window).height());
canvas.setAttribute("height", divSignature.height());

context = canvas.getContext("2d");

context.rotate(1.5 * Math.PI);
context.translate(-canvas.height, 0);
```

`canvas` is inside a `<div class='signature'>` rotated via CSS:

```
.rotate90right {
    -webkit-transform: rotate(90deg);
    -webkit-transform-origin: left bottom;
    transform: rotate(90deg);
    transform-origin: left bottom;

    width: 100vh;
    height: 100vw;
    overflow-x: hidden;
    position: absolute;
    top: -100vw;
    left: 0;
}
```

After all rotations, i'm initializing the signaturepad:
```
        var signaturePad = new SignaturePad(document.getElementById('signature-pad'), {
            backgroundColor: 'rgb(255, 255, 255)',
            penColor: 'rgb(0, 0, 0)'
        });
        signaturePad.clear();
```

and, as wrote above, i'm able to sign properly. The only missing thing is how to properly use the `signaturePad.toDataURL` horing the rotated canvas.

I don't need to support multiple rotations, this page starts rotated and the mobile app that i'm developing can't change orientation (is fixed in portrait), that's why I need to rotate everything via CSS

Any idea ?

**Comment by guestisp** [comment]
Any hint ? I'm using v2, latest version.

**Comment by guestisp** [comment]
bump

**Comment by 360hnjd-fe** [comment]
m
