### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getContext' of null

### ISSUE THREAD

**Issue by ibrokemypie** [szimek/signature_pad#372]
**Do you want to request a feature or report a bug?**
Report Bug

**What is the current behavior?**
signature_pad fails to initialise with ``Uncaught TypeError: Cannot read property 'getContext' of null`` on chrome and ``TypeError: t is null`` on firefox

https://hastebin.com/isayubiyam.xml
I simply copied the jsfiddle (https://jsfiddle.net/szimek/d6a78gwq/) into my own file and attempted to access it.

**What is the expected behavior?**
signature_pad working

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**
Chrome and Firefox tested, 1.5.3 and 2.3.2

**Comment by lstables** [comment]
+ 1, this all of a sudden stopped working.

**Comment by szimek** [comment]
Are you sure that you're passing valid canvas element to SignaturePad constructor? The code in already released versions hasn't changed, so it must be something caused by some change in your code or in new browser versions.

**Comment by lstables** [comment]
@szimek This is the current code I have had and had from the start and I don't believe Chrome as since updated either.

````
$( function() {

        //var SignaturePad = require('signature_pad');
        var canvas = document.getElementById("signature-pad");

        var signaturePad = new SignaturePad(canvas, {
              backgroundColor: 'rgba(255, 255, 255, 0)',
              penColor: 'rgb(0, 0, 0)'
        });
    
        var saveButton = document.querySelector('.btn-save');
        var clearButton = document.querySelector('[data-action=clear]');

        saveButton.addEventListener('click', function (e) {
            document.querySelector('[name=signature_data]').value = signaturePad.toDataURL('image/png', 100);
        });

        clearButton.addEventListener('click', function () {
            signaturePad.clear();
        });
       
        var form = $('#sign_form');

        $(saveButton).click(function() {
            $.ajax({
                url: form.attr( 'action' ),
                data: form.serialize(),
                type: 'POST',
                success: function(response, ui) {
                    swal({
                      title: "Signature Saved",
                      text: "Your signature has now been stored.",
                      icon: "success",
                    });
                    window.setTimeout(function(){window.location.reload()}, 3000);
                },
                error: function(response) {
                    console.log('Error!');
                }
            });
        });

});
````

Which comes from this form:

````
<form class="form-horizontal text-center" role="form" id="sign_form" method="post" action="{{ url('api/signature/' . user()->id) }}">

        {{ csrf_field() }}

        <div>
            <div class="digital-signature">
                <div class="form-group">
                    <canvas id="signature-pad" class="signature-pad" width="640" height="480"></canvas>
                </div>
            </div>

        </div>

        <div class="form-group">
            <input type="hidden" id="signature_data" name="signature_data" class="form-control" value="">
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default clear" data-action="clear">Clear</button>
        <button type="submit" class="btn btn-primary btn-save">Save</button>
      </div>

      </form>
````

**Comment by lstables** [comment]
Which the error is coming from the CDN script

````
Uncaught TypeError: Cannot read property 'getContext' of null
    at new b (signature_pad.min.js:5)
````

**Comment by szimek** [comment]
The line where it fails has the following code:
```ts
this._ctx = canvas.getContext("2d") as CanvasRenderingContext2D;
```
If it fails with `Cannot read property 'getContext' of null` error, then it means that `canvas` is `null`. Can you confirm that the `canvas` variable that you pass to the constructor is not null?

**Comment by lstables** [comment]
@szimek - I can confirm the canvas was null, my bad. Been a long couple of days. So as far as I am concerned I no longer have this issue 👍 :)

**Comment by ibrokemypie** [comment]
Ah yes, was calling it before the document loaded, my mistake

**Comment by HadiNiazi** [comment]
I guess the problem is your js runs before the html is loaded.

If you are using jquery, you can use the document ready function to wrap your code:

~~~
$(function() {
    var Grid = function(width, height) {
        // codes...
    }
});
~~~

**Comment by LP16333** [comment]
My bad i forget that my canvas was null i just put defer

**Comment by IuliiaLykova** [comment]
> I guess the problem is your js runs before the html is loaded.
> 
> If you are using jquery, you can use the document ready function to wrap your code:
> 
> ```
> $(function() {
>     var Grid = function(width, height) {
>         // codes...
>     }
> });
> ```

thanks, that help me too)

**Comment by sancia15** [comment]
I get same error, Cannot read property 'getContext' of null
var canvas = document.getElementById("canvas");  
    const ctx = this.canvasRef.current.getContext("2d") ;
    ctx.clearRect(0, 0, ctx.canvas.width, ctx.canvas.height);
    // Font options.
    const font = "16px sans-serif";
    ctx.font = font;
    ctx.textBaseline = "top";

**Comment by Abhishek651** [comment]
I get same error, Cannot read property 'getContext' of null




var ctx = document.getElementById("canvas").getContext("2d");
var mychart = new Chart(ctx,{
	//define type
	type:"bar",
	data:{
		labels:["Principal","Amount","interest"],
		datasets:[{
			data:[25, 60, 15],
},],
},

	
	
	
});

**Comment by UziTech** [comment]
@Abhishek651 it seems like you don't have an element with the id `canvas` so `document.getElementById("canvas")` returns null.

You probably want `document.querySelector("canvas")`
