### ISSUE TITLE
Duplicate Signature on tablet

### ISSUE THREAD

**Issue by kjaraa** [szimek/signature_pad#373]
Hi all,

I've implemented two signature pads in my project, I've this typescript class to configure them:

export class SignaturePadClienteEditor extends Serenity.Widget<any>
        implements Serenity.IGetEditValue, Serenity.ISetEditValue {

        private signaturePad: SignaturePad;
        private canvas: HTMLCanvasElement;
        private clearButton: Element;

        constructor(div: JQuery) {
            super(div);

            var canvasDiv = div.append("<canvas id='cliente'></canvas>");
            this.canvas = document.getElementById('cliente') as HTMLCanvasElement;
            this.signaturePad = new SignaturePad(this.canvas);
            var button = div.append("<button type='button' id='clear_cliente' class='button clear' data-action='clear'>Cancella</button>");
            this.canvas.height = 250;
            this.canvas.width = 500;
            this.clearButton = document.getElementById('clear_cliente');

            // Quando clicco sul bottone 'Cancella', il canvas si pulisce
            this.clearButton.addEventListener('click', () => this.signaturePad.clear());
        }

        getEditValue(prop: Serenity.PropertyItem, target) {
            target[prop.name] = this.signaturePad.toDataURL();;
        }

        setEditValue(source, prop: Serenity.PropertyItem) {
            this.signaturePad.fromDataURL(source[prop.name] || "");
        }

        // Serve per disabilitare la firma
        disableCanvas() { this.signaturePad.off(); }
        disableClearButton() { this.clearButton.setAttribute("disabled", "disabled"); }
    }

On PC is working fine, but if I use it on tablet, I have that:

![img](https://user-images.githubusercontent.com/22232670/42678086-20066076-867e-11e8-9987-b4ccf71f7577.png)

I don't understand why I got this. Does anyone have this problem and could help me ??

Thanks all for your time :)

Chiara

**Comment by kjaraa** [comment]
Anyone could help me ?

Thanks all !!

**Comment by szimek** [comment]
Can you create a demo where I can replicate this issue?

**Comment by lobo-tuerto** [comment]
Yes this is definitely happening on Android devices. It works perfectly on desktop, but when the web app is opened on a tablet it does the ghost thing signature.

**Comment by lobo-tuerto** [comment]
BTW this happens when you resize the canvas and don't go with the default size (might shed some light on why this is happening).

**Comment by lobo-tuerto** [comment]
Current workaround is to not modify the default canvas size, just leave it at 300x150 and you'd be fine.

**Comment by lobo-tuerto** [comment]
Hello, I have a live demo that showcases the problem here: https://lobotuerto.com/signature-pad

Here is a screenshot of the problem (you can reproduce it on desktop using the device toolbar on Chrome's dev tools):
![phantom-signatures](https://user-images.githubusercontent.com/5730/45334996-f48ab480-b542-11e8-8f56-d514cfa87ea1.png)

I think the nature of the problem is related to tablets/phones higher pixel densities (thus related to scaled screens). Desktop does not do screen scaling, so it works without problems there.

Here is the repo for the demo above: https://github.com/lobo-tuerto/signature-pad-troubleshooting

Hopefully this will be helpful for you.

**Comment by lobo-tuerto** [comment]
BTW I just discovered that you also get the strange behaviour if your browser zoom level is different from 100%.

**Comment by UziTech** [comment]
cloasing as stale
