### ISSUE TITLE
does not render in a jquery modal dialog form

### ISSUE THREAD

**Issue by sticcino** [szimek/signature_pad#374]
Hello,

was just exploring the library for one of my projects. I'm attempting to display the signature pad in a jquery popup window, all items appear but it will not accept any keystrokes ---
 run in a standard browser window and it works as expected.

I've downloaded the latest version from this site.

![2018-07-18 20_10_14-electron 2 0](https://user-images.githubusercontent.com/25625150/42914149-b4a6294a-8ac6-11e8-957a-4d7539560eb2.png)

**Comment by alcidesfmelof** [comment]
Same problem trying to render this in a Modal, but I am using Angular.

**Comment by szimek** [comment]
Make sure that you initialize SignaturePad **after** the canvas is present in DOM tree.

**Comment by szimek** [comment]
Please reopen this issue if the problem is still present after applying the suggestion from my previous comment.
