### ISSUE TITLE
i am unable to integrate with angular6.please provide me the code for that

### ISSUE THREAD

**Issue by Prasanth-Android** [szimek/signature_pad#375]
_If you have a question, please ask it on [StackOverflow](https://stackoverflow.com/questions/ask?tags=javascript+signature-pad) and use `signature-pad` tag instead of creating an issue._

**Do you want to request a feature or report a bug?**

**What is the current behavior?**

_If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via <https://jsfiddle.net> or similar (template: <https://jsfiddle.net/szimek/h80phxyr/>)._

**What is the expected behavior?**

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**

**Comment by denisbetsi** [comment]
If you google Angular Signature Pad you will find Angular 6 friendly wrappers.
