### ISSUE TITLE
Undo lines only on signature pad

### ISSUE THREAD

**Issue by pgtee** [szimek/signature_pad#376]
Currently I am developing a project, found out that signature pad from Github interests me and planned to use it in my project.

I have added some extra feature inside it, which enables users to upload a picture and display it on the canvas so that they can draw over the picture and save it (see the code below shows the extra code added).

The problem here is, whenever I click the undo button after I drew multiple lines over the picture, the picture disappeared as well. I want the picture to always be there, only the lines will be undone when undo button is clicked. Thanks a lots.

Extra HTML:
```
<input type='file' id="annotationUpload" name="annotationUpload" />
<div class="signature-pad--body">
  <canvas id="canvas"></canvas>
</div>
```

Extra Javascript:
```
var fileUpload = document.getElementById('annotationUpload');
var canvas = document.getElementById('canvas');
var ctx = canvas.getContext("2d");

function readImage() {
  if (this.files && this.files[0]) {
    var FR = new FileReader();
    
    FR.onload = function(e) {
      var img = new Image();
      
      img.src = e.target.result;
      img.onload = function() {
        ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
      };
    };
    FR.readAsDataURL(this.files[0]);
  }
}

fileUpload.onchange = readImage;
```

**Comment by RahulRathodGitHub** [comment]
Please refer to: https://github.com/szimek/signature_pad/issues/270#issuecomment-676843536
