### ISSUE TITLE
Feature request: Respect pressure/force on touchevents

### ISSUE THREAD

**Issue by maxfahl** [szimek/signature_pad#379]
When using for example an Apple Pen, I would love if signature_pad could respect the pressure/force property of a touch event to adjust the dotSize dynamically. Is this a feature that could be easily implemented somehow?

I will experiment a bit myself and see if I come up with a solution. Do you have any pointers of where this functionality could be implemented @szimek?

One idea is to pass the mouse/touch event to the dotSize option whenever this is a function, and let that function decide what to do with it. Would this work?

**Comment by szimek** [comment]
It's hard to answer. 

On one hand I've just added support for pointer events, which unify mouse, touch, stylus, etc. events and provide info like width of contact, pressure, tilt etc. This data is not used yet, but I plan (given enough free time) to use it to improve the drawing algorithm.

Unfortunately, Safari (desktop and iOS) does not support pointer events. However, it should provide a similar info through [touch events](https://w3c.github.io/touch-events/#idl-def-touch), which provide data such as `force` and  etc. But then the code to calculate it would probably need to be duplicated...

Also, I don't have any device (Android or iOS) that supports stylus, so it's hard for me to test it or even verify that someone's PR actually works :/

**Comment by UziTech** [comment]
Should be fixed in #566
