### ISSUE TITLE
Antialiasing bad since Chrome > 61

### ISSUE THREAD

**Issue by RomuxX** [szimek/signature_pad#386]
**bug**

**What is the current behavior?**

In Chrome 61, lines in canvas are smooth: 
![image](https://user-images.githubusercontent.com/9295109/44094577-d1819610-9fd6-11e8-9444-b17cb36138f8.png)

But since Chrome 66, lines in canvas are pixalated:
![image](https://user-images.githubusercontent.com/9295109/44094605-e6a1e78e-9fd6-11e8-8a38-c36cbec08c14.png)

**What is the expected behavior?**

Smooth lines :)

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**

3.0.0 beta 3

**Comment by szimek** [comment]
@RomuxX Just to be sure - you used the same version of this library in both Chrome 61 and 66?

**Comment by hongmomanu** [comment]
> Just

so how do you resolve the issure

**Comment by MartinH0** [comment]
@RomuxX a little late, but I think i do have to solution to this problem.

See -> #505

**Comment by UziTech** [comment]
closing as stale
