### ISSUE TITLE
Save and Clear Buttons

### ISSUE THREAD

**Issue by PMdinh** [szimek/signature_pad#39]
First of all, Thank you for sharing the wonder signature pad source code!  I am very new and very inexperience with this whole new concept.  Please help!

I am trying to implement the signature pad into an existing form.  Everything work great so far.  However, every time I click the Save or Clear buttons, it submitted my whole form instead of just clear the drawn signature.  Also, every time I click the Save button, I can see it open another window with the signature .png file but it also submitted my form.

1) How can I get the Clear button to just clear the drawn image?
2) How can I use the Save button to replay the signature pad and display the image?

Any help/suggestion would be greatly appreciated! 

Thank you,
TD

**Comment by liyansasongko** [comment]
Thank you
