### ISSUE TITLE
Signature pad on iPad not working. What do I need to do?

### ISSUE THREAD

**Issue by evan-venable** [szimek/signature_pad#391]
_If you have a question, please ask it on [StackOverflow](https://stackoverflow.com/questions/ask?tags=javascript+signature-pad) and use `signature-pad` tag instead of creating an issue._

**Do you want to request a feature or report a bug?**

**What is the current behavior?**

_If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via <https://jsfiddle.net> or similar (template: <https://jsfiddle.net/szimek/h80phxyr/>)._

**What is the expected behavior?**

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**

**Comment by EvanGertis** [comment]
I am also having issues with this feature on ipad.

**Comment by evan-venable** [comment]
I actually figured my issue out. I was testing it on an iPad that was connected to my company wifi (it doesn't have an antenna) and that wifi was preventing the scripts from loading (I'm assuming). Once I disconnected from that and tested it on another unrestricted wifi network it worked fine.


Evan Venable

IT ECM Analyst/Electronic Forms Developer

Turner Industries Group, L.L.C.

8687 United Plaza Blvd.
Baton Rouge, LA 70809
Office: 225-214-2715

Mobile: 225-454-0084

Email: evenable@turner-industries.com<http://evenable@turner-industries.com>

________________________________
