### ISSUE TITLE
Bug : scroll up/down clear signature_pad

### ISSUE THREAD

**Issue by merajmehri** [szimek/signature_pad#393]
Hi,everone
When use of the source in mobile/tablet scroll down/up signaturpad cleaning automatic how can fix this bug? Please help me 
Thanks

**Comment by BlackJohan** [comment]
Same issue here.

**Comment by razier** [comment]
I just disabled this line, its because mobile chrome triggers the onresize (since it hides the navigation bar)
//window.onresize = resizeCanvas;

But you can also modify the resizeCanvas() function to not clear the pad.

**Comment by Genarito** [comment]
You can save the data in a variable and use `fromDataURL()` to set the content every time _resizeCanvas_ is called

**Comment by JoeLeung32** [comment]
var cachedWidth;

for resize canvase

```
if(canvas.offsetWidth !== cachedWidth){ //add
    cachedWidth = canvas.offsetWidth;   //add
    var ratio = Math.max(window.devicePixelRatio || 1, 1);
    canvas.width = canvas.offsetWidth * ratio;
    canvas.height = canvas.offsetHeight * ratio;
    canvas.getContext("2d").scale(ratio, ratio);
    if (typeof signaturePad != 'undefined') {
        signaturePad.clear();
    }
}
```

**Comment by h4de5** [comment]
to temporary save and load a signature when resizing the canvas:

	function resizeCanvas() {
		var cachedWidth;
		var cachedImage;
	
		if(canvas.offsetWidth !== cachedWidth){ //add
			if (typeof signaturePad != 'undefined') { // add
				cachedImage = signaturePad.toDataURL("image/svg+xml");
			}
			cachedWidth = canvas.offsetWidth;   //add
			// When zoomed out to less than 100%, for some very strange reason,
			// some browsers report devicePixelRatio as less than 1
			// and only part of the canvas is cleared then.
			var ratio = Math.max(window.devicePixelRatio || 1, 1);
			canvas.width = canvas.offsetWidth * ratio;
			canvas.height = canvas.offsetHeight * ratio;
			canvas.getContext("2d").scale(ratio, ratio);
			if (typeof signaturePad != 'undefined') {
				signaturePad.clear();
				signaturePad.fromDataURL(cachedImage); // add
			}
		}
	}

Please note, when switching between different image ratios, the drawn signature will be dissorted.

**Comment by markdimi** [comment]
> I just disabled this line, its because mobile chrome triggers the onresize (since it hides the navigation bar)
> //window.onresize = resizeCanvas;
> 
> But you can also modify the resizeCanvas() function to not clear the pad.

Sometimes the browser clears the canvas on its own, when resizing. Hopefully this doesn't happen when just scrolling by a canvas.

**Comment by UziTech** [comment]
closing as stale. Nothing this library can do about it.
