### ISSUE TITLE
Penwidth not same when using fromData and toData

### ISSUE THREAD

**Issue by t42ji2ji** [szimek/signature_pad#396]
I write a program it can support changing penwidth when you drawing
but when I draw something and click undo (fromData toData)
canvas did not perform right

**What is the current behavior?**
1. First I draw two circles. One penwidth is 2 and another is 10 (pic.1)
2. I run "undo (fromData toData)". The first circle width become to 10 and it should be 2 (pic.2)
https://imgur.com/a/2PXmCgE 

You can test it on https://line-draw-liff.herokuapp.com/

When I look at the toData() I can't find the record of penwidth?
Is there any method to solve this problem?

**Comment by JoeLeung32** [comment]
Ref:  #421 
If you don't want to fix erase problem, just copy the code had tagged `// Enhance undo`
