### ISSUE TITLE
Mouse pointer goes outside the canvas. In the canvas, it is still drawing.

### ISSUE THREAD

**Issue by midhunadarvin** [szimek/signature_pad#400]
Steps to reproduce : 

- Start drawing on the canvas
- Do not release the mouse. Move it outside the canvas area.
- Release the mouse primary key, and move the mouse to the canvas again.
- Earlier stroke has not been finished. It will show drawing even without the mouse key pressed.

**Comment by sudinem** [comment]
You might have used event.preventDefault() method in the code. Please check.

Its better to show your code on : http://jsfiddle.net/

**Comment by midhunadarvin** [comment]
@sudinem https://jsfiddle.net/szimek/jq9cyzuc/

You can try the steps that i have mentioned above. You can also see it here https://giphy.com/gifs/pVBRMJMqclpWpF1jDt ( please note when the yellow shade is around the pointer the mouse button is clicked. )
