### ISSUE TITLE
signature pad is not fixed position making difficult to sign in ios app 

### ISSUE THREAD

**Issue by saudblaze** [szimek/signature_pad#401]
i have use signature pad many times even in android application it works fine but now i m using it the same way i used in android app but in ios when user start signing on it box it get moved with finger making difficult to sign in ios app

**Comment by helloHupc** [comment]
do you resolve this problem? i hanve the same problem, it just can't drawing when open the canvas from dingTalk or weChat on iPhoneX and iPhoneXR
