### ISSUE TITLE
Attach signature_pad to existing canvas

### ISSUE THREAD

**Issue by Jojoshua** [szimek/signature_pad#402]
I was not able to post this on StackOverflow because the signature-pad tag requires 1500 reputation.

I need to dynamically create/save/load canvas data that was created with signature_pad. How can I attach signature_pad to an existing canvas without having to keep them all in global scope? The following code wipes out the data in the existing canvas. 

    let canvas = document.getElementById("existingCanvas");
    let signaturePad = new SignaturePad(canvas);

**Comment by denisbetsi** [comment]
The above code which you've used as an example should work as is. That's how I have mine setup and it's working like that.

This is from angular 6 app

`this.signaturePad = new SignaturePad(this.canvas);`

That works just fine

**Comment by digaus** [comment]
@Jojoshua 
have you found a solution? for me it also clears the canvas. I can workarround this by pulling data first from canvas and then setting it again. However then I have flickering.
