### ISSUE TITLE
IE error on tablet

### ISSUE THREAD

**Issue by tdclogic** [szimek/signature_pad#407]
_If you have a question, please ask it on [StackOverflow](https://stackoverflow.com/questions/ask?tags=javascript+signature-pad) and use `signature-pad` tag instead of creating an issue._

**Do you want to request a feature or report a bug?**

**What is the current behavior?**

_If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via <https://jsfiddle.net> or similar (template: <https://jsfiddle.net/szimek/h80phxyr/>)._

**What is the expected behavior?**

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**

**Comment by tdclogic** [comment]
I'm using the sample files in the doc folder.  Chrome seems to work fine and it works fine on both IE and Chrome on desktop.
But in IE Tablet I get a yellowed box and no option to sign.  Is there another file I'm missing or setting. I saw a commented out if statement for IE 9.

Thanks,
Dan

**Comment by szimek** [comment]
Can you somehow open JS console to see if there are any JS errors reported?

**Comment by tdclogic** [comment]
It was a compatibility issue.
Thanks

**Comment by szimek** [comment]
I'll close this issue then.
