### ISSUE TITLE
No value on mobile version

### ISSUE THREAD

**Issue by sudinem** [szimek/signature_pad#408]
The signaturepad works fine on desktop version and return value in console. But, in mobile view, it does not returns value.  Please help

**Comment by szimek** [comment]
Could you create a demo on e.g. https://codesandbox.io/ or https://jsfiddle.net/szimek/h80phxyr/?

**Comment by sudinem** [comment]
https://jsfiddle.net/sudinem/L27gxhrp/2/

If you view the console in desktop version, it returns value in console. But, when you move to mobile version it does not return anything on console.

I'm using Chrome browser.

**Comment by szimek** [comment]
I assume it's because you're listening to `mouseup` event, but there's no such event on mobile (touch) devices.

**Comment by sudinem** [comment]
Thanks for the reply. Its working now on mobile version as well. But, the problem is after I sign do the signature it auto scrolls up.
