### ISSUE TITLE
In Windows, only Chrome and Firefox works fine , everyting else browser can not work .

### ISSUE THREAD

**Issue by liumapp** [szimek/signature_pad#409]
The canvas backgroud color is black no matter what style it is . 

![1.pic.jpg](https://github.com/liumapp/imageFolder/blob/master/bug-report/1.pic.jpg?raw=true)

I tried all the version of signature_pad . 

And here is the code : 

````html
     <div id="signature-pad" class="signature-pad">
        <div class="signature-pad--body">
          <canvas style="touch-action: none;"></canvas>
        </div>
      </div>
````

````javascript
    resizeCanvas(canvas) {
      var ratio = Math.max(window.devicePixelRatio || 1, 1);
      canvas.width = canvas.offsetWidth * ratio;
      canvas.height = canvas.offsetHeight * ratio;
      canvas.getContext("2d").scale(ratio, ratio);
      this.signaturePad.clear();
    },
    initCanvas() {
      var wrapper = document.getElementById("signature-pad");
      var canvas = wrapper.querySelector("canvas");
      this.signaturePad = new SignaturePad(canvas, {
        backgroundColor: "rgb(0,0,0,0)"
      });
      window.onresize = this.resizeCanvas(canvas);
      this.resizeCanvas(canvas);
      this.spinShow = false;
    }
  },
````

**Comment by szimek** [comment]
Which browser are you using exactly?

**Comment by liumapp** [comment]
[QQ  Browser](https://browser.qq.com/?adtag=SEM170314007) and [UC Browser](https://www.uc.cn/) , which is sparsely populated in English speaking country.

**Comment by szimek** [comment]
I just tested it in UC Browser (the latest version on Windows 10) and it works fine. Does the demo app (http://szimek.github.io/signature_pad/) work for you in these browsers?

**Comment by liumapp** [comment]
Sorry for wrong code . There is nothing wrong with Signature_pad .
