### ISSUE TITLE
Ionic v4 beta support

### ISSUE THREAD

**Issue by petermeester** [szimek/signature_pad#412]
Hi guys,

I'm spending hours to get this signature pad working on Ionic v4 beta. Also tried on Ionic v3 but I can't get it to work. I've followed several tutorials but none of them works..

Does someone knows how to get this working on Ionic v4 beta or Ionic 3?

**Comment by Genarito** [comment]
I tried but it doesn't work as expected: line draws several centimetres below my finger

**Comment by Genarito** [comment]
Ok, solved thank to [this issue](https://github.com/szimek/signature_pad/issues/400). This is my code:

```
let canvas = document.querySelector("canvas");
this.padDeFirma = new SignaturePad(canvas);
function resizeCanvas() {
	// When zoomed out to less than 100%, for some very strange reason,
	// some browsers report devicePixelRatio as less than 1
	// and only part of the canvas is cleared then.
	var ratio = Math.max(window.devicePixelRatio || 1, 1);
	canvas.width = canvas.offsetWidth * ratio;
	canvas.height = canvas.offsetHeight * ratio;
	canvas.getContext("2d").scale(ratio, ratio);
}

window.onresize = resizeCanvas;
resizeCanvas();
```

Hope it helps

**Comment by petermeester** [comment]
Hi Genarito,

Thanks for your solution! I will try it this week and will let you know and mark this issue as solved. 
How did you include the module in Angular? Thanks!

**Comment by Genarito** [comment]
I installed the library as documentation says:

`npm install --save signature_pad`

And then, imported this way:

`import SignaturePad from 'signature_pad';`

_padDeFirma_ is a instance's variable, I declared this way:


```
export class ModalHistoriaClinica {
    `padDeFirma: SignaturePad;`
    ...
}
```

**Comment by petermeester** [comment]
Many thanks Genarito! I will try this asap.

**Comment by Genarito** [comment]
Oh! Also I have to put the instanciation of SignaturePad inside a timeout because Ionic executes constructor before the view finishes to render, so `document.querySelector("canvas");` returned null

**Comment by TheBrockEllis** [comment]
I'm running into the same issue using Ionic 4 w/ Angular. Inside of `ngOnViewInit` the instance variable is not defined. If I wrap the code in a `setTimeout` for a second, it will work. 

# Works
```typescript
ngAfterViewInit() {
    setTimeout(() => {
      console.log('signature pad', this.signaturePad);
    }, 1000);
  }
```

# Does not work
```typescript
ngAfterViewInit() {
  console.log('signature pad', this.signaturePad);
}
```

Does anyone else have a more elegant solution for waiting for the signature pad to init before trying to access it?

**Comment by daltonpearson** [comment]
On ionic V4 I don't have to use a timeout as long as I initialize the signature in ionViewDidEnter instead of in ngAfterViewInit. I assume that ionViewDidEnter must get called slightly after ngAfterViewInit does. Let me know If this doesn't work for you, I have some other ideas.

**Comment by hichemhlm** [comment]
this.signaturePad property is a ViewChild ? 
If yes you have to add static option to true. If the Element is inside ngIf it ill be visible only after DetectChange event.
```
@ViewChild('signCanvas', { static: false })
signaturePad : ElementRef;
```
