### ISSUE TITLE
Signature not smooth at all

### ISSUE THREAD

**Issue by CodeCurosity** [szimek/signature_pad#415]
How come signature is not smooth at all as compared to https://www.supersignature.com/

**Comment by szimek** [comment]
Feel free to use SuperSignature library ;) 

SuperSignature simplifies drawn lines after user stops drawing, which is something that I wanted to look into as well, but I simply don't have enough free time. I also think it would be better to simplify just the the last part of a line as it's being drawn, not the whole line after it's drawn.
