### ISSUE TITLE
Calling event.preventDefault() on non cancellable events leads to errors.

### ISSUE THREAD

**Issue by denisbetsi** [szimek/signature_pad#418]
**Do you want to request a feature or report a bug?**
Bug Report

**What is the current behavior?**
Attempt to prevent Default on non cancellable Events lead to JS errors

`this._handleTouchMove = function (event) {`

       // Prevent scrolling.
       event.preventDefault();
       var touch = event.targetTouches[0];
       self._strokeMoveUpdate(touch);
`   };`

 ` this._handleTouchEnd = function (event) {`

    var wasCanvasTouched = event.target === self._canvas;

    if (wasCanvasTouched) {
      event.preventDefault();
      self._strokeEnd(event);
    }

`  };`
`

` event.preventDefault();`  should be wrapped in

`if (e.cancelable) {
   e.preventDefault();
}`

**Comment by UziTech** [comment]
According to the [spec](https://dom.spec.whatwg.org/#dom-event-preventdefault):

> There are scenarios where invoking `preventDefault()` has no effect. User agents are encouraged to log the precise cause in a developer console, to aid debugging.

logging is not the same as throwing an error. I think we would want to log the cause if a touch event were not cancelable.
