### ISSUE TITLE
Discontinue writing.

### ISSUE THREAD

**Issue by RizvanWaheed** [szimek/signature_pad#422]
Writing on canvas continuously is great, it also works fine with discontinuous writing using finger touch but when i tried to write on Samsung and other Tablet with stylus in little speed it skips some points.
So problem occurs when writing with stylus.
![pad_problem](https://user-images.githubusercontent.com/6370827/53620644-8089b900-3c15-11e9-85c6-558d6d5cb0f7.jpg)

**Comment by dariobednarski** [comment]
Same issue here! Any solutions yet?

**Comment by UziTech** [comment]
closing as stale
