### ISSUE TITLE
docs/js/app.js onresize missing ()

### ISSUE THREAD

**Issue by fourjs-reuben** [szimek/signature_pad#424]
Line 39 of https://github.com/szimek/signature_pad/blob/master/docs/js/app.js is currently

        window.onresize = resizeCanvas;

Should that be?  

        window.onresize = resizeCanvas();

**Comment by omensa** [comment]
AAAAAPs/IfFolFceFp69zD1OyC1GMy5eQp8FsGUM+xorCrdPAAAAZACtjykAAAAEAAAAAAAAAAEAAAALc2VuZCBsdW1lbnMAAAAAAQAAAAAAAAABAAAAAKdQRr5WLIzQYIVRkzLdb7QumVwsJHkDi4IJnXrWyP1GAAAAAAAAAACYXTwzAAAAAAAAAAErCrdPAAAAQGf3/gOJyZa+SrWXK+kgxu8Lo8Z2zN+S6mj+EOeNrzZC9y83Yb6vILYsVq+HeN7Rx5bqsLVFoh68hbo2NOPeIgI=
