### ISSUE TITLE
DPR 2 causing oversized canvas

### ISSUE THREAD

**Issue by sonicblis** [szimek/signature_pad#428]
**Do you want to request a feature or report a bug?**
Report a bug

**What is the current behavior?**
A DPR of 2 causes the canvas to be larger than expected and create a mismatch of pointer to stroke.

I could not reproduce this on jsfiddle (DPR would never be 2 despite setting it to 2), but I have on codepen.io at https://codepen.io/anon/pen/ywwwPE.  In order to see the issue, in chrome, I turned on mobile emulation, added the DPR drop down to the mobile tools (three dots on the right of the mobile setting headers), changed it to 2.0 DPR, closed mobile view, and then re-opened mobile view.

**What is the expected behavior?**
The signature pad would render appropriately on DPR 2 screens.

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**
signature_pad@2.3.2, chrome Version 73.0.3683.86 (Official Build) (64-bit).  This is the only version I've used.

**Comment by dshastry** [comment]
Dealing with the same issue. Tried using the resize function from the docs but doesn't seem to resolve.

**Comment by sonicblis** [comment]
I ended up modifying the `_toSVG()` function in signature_pad.ts to never ensure ratio never exceeded 1 and it resolved the issue.

**Comment by dshastry** [comment]
Interesting. I used a CSS transform scale to resolve my issue cause I didn't want to muck with the main file. Here's what I ended up using.

`function resizeCanvas(signaturePad, canvas, wdh, hgt)
{
    var ratio =  Math.max(window.devicePixelRatio || 1, 1);
	
	if(ratio>1 && canvas.id==='signatureCanvas'){
		canvas.width = wdh * ratio;
    	canvas.height = hgt * ratio;
    	canvas.getContext("2d").scale(ratio, ratio);
		signaturePad.clear();
	}
	else if(ratio>1 && canvas.id==='initialCanvas'){
		canvas.width = wdh * ratio;
    	canvas.height = hgt * ratio;
    	canvas.getContext("2d").scale(ratio, ratio);
		canvas.style.transform="scale(0.5)";
		
		
		window.signaturePad = signaturePad;
		window.icanvas = canvas;
		
		signaturePad.clear();
		
	}
}
`


Could you perhaps create a Pull request for your change, so it's resolved in future versions of the plugin?

**Comment by Teuthis** [comment]
I was running into this as well, primarily on iPads, but just zooming Firefox to get a DPR of 2 was enough to reproduce it. In my case, the horizontal scaling was fine, but vertical was off any time the DPR != 1. My solution was to change the context scaling in the example resizeCanvas function from
`canvas.getContext("2d").scale(ratio, ratio);`
to
`canvas.getContext("2d").scale(ratio, 1);`
