### ISSUE TITLE
minWidth / maxWidth changes not remembered by undo

### ISSUE THREAD

**Issue by rabbitfufu** [szimek/signature_pad#429]
Thanks for this great library!

I'm using it with an undo feature similar to the example linked on the readme:

```
var data = signaturePad.toData();
  if (data) {
    data.pop(); // remove the last dot or line
    signaturePad.fromData(data);
  }
```

This works great, except, I've noticed that it does not remember changes to minSize and maxSize that are made at runtime.  For instance, if I draw for awhile with these settings...

```
signaturePad.minWidth = 5;
signaturePad.maxWidth = 10;
```

...then draw some more with the these settings...

```
signaturePad.minWidth = 10;
signaturePad.maxWidth = 20;
```

...then click undo, everything on the canvas is redrawn with the latest minWidth / maxWidth settings.  

Thanks!

**Comment by UziTech** [comment]
I can't think of a valid reason to change min/max width in the middle of a signature. closing as stale.
