### ISSUE TITLE
Signature not working on Samsung.

### ISSUE THREAD

**Issue by dedricktucker** [szimek/signature_pad#43]
Signature pad is not working on Samsung device if the user needs to scroll.  Everything appears to work correctly if the signature pad is at the very top of the page.  If i need to scroll down the page to use the pad the drawing in not accurate.  Works on chrome but not stock browser.

**Comment by upendra15** [comment]
Samsung phone's native browser fires Mouse events along with touch events. I faced same bug and was shocked after I removed mouse handling code, everything worked well.

**Comment by ryosaebasg1** [comment]
I have the same issue on OnePlus 6T, Xiaomi Mi 5, Samsung galaxy A5 2018, Huawei P20 with Chrome only.
That work on all other browser like FireFox,...

**Comment by szimek** [comment]
@ryosaebasg1 Can you debug it somehow and check what happens there exactly? Also, which version of the library are you using?

**Comment by ryosaebasg1** [comment]
If i scroll to bottom, when i try to sign, i have only some dot and the move not write, it scroll. If i stell on bottom and i refresh using the arrow turning in menu, that's work.

I have try to add signature on top of page and i have the same issue if need to scroll before it don't work, if i refresh at the rigth place it work.

I use this : https://cdn.jsdelivr.net/npm/signature_pad@2.3.2/dist/signature_pad.min.js

**Comment by szimek** [comment]
Could you try out this version: https://cdn.jsdelivr.net/npm/signature_pad@3.0.0-beta.3/dist/signature_pad.min.js? It supports pointer events, so maybe it will work.

**Comment by ryosaebasg1** [comment]
I still have the same issue

**Comment by ryosaebasg1** [comment]
I have create codepen : 

https://codepen.io/anon/pen/eoMBPa

Use it on android chrome to see the issue and remove the div with heigth 5000px to see that's work

**Comment by szimek** [comment]
@ryosaebasg1 Thanks! I can replicate this issue, but I have no idea when I'll have time to look into it.

**Comment by ryosaebasg1** [comment]
I have search and the only way to use it is to create the div with a button ;-)
Hope you find a direct way or Chrome accept it.
