### ISSUE TITLE
PHP example has a little error?

### ISSUE THREAD

**Issue by SergeGirardChamoison** [szimek/signature_pad#432]
$encoded_image = explode(",", $data_uri) [1]; 

I can't get this working!

I want to put a signature in my database like this:
`
(button onclick="Save_in_DB()")Save(/button)

<jscript>

function Save_in_DB() {
var dataUrl = signaturePad.toDataURL("image/png"); 
dataUrl = dataUrl.trim(); 
window.location.href = "indext.php?si=" + dataUrl; 
} 
</jscript> 
`
Then I do this:

`if (isset($_GET["si"]) AND (!empty($_GET["si"])) ) :   
 
   $data_uri = $_GET["si"] ;  
   $encoded_image = explode(",", $data_uri)[1];
   $encoded_image = $encoded_image ;
   $decoded_image = base64_decode($encoded_image);
   // $decoded_image to db 
endif;
`

What is wrong?
Thx for this wonderful tool !
Serge

**Comment by SergeGirardChamoison** [comment]
If you want to save data that is derived from a Javascript canvas.toDataURL() function, you have to convert blanks into plusses. If you do not do that, the decoded data is corrupted:
`
<?php
  $encodedData = str_replace(' ','+',$encodedData);
  $decocedData = base64_decode($encodedData);
?>
`

**Comment by SergeGirardChamoison** [comment]
How to avoid : Request-URI Too Large ?
Serge

**Comment by h4de5** [comment]
see #234
