### ISSUE TITLE
How to operate with 100% width?

### ISSUE THREAD

**Issue by hostcia** [szimek/signature_pad#437]
How to operate with 100% width?

**Comment by freezed** [comment]
Please be more explicit…

**Comment by tiagocaus** [comment]
> Please be more explicit…

I had made the canvas thinking of the handheld, the width had been perfect.

But they decided to use a tablet, so the width got smaller.

See the image:


How to make the signature screen responsive (Width 100%) to any screen size.


Thank you.

**Comment by freezed** [comment]
(I cannot see your image)
Did the [demo code](http://szimek.github.io/signature_pad/)_ work on your tablet ?

**Comment by xiaoxiaofan123** [comment]
Have the same issue.
I set the canvas width 100% height 100% in the mobile screen
Then the canvas don't work correct

**Comment by freezed** [comment]
Talk is cheap. Show us the code.

**Comment by cncolder** [comment]
I use `div` wrap `canvas`. Then use `ResizeObserver` listen `div` size change. pass to `canvas`.

It's complex but worked. To save time. I use `useMeasure` of `react-use`. See below:

```jsx
import React from 'react'
import { useMeasure } from 'react-use'

export default () => {
	const [containerRef, { width, height }] = useMeasure();

	return (
		<div ref={containerRef}>
			<canvas width={width} height={height} />
		</div>
	)
}
```
