### ISSUE TITLE
getPaths for scalable Vectorgraphic

### ISSUE THREAD

**Issue by BurnedToast** [szimek/signature_pad#44]
Would it be possible to support a "getPaths" method that returns a Array of X and Y Koordinates for each Stoke done on the SignaturePad?

This would be really helpful to minimize the Data that is transfered to the Server and it would open the possibility to scale the Signature on the Server without loosing too much quality.

I know that its not possible to generate such a smooth Signature as you do on client side with that method.

**Comment by szimek** [comment]
Version 2.0.0 supports SVG output.
