### ISSUE TITLE
Add TypeIt

### ISSUE THREAD

**Issue by dortega88** [szimek/signature_pad#442]
Feature Request:
Add a TypeIt function; ie, it takes in a string, full name, and lays it on the signature line, for accessibility and for people who don't want to draw with the mouse.

References Issue #82 Type to sign support

This would increase accessibility for people who may not be able to use the mouse effectively, giving people another way to sign.

**Comment by dortega88** [comment]
#82 Type to sign support

This would increase accessibility for people who may not be able to use the mouse effectively, giving people another way to sign.

**Comment by UziTech** [comment]
This library calculates the bezier curve for a signature using pointer events. If you need something other than that you will have to use a different library to complete the additional functionality. This is not trying to be a one stop shop for signatures, just a small part of it.

**Comment by dominique-mueller** [comment]
I understand, totally makes sense - thanks for the quick reply!
