### ISSUE TITLE
Saving as JPEG

### ISSUE THREAD

**Issue by rogerfar** [szimek/signature_pad#45]
I am trying to save the signature as a JPEG so that it can be used in JsPDF (which only accepts PNG).

When I do:

```
var img = signaturePad.toDataURL("image/jpeg", 100);
```

It does not get to the

```
SignaturePad.prototype.toDataURL
```

function but instead saves the object as JPG (resulting in a black img).

Is there a different way to save as JPG?

**Comment by Iezenyimulu** [comment]
@szimek, I still get a black box after setting the background color as you said. PNG works but not JPEG.
What might be the issue pls?

**Comment by triplethreat77** [comment]
@Iezenyimulu same

**Comment by szimek** [comment]
@Iezenyimulu @triplethreat77 Could you prepare a demo e.g. on codesandbox or sth similar to show this issue? I think that setting the background color correctly should work, but there might be some bug I'm not aware of.

**Comment by its4manasi** [comment]
Issue is creating due to using the backgroundColor: 'rgb(255,255,255)' or backgroundColor: 'rgba(255,255,255,0)'
Instead of above please use this: backgroundColor: '#ffffff' will work.

**Comment by Iezenyimulu** [comment]
Ok thanks.

**Comment by Rod911** [comment]
I was using 
```
const ratio = Math.max(window.devicePixelRatio || 1, 1);
const canvas = document.querySelector("canvas");
const ctx = canvas.getContext("2d");
canvas.width = canvas.offsetWidth * ratio;
canvas.height = canvas.offsetHeight * ratio;
ctx.scale(ratio, ratio);
```
to scale the canvas for high dpi screens, had to put it before the signaturepad init to get the white background working, otherwise jpeg would just give a black image
