### ISSUE TITLE
Problem with multitouch on big screens

### ISSUE THREAD

**Issue by Hanzofm** [szimek/signature_pad#454]
**Do you want to request a feature or report a bug?**
Bug?

**What is the current behavior?**
When a user put his hand on the tablet to sign, the the canvas stops to recognize movemets and not write anything.

Only if the object that holds on screen is big the problem appears. If puts a finger and tries to write it works.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via <https://jsfiddle.net> or similar (template:**

With your live demo
http://szimek.github.io/signature_pad/

**What is the expected behavior?**
On big devices is common to hold the hand on screen while writting. I am not sure that it would be fixed but its a very common problem

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**

With your live demo
http://szimek.github.io/signature_pad/

3.0.0-beta-3?

Related:

https://github.com/szimek/signature_pad/issues/48

Video with the problem:

https://drive.google.com/open?id=1HymdaNwNlGEyezcEmckM0nlupT29z7Ah

**Comment by UziTech** [comment]
this seems to be working as expected it should not draw when multiple fingers are touching
