### ISSUE TITLE
Feature request - Percentage of coverage

### ISSUE THREAD

**Issue by mlemmers** [szimek/signature_pad#457]
Within our current implementation we are experiencing problems where people will just input one or two dots and submit the form it is attached to.

As of now you can only check wether the canvas is filled or not. It would be great if it were possible to see a percentage or define a threshold for it to be considered "filled".

**Comment by jbeyer05** [comment]
@UziTech can you clarify what functionality covers what @mlemmers asked about?  I don't see anything in the GitHub README.

I see isEmpty( ), but I think @mlemmers was asking about a different situation (i.e. how do you detect that someone hasn't just entered a dot or two in the pad).

**Comment by UziTech** [comment]
This is a feature that should be created outside of signature_pad.

One way I can think of to do this is to check the color of each pixel on the canvas and do the calculation. Another way could be to use `signaturePad.toData()` and count the points.

**Comment by jbeyer05** [comment]
Thanks @UziTech .  Yes, I ended up counting the number of points.  For anyone stumbling across this issue looking for a solution, something like the follow should work, where you intercept the form submission, and block the form submission if the signature is empty or has less than X points:


```
    $( 'form.edit_access_consent_letter' ).submit( function( ) {
      var numPoints = 0;

      signaturePad.toData( ).forEach(( element, index, array ) => {
        numPoints += element.points.length;
      });

      console.log( "Total Points: " + numPoints );

      if( signaturePad.isEmpty( )) {
        alert( 'Your signature appears to be empty, please sign the signature pad with your mouse.' );
        return false;
      } else if( numPoints < 50 ) {
        alert( 'Your signature appears to be very small, please make your signature larger.' );
        return false;
      }

      var imageData = signaturePad.toDataURL();
      $( 'input#access_consent_letter_signature_png' ).val( imageData );

      return true;
    });
```
