### ISSUE TITLE
All black image/broken image.

### ISSUE THREAD

**Issue by fsnightmckngbrd** [szimek/signature_pad#462]
File saved is always broken. I've used this plugin on other websites and I managed to work it out. I don't know what's the problem now. I'm previewing the signatures on an img by the data url of signaturePad before saving to the database and a file.

Here is the summarized codes.

javascript:
```
$('.field').find('img').attr('src', signature_pad.toDataUrl());
var post = $('.field').find('img').attr('src').replace(/^data:image\/(png|jpg);base64,/, "");
```

php:
```
$post = base64_decode($_POST);
$signature = base64_decode($value->val);
$file = fopen($file_path.$file_name, 'w');
fwrite($file, $signature);
fclose($file);
```

I'm getting the posted data, file is saved, no errors encountered but the filesize is so small and after opening it I found out that the image is broken.

**Comment by fsnightmckngbrd** [comment]
Problem solved. Incorrect assignment of variables.

**Comment by cmichaelis** [comment]
Just as a note for others that search for this issue -- I was getting all black images too, with....
signaturePad.toDataURL("image/jpeg")

Change that to image/jpg, and it works great.

**Comment by asivaneswaran** [comment]
I am having the same issue and changing to 'image/jpg' doesn't work.
