### ISSUE TITLE
can't drawing on iPhoneX and iPhoneXR

### ISSUE THREAD

**Issue by helloHupc** [szimek/signature_pad#464]
it can't drawing when my link open from dingTalk or weChat on iPhoneX and iPhoneXR ,but is ok on safari browser. The canvas just like added disabled when open the link from dingTalk and weChat.
it worked on other iPhone mobile and all android mobile.
can you help me resolve the problem~

**Comment by helloHupc** [comment]
this is my version:
https://cdn.jsdelivr.net/npm/signature_pad@2.3.2/dist/signature_pad.min.js

**Comment by ShingLi** [comment]
> it can't drawing when my link open from dingTalk or weChat on iPhoneX and iPhoneXR ,but is ok on safari browser. The canvas just like added disabled when open the link from dingTalk and weChat.
> it worked on other iPhone mobile and all android mobile.
> can you help me resolve the problem~

Hello, have you solved it？
