### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by Sparticuz** [szimek/signature_pad#465]
Is this project maintained? If not, are there any good alternatives?

**Comment by szimek** [comment]
I don't really have time to maintain it anymore, but I hope to merge a few PRs, update a few dependencies (e.g. TypeScript) and release final 3.0 till mid of January.

**Comment by abraxxa** [comment]
Seems the mid January release didn' t work out.
Is there anything we can do to help?
My main issue is the incorrect save/load on HiDPI screens.

**Comment by szimek** [comment]
@abraxxa Could you please aggregate all issues and PRs regarding your issue here? It would be great if it was also described how to replicate it. This way there's much higher chance that I'll find time to work on it...

**Comment by abraxxa** [comment]
The issue is described in #453, the pull-request which should fix it is in #411.

**Comment by szimek** [comment]
@abraxxa Thanks! I'll read a bit about SVG sizing again, because I don't remember how it all works and there's a bunch of places where height and width are set, e.g.
```js
const minX = 0;
const minY = 0;
const maxX = this.canvas.width / ratio;
const maxY = this.canvas.height / ratio;
...
svg.setAttribute('width', this.canvas.width.toString());
svg.setAttribute('height', this.canvas.height.toString());
...
const header =
  '<svg' +
  ...
  ` viewBox="${minX} ${minY} ${maxX} ${maxY}"` +
  ` width="${maxX}"` +
  ` height="${maxY}"` +
  '>';
```

**Comment by abraxxa** [comment]
Thanks!

**Comment by szimek** [comment]
@abraxxa @gimyboya I moved the discussion about the SVG issue to #453.
