### ISSUE TITLE
Width/height initializes from attributes only (not from real width/height in some cases).

### ISSUE THREAD

**Issue by moshenskyDV** [szimek/signature_pad#468]
**Do you want to request a feature or report a bug?**

This issue is possible bug.

**What is the current behavior?**

`<canvas width="400" height="400"></canvas>` -  works well, canvas fit as expected.
`<canvas style="width:400px;height:200px"></canvas>` - incorrect behavior (it think, that canvas has 300x150 px size).

**What is the expected behavior?**

Signature pad should respect canvas size, given by CSS. Probably somewhere in code (on init) used `.width` and `.height` attributes instead of `.offsetWidth` and `.offsetHeight` properties.

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**

Looks like it affects all browsers/OS.

PS: I'll try to investigate and make PR in next couple of days.

**Comment by moshenskyDV** [comment]
#446 
Looks like PR already created. I'll close this issue.

**Comment by emilfihlman** [comment]
This is a total misunderstanding what the width/height parameters and style width/height parameters mean.

They are absolutely not the same thing.
