### ISSUE TITLE
signatire pad not working. after i sign the pad its clearing the pad and replaing it with a blank image

### ISSUE THREAD

**Issue by aizeek1** [szimek/signature_pad#472]
_If you have a question, please ask it on [StackOverflow](https://stackoverflow.com/questions/ask?tags=javascript+signature-pad) and use `signature-pad` tag instead of creating an issue._

**Do you want to request a feature or report a bug?**

**What is the current behavior?**

_If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via <https://jsfiddle.net> or similar (template: <https://jsfiddle.net/szimek/h80phxyr/>)._

**What is the expected behavior?**

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**

**Comment by osharim** [comment]
Not sure if you solve it, but for future people, please try to not include the `resizeCanvas` snippet that this author suggest to handle high DPI screens.

And please, if you are re-drawing using `fromDataURL` function, don't forget to add the ratio property. 

`.fromDataURL(url, {ratio: 1})`

**Comment by aizeek1** [comment]
So then I shouldn’t call that function at all or have the window.resize line of code
