### ISSUE TITLE
save as svg when rotate has bug

### ISSUE THREAD

**Issue by mipawn** [szimek/signature_pad#478]
When I was rotating the horizontal screen on the mobile end, I found that there was a problem saving as SVG. Using the API todataurl ('image / SVG + XML ') in the library, it is found that the lower part of the image is not saved, and the direction is wrong. It is correct to use canvas's native API todataurl ('image / SVG + XML '). Presumably you are not compatible with rotation at save time. Please pay attention.

**Comment by cyberdarius** [comment]
I confirm this bug saving in SVG from mobile view horizontal.

**Comment by UziTech** [comment]
cloasing as stale
