### ISSUE TITLE
Save image and signature as one

### ISSUE THREAD

**Issue by ammdsoftdev** [szimek/signature_pad#483]
I am currently using this [SignaturePad](https://jsfiddle.net/szimek/d6a78gwq/). My goal is to have an image of file/document to be signed. What I want is to save the image and the signature as one image file.

**What is the current behavior?**
When I click save, I only get the signature alone.

**What is the expected behavior?**

When I click save, It should save the image and the signature as one jpeg or png.

**Comment by hughanderson4** [comment]
My Fiddle linked in #511 could solve this
https://jsfiddle.net/HugeHugh/mhp5rxqk/

**Comment by Jucesr** [comment]
It is not from this library but I made my own react component. In case someone needs it.

https://codesandbox.io/s/canva-with-background-image-uf652c
