### ISSUE TITLE
How to integrate in angular 9 ?

### ISSUE THREAD

**Issue by samuelrajsams** [szimek/signature_pad#484]
_If you have a question, please ask it on [StackOverflow](https://stackoverflow.com/questions/ask?tags=javascript+signature-pad) and use `signature-pad` tag instead of creating an issue._

**Do you want to request a feature or report a bug?**

**What is the current behavior?**

_If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via <https://jsfiddle.net> or similar (template: <https://jsfiddle.net/szimek/h80phxyr/>)._

**What is the expected behavior?**

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**

**Comment by hughanderson4** [comment]
I discovered such repo who already implemented that.
https://github.com/ramsatt/Angular9SignaturePad
Shout out to @ramsatt thanks for sharing it 🍺 

I used [auto adapter](https://medium.com/stackblitz-blog/stackblitz-online-vs-code-ide-for-angular-react-7d09348497f4) to make it into a Stackblitz:
https://stackblitz.com/github/ramsatt/Angular9SignaturePad

Here I provide relevant details to the community in step-by-step:

1. npm i as stated in [readme](https://github.com/szimek/signature_pad)
```bash
npm install --save signature_pad
```

2. import it in your angular component.  it is not necessary to do module import in angular module.
```javascript
import SignaturePad from 'signature_pad';
```

3. create canvas in your html and use a template variable to reference it, here i use `#sPad`
```xml
<canvas #sPad></canvas>
<button (click)="setSignature()">JH</button>
```

4. make angular `@ViewChild` reference in your component to grab the canvas dom element needed by SignaturePad
```javascript
@ViewChild('sPad', { static: true }) canvasElement;
```

5. create a component var to store SignaturePad reference.  then, implement `afterViewInit()` of angular, to wait for canvas to appear in DOM, and set this reference.  Inject `nativeElement` of your canvas viewchild to Signaturepad ctor.
```javascript
signaturePad: any;
ngAfterViewInit() {
        this.signaturePad = new SignaturePad(this.canvasElement.nativeElement);
    }
```

6. now you can use SignaturePad in your angular component anywhere you want
```javascript
setSignature() {
    this.signaturePad.fromDataURL('https://ourlostfounding.com/wp-content/uploads/2017/01/John-Hancock-signature-1024x287.png');
}
```
