### ISSUE TITLE
DataURL creates empty pngs

### ISSUE THREAD

**Issue by skizznited** [szimek/signature_pad#486]
I have a document, and the user has to put his signature in 4 signature fields. On submit, I am going to get the DataURL of all Signature Pads and send it to my server to create an image and store it on my server. Then I am going to remove the Signature Pads and replace it with the stored image.

The wrappers are the divs with the Signature Pads.

```
$("#wrapper1").remove();
$("#wrapper2").remove();
$("#wrapper3").remove();
$("#wrapper4").remove();
var sig1 = signaturePad1.toDataURL();
var sig2 = signaturePad2.toDataURL();
var sig3 = signaturePad3.toDataURL();
var sig4 = signaturePad4.toDataURL();
$.post( "convert.php", { datauri1: sig1, datauri2: sig2, datauri3: sig3, datauri4: sig4 })
.done(function( data ) {
  $("#sigpad1").attr("src", data.ret1);
  $("#sigpad2").attr("src", data.ret2);
  $("#sigpad3").attr("src", data.ret3);
  $("#sigpad4").attr("src", data.ret4);
});
```

My backend looks like this:

```
header('Content-Type: text/javascript');
header('content-type: application/json; charset=utf-8');
$data_uri1 = $_POST["datauri1"];
$data_uri2 = $_POST["datauri2"];
$data_uri3 = $_POST["datauri3"];
$data_uri4 = $_POST["datauri4"];

$encoded_image = explode(",", $data_uri1)[1];
$decoded_image = base64_decode($encoded_image);
$filename = uniqid (rand (),true);
file_put_contents("sigs/".$filename.".png", $decoded_image);
$ret1 = "sigs/".$filename.".png";

$encoded_image = explode(",", $data_uri2)[1];
$decoded_image = base64_decode($encoded_image);
$filename = uniqid (rand (),true);
file_put_contents("sigs/".$filename.".png", $decoded_image);
$ret2 = "sigs/".$filename.".png";

$encoded_image = explode(",", $data_uri3)[1];
$decoded_image = base64_decode($encoded_image);
$filename = uniqid (rand (),true);
file_put_contents("sigs/".$filename.".png", $decoded_image);
$ret3 = "sigs/".$filename.".png";

$encoded_image = explode(",", $data_uri4)[1];
$decoded_image = base64_decode($encoded_image);
$filename = uniqid (rand (),true);
file_put_contents("sigs/".$filename.".png", $decoded_image);
$ret4 = "sigs/".$filename.".png";

echo json_encode(Array("ret1" => $ret1, "ret2" => $ret2, "ret3" => $ret3, "ret4" => $ret4));
```

When this is done I am getting the html of the document and generate a PDF.

What happens:

Sometimes, on some deviced e.g. Android & Chrome only the first signature is stored correctly on the server. The other three signatures are blank and their file size is much lower than the correct one.

Sometimes it creates signature 1, 3 and 4, but signature 2 is empty.

Also sometimes the stored signatures are much bigger than the actual signature drawn on the signature pad.

Any idea what I am doing wrong here?

Thank you

**Comment by asivaneswaran** [comment]
I am having the same issue. The base64 code send to the backend is empty. It's not generating any image on tools like: https://base64.guru/converter/decode/image

**Comment by skizznited** [comment]
Sehr geehrte Damen und Herren, 

vielen Dank für Ihre Nachricht an Herrn Florian Sauerwein. 
Herr Florian Sauerwein ist seit 01.02.2021 nicht mehr in unserem Unternehmen beschäftigt. 
Wenden Sie sich bitte ab sofort für Anfragen zu jeder Zeit an den Customer Service unter ***@***.*** oder bei technischen Fragen an ***@***.***

Mit freundlichen Grüßen
Ihr Pronummus Team
