### ISSUE TITLE
How to get instance of already created signpad?

### ISSUE THREAD

**Issue by tejashapani** [szimek/signature_pad#487]
Hello,

I would like to get instance of already created signpad.

For example, i have 2 sign pad on a page, one for buyer and one for seller.
When buyer sign, i would like to disable sign pad for seller and vice-versa.

Here is JS fiddle: https://jsfiddle.net/nw7b1zj5/
If i use static js code to disable signpad, it works but in my case, i am generating this as a shortcode in Wordpress.
All signpad variable is dynamic and unique.

This is where i need to get instances from all signpad.

Is there anything i can get it?

**Comment by CatalinRadoi** [comment]
I have the same issue. I have a canvas already with a signature_pad attached and I want to update it's image.

**Comment by CatalinRadoi** [comment]
Ok I did it by using dynamic variables



e.g. window["signaturePad1"] = new SignaturePad..... 
and then I would directly use window["signaturePad1"] 

"1" is actually unknown to me, it is generated on runtime etc
