### ISSUE TITLE
Vertical writing/drawing not working in web view

### ISSUE THREAD

**Issue by faransajid** [szimek/signature_pad#488]
I am able to draw lines or write horizontally but they don't seem to be working vertically.

Everything works fine in Desktop and Mobile Google chrome browser and signatures work perfect but when I use the same link inside web-view, only dots appear when I try to write vertically.

![image](https://user-images.githubusercontent.com/24614101/86986513-4fc47700-c1ad-11ea-8281-d696a0ea455d.png)

**Comment by thedoglett** [comment]
@faransajid - I've just come across the same problem.

Did you manage to solve it? If so, what did you do?

Cheers!

**Comment by UziTech** [comment]
closing as stale
