### ISSUE TITLE
Does anyone get empty signatures stored as `data:,`

### ISSUE THREAD

**Issue by 949mac** [szimek/signature_pad#490]
About 2% of my collected signatures are stored as `data:,`; they are effectively empty.

I'm almost certain this is device related or browser specific? Has anyone seen this?

![image](https://user-images.githubusercontent.com/23151962/87081399-28d26900-c1de-11ea-97be-922b825c5fe6.png)

I'm using the latest version.

**Comment by davissp14** [comment]
Yes, I am seeing the same issue.  I have not been able to track down exactly how this happens.

**Comment by supairish** [comment]
@davissp14 what kind of validation did you use?  Using the inbuilt isEmpty can be simply bypassed via just clicking on the canvas and not actually drawing a signature.

**Comment by davissp14** [comment]
>  what kind of validation did you use? Using the inbuilt isEmpty can be simply bypassed via just clicking on the canvas and not actually drawing a signature.

This issue has to do with valid signatures occasionally/randomly getting zeroed without any reporting from this or dependent libraries.  The issue of verifying a valid signature vs. a single dot is an interesting problem, but they are not related.  That being said, this probably isn't the best place to discuss it.
