### ISSUE TITLE
Chrome antialiasing problem

### ISSUE THREAD

**Issue by MartinHotmann** [szimek/signature_pad#505]
I use the latest **v3.0.0-beta.3** version. Installed it and on Chrome I discovered a weird behaviour.

When I draw something it is pixxled. Sometimes it is antialiasing itself by default but sometimes its not.
On Chrome its very fluctuating. Sometimes it works sometimes not.

But when I draw one more thing and press the "undo" button it will re-antialiase the rest of the canvas.
Is there a way to manually trigger the antialiasing function?

For me this library works much better on mobile devices then on desctop. On desctop everything is very much pixxled and on mobile its really smooth!

I really like the application, I hope it was not discontinued and will get some updates.

**Comment by MartinH0** [comment]
Just realised, that pressing "CTRL + A" after a click outside the canvas triggers immediate re-render/antialiasing. Will provide a Video for this.

**Comment by MartinH0** [comment]
Ok no need for the video anymore.
Got the solution.

In Chrome go to **`chrome://flags/`** and deactivate **`Accelerated 2D canvas`**. Now relaunch Chrome and have fun with good antialiased canvas.. there should be an option to deactivate this for canvas from the DOM or the application should choose.. this is so bad.

This should fix #386
