### ISSUE TITLE
how can i add image for background?

### ISSUE THREAD

**Issue by david-akb** [szimek/signature_pad#509]
hi
i want to make psychology app that i need to add image to drawing or acting with visual ability, so plz help me where can i put image background of the signature?

**Comment by vik17ag** [comment]
Programmatically -
`this. signaturePad.fromDataURL(img)`

where `img ` is the the blob or the local file in your project. 
I am not sure if it can be a url also. Hope this helps

**Comment by hughanderson4** [comment]
@david-akb I worked on it awhile.
Default Grumpy Cat demo might suit your needs, but in our case we need background as part of sig.
So far the only way I found to do it makes me access a couple of SignaturePad's private methods.
I have a writeup for it on #511 
There's a Fiddle there who does what you need.

**Comment by jaredgibb** [comment]
just to add my two cents. I have been working on this today. 

I added the date and a line for the user to sign on. these become part of the signature image. I am having issues when the component resizes. it messes up the image only when clearing the canvas after a rezise

this is before resize
  var background = new Image();
  background.id = 'background_image'
  background.src = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAV4AAABkCAYAAADOvVhlAAAK20lEQVR4Xu3da6g1VR3H8a9PSVlaklBSD2GRXehK0guTwBLSblCoiGAKgb3QSiQwEStNBBOJUimQRDEJwcwEDUUqIcwXkgRFkoYJGlgvwtIw0TR+MBumYZ3j7L3XzJy95/t/c+TsPevy2dv/mWfNuhyAoYACCigwqsABo9ZmZQoooIACmHj9EiiggAIjC5h4Rwa3OgUUUMDE63dAAQUUGFnAxDsyuNUpoIACJl6/AwoooMDIAibekcGtTgEFFDDx+h1QQAEFRhYw8Y4MbnUKKKCAidfvgAIKKDCygIl3ZHCrU0ABBUy8fgcUUECBkQVMvCODW50CCihg4vU7oIACCowsYOIdGdzqFFBAAROv3wEFFFBgZAET78jgVqeAAgpsSuJ9LfBPPy4FFFBgGwRWSbyHAE+N3PlrgI8AXwJ+MXLdVqeAAgpUFVgm8X4K+C5wN3BW1VbsXtjbgQeBfc3b7gS+Ajw8YhusSgEFFKgm0CfxvhXIHedxTa0vAh8CflutFbsXdDuQpN+OfwFvAP4zUhusRgEFFKgm0CfxPgbs79T4e+B91Vqxc0EfBX5ZePki4OIR6rcKBRRQoLpAn8R7KvDjQs1fBb5TvUX/X2AS/Hs6dfwdyF34vweu2+IVUECBQQT6JN5U/Cvg2E4LngEy/vr4IC2DzwM3FMo+E/jhQHVarAIKKDC4QN/E+5bmAdcrOi26CzhhgFa+Evgz8KZO2Q8B7wJeGKBOi1RAAQVGEeibeNOYC4FLCq36LHBb5dZ+DbisUGYesv28cl0Wp4ACCowqsEzifTnwB+AdnRZmqCFDDhl6qBGvA/4CvKZTWIY7PlajAstQQAEFphRYJvGmnUcDvyk0OA/Z8rCtRlwJfLlQ0HubxF+jDstQQAEFJhNYNvGmodcDZ3Ra/F/gAxUS4xHN2O7LOuX/CDh9MiUrVkABBSoKrJJ4D2uS46GddmRBRRZWZIHFqvET4MTOxVkk8Tbgr6sW6nUKKKDAXhJYJfGm/V8Ari105Gzg+yt28MPAvYVrvw2cv2KZXqaAAgrsOYFVE286krHejPm242ngSOCJFXqaO+YPdq77B5CpbFkibCiggAJbIbBO4s3shsxyyGyHdtwEZLXbMnEScHPhgmyGc9UyBfleBRRQYK8LrJN407dLgQsKncweC/f07PyBQBZG5MFaOx5txnbz4M5QQAEFtkZg3cSblWzZsjHDAe3IPNysMHu2h1Tuar9XeF/ugm/pcb1vUUABBTZKYN3Em85mD4csbuhG7oaz2m23yCKJJOksmmhHxo+P2ShJG6uAAgr0FKiReFNVxnVP6dT5fLOz2J92aUtmLJxXeP0o4IGeffBtCiigwEYJ1Eq8hzcnQhzc6f19QKaJlSIb4GQjnGyI047M5T15oxRtrAIKKLCEQK3Emyozh/fqQt2Z83td4fdZjXZa5/fPNfs+5MGaoYACCmylQM3Em7LuBzJM0I4nm4dv+bmIbG6eTc67kX0aztlKaTulgAIKNAI1E2+KTEL9HdDdayF3vLnzXUSO88mUs3ZkkURmR2TRhKGAAgpsrUDtxBuo7FR2bkEsY70Z882eujnAshvZg/fyrZW2YwoooMBAd7wp9iDgESAP3NqR2Q2LrR2zf287sgFONsLx1GC/mgoosPUCQ9zxBi2nUtxa0PtZ81r3pZyvduPWa9tBBRRQABgq8Qb3TuD4HsrZ7yF3woYCCigwC4EhE+/+Zg+GDD3sFjnOp7TybRYfgJ1UQIH5CQyZeKOZ44Cu2IX1DuDT82O3xwooMGeBoRNvppVlelmmmXUjR7RnI53sTGYooIACsxEYOvEG8nPATwuifwTePRtpO6qAAgo0AmMk3gwnfLIgnrPZckZbTp4wFFBAgdkIDJ14szotq9R2isxoyOnEbnY+m6+cHVVAgaETb/ZjKI3vtuXzAC6r3QwFFFBgFgJDJt4sirihh+IzzY5kj/d4r29RQAEFNl5gqMSbPXaz12723G1HTpt4I5Ajg9pxF3DCxmvaAQUUUKCHwFCJNxveXFaoPxvk5Aj3SwqvZZnxbT3a7FsUUECBjRYYIvHm/LTc2eY8tXZkdVpWqeU4+DxUy/Hw7chQQzbPydCDoYACCmytwBCJNycG5+Tgbix2JsvvjwZyoGU38pAtD9sMBRRQYGsFaifeI5qx3e5G6Dnm5/SO4vXAGZ3fZVpZppfljthQQAEFtlKgduLNQZUndqSyx2722s2eu+04rEnSh3Z+nwUVWViRBRaGAgoosHUCNRNvTpi4tyCUI9zP30EuxwFdW3jtLOAHW6dthxRQQIHK+/HmTjUzFtqR89NyjlrOU9spMtabMd92PA0cCTzhp6SAAgpsm0CtO96TgJsLOHnIdtVLoGV2Q8Z0M9uhHTcBp24buP1RQAEFaiTeA5utHfNgrR2PNmO7ffZhuBS4oPBxZK+He/yYFFBAgW0SqJF4c1ebKWTdyF3wLT2xspLtwWZYon1J5gNnz95ne5bj2xRQQIE9L7Bu4s0iiSTHLJpoR8Ztj1my98fucARQ7oYvXLIs366AAgrsWYF1E29mLJxX6N1RwAMr9Drjuqd0rnu+2eEsx8MbCiigwMYLrJN4swFONsLJhjjtyFzek1eUORx4GDi4c/19QKarGQoooMDGC6yTeLMa7bSOwHPNfgt5sLZqnA1cXbg4c36vW7VQr1NAAQX2isCqiTebm2eT825cCZyzZufSpvuBDFe048nm4Vt+GgoooMDGCqyaeHOcT6Z6tSOLJLJYIosm1o0k9pxO3N3zIXe8ufM1FFBAgY0VWCXxZk/d2ws9zh68l1eUyE5l5xbKy1hvxnwNBRRQYCMFlk28+5r5ttk3tx3ZACcb4WRDnFpxEPAIkAdu7cjshtwRZ7aDoYACCmycwLKJ90zgmkIvc77ajQP0PqdS3FooN/N6M7/XUEABBTZOYJnE++rmDvT1nV5mn4Vscj5U3Akc3yk8K9myoi2LNwwFFFBgowSWSbwXAd8s9C7H+eRYn6Fif7MXRIYe2pE9HLoP+IZqg+UqoIAC1QT6Jt5XAX8rLGzIQ7bPVGvNzgXlOKArCi9n97KsdjMUUECBjRHom3jToXc2CxuOa3r3QvPP/YdG6m2ml72/U9djwJtHqt9qFFBAgSoCyyTeRYWfADLV69fAF6u0ol8hWVCRhRWLNt/RHKqZmQ+GAgoosDECqyTeRedyVtrYq8hyHNDHgSwrzkM3QwEFFNg4gXUS7xSdPQR4aoqKrVMBBRSoJbBpibdWvy1HAQUUmEzAxDsZvRUroMBcBUy8c/3k7bcCCkwmYOKdjN6KFVBgrgIm3rl+8vZbAQUmEzDxTkZvxQooMFcBE+9cP3n7rYACkwmYeCejt2IFFJirgIl3rp+8/VZAgckETLyT0VuxAgrMVcDEO9dP3n4roMBkAibeyeitWAEF5iqwSLw5wyxHqWeP3Rd3+bnba0Neuyh7nfqnLGOu3y/7rYACBYFF4v068C2FBhMo/cFY54/IOtdO+Qeo3e5t6EMNy73sMNj/EHMveJF4c5ZazlQzFFBAgYXAS/0rtvv61H9Epq6/9x/iReLd6SBLv4IKKKCAAnUFLlkk3gwzZLjBUEABBRQYVuDi9lBD/ntfc6bZTj/7vGevlzFFH4b9GC1dAQU2SeAip5ON83GVkv0UfwBqt2Mb+rC4UVinL+tcW6P+GmWU+jDO/x3zq+Ub/wMZkGkAOPUFqAAAAABJRU5ErkJggg=="

  background.onload = function() {

    let context = canvas.getContext('2d');

    ctx.drawImage(background, 0, 0, 350, 97, // source rectangle
      0, 0, sigWidth, adjustedHeight); // destination rectangle)
    var monthNames = ["January", "February", "March", "April", "May", "June",
      "July", "August", "September", "October", "November", "December"
    ];
    var dateObj = new Date();
    var month = monthNames[dateObj.getMonth()];
    var day = String(dateObj.getDate()).padStart(2, '0');
    var year = dateObj.getFullYear();
    var output = month + '\n' + day + ',' + year;



    //Set the font size and the fontface to use.
    context.font = fontSize+'px Palatino';

    //Set the color of the text. This can be
    //an RGB color or a textual description
    //such as red.
    context.fillStyle = '0,0,0';

    //The X coordinate where to start
    var x = 5;

    //The Y coordinate where to start
    var y = adjustedHeight * .94;

    //Use the fillText method to draw the text.
    context.fillText(output, x, y);
  }
<img width="511" alt="Screen Shot 2021-01-16 at 10 02 29 PM" src="https://user-images.githubusercontent.com/70493366/104829882-78a58300-5846-11eb-8786-32848f63b79d.png">
 
and this is after. you'll see that the X is clipped several times. 
<img width="400" alt="Screen Shot 2021-01-16 at 10 02 37 PM" src="https://user-images.githubusercontent.com/70493366/104829892-865b0880-5846-11eb-8fa9-cc681e994410.png">

this error goes away after another resize. 

```  
var background = new Image();
  background.id = 'background_image'
  background.src = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAV4AAABkCAYAAADOvVhlAAAK20lEQVR4Xu3da6g1VR3H8a9PSVlaklBSD2GRXehK0guTwBLSblCoiGAKgb3QSiQwEStNBBOJUimQRDEJwcwEDUUqIcwXkgRFkoYJGlgvwtIw0TR+MBumYZ3j7L3XzJy95/t/c+TsPevy2dv/mWfNuhyAoYACCigwqsABo9ZmZQoooIACmHj9EiiggAIjC5h4Rwa3OgUUUMDE63dAAQUUGFnAxDsyuNUpoIACJl6/AwoooMDIAibekcGtTgEFFDDx+h1QQAEFRhYw8Y4MbnUKKKCAidfvgAIKKDCygIl3ZHCrU0ABBUy8fgcUUECBkQVMvCODW50CCihg4vU7oIACCowsYOIdGdzqFFBAAROv3wEFFFBgZAET78jgVqeAAgpsSuJ9LfBPPy4FFFBgGwRWSbyHAE+N3PlrgI8AXwJ+MXLdVqeAAgpUFVgm8X4K+C5wN3BW1VbsXtjbgQeBfc3b7gS+Ajw8YhusSgEFFKgm0CfxvhXIHedxTa0vAh8CflutFbsXdDuQpN+OfwFvAP4zUhusRgEFFKgm0CfxPgbs79T4e+B91Vqxc0EfBX5ZePki4OIR6rcKBRRQoLpAn8R7KvDjQs1fBb5TvUX/X2AS/Hs6dfwdyF34vweu2+IVUECBQQT6JN5U/Cvg2E4LngEy/vr4IC2DzwM3FMo+E/jhQHVarAIKKDC4QN/E+5bmAdcrOi26CzhhgFa+Evgz8KZO2Q8B7wJeGKBOi1RAAQVGEeibeNOYC4FLCq36LHBb5dZ+DbisUGYesv28cl0Wp4ACCowqsEzifTnwB+AdnRZmqCFDDhl6qBGvA/4CvKZTWIY7PlajAstQQAEFphRYJvGmnUcDvyk0OA/Z8rCtRlwJfLlQ0HubxF+jDstQQAEFJhNYNvGmodcDZ3Ra/F/gAxUS4xHN2O7LOuX/CDh9MiUrVkABBSoKrJJ4D2uS46GddmRBRRZWZIHFqvET4MTOxVkk8Tbgr6sW6nUKKKDAXhJYJfGm/V8Ari105Gzg+yt28MPAvYVrvw2cv2KZXqaAAgrsOYFVE286krHejPm242ngSOCJFXqaO+YPdq77B5CpbFkibCiggAJbIbBO4s3shsxyyGyHdtwEZLXbMnEScHPhgmyGc9UyBfleBRRQYK8LrJN407dLgQsKncweC/f07PyBQBZG5MFaOx5txnbz4M5QQAEFtkZg3cSblWzZsjHDAe3IPNysMHu2h1Tuar9XeF/ugm/pcb1vUUABBTZKYN3Em85mD4csbuhG7oaz2m23yCKJJOksmmhHxo+P2ShJG6uAAgr0FKiReFNVxnVP6dT5fLOz2J92aUtmLJxXeP0o4IGeffBtCiigwEYJ1Eq8hzcnQhzc6f19QKaJlSIb4GQjnGyI047M5T15oxRtrAIKKLCEQK3Emyozh/fqQt2Z83td4fdZjXZa5/fPNfs+5MGaoYACCmylQM3Em7LuBzJM0I4nm4dv+bmIbG6eTc67kX0aztlKaTulgAIKNAI1E2+KTEL9HdDdayF3vLnzXUSO88mUs3ZkkURmR2TRhKGAAgpsrUDtxBuo7FR2bkEsY70Z882eujnAshvZg/fyrZW2YwoooMBAd7wp9iDgESAP3NqR2Q2LrR2zf287sgFONsLx1GC/mgoosPUCQ9zxBi2nUtxa0PtZ81r3pZyvduPWa9tBBRRQABgq8Qb3TuD4HsrZ7yF3woYCCigwC4EhE+/+Zg+GDD3sFjnOp7TybRYfgJ1UQIH5CQyZeKOZ44Cu2IX1DuDT82O3xwooMGeBoRNvppVlelmmmXUjR7RnI53sTGYooIACsxEYOvEG8nPATwuifwTePRtpO6qAAgo0AmMk3gwnfLIgnrPZckZbTp4wFFBAgdkIDJ14szotq9R2isxoyOnEbnY+m6+cHVVAgaETb/ZjKI3vtuXzAC6r3QwFFFBgFgJDJt4sirihh+IzzY5kj/d4r29RQAEFNl5gqMSbPXaz12723G1HTpt4I5Ajg9pxF3DCxmvaAQUUUKCHwFCJNxveXFaoPxvk5Aj3SwqvZZnxbT3a7FsUUECBjRYYIvHm/LTc2eY8tXZkdVpWqeU4+DxUy/Hw7chQQzbPydCDoYACCmytwBCJNycG5+Tgbix2JsvvjwZyoGU38pAtD9sMBRRQYGsFaifeI5qx3e5G6Dnm5/SO4vXAGZ3fZVpZppfljthQQAEFtlKgduLNQZUndqSyx2722s2eu+04rEnSh3Z+nwUVWViRBRaGAgoosHUCNRNvTpi4tyCUI9zP30EuxwFdW3jtLOAHW6dthxRQQIHK+/HmTjUzFtqR89NyjlrOU9spMtabMd92PA0cCTzhp6SAAgpsm0CtO96TgJsLOHnIdtVLoGV2Q8Z0M9uhHTcBp24buP1RQAEFaiTeA5utHfNgrR2PNmO7ffZhuBS4oPBxZK+He/yYFFBAgW0SqJF4c1ebKWTdyF3wLT2xspLtwWZYon1J5gNnz95ne5bj2xRQQIE9L7Bu4s0iiSTHLJpoR8Ztj1my98fucARQ7oYvXLIs366AAgrsWYF1E29mLJxX6N1RwAMr9Drjuqd0rnu+2eEsx8MbCiigwMYLrJN4swFONsLJhjjtyFzek1eUORx4GDi4c/19QKarGQoooMDGC6yTeLMa7bSOwHPNfgt5sLZqnA1cXbg4c36vW7VQr1NAAQX2isCqiTebm2eT825cCZyzZufSpvuBDFe048nm4Vt+GgoooMDGCqyaeHOcT6Z6tSOLJLJYIosm1o0k9pxO3N3zIXe8ufM1FFBAgY0VWCXxZk/d2ws9zh68l1eUyE5l5xbKy1hvxnwNBRRQYCMFlk28+5r5ttk3tx3ZACcb4WRDnFpxEPAIkAdu7cjshtwRZ7aDoYACCmycwLKJ90zgmkIvc77ajQP0PqdS3FooN/N6M7/XUEABBTZOYJnE++rmDvT1nV5mn4Vscj5U3Akc3yk8K9myoi2LNwwFFFBgowSWSbwXAd8s9C7H+eRYn6Fif7MXRIYe2pE9HLoP+IZqg+UqoIAC1QT6Jt5XAX8rLGzIQ7bPVGvNzgXlOKArCi9n97KsdjMUUECBjRHom3jToXc2CxuOa3r3QvPP/YdG6m2ml72/U9djwJtHqt9qFFBAgSoCyyTeRYWfADLV69fAF6u0ol8hWVCRhRWLNt/RHKqZmQ+GAgoosDECqyTeRedyVtrYq8hyHNDHgSwrzkM3QwEFFNg4gXUS7xSdPQR4aoqKrVMBBRSoJbBpibdWvy1HAQUUmEzAxDsZvRUroMBcBUy8c/3k7bcCCkwmYOKdjN6KFVBgrgIm3rl+8vZbAQUmEzDxTkZvxQooMFcBE+9cP3n7rYACkwmYeCejt2IFFJirgIl3rp+8/VZAgckETLyT0VuxAgrMVcDEO9dP3n4roMBkAibeyeitWAEF5iqwSLw5wyxHqWeP3Rd3+bnba0Neuyh7nfqnLGOu3y/7rYACBYFF4v068C2FBhMo/cFY54/IOtdO+Qeo3e5t6EMNy73sMNj/EHMveJF4c5ZazlQzFFBAgYXAS/0rtvv61H9Epq6/9x/iReLd6SBLv4IKKKCAAnUFLlkk3gwzZLjBUEABBRQYVuDi9lBD/ntfc6bZTj/7vGevlzFFH4b9GC1dAQU2SeAip5ON83GVkv0UfwBqt2Mb+rC4UVinL+tcW6P+GmWU+jDO/x3zq+Ub/wMZkGkAOPUFqAAAAABJRU5ErkJggg=="

  background.onload = function() {

    let context = canvas.getContext('2d');

    ctx.drawImage(background, 0, 0, 350, 97, // source rectangle
      0, 0, sigWidth, adjustedHeight); // destination rectangle)
    var monthNames = ["January", "February", "March", "April", "May", "June",
      "July", "August", "September", "October", "November", "December"
    ];
    var dateObj = new Date();
    var month = monthNames[dateObj.getMonth()];
    var day = String(dateObj.getDate()).padStart(2, '0');
    var year = dateObj.getFullYear();
    var output = month + '\n' + day + ',' + year;



    //Set the font size and the fontface to use.
    context.font = fontSize+'px Palatino';

    //Set the color of the text. This can be
    //an RGB color or a textual description
    //such as red.
    context.fillStyle = '0,0,0';

    //The X coordinate where to start
    var x = 5;

    //The Y coordinate where to start
    var y = adjustedHeight * .94;

    //Use the fillText method to draw the text.
    context.fillText(output, x, y);
  }
```
