### ISSUE TITLE
`fromDataUrl()` aspect ratio problem

### ISSUE THREAD

**Issue by FirstVertex** [szimek/signature_pad#512]
## Bug Report
SignaturePad draws an image with a wrong aspect ratio when it is provided to `fromDataUrl()`

## Demo
https://jsfiddle.net/HugeHugh/ydgbef69/
In this fiddle we can see the image is wide and short when using an `<img>` tag.

When the same image is loaded to the SignaturePad using `fromDataUrl()` it has become horizontally scaled.

Such modification of the aspect ratio is not acceptable in our application.

## Workaround
Using technique discovered [here](https://stackoverflow.com/a/23105310/213050) I have to write a routine to first fetch the image to discover it's dimensions, and then provide the width, height, and ratio parameters to `fromDataUrl()`.
I created a Fiddle with this workaround applied: https://jsfiddle.net/HugeHugh/z5tg2eha/
This shows correct aspect ratio of input img

## Expectation
The data we are handling represents a user's signature, and in such content the aspect ratio is important. It is expected that the library should not change the signature's aspect ratio.  If the image is too large to fit on the canvas it is expected that it should be scaled down to fit, without any clipping.  If the image is too small it is expected that it should be centered.  It is expected the dev should not have to fetch and measure the image in order to preserve the image's aspect ratio.

It was already reported in #81 
I have already tried applying the techniques therein of `window.devicePixelRatio`

**Comment by skylarmt** [comment]
Here's a function I wrote that takes the object produced by `toDataUrl()` as well as the width and height of the destination signature pad, scales the signature data, and returns it.

```js

function scaleSignatureData(data, width, height) {
    // Get width and height of data
    // Get the minimum positions too for adding a bit of margin
    var oldwidth = 0;
    var oldheight = 0;
    var oldminX = 999999999;
    var oldminY = 999999999;
    for (var i = 0; i < data.length; i++) {
        for (var j = 0; j < data[i].points.length; j++) {
            oldwidth = Math.max(data[i].points[j].x, oldwidth);
            oldheight = Math.max(data[i].points[j].y, oldheight);
            oldminX = Math.min(data[i].points[j].x, oldminX);
            oldminY = Math.min(data[i].points[j].y, oldminY);
        }
    }
    var xPad = oldminX / 2;
    var yPad = oldminY / 2;
    // Calculate scale ratios
    var scaleX = (oldwidth + xPad * 2) / width;
    var scaleY = (oldheight + yPad * 2) / height;
    // Pick the largest scale ratio and use only that one so it maintains aspect ratio
    var scale = Math.max(scaleX, scaleY);
    // Loop over the old data and scale the points into a new signature data object
    var newdata = [];
    for (var i = 0; i < data.length; i++) {
        var newpoints = [];
        for (var j = 0; j < data[i].points.length; j++) {
            newpoints.push({
                time: data[i].points[j].time,
                x: (data[i].points[j].x + xPad) / scale,
                y: (data[i].points[j].y + yPad) / scale
            });
        }
        newdata.push({
            color: data[i].color,
            points: newpoints
        });
    }
    return newdata;
}
```
