### ISSUE TITLE
SVG Output does not include raster background

### ISSUE THREAD

**Issue by FirstVertex** [szimek/signature_pad#516]
## Bug Report
When a signature is initialized using `fromDataUrl("img.png")` the subsequent output using `toDataUrl("image/svg+xml")` doesn't contain the raster image that was previously loaded.

## Stackblitz Repro
https://jsfiddle.net/HugeHugh/f7m5sr48/

1. Initialized signature with bitmap
2. Exported to PNG with no issue
3. Exported to SVG does not contain bitmap background

## Possible Solution
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image
SVG output could be enhanced to contain `<image>` node with background that was previously loaded.

Even better enhancement would be to treat `fromDataUrl()` the same as a stroke, so it could be layered, played back, pushed and popped, etc.

**Comment by UziTech** [comment]
closing this as stale you can copy the background image yourself if it is needed. No need for this library to do it.
