### ISSUE TITLE
Signing with Apple Pencil is not possible

### ISSUE THREAD

**Issue by dominikfladung** [szimek/signature_pad#518]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
While signing with apple pencil not all lines are in the canvas

_If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via <https://jsfiddle.net> or similar (template: <https://jsfiddle.net/szimek/h80phxyr/>)._
With the iPad Air 2020 and Apple Pencil 1 just use the demo.
http://szimek.github.io/signature_pad/

**What is the expected behavior?**
All lines are shown in canvas.

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**
Current Safari on iPad

**Comment by mahy50** [comment]
I also encountered this problem, do you have a solution?

**Comment by dominikfladung** [comment]
In our project we developed an app with a Webview. 
You can take it easy with something like this repo. 

https://github.com/TorIsHere/SignaturePad

**Comment by UziTech** [comment]
This seems to be a known issue with the apple pencil. https://developer.apple.com/forums/thread/664108

If anyone has an apple pencil to test and would like to submit a PR that works with touch events, that would be much appreciated. 😁👍
