### ISSUE TITLE
Events doesn't work after Init on IOS Chrome / Safari

### ISSUE THREAD

**Issue by alekradev** [szimek/signature_pad#520]
**Do you want to request a feature or report a bug?**
report a bug

**What is the current behavior?**
After the initialization, Click or Touch events no longer work under IOS

**What is the expected behavior?**
That the events still work after initialization

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**
Chrome / Safari on IOS

**Comment by commi** [comment]
The signature-pad also interferes with angular-click-handlers. They can only be restored by calling .off(). This PR fixes this.
