### ISSUE TITLE
I am unable to do undo function on the signaturepad canvas image .undo function clear canvas background image

### ISSUE THREAD

**Issue by sailajalingolu** [szimek/signature_pad#524]
In my project i have  set the background image to signaturepad using signaturepad.fromdataurl("imagelink").
i am able to save the signature write on the background image but not able to get same image in undo function.using todata i am able to read only signature.please help me.
my code
function resizeCanvas() {
    var ratio = Math.max(window.devicePixelRatio || 1, 1);

    canvas.width = canvas.offsetWidth * ratio;
    canvas.height = canvas.offsetHeight * ratio;
    canvas.getContext("2d").scale(ratio, ratio);
    signaturePad.fromDataURL("https://preview.ibb.co/jnW4Qz/Grumpy_Cat_920x584.jpg");
   
    signaturePad.clear();
}

undoButton.addEventListener("click", function (event) {
    var data = signaturePad.toData();
       
    if (data) {
        data.pop(); // remove the last dot or line
        signaturePad.fromData(data);
    }
});

**Comment by sjoerdloeve** [comment]
I am experiencing the same issue.

The solution as provided in this issue might be the correct fix: #511
