### ISSUE TITLE
[BUG] toDataUrl() returns empty image

### ISSUE THREAD

**Issue by asivaneswaran** [szimek/signature_pad#525]
For some reason, I am unable to produce an image output from toDataUrl();

I have the following code:
```
            @this.on('validated', () => {
                canvas = document.getElementById("signature-canvas");
                signaturePad = new SignaturePad(canvas, {
                    backgroundColor: '#ffffff',
                });
                signaturePad.on();
                resizeCanvas();
            });

          @this.on('parseSignature', () => {@this.signature
                = signaturePad.isEmpty() ? null : console.log(signaturePad.toDataUrl("image/jpeg"));
            });
```

When I click the output image in the console, it returns a black rectangle. 

This is the base64 code generated: ```data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wAARCACWASwDAREAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAv/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AJ/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/Z```

If you run this on a decoder like: https://base64.guru/converter/decode/image
It's a black square...

**Comment by indaqoo** [comment]
@asivaneswaran 
`          @this.on('parseSignature', () => {@this.signature
                = signaturePad.isEmpty() ? null : console.log(signaturePad.toDataURL("image/jpeg"));
            });`
This should work I think.

**Comment by shawe** [comment]
This problems still happens to me on Signature Pad v3.0.0-beta.4 used on the demo page.

There is no way to refill signaturePad points and image previously generated to allow re-sign only if needed or re-use the same signature details?

Also seems to not be possible of doing it by only loading the array of points, that I think that maybe can be enough to re-generate it from scratch.

According to details on the README.md file, this must work only using fromData function.

```
var canvas = document.querySelector("canvas");

var signaturePad = new SignaturePad(canvas);

// Returns signature image as an array of point groups
//const data = signaturePad.toData();
const data = {{ signaturePadData }}; // Data previously stored from signaturePad.toData()

// Draws signature image from an array of point groups
signaturePad.fromData(data);
```

**Comment by romarioliveira25** [comment]
Any news about that?

**Comment by UziTech** [comment]
Anyone have a way to reproduce this or have specific browsers that this happens with?

**Comment by shawe** [comment]
I can attach the original JS that I modified, but maybe is not do it the best way to solve it. With this changes, I get it working.

Also, if I remember well, the problem is that structure saved for the signature was changed, and in my case, require still work with all way stored in database.

**Comment by UziTech** [comment]
@shawe can you create a PR?

**Comment by shawe** [comment]
> @shawe can you create a PR?

Yes, I can without problem, but this beta version it's only on the online demo of signature_pad, but in no other place like in a beta branch. Can you add the v3.0.0-beta.4 branch to do it on it?

**Comment by UziTech** [comment]
the online demo is v3.0.0-beta.4

**Comment by shawe** [comment]
> the online demo is v3.0.0-beta.4

Yes, I know that, but in what branch is this version to do the PR you ask me to create?

This is my question for this reason I use it as last version, but isn't available on any other place except in demo site.

**Comment by UziTech** [comment]
master is the branch with v3.0.0-beta.4

**Comment by luisricardo502** [comment]
This fix was added into the lastest version v4.0.1?

Regards

**Comment by shawe** [comment]
It is my fault, I not remember anymore to upload my changes in a PR, the day we talk about this was to late for me, and I don't remember anymore.

**Comment by luisricardo502** [comment]
> It is my fault, I not remember anymore to upload my changes in a PR, the day we talk about this was to late for me, and I don't remember anymore.

Hi @shawe 

And you have any idea was be the change?
