### ISSUE TITLE
Highlighting/Copying issue on iOS 14.x+

### ISSUE THREAD

**Issue by marcodafonseca** [szimek/signature_pad#532]
**Do you want to request a feature or report a bug?**

**What is the current behavior?**
Setup the canvas as per normal. While signing on an iOS device running version 14.x+ it will highlight the canvas allowing the user to "copy" (as if they had highlighted text).
If the user chooses to "copy" at this point it will copy any highlighted text as well as the underlying HTML of the canvas itself.

An example "copy" output we received from a user:
```
<canvas height="516" class="signature-pad" width="1432" style="box-sizing: border-box; border: 1px solid rgb(204, 204, 204); background-color: rgb(255, 255, 255); border-top-left-radius: 5px; border-top-right-radius: 5px; border-bottom-right-radius: 5px; border-bottom-left-radius: 5px; width: 716px; caret-color: rgb(33, 37, 41); color: rgb(33, 37, 41); font-family: &quot;Chalet LondonNineteenSixty&quot;, &quot;Open Sans&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); -webkit-text-size-adjust: 100%; -webkit-text-stroke-width: 0px; text-decoration: none; touch-action: none; background-position: initial initial; background-repeat: initial initial;"></canvas>
```

**What is the expected behavior?**
It should behave like it does on other browsers and older iOS versions where the canvas does not highlight at all and even if it didn't highlight the user definitely shouldn't be able to copy the underlying HTML

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**
I don't think this issue is specific to any versions of the Signature Canvas. I think it's a bug brought on by the latest release by Apple

**Comment by UziTech** [comment]
If you add `user-select: none` to the canvas css does it fix it?

**Comment by UziTech** [comment]
closing as stale
