### ISSUE TITLE
_toSVG ratio cutting my signature off

### ISSUE THREAD

**Issue by Tthecreator** [szimek/signature_pad#539]
I'm trying to get a form signed and have the signature mailed to me. I use the toDataURL function for this. I'm using svg.
The problem was that my signature was cut off whenever I submitted the form on my phone. On my computer things did work.

My HTML looks like this:
`<li><label>Signature:</label>
                <ul class="sign">
                    <li class='canvas-wrapper'>
                        <canvas id="signature"></canvas>
                    </li>

                    <li><%= first_name %> <%= sur_name %></li>
                    <li id="sign-date">Date here</li>
                </ul>
                <input id="sign-data" type="text" name="sign_data" height="0" readonly>
            </li>`

My CSS:
`.formList {
    margin: 0;
    padding: 0;
}

input {
    width: 100%;
    box-sizing: border-box;
    font-size: 24px;
}

.formList li {
    margin-left: 0;
    margin-bottom: 10px;
    list-style: none;
}

.formList li ul li {
    margin-left: 0;
    list-style: circle;
    margin-bottom: 3px;
}

#signature {
    border: black 1px dashed;
    width: 100%;
    min-width: 300px;
}

.sign li {
    list-style: none !important;
}

.sign {
    margin-left: 0;
    padding-left: 0;
}

#sign-data, #link-id {
    visibility: hidden;
    height: 0;
    max-height: 0;
    display: none;
}

`

It seems that the issue is caused by me scaling my canvas in a certain way using CSS. Especially the "#Signature" part may be at fault. What I've done in the signature_pad code is forced the ratio in the _toSVG function to always be 1 by changing line 466. Doing so makes things work perfectly. But I'm still making a report as other people might run into this.

**Comment by UziTech** [comment]
When you set the width and height of the canvas you have to take into account the `devicePixelRatio` of the device so it looks smoother

```js
const ratio = Math.max(window.devicePixelRatio || 1, 1);
const width = window.innerWidth * .9; // set desired width
const height = window.innerHeight * .9; // set desired height
canvas.style.width = `${width}px`;
canvas.style.height = `${height}px`;
canvas.width = width * ratio;
canvas.height = height * ratio;
canvas.getContext("2d").scale(ratio, ratio);
```

see [Handling high DPI screens](https://github.com/szimek/signature_pad#handling-high-dpi-screens)

**Comment by Tthecreator** [comment]
Ow well, if it was in the manual then that was on me. Sorry for bothering you then.
