### ISSUE TITLE
Make signature_pad an event emitter

### ISSUE THREAD

**Issue by UziTech** [szimek/signature_pad#543]
This is an issue to track https://github.com/szimek/signature_pad/pull/353#issuecomment-857077908 probably for v4

**Comment by JamesCatt** [comment]
Just wanted to +1 this. In particular, I'm hoping to be able to execute a callback if/when the user hits the edge of the canvas. 

My use case is to try and make it usable by blind users—i.e., alert them via a sound or aria-live announcement if they run off the edge with a stroke.
