### ISSUE TITLE
I want to request a report for a bug?

### ISSUE THREAD

**Issue by SagarSRathod** [szimek/signature_pad#549]
When I draw the signature for the first time and after drawing, 
if I download any file under that signature pad then canvas gets clear, but if we do the same process then canvas remains as it is. so can anyone give me the best solution for this problem

**Comment by UziTech** [comment]
If your code resizes the canvas after drawing it the browser will clear the canvas there is nothing we can do about it. Without seeing some code I don't know how else to help.

**Comment by SagarSRathod** [comment]
var wrapper = document.getElementById("signature-pad");
var clearButton = wrapper.querySelector("#clear");
var savePNGButton = wrapper.querySelector("#png");
var saveJPGButton = wrapper.querySelector("#jpg");
var saveSVGButton = wrapper.querySelector("#svg");
var canvas = wrapper.querySelector("canvas");
var signaturePad = new SignaturePad(canvas,
{
    backgroundColor: 'rgb(255, 255, 255)'
});
function resizeCanvas()
{
    var ratio = Math.max(window.devicePixelRatio || 1, 1);

    canvas.width = canvas.offsetWidth * ratio;
    canvas.height = canvas.offsetHeight * ratio;
    canvas.getContext("2d").scale(ratio, ratio);
   signaturePad.clear();
}
window.onresize = resizeCanvas;
resizeCanvas();

function download(dataURL, filename)
{
    if (navigator.userAgent.indexOf("Safari") > -1 && navigator.userAgent.
indexOf("Chrome") === -1)
    {
        window.open(dataURL);
    }
    else
    {
        var blob = dataURLToBlob(dataURL);
        var url = window.URL.createObjectURL(blob);
        var a = document.createElement("a");
        a.style = "display: none";
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
    }
}
function dataURLToBlob(dataURL)
{
    var parts = dataURL.split(';base64,');
    var contentType = parts[0].split(":")[1];
    var raw = window.atob(parts[1]);
    var rawLength = raw.length;
    var uInt8Array = new Uint8Array(rawLength);

    for(var i = 0; i < rawLength; ++i)
    {
        uInt8Array[i] = raw.charCodeAt(i);
    }

    return new Blob([uInt8Array],
    {
        type: contentType
    });
}

clearButton.addEventListener("click", function (event)
{
    signaturePad.clear();
});
savePNGButton.addEventListener("click", function (event)
{
    var dataURL = signaturePad.toDataURL();
        download(dataURL, "signature.png");
});

saveJPGButton.addEventListener("click", function (event)
{
    var dataURL = signaturePad.toDataURL("image/jpeg");
    download(dataURL, "signature.jpg");
});

saveSVGButton.addEventListener("click", function (event)
{
    var dataURL = signaturePad.toDataURL('image/svg+xml');
     download(dataURL, "signature.svg");
});

**Comment by SagarSRathod** [comment]
that's my code for signaturepad

**Comment by UziTech** [comment]
Can you create a [jsfiddle](https://jsfiddle.net/szimek/h80phxyr/) with the error and steps to reproduce it?

**Comment by SagarSRathod** [comment]
Yes, I will do that.
https://jsfiddle.net/xeyz3m1t/4/

**Comment by SagarSRathod** [comment]
https://jsfiddle.net/xeyz3m1t/4/#&togetherjs=JDaegkoFfm

**Comment by UziTech** [comment]
Looks like you are calling `signaturePad.clear();` on resize. if the download causes the window to resize than it will clear the canvas. If you remove the window.resize callback it shouldn't clear on download.

**Comment by SagarSRathod** [comment]
Thanks for the tip!
  It's Worked

**Comment by SagarSRathod** [comment]
Awesome, thanks!
