### ISSUE TITLE
Save only the around the signed location

### ISSUE THREAD

**Issue by tiagocaus** [szimek/signature_pad#555]
Is it possible to save only the area around the signed location?

I have a good area for the person to sign, the problem is that every area is being generated in the base64 file.

is it possible to save only around the signature? In the image below, I marked it in red.

> https://prnt.sc/1q82hsb

Thanks.

**Comment by UziTech** [comment]
See https://github.com/szimek/signature_pad/issues/49#issuecomment-260976909

**Comment by tiagocaus** [comment]
@UziTech How to implement?

See how I'm doing: https://jsfiddle.net/n0zh8sbp/

Thanks.
