### ISSUE TITLE
fromData() and Point class problem with string coords

### ISSUE THREAD

**Issue by hembachrterran** [szimek/signature_pad#559]
**Do you want to request a feature or report a bug?**
Report a bug

**What is the current behavior?**
If fromData() function get a PointsGroup and the x and y coords are string (e.g. "54.242422523") the type is not checked that causing 'NaN' values in Bezier class calculateControlPoints() function and draw a wrong empty drawing.

**What is the expected behavior?**
Check for type, if string then parse float

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**
v3.0.0-beta.4

**Suggestion to fix**
`class Point {
    constructor(x, y, time) {
        this.x = ((typeof x == 'string') || (x instanceof String)) ? parseFloat(x) : x;
        this.y = ((typeof y == 'string') || (y instanceof String)) ? parseFloat(y) : y;
        this.time = time || Date.now();
    }`

**Comment by romarioliveira25** [comment]
> @UziTech Yes, I will in the next few days.

Any news about that?

**Comment by hembachrterran** [comment]
@romarioliveira25 Sorry, I have no time at the past days. Today I will make a PR to fix this problem.
