### ISSUE TITLE
Changing maxWidth (penWidth) affecting entire canvas?

### ISSUE THREAD

**Issue by Committing** [szimek/signature_pad#561]
Changing the pen width affects the entire canvas.

Is there something I need to do in order to stop this occurring? Looks like a bug maybe?

signaturePad.maxWidth = 10

Video of issue (Cannot embed):

https://i.gyazo.com/a26825aa236ec234e65957cf219f8127.mp4

**Comment by UziTech** [comment]
Doesn't seem like a valid use of this library. There shouldn't be any reason to change the pen width in the middle of the signature.

**Comment by Committing** [comment]
Thanks for the fix @UziTech
