### ISSUE TITLE
Chrome/96.0.4664.45 on Android 11 (Pixel 4a)

### ISSUE THREAD

**Issue by plutext** [szimek/signature_pad#572]
I was getting weird behaviour:
- canvas too wide for the screen
- strokes appearing 1 or 2 cm to the right of where i drew

until I removed the demo resizeCanvas() code.  Then Android seemed to work fine.

_If you have a question, please ask it on [StackOverflow](https://stackoverflow.com/questions/ask?tags=javascript+signature-pad) and use `signature-pad` tag instead of creating an issue._

**Do you want to request a feature or report a bug?**

**What is the current behavior?**

_If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via <https://jsfiddle.net> or similar (template: <https://jsfiddle.net/szimek/h80phxyr/>)._

**What is the expected behavior?**

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**

Signature Pad v3.0.0-beta.4 
Mozilla/5.0 (Linux; Android 11; Pixel 4a) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Mobile Safari/537.36

**Comment by UziTech** [comment]
It sounds like you were able to fix the issue by removing the resizeCanvas() code. If you have any other issues make sure you fill out the template completely so we can more easily help you.
