### ISSUE TITLE
JPEG defaults result in a black box image

### ISSUE THREAD

**Issue by drwahl** [szimek/signature_pad#584]
Bug: When using JPEG, the default colors result in black box due to the default black background and default black "ink".

If you instantiate the pad with defaults, but select jpeg for the resulting image, you get a black box due to the "black on black" defaults.

  `this.signaturePad = new SignaturePad(this.canvas);
   this.signaturePad.toDataURL("image/jpeg")`

Ideally, the defaults for `image/jpeg` would be black ink on a white canvas. Is it possible to have the toDataURL function recognize the jpeg request and set the background to white before snagging the inked image?

**Comment by UziTech** [comment]
you can set the background color for jpg with the `background` option.

```js
this.signaturePad = new SignaturePad(this.canvas, {
  background: '#ffffff',
});
this.signaturePad.toDataURL("image/jpeg")
```

**Comment by drwahl** [comment]
@UziTech that's what I have done for now. However, it still seems silly for the defaults to result in a unusable result. This request is for the default configuration for jpeg to default to black ink on a white canvas.

**Comment by UziTech** [comment]
The default is transparent so a user can add an image to the canvas and the signature will go over it and anyone using svg or png get a transparent background. 

The defaults can't please everyone which is why we have the background option.

**Comment by distante** [comment]
@UziTech that means we have to choose between use a PNG with transparency or a JPEG, but not both? 

I can not export both and transparent PNG and a JPEG with white background. Correct?

Thanks.

**Comment by UziTech** [comment]
I don't know why you would want to do that but you can change the background color.

```js
signaturePad.backgroundColor = "#fff";
signaturePad.fromData(signaturePad.toData());
```

**Comment by MarcBollmann** [comment]
when exporting to jpeg I had to set the background of the canvas manually:
```
context.fillStyle = 'rgba(255, 255, 255, 1)';
    context.fillRect(
      0,
      0,
      this.canvas.nativeElement.width,
      this.canvas.nativeElement.height
    );
```
