### ISSUE TITLE
V4 was published incorrectly

### ISSUE THREAD

**Issue by felixmosh** [szimek/signature_pad#589]
I installed the latest `v4.0.0` of `signature_pad` and looks like it doesn't contains the latest code (it missing `signature_event_target` class and more).

![image](https://user-images.githubusercontent.com/9304194/147925980-c3304269-82fe-4e6b-a19c-586c46b713b2.png)

**Comment by UziTech** [comment]
The latest code hasn't been published yet.

**Comment by felixmosh** [comment]
Sorry 😅
