### ISSUE TITLE
Rendering signature image with same aspect ratio regardless of window size

### ISSUE THREAD

**Issue by bryangoldberg** [szimek/signature_pad#59]
I can't seem to get the aspect ratio of the saved signature image to be the same across the different browser sizes and devices I use.

For example: Signing on a laptop vs signing on a phone vs signing on a smaller window on a computer doesn't have the same image aspect ratio.

I made my #sigPadContainer to have a responsive aspect ratio depending on the size of the screen but my signatures are off by 50-200 pixels. Could anyone possibly give some insight in how I could get the same aspect ratio of the image?

I am using the default .min.js of the signature pad.

**Comment by Remo** [comment]
did you ever find a problem around this? Having the same issue..

**Comment by szimek** [comment]
What's the problem exactly? Is it that you have a canvas of size e.g. 300x400px and after saving the image it has different size?

**Comment by Remo** [comment]
No, when I "draw" the signature the signature isn't drawn where I touched the screen, it's more to the right.

**Comment by szimek** [comment]
Are you sure that the displayed size of the canvas (the one set via CSS) and the real size of the canvas (the one set via `canvas.width` and `canvas.height`) is the same?

**Comment by Remo** [comment]
I wasn't aware that I have to set the width/height manually, will check it out, thanks!

**Comment by szimek** [comment]
Check this code from the demo: https://github.com/szimek/signature_pad/blob/gh-pages/js/app.js#L10-L18. Let me know if it helps.

**Comment by Remo** [comment]
works like a charm, thanks a lot! Is there a reason why you didn't add that code directly into your library?

**Comment by szimek** [comment]
The main reason is that resizing canvas also clears it. It's probably better to have more control over it. That's also why this code is in the demo app :)
