### ISSUE TITLE
Signature is being refresh on right bottom corner ( Only iphone using safari) 

### ISSUE THREAD

**Issue by joanrotbard** [szimek/signature_pad#590]
When trying to sign using iphone and safari in the right bottom corner the signature pad is getting refreshed. attached sample video

https://user-images.githubusercontent.com/8891802/148442358-13a70c19-2be9-48b2-9d6f-0d6c0a7f99b0.mp4

**Comment by UziTech** [comment]
What version of ios?

**Comment by joanrotbard** [comment]
> What version of ios?

ios 15.2

**Comment by UziTech** [comment]
v4.0.1 fixes some stuff on iOS. see if that fixes this issue for you.

**Comment by UziTech** [comment]
Was this fixed with the latest update?

**Comment by yvesvdv** [comment]
I don't know if it's worth something but I had a refreshing issue on all tablets. It seems that (only on tablet/smartphone) signaturepad did some auto refresh. Maybe something like this is also happening here?
