### ISSUE TITLE
Yellow screen on mobile devices.

### ISSUE THREAD

**Issue by Nyavowoyi** [szimek/signature_pad#592]
I am getting serious issue with this library. It works well on Desktop devices. However, on my Android 8.1 device, the captured signature is rendered as a blank yellow box.

Anyone facing the same issue or have solved it?

**Comment by SimoneNicoletti** [comment]
I made some test: if I export the image as SVG, it works.
So the problem seems to be the call to `canvas.toDataURL` in the method `toDataURL(type = 'image/png', encoderOptions)`
I tried also to pass 1 as encoderOptions, but same result.

**Comment by UziTech** [comment]
Exporting to PNG and jpg is just sent to the browser. I don't think there is anything we can do about a browser bug.

**Comment by rkkirky1** [comment]
Looking at the demo, the author notes setting a opaque background:

  signaturePad = new SignaturePad(canvas, {
            // It's Necessary to use an opaque color when saving image as JPEG;
            // this option can be omitted if only saving as PNG or SVG
            backgroundColor: 'rgb(255, 255, 255)'
        });

I had an issue where the image would be a black rectangle until I included the backgroundColor

**Comment by SimoneNicoletti** [comment]
> Looking at the demo, the author notes setting a opaque background:
> 
> signaturePad = new SignaturePad(canvas, { // It's Necessary to use an opaque color when saving image as JPEG; // this option can be omitted if only saving as PNG or SVG backgroundColor: 'rgb(255, 255, 255)' });
> 
> I had an issue where the image would be a black rectangle until I included the backgroundColor

Thank you for the note rkkirky1. In my project I already had the opaque background.
What I found in my tests was that, with the last version of Chrome, in mobile devices with limited RAM (uleFone Armor X3) I had the problem. If I downgraded to a previous version of Chrome, it worked. In other mobile devices more performing, tere were no problems also with the last version of Chrome.

**Comment by katzura1** [comment]
> > Looking at the demo, the author notes setting a opaque background:
> > signaturePad = new SignaturePad(canvas, { // It's Necessary to use an opaque color when saving image as JPEG; // this option can be omitted if only saving as PNG or SVG backgroundColor: 'rgb(255, 255, 255)' });
> > I had an issue where the image would be a black rectangle until I included the backgroundColor
> 
> Thank you for the note rkkirky1. In my project I already had the opaque background. What I found in my tests was that, with the last version of Chrome, in mobile devices with limited RAM (uleFone Armor X3) I had the problem. If I downgraded to a previous version of Chrome, it worked. In other mobile devices more performing, tere were no problems also with the last version of Chrome.

Do you already found the solution ?

**Comment by SimoneNicoletti** [comment]
> > > Looking at the demo, the author notes setting a opaque background:
> > > signaturePad = new SignaturePad(canvas, { // It's Necessary to use an opaque color when saving image as JPEG; // this option can be omitted if only saving as PNG or SVG backgroundColor: 'rgb(255, 255, 255)' });
> > > I had an issue where the image would be a black rectangle until I included the backgroundColor
> > 
> > 
> > Thank you for the note rkkirky1. In my project I already had the opaque background. What I found in my tests was that, with the last version of Chrome, in mobile devices with limited RAM (uleFone Armor X3) I had the problem. If I downgraded to a previous version of Chrome, it worked. In other mobile devices more performing, tere were no problems also with the last version of Chrome.
> 
> Do you already found the solution ?

No, with new and more performant devices the problem disappeared.
