### ISSUE TITLE
Version number is incorrect in the signature_pad.umd.js file

### ISSUE THREAD

**Issue by larrymcp** [szimek/signature_pad#593]
With the latest version 4.0.2, in the comments section at the top of `signature_pad.umd.js` it says the version number is 4.0.1.

I also noticed the same issue in version 4.0.1.  In that version the JS file is labeled as 4.0.0.

**Comment by UziTech** [comment]
Yes it looks like the umd file is compiled before the version is bumped.

We will have to figure out a way to get the next version from semantic release before building the file.

**Comment by UziTech** [comment]
fixed in v4.1.3
