### ISSUE TITLE
Is there anyway to have a transparent background?  

### ISSUE THREAD

**Issue by stccorp** [szimek/signature_pad#597]
Hello,

Sorry, I tried posting a question as suggested and I got the following error
Creating the new tag 'signature-pad' requires at least 1500 reputation

Is there anyway to have a transparent background?  Everytime I do it I wjust get a white background.  The problem is that when you print the signature and is not transparent id covers whatever is behind in the PDF

Also, I can donate some money to the project if you want.

Thank you

**Comment by szimek** [comment]
Hey!

Do you mean transparent background in the generated image or transparent background of the canvas you draw on?

BTW. Next time you can use tag `signaturepad`: https://stackoverflow.com/questions/tagged/signaturepad

**Comment by stccorp** [comment]
On the generated image. Something like this. See attachment
![transparent](https://user-images.githubusercontent.com/8180135/152842819-f96f9bd4-220a-42ba-8aa0-4154c3738d1e.png)
.

**Comment by stccorp** [comment]
![paintdotnet_6mpZcZhaXJ](https://user-images.githubusercontent.com/8180135/152843007-2f19d455-acfb-4fcb-905a-bb2e174473a2.png)

**Comment by szimek** [comment]
I think it should "just work".

By default the background color is set to `rgba(0,0,0,0)`, which means it's transparent. When you call `signaturePad.toDataURL()` it will save it as PNG with a transparent background.

Here's an example: https://codesandbox.io/s/objective-browser-p4e1f.

Let me know if it helps.

**Comment by stccorp** [comment]
Thank you. that worked.  I didnt notice the example (that I was using() had 255,255,255

Where can I dontate to the project?

**Comment by szimek** [comment]
Awesome!

Unfortunately, there's no way to donate to the project at the moment.
