### ISSUE TITLE
Signature Pad doesn't show on new IPad IOS 15

### ISSUE THREAD

**Issue by Ume187** [szimek/signature_pad#598]
Same code doesn't work on the new IPad 2021:

The Pad doesn't show

**Comment by Ume187** [comment]
It worked on IPad Air 2

**Comment by UziTech** [comment]
could you share some code that doesn't seem to work?

**Comment by Ume187** [comment]
Creating new Issue this is wrong

**Comment by Ume187** [comment]
I had the version 2.3 signature_pad.js
