### ISSUE TITLE
Signature Pad: Can't sign, doesn't show on safari

### ISSUE THREAD

**Issue by Ume187** [szimek/signature_pad#599]
Using the latest version 4.0.

With firefox the pad appears but cannot be signed.
With safari the pad doesn't show.

**Comment by FlorisVeldhuizen** [comment]
I also encountered a similar issue (with version 4.0.2), on an iPad with iOS 12.5.5. The signature pad did appear but was not interactive. Before the bump to 4.0.2 this issue was not encountered before.

**Comment by marmooo** [comment]
It certainly seems to happen on older OS.
However, I do not know the exact conditions and solution now.
I have checked on the following environments.

iPad (2010) with iOS 9.3.5 + Safari.
- 4.0.2: not work
- 4.0.1: not work
- 4.0.0: not work
- 3.0.0-beta.4: work

**Comment by ConstantBrum** [comment]
I'm receiving this error on an iPhone 8 OS v12.2 on BrowserStack and also unable to sign.

`TypeError: function is not a constructor (evaluating 'super()')
SignaturePad @ signature_pad.umd.js:140
dispatch  @  jquery.js:5429`

**Comment by szimek** [comment]
@ConstantBrum can you try version 4.0.1, e.g. from here: https://github.com/szimek/signature_pad/blob/master/docs/js/signature_pad.umd.js ?

**Comment by UziTech** [comment]
This seems to be an issue with specific code if some code is working on versions of safari and some is not. I don't think there is anything we can change in this library to help that.

If you have a reason to believe it is a bug in this libraries code, please create another issue with the code necessary to reproduce the issue.

If you just have a question about why your code isn't working on a certain browser, you would be better off posting the question to https://stackoverflow.com and using the tag `signaturepad`.
