### ISSUE TITLE
Signature very large for some users (doesn't resize)

### ISSUE THREAD

**Issue by Usr5313** [szimek/signature_pad#600]
For most of our users the signature pad works great.  For some users the signature image is very large (doesn't resize) and causes an issue with saving the image file in our application.  Do you know what causes the variation?  See attached for visual...

![SignaturePad_SometimesLargeSignature](https://user-images.githubusercontent.com/31089788/154149308-17b33c7c-afce-4d37-b324-dedb96432298.png)

**Comment by UziTech** [comment]
I think this could be a DPI issue. If saved on a device with high DPI then shown on a device with low DPI the image could be bigger.
