### ISSUE TITLE
Bug: endStroke event does not trigger if mouse movement ends outside of the pad

### ISSUE THREAD

**Issue by ysu2** [szimek/signature_pad#603]
Bug:
The endStroke event does not seem to trigger after a line, if the end of the line is outside of the canvas.
(Edit:
I've now tested it on mobile; it's not a problem, the touch works fine. Only the desktop/mouse combo causes this issue as far as I can tell.)

The code otherwise works in our environment very nicely.

I've tried to set up a jsFiddle, however I have to admit defeat. I've run into an error I can't fix:
"signaturePad.addEventListener is not a function"
https://jsfiddle.net/brandywine/wfp923oa/28/
(I've tried wrapping it into window.onload, to no avail - there must be something I don't know about jsFiddle here)

p.s. If someone could enlighten me what is the problem in jsFiddle, I'd really appreciate it :)

**Comment by UziTech** [comment]
Looks like you were using v3.0.0-beta event listeners were added in v4

https://jsfiddle.net/UziTech/mh1yewfx/1/

**Comment by ysu2** [comment]
Thanks for that!

To add some value, too: I've identified a work-around that works well to mitigate this issue:

canvasElement.addEventListener("mouseout", copyData);

**Comment by UziTech** [comment]
The only problem with mouseout is it will trigger when you leave the canvas even if you come back without lifting up your mouse and continue drawing.

**Comment by ysu2** [comment]
Yeah, where I want to use it - update preview and copy the value out - it's perfectly good.

**Comment by ysu2** [comment]
This was a quick fix, well done guys!
