### ISSUE TITLE
cdnjs outdated

### ISSUE THREAD

**Issue by turktorker** [szimek/signature_pad#609]
Hello - 

Great library. I see that cdnjs.com has this hosted and it is severely out of date (v1.5.3). I've looked at their update process, and it seems after 1.5.3 was tagged the compiled.min (signature_pad.min.js) version of the library was removed from this repo. Therefore it hasn't updated on cdnjs. 

I thought about issuing a pull on cdnjs to update to your docs/js version of signature_pad.umd.js, but that seems like a hack. 

Is there a possibility this could be resolved somehow? 

Here is the settings file for cdnjs (https://github.com/cdnjs/packages/blob/master/packages/s/signature_pad.json).

**Comment by UziTech** [comment]
If there is a way to serve the file from npm you can use the `dist/signature_pad.umd.min.js` file.

**Comment by turktorker** [comment]
Due to a white listed network, we allow self hosted or cdnjs. We'll self host it, but the reason I wrote this is, cdnjs is really out of date. It would seem better to remove it, than have such old libraries being used. 

If the docs/js/signature_pad.umd.js was updated as part of the build the cdnjs settings could grab it.

**Comment by UziTech** [comment]
I meant to serve from cdnjs from npm instead of a git repo. It looks like `type` is set to `"git"` but maybe it could be `"npm"`?

**Comment by agilgur5** [comment]
It seems like OP fixed this themselves in https://github.com/cdnjs/packages/pull/1087, so think this can be closed now

**Comment by turktorker** [comment]
I did update cdnjs, but it looks like someone changed my pull and the map files are missing from the cdn. :-1: 

I was awaiting for cdnjs to update, which it looks like it updated. I'll re-pull and update the mask again to include the map files, unless someone else wants to.

**Comment by agilgur5** [comment]
> I'll re-pull and update the mask again to include the map files

Looks like this was completed in https://github.com/cdnjs/packages/pull/1106
