### ISSUE TITLE
On Resizing the screen, value in the signature pad gets erased. The same is replicable in the examples shared in readme file as well. Is this a known issue? 

### ISSUE THREAD

**Issue by rohitnanda016** [szimek/signature_pad#618]
On Resizing the screen, value in the signature pad gets erased. The same is replicable in the js fiddle examples shared in readme file of this repo as well. Is this a known issue or there is a way to handle this? 

Before Window Resize:
![image](https://user-images.githubusercontent.com/9382592/167546826-46e04b5b-55f2-4c89-a3da-45e38ed1664a.png)

After Window Resize:
![image](https://user-images.githubusercontent.com/9382592/167546902-fb53f1e6-820a-4137-9526-19781b0398e4.png)

**Comment by plocket** [comment]
#32 is the same problem. I've posted a jsfiddle with a solution that works for me. Comment at https://github.com/szimek/signature_pad/issues/32#issuecomment-1406826837.
