### ISSUE TITLE
Pen color change updation to existing signature

### ISSUE THREAD

**Issue by vishnumurthy-nd** [szimek/signature_pad#624]
Dynamic update of color change to the existing drawing in signature pad

If the signature has been drawn in one pen color and later updated to other color. New pen stroke applies that change but the previously drawn signature doesn't inherits current color change.

Can be reproduced as below:
1. Draw signature in black color.
2. Change color to blue.
3. But the previous signature color is not updated.
4. Now, when user starts signing the previously created sign color  won't be updated.
5. Refer the attached image to observe reported behaviour.

![image](https://user-images.githubusercontent.com/103933535/171984249-9115dc5c-77b1-4e19-9a89-f8f201abeb30.png)

**What is the expected behavior?**
Whenever user updates an pen color, the existing signature color must be updated.

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**

Current/Latest version

**Comment by UziTech** [comment]
That is intended behavior. So each stroke can have a different color. You can update all stroke colors with something like:

```js
function updateColor(color) {
  signaturePad.penColor = color;
  const data = signaturePad.toData();
  signaturePad.fromData(data.map(d => {
    d.penColor = color;
    return d;
  }));
}
```

**Comment by vishnumurthy-nd** [comment]
Thanks.. It's working as expeced. Now I can color change of drawing without clearing the previous drawing.
