### ISSUE TITLE
Page is scrolling around when trying to sign

### ISSUE THREAD

**Issue by joanrotbard** [szimek/signature_pad#626]
version: Signature Pad v4.0.3 
iPhone SE using iOS 15.4.1

This issue only seems to occur in the iOS application. The only place I experience the page scrolling up and down while I’m trying to sign is in in the iOS application. 
- There is no specific part of the screen that it happens on. You can touch anywhere, and it will treat your touch like you’ve grabbed the page to scroll. The “ink” still shows up as I’m trying to sign, but because the page also scrolls at the same time with my movement it makes it impossible to write a clear signature.

**Comment by UziTech** [comment]
I don't have an iOS device to debug this but if someone wants to contribute a fix I would be happy to merge it.

**Comment by sinswear** [comment]
I also run into this problem.
My solution is use [iNoBounce.js](https://github.com/lazd/iNoBounce).
Just make sure your `iNoBounce.isEnabled()` is correct.

**Comment by zekeriyaerogluu** [comment]
> I also run into this problem. My solution is use [iNoBounce.js](https://github.com/lazd/iNoBounce). Just make sure your `iNoBounce.isEnabled()` is correct.

Can you give some information on how you use it? my scroll is broken.

**Comment by Hermanverschooten** [comment]
If you add `style="touch-action: none;"` to the element then it will prevent this.

**Comment by UziTech** [comment]
`touch-action: none` should already be set.

https://github.com/szimek/signature_pad/blob/bf6c8777e036141b7425cba78e9bb6ca5cb66058/src/signature_pad.ts#L152

**Comment by Hermanverschooten** [comment]
Ah yes, I had to put it on the surrounding div for it to stop scrolling.
But for me it is not working at all on my iPhone14 Pro, it works on my iPad.
