### ISSUE TITLE
Wrong width and height in viewBox when saving as SVG with `window.devicePixelRatio !== 1`

### ISSUE THREAD

**Issue by solis-eduardo** [szimek/signature_pad#630]
When saving image as SVG, the viewbox gets the wrong size in devices with `window.devicePixelRatio !== 1`, causing the image to be rendered in just a part of the desired space.

I was able to reproduce it here: https://jsfiddle.net/a18yLum9/1/, after downloading the 2 images, its easy to spot the difference in Inkscape.

The expected behavior is for the saved image to be the same, no matter the ratio, as in the 3.0.0-beta.3.

As far as I tested, the only difference between 3.0.0-beta.3 and 4.0.5 relating to this issue is the definition of the variable `header` at `_toSVG`, the former uses `maxX` and `maxY` in the viewBox dimensions, but `this.canvas.width` and `this.canvas.height` are used in the latter.

**Comment by UziTech** [comment]
I think this is actually working as intended. If the dpr is 5 the resulting image should be 1/5 the size it is on the screen. This results in an image that is the same size as on the screen when displayed on a screen with dpr === 1.

**Comment by UziTech** [comment]
#411 seems to have changed this
