### ISSUE TITLE
Resizing/scrolling window 

### ISSUE THREAD

**Issue by besicker** [szimek/signature_pad#639]
When the browser window is resized or scroll up, the previously drawed canvas goes blank:

https://jsfiddle.net/szimek/h80phxyr/

Windows 11 Chrome Versión 103.0.5060.134 (Build oficial) (64 bits)
And Chrome for Android  103.0.5060.129

Thanks.

**Comment by CoderCCM** [comment]
I had the same issue, this thread helped me find the solution: https://github.com/szimek/signature_pad/issues/254

**Comment by besicker** [comment]
Works! Thanks.
