### ISSUE TITLE
How to put multiple signatures on 1 page 

### ISSUE THREAD

**Issue by SGE66** [szimek/signature_pad#64]
How,

I'm not a JS expert and I don't succeed in having more than 1 signature on a page. How can I have multiple var SignaturePad instances ?

Any idea or some short sample code to get me started ?

Thx,

Stefan

**Comment by dpp1983** [comment]
Hi, i'm trying to add multiple signpads. I've used your jsfiddle above and I can draw now. But the clear buttons don't work. Can you show me how to make this work please?

Thank you!
