### ISSUE TITLE
Save status between horizontal and vertical screens

### ISSUE THREAD

**Issue by my2061** [szimek/signature_pad#647]
Hi～

The problem is this: I want to display my signature when the vertical screen is switched to the horizontal screen, and automatically help me flip it. However, after watching the demo, it seems that the horizontal and vertical screens are saved in two states that do not interfere with each other. Is there any relevant API?

**Comment by UziTech** [comment]
The canvas is cleared by the browser automatically on resize so you can add the data back to it with:

```
signaturePad.fromData(signaturePad.toData())
```
