### ISSUE TITLE
Pad does not work when placed behind a Bootstrap 3.x tab pane

### ISSUE THREAD

**Issue by ArthurN** [szimek/signature_pad#65]
See this fiddle: http://jsfiddle.net/fMXH5/

Worse yet, the isEmpty() function returns false (as if there is data there).

Tested with latest Chrome, FF, Safari, and mobile versions of those.

**Comment by ghprod** [comment]
Any update for this?

i also experience the same thing, when open tab, signature canvas not working :(

**Comment by ghprod** [comment]
@ArthurN Thanks for your fiddle, then i came up with this code

```js

// Adjust canvas coordinate space taking into account pixel ratio,
		// to make it look crisp on mobile devices.
		// This also causes canvas to be cleared.
		function resizeCanvas() {
		    // When zoomed out to less than 100%, for some very strange reason,
		    // some browsers report devicePixelRatio as less than 1
		    // and only part of the canvas is cleared then.
		    var ratio	=  Math.max(window.devicePixelRatio || 1, 1)
		    // canvas		= canvas[0]
		    canvas.width 	= canvas.offsetWidth * ratio
		    canvas.height 	= canvas.offsetHeight * ratio
		    canvas.getContext("2d").scale(ratio, ratio)
		}

		function drawSignature() {
			// check for existing signature
			if (inputHidden.val() != '') {
				signaturePad.fromDataURL(inputHidden.val())
			}
		}

$('a[data-toggle=tab]').on('shown.bs.tab', function (e) {
			if (e.target.hash === "#signature") {
		        resizeCanvas()
		        drawSignature()
		    }
		});
```

**Comment by idea-box** [comment]
Hey guys, we finally found our dream sign pad.

But we tried the above and it looks like this still doesnt work for us. Was there any updates on this matter?

Cheers,

**Comment by szimek** [comment]
Like in other Bootstrap related issues with this library, most likely you need to resize canvas *after* it's shown on the screen. When it's inside a hidden tab, modal, popover etc. its size is 0x0 px, so calling resize at that point doesn't work. In all these cases one needs to listen to respective `show.bs.whatever` event and call resize and initialize SignaturePad then.

Please reopen it, if there are still any issues.

**Comment by jesusquev3311** [comment]
HI I got this problem on a bootstrap collapse on a vue Js project, so following the examples above a made a much raw solution and asign the value for the canvas attr width and height when the collapse title is clicked 
<a  data-toggle="collapse" data-target="#target" @click="signatureResize" > title</a>


methods:{
            signatureResize(){
                console.log('resize signature canvas')
                $('canvas').attr('height', '200px')
                $('canvas').attr('width', '936px')
            }
        }
