### ISSUE TITLE
dotSize not used for curves

### ISSUE THREAD

**Issue by creffect** [szimek/signature_pad#651]
Thank you for this great module, it works very fine. I found a small bug, which I fixed already myself, and I wanted to share it with you.

**Do you want to request a feature or report a bug?**

Bug

**What is the current behavior?**

If you specify **dotSize**, it will be respected for dots, but not for curves.

**What is the expected behavior?**

dotSize is considered both for dots and curves

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**

Version 4.0.7

**Potential fix**

In file signature_pad.ts on line 535:

```
   ctx.closePath();
   if (options.dotSize) {
      ctx.lineWidth = options.dotSize
      ctx.strokeStyle = options.penColor
      ctx.stroke()
    }
    ctx.fill();
```

**Comment by UziTech** [comment]
`dotSize` is only for dots. `minWidth` and `maxWidth` are for lines.
