### ISSUE TITLE
Signature pad isnt working in modal

### ISSUE THREAD

**Issue by adam-papp98** [szimek/signature_pad#652]
Signature pad is not working in modal. I use Vue.js where i have at start v-if set on false in canvas and when i change v-if on true canvas show but doesnt work.

![image](https://user-images.githubusercontent.com/78722161/190001055-03e6e978-a3eb-4976-b03e-75ddb6773227.png)
Is there any option how to do it ? I saw last issue with this title but there was not correct answer.

**Comment by UziTech** [comment]
Can you create a repo with a minimal reproduction?

**Comment by adam-papp98** [comment]
[CreateOwnDocument.txt](https://github.com/szimek/signature_pad/files/9564120/CreateOwnDocument.txt)
[Dialog.txt](https://github.com/szimek/signature_pad/files/9564122/Dialog.txt)
I add you my two files here. I hope it will be enought.
I have component in vue Dialog its modal window witch i call in my file CreateOwnDoument.
When i have variable showSignDialog on true at start everythink is ok but when i set it on false at start signiture pad is not working

**Comment by UziTech** [comment]
My guess is that switching it to true creates a new canvas element that doesn't have signature pad attached. Can you initialize signature pad after setting it to true?

**Comment by adam-papp98** [comment]
I found the problem, i used 2 same canvas and they fought each other. So thank you for help.
