### ISSUE TITLE
Property 'prototype' is missing in type 'SignatureEventTarget' but required in type 'EventTarget'

### ISSUE THREAD

**Issue by zornic84** [szimek/signature_pad#659]
Version: Signature Pad v4.0.9
Visual Studio Code 1.72.0

This problem occurs when debugging

Error: node_modules/signature_pad/dist/types/signature_event_target.d.ts:1:22 - error TS2420: Class 'SignatureEventTarget' incorrectly implements interface 'EventTarget'.
  Property 'prototype' is missing in type 'SignatureEventTarget' but required in type 'EventTarget'.

1 export declare class SignatureEventTarget implements EventTarget {
                       ~~~~~~~~~~~~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:5162:5
    5162     prototype: EventTarget;
             ~~~~~~~~~
    'prototype' is declared here.


I've already tried a lot in the tsconfig
tsconfig.json:

"angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": false,
    "strictInputAccessModifiers": false,
    "strictTemplates": false,
    "strictDomEventTypes": false,
    "strictFunctionTypes": false
  }

**Comment by PawelBronka** [comment]
Downgrading @types/node from v18.8.4 to v18.8.3 helped.

**Comment by zornic84** [comment]
Unfortunately, the downgrade did not work either

**Comment by zornic84** [comment]
Nice, without the characters it works again. Thank you very much!
