### ISSUE TITLE
Add ability to get an SVG without encoding to base64 and decoding it again.

### ISSUE THREAD

**Issue by rodrigoaguilera** [szimek/signature_pad#662]
**Do you want to request a feature or report a bug?**
Feature

**What is the current behavior?**
When saving an SVG as a text file, given the current signature_pad API it is mandatory to encode to base64 first.

**Which versions of SignaturePad? 
4.0.10

**What is the expected behavior?**
 I want to be a little more efficient and save the step of encoding to base64 since SVG is already a text format.

I would expose a `toSVG()` method that returns the SVG string and refactor a bit the private `_toSVG` to do the base64 operations.

With jpeg and png I can skip the base64 encoding just using `toBlob` on the canvas.

More info https://css-tricks.com/probably-dont-base64-svg/

What do you think?

**Comment by UziTech** [comment]
I think that would be fine to expose a `toSVG()` function. @szimek any thoughts?

**Comment by UziTech** [comment]
Thanks! I'll take a look at this this weekend.
