### ISSUE TITLE
Suggestion: Add method to convert from `data` to `dataURL`

### ISSUE THREAD

**Issue by ThomasLandauer** [szimek/signature_pad#669]
**Do you want to request a feature or report a bug?**

Feature

**What is the current behavior?**

`.fromDataURL()` loads the picture into the `<canvas>`, but it doesn't update the internal data. Therefore, when you try to draw something *additionally* to this picture, only the new drawing is exported (the old/loaded part is dropped).

However, when using `.fromData()` it *is* possible to "augment" the loaded picture.

**What is the expected behavior?**

It would be nice to have a way to convert between the output of `.toDataURL()` (=SVG etc.) and `.toData()` (=array of points).

**Comment by ThomasLandauer** [comment]
So if you have ust the SVG, it's (rather) not possible to get the array of points back?

But what about the other way (i.e. create the SVG from the array of points)?

Right now, if I export the drawing with `.toData()`, I cannot create the SVG directly from it, right? The only way would be to load the `data` back into the `<canvas>`, then export the `dataURL` from there, right?
So what I'm suggesting would be to make the conversion of `data` => `dataURL` public (which is currently only happening internally, right?)

**Comment by UziTech** [comment]
Moving from data to dataurl is already possible.

```js
signaturePad.fromData(data);
const dataurl = signaturePad.toDataUrl("image/svg+xml");
```

Going the other way is what I think is not currently possible.

**Comment by ThomasLandauer** [comment]
Indeed, great, thanks! :-)
Should I add this as a separate point to https://github.com/szimek/signature_pad#tips-and-tricks ?

**Comment by UziTech** [comment]
The `fromData` method is documented in the [API](https://github.com/szimek/signature_pad#api) section.

**Comment by ThomasLandauer** [comment]
Yeah, but the info that only `.fromData()` will allow you to add something to the existing painting is missing.

**Comment by UziTech** [comment]
The `clear` option is documented there as well.

It seems like you want to take a dataurl (image) and add those points to the internal data so they can be added to and exported again as an svg dataurl. The first step of converting an image to internal data isn't possible.

You can however add the old dataurl, essentially as a background image, draw over it and export the whole canvas as a dataurl again.
