### ISSUE TITLE
width and height of an SVG is wrong because of window.devicePixelRatio

### ISSUE THREAD

**Issue by dnlrbz** [szimek/signature_pad#675]
**What is the current behavior?**
When downloading a canvas with `toSVG()` method, its ratio is incorrect, which leads to cutting off part of the image.

**What is the expected behavior?**
Developer can pass devicePixelRatio to `toSVG()` method as paramter, in order to capture whole canvas independent of its size.
The `window.devicePixelRatio` on my device is 2. That is why the image is cropped. If I set it to 1 through console, the image is correct. 

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**
Signature pad: 4.1.4
Chrome 107.0.5304.110
MacBook Pro 16' 2021

Repro: 
1. open attached minimal Angular project
2. npm install
3. npm run start
4. draw on canvas and press "save"
5. downloaded SVG is cropped and part of image is cut off because of wrong ratio

[untitled.zip](https://github.com/szimek/signature_pad/files/10013726/untitled.zip)

Video with repro: 

https://user-images.githubusercontent.com/34266035/201952774-359ea6ff-3a80-4e4d-9249-cc7acd567421.mov

**Comment by UziTech** [comment]
See [Handling high DPI screens](https://github.com/szimek/signature_pad#handling-high-dpi-screens) in the readme. Your canvas width and height should take into account the `devicePixelRatio`.

set the canvas size with css then use the following to scale the canvas based on the screen DPI.

```js
const ratio =  Math.max(window.devicePixelRatio || 1, 1);
canvas.width = canvas.offsetWidth * ratio;
canvas.height = canvas.offsetHeight * ratio;
canvas.getContext("2d").scale(ratio, ratio);
```

Without scaling the canvas saving the signature as png or jpg will be the wrong size.

If you really just want to change the ratio you can do:

```js
const dpi = window.devicePixelRatio;
window.devicePixelRatio = 1;
const file = new File([this.sig?.toSVG() as string], "signature.svg", { type: "image/svg+xml" });
window.devicePixelRatio = dpi;
```

but I think adding a ratio parameter to `toSVG()` function would encourage the wrong behavior.
