### ISSUE TITLE
After upgrading svgs are saved at a higher dpi/resolution

### ISSUE THREAD

**Issue by johncarl81** [szimek/signature_pad#679]
**Current behavior**

After upgrading from 4.0.7 to 4.1.4 the `toDataURL("image/svg+xml")` seems to save svgs at double dpi.

Input:
![Peek 2022-12-13 18-10](https://user-images.githubusercontent.com/167081/207480254-668ee7c6-9515-410c-88b1-6d2325e9c414.gif)

Output:
![image](https://user-images.githubusercontent.com/167081/207480288-1e1fe1be-6cab-4b0d-8daf-8b914a653f18.png)

**What is the expected behavior?**

The output svg should match the input signature.

**Comment by UziTech** [comment]
See https://github.com/szimek/signature_pad#handling-high-dpi-screens

Make sure you are scaling the canvas by the dpr

**Comment by UziTech** [comment]
You can look at our [demo](http://szimek.github.io/signature_pad/) for a working example.

If you have a repo I can look at with the code I can help find what you are doing wrong.

**Comment by johncarl81** [comment]
Stand by, I'll put together a minimal example...

**Comment by johncarl81** [comment]
Here you go: https://github.com/johncarl81/signature-example

**Comment by davejtoews** [comment]
I'm seeing the exact same thing as @johncarl81. Doesn't seem specific to "image/svg+xml" either. Same problem with png.

**Comment by UziTech** [comment]
Looks like the issue is that you are not setting the width and height with css.

```diff
// App.js
- <div><canvas id="signature-pad" ref={signatureRef} className="signature-pad" width="500" height="150"/></div>
+ <div><canvas id="signature-pad" ref={signatureRef} className="signature-pad" style={{width: "500px", height: "150px"}}/></div>
```

![sig](https://user-images.githubusercontent.com/97994/208016057-e6d1c083-d468-4b12-bede-b070ee222708.gif)

**Comment by johncarl81** [comment]
Ah, that did the trick, thanks @UziTech !
