### ISSUE TITLE
signature_pad not working on iOS

### ISSUE THREAD

**Issue by cmartin6** [szimek/signature_pad#685]
I am using version 4.0.10 of signature_pad, and it seems to not work on iOS?!

**Comment by UziTech** [comment]
Please give a list of steps to reproduce and the code used to setup signature_pad. What version of iOS are you using?

**Comment by sam-malanchuk** [comment]
Yeah I've seen some issue, with iOS 16 specifically, and seems to be on the iPad Mini (5th Gen). Only reproducible sometimes the canvas stays `isEmpty` even with signature on it.

**Comment by UziTech** [comment]
Seems like a safari bug. I don't think there is anything we can change in this library to fix that.

**Comment by Shino161** [comment]
same issue, with IOS 16

**Comment by UziTech** [comment]
@Shino161 did you report this bug to safari?

**Comment by Shino161** [comment]
> @Shino161 did you report this bug to safari?

Yes. Wait for answer yet.
