### ISSUE TITLE
The clear function doesn't seem to work correctly.

### ISSUE THREAD

**Issue by magiclen** [szimek/signature_pad#686]
**Do you want to request a feature or report a bug?**
Bug, perhaps caused by scaling.

**What is the current behavior?**

https://jsfiddle.net/magiclen/35paw6fL/

https://youtu.be/wzfhuZBmv_A

**What is the expected behavior?**

Clear the whole area.

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**

* SignaturePad: 4.1.4
* Firefox 108.0.2 and Chromium 108.0.5359.124

SignaturePad 4.0 also has this issue.

**My Solution**

Use `context.clearRect(0, 0, canvas.width / ratio, canvas.height / ratio);`

https://jsfiddle.net/magiclen/g523x09p/

**Comment by UziTech** [comment]
Your `canvas.width` is constant 960px but your css width is changing. If you change your canvas width to match the css width it will work.

See https://github.com/szimek/signature_pad#handling-high-dpi-screens

**Comment by magiclen** [comment]
I want to **export a fixed-size image** instead of depend on the element size. That is why I use a constant `canvas.width`. Do you have any suggestion?

**Comment by UziTech** [comment]
That isn't what signature_pad is for. It looks like you already have a way to solve it. I would just stick with that.
