### ISSUE TITLE
`dotSize` documentation could be clarified

### ISSUE THREAD

**Issue by plocket** [szimek/signature_pad#688]
_If you have a question, please ask it on [StackOverflow](https://stackoverflow.com/questions/ask?tags=javascript+signature-pad) and use `signature-pad` tag instead of creating an issue._

**Do you want to request a feature or report a bug?**
Feature? Enhancement?

**What is the current behavior?**
This was my original issue: Thick line starts with a big dot and then doesn't stay thick. That wasn't the problem, though. After a lot of experimentation, I found that `dotSize` wasn't just the size of a single dot, it was also the size of the start of the stroke. I needed to make `dotSize` and `maxWidth` the same value (or close to it) in order not to get an ugly oversized dot at the start of my line.

I know that might seem obvious to some. For the others, you're not alone.

_If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via <https://jsfiddle.net> or similar (template: <https://jsfiddle.net/szimek/h80phxyr/>)._

**What is the expected behavior?**
A clear explanation of the side effects of `dotSize` - that it is also the size of the mark at the start of drawing a line.

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**
N/A

Thanks for this great library 🚀

**Comment by UziTech** [comment]
If you want to create a PR with what you want the documentation changed to that would be very helpful. 😁👍

**Comment by plocket** [comment]
Done, thanks
