### ISSUE TITLE
Add `signaturePad.scale(x, y)`

### ISSUE THREAD

**Issue by plocket** [szimek/signature_pad#690]
Scaling the signature lets a developer adjust its size according to the canvas it's in. So if the canvas shrinks or grows, the developer can do the same to the image. I have an example of using such a function at https://jsfiddle.net/j2Lurpd5/1/. I've written a comment showing the code at https://github.com/szimek/signature_pad/issues/32#issuecomment-1406826837. I'll make a PR with the code for a `.scale()` method.

**Do you want to request a feature or report a bug?**
Feature

**What is the current behavior?**
There is no way for a developer to scale the signature without counting on the current internal structure of a SignaturePad. That is, if the interface changes, the developer would need to change their code as well. If SignaturePad handled it, this wouldn't be a concern.

**What is the expected behavior?**
Allow access to a `.scale(x, y)` method so that the developer doesn't have to touch the internal structure of a SignaturePad.

I'm not sure if this is really appropriate for this library. From other comments I've seen, I get the impression that this library is trying to keep its scope very focused. If this change doesn't fit that scope, I understand. If this isn't the right place to solve this, does anyone know of a non-React wrapper library that does this?

**Comment by UziTech** [comment]
I don't think we want to maintain any more helper functions. Editing the data points is how someone should do this. We are trying to keep the scope of this library small to be mostly for drawing the signature. Scaling the signature is out of scope. If you want to maintain another package that has helper functions for signature_pad that could be very useful for some people.
