### ISSUE TITLE
Sometimes getting Partially/Fully Corrupted Images when using toDataUrl("image/jpeg")

### ISSUE THREAD

**Issue by Tarekajaj** [szimek/signature_pad#695]
<img width="320" alt="image" src="https://user-images.githubusercontent.com/11189145/218698397-4438f929-3f11-49fb-ae1b-e00eb6b3f025.png">

We have a page with 2 signature pads, sometimes (1 in 200)  one of the images generated is given partially corrupted (sometimes fully black)

This is completely random, as in we're not able to reproduce it under controlled tests.

Any Idea why this might happens?

**Comment by UziTech** [comment]
The jpg and png convertions are done completely by the browser (see [canvas.toDataURL()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL)). 

So there is nothing we can change in this library to fix it.

**Comment by bgallz** [comment]
Just in case it helps someone else, I was able to fix this issue by using "image/png" instead of "image/jpeg". I was consistently getting completely black images on Chrome (v110.0.5481.104).

**Comment by ykozatskyi** [comment]
> Just in case it helps someone else, I was able to fix this issue by using "image/png" instead of "image/jpeg". I was consistently getting completely black images on Chrome (v110.0.5481.104).

HAve the same issue

**Comment by Tarekajaj** [comment]
@UziTech but this is still not solved

**Comment by UziTech** [comment]
Like I mentioned above this is a browser bug. Nothing we can do. add a bug report to the browser that this is happening on.
