### ISSUE TITLE
Check if SignaturePad is on or off feature request.

### ISSUE THREAD

**Issue by nizans** [szimek/signature_pad#696]
Hello, I was trying to find a way to check if the pad was on or off, didn't find anything that can help with that, so I patched the package and thought it might be a useful feature.
I can open a PR for it if the feature seem to be useful

**What is the current behavior?**
There is no way of telling if the pad is on or off.

**What is the expected behavior?**
A small getter that returns if the pad is on or of, similar to `isEmpty`

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/signature_pad/src/signature_pad.ts b/node_modules/signature_pad/src/signature_pad.ts
index b8a5893..22dd6f1 100644
--- a/node_modules/signature_pad/src/signature_pad.ts
+++ b/node_modules/signature_pad/src/signature_pad.ts
@@ -69,6 +69,7 @@ export default class SignaturePad extends SignatureEventTarget {
   private _lastVelocity: number;
   private _lastWidth: number;
   private _strokeMoveUpdate: (event: SignatureEvent) => void;
+  private _isOn: boolean
   /* tslint:enable: variable-name */
 
   constructor(private canvas: HTMLCanvasElement, options: Options = {}) {
@@ -93,6 +94,7 @@ export default class SignaturePad extends SignatureEventTarget {
 
     // Enable mouse and touch event handlers
     this.on();
+    this._isOn = true
   }
 
   public clear(): void {
@@ -187,6 +189,7 @@ export default class SignaturePad extends SignatureEventTarget {
         this._handleTouchEvents();
       }
     }
+    this._isOn = true
   }
 
   public off(): void {
@@ -212,12 +215,18 @@ export default class SignaturePad extends SignatureEventTarget {
     this.canvas.removeEventListener('touchstart', this._handleTouchStart);
     this.canvas.removeEventListener('touchmove', this._handleTouchMove);
     this.canvas.removeEventListener('touchend', this._handleTouchEnd);
+
+    this._isOn = false
   }
 
   public isEmpty(): boolean {
     return this._isEmpty;
   }
 
+  public isOn(): boolean {
+    return this._isOn
+  }
+
   public fromData(
     pointGroups: PointGroup[],
     { clear = true }: FromDataOptions = {},
```

**Comment by UziTech** [comment]
Just curious why do you need to know if it is on or not?

**Comment by nizans** [comment]
Hey @UziTech ,
I'm building a small react wrapper around the library. In my case I was trying to disable the pad when an initial SVG base 64 was loaded using the `fromDataUrl` method, but I noticed that isEmpty return false which makes sense, but the data array is still empty. so when you use `toDataUrl` on the initial loaded signature you'll get an empty box. 

In my case I needed to turn off the pad anyway until the initial signature was cleared, so if I could check if the pad is off I could also disable the button calls the `toDataUrl` method.

Just thought it would be a small and simple feature to add.

**Comment by UziTech** [comment]
But you are the one turning it on and off so you already know when it is on or off. I don't see any reason for signature_pad to hold that information.

**Comment by nizans** [comment]
In my case I'm sharing the instance of the pad between components, so tracking when it was turned off and on is defiantly possible, but a bit more complicated then getting that info directly from the instance.

I think it could be helpful having it in the library.
Thank you for you're response

**Comment by UziTech** [comment]
We are trying to keep this library small and focused on the drawing of the signature. Anything that's can be handled outside the library should be. If we added every little feature that would by nice to have people would have to include a lot of code that most people will never need.

**Comment by UziTech** [comment]
Ideally there could be a wrapper around this library that handles all of those little things.

**Comment by nizans** [comment]
@UziTech 
Understood, I'll close the PR

Thanks for the response and for keeping the library clean;)
