### ISSUE TITLE
Flickering signature / missing parts

### ISSUE THREAD

**Issue by lanort** [szimek/signature_pad#697]
Just tried signature pad for the first time on my pixel 6 in chrome. I just used the demo site. 

Parts of the signature are flickering during signing. And after I lost my finger parts are also missing.

See video here: [https://youtu.be/j9COoKAu91o](https://youtu.be/j9COoKAu91o)

**Comment by UziTech** [comment]
That seems like a browser issue. I recommend filing a bug with the browser. There is nothing we can do to fix it in this library.
