### ISSUE TITLE
Add ability to retrieve SVG element instead of string.

### ISSUE THREAD

**Issue by rodrigoaguilera** [szimek/signature_pad#706]
## Feature request

**What is the current behavior?**
I can use `toSVG()` to retrieve a SVG string

**What is the expected behavior?**
A new encoderOption named `asElement` for `ToSVGOptions` with a default of false. When set to true instead of a SVG string the element is returned.

In my use case I want to add metadata to the SVG with info like the background and and the signature_pad json data. That way I can read it back later and load all the source info so features like undo work even when you load a previous SVG.
Currently I parse the SVG string back to an js Element I can manipulate easily.

Should be fairly easy to implement changing the line
```js
    return svg.outerHTML;
```
to
```js
    return asElement ? svg : svg.outerHTML;
```
but I'm currently away from my laptop.

**Comment by UziTech** [comment]
I don't want to add a whole bunch of options. I think if it is something that is easy to do without an option we shouldn't have an option for it.

If this is a common thing we could change toSvg to return the svg element instead of the string in a major version, but I think more people are looking for a string than an element.

**Comment by rodrigoaguilera** [comment]
Let me show the code to process the string back into an element (with the metadata part included)
```js 
            let svgString = signaturePad.toSVG();
              const parser = new DOMParser();
              const svgXMLDocument = parser.parseFromString(svgString, 'image/svg+xml');
              const svgElement = svgXMLDocument.documentElement;
              const metadata = svgXMLDocument.createElementNS('http://www.w3.org/2000/svg', 'metadata');
              const rdf = svgXMLDocument.createElementNS('http://www.w3.org/1999/02/22-rdf-syntax-ns#', 'rdf:RDF');
              const sourceCode = svgXMLDocument.createElementNS('http://schema.org/','schema:SoftwareSourceCode');
              const sourceData = svgXMLDocument.createElementNS('http://schema.org/','text');
              sourceData.textContent = JSON.stringify(signaturePad.toData());
              sourceCode.appendChild(sourceData);
              rdf.appendChild(sourceCode);
              metadata.appendChild(rdf);
              svgElement.insertBefore(metadata, svgElement.firstChild);
              svgString = new XMLSerializer().serializeToString(svgElement);
            
```

I want to avoid the re-parsing of the SVG string into an element that can be easily manipulated.

I include the part about the metatada because I want save the signature in a lossless format that can be edited later since I noticed the SVG saved is not 100% faithful to the original.

SVG rendered by firefox:
![svg](https://user-images.githubusercontent.com/655187/224487858-324e5afc-5575-4c75-a4e1-8eef378ff7ee.png)


Canvas
![image](https://user-images.githubusercontent.com/655187/224487749-561f1135-dd2f-48c9-b80d-bcc269695704.png)
