### ISSUE TITLE
Signature pad is not working with rotate/scale of css property

### ISSUE THREAD

**Issue by KostadinGorgiev** [szimek/signature_pad#713]
If I set css property for scale, rotate to the canvas or it's parent, it doesn't calculate the position correctly.
How should we fix this issue?

**Comment by UziTech** [comment]
Instead of setting scale or rotate css properties just set the correct width and height with css and use [this tip](https://github.com/szimek/signature_pad#handling-high-dpi-screens) to resize the canvas.
