### ISSUE TITLE
Chrome 112.X.X for Android, destroy Signature Pad

### ISSUE THREAD

**Issue by lgeronimov** [szimek/signature_pad#714]
I updated my version of Chrome to the latest and when I try to paint on the signature pad, the pad flashes and the signature is erased intermittently.

Please help me and thanks a lot.

**Comment by UziTech** [comment]
Sounds like a chrome issue. You should file a bug report for chrome.

**Comment by Offbeatmammal** [comment]
was seeing a similar behaviour. added a `window.onorientationchange = resizeCanvas();` and removed the standalone call to `resizeCanvas()` that I had on document ready and it now behaves (looks like it is firing on `orientationchange` when the page first renders)
