### ISSUE TITLE
Signature  pad  cursor issue on mac chrome.

### ISSUE THREAD

**Issue by k2Sachin** [szimek/signature_pad#717]
I am using your plugin and test with mac chrome. the cursor not moving fine and typing speed it is too slow compare to normal chrome. I am using 4.0 version with jquery 3.5.1

**Comment by UziTech** [comment]
Can you share the code so we can try to reproduce it?
Can you share a video of it happening?

**Comment by k2Sachin** [comment]
Hello,
https://fausto.morello.me/ifratest.html : Open this iframe url and paste
this link
https://dev.wenoexchange.com/en/newrx/CompletePendingRxAPI?msgid=TEST_RX_13Oct_005&userId=6180

Check on macbook chrome. Please tell me what I am missing. It is working
fine on windows browsers and my android phone.

**Comment by UziTech** [comment]
I can't find anything wrong. We have fixed a few things since v4.0.0. You can try updating to the latest version and see if it is fixed. Otherwise this is most likely a browser issue.

**Comment by k2Sachin** [comment]
Signature cursor so slow to move on chrome and on safari 11 version on Mac
Book not working. It is very easy to say it is browser issue.

**Comment by k2Sachin** [comment]
Please look at the calibration of signatures when ordering prescriptions.
When we are on the signature page, the cursor/mouse/pen does not line up
with writing and the display moves rapidly to the right of the cursor.
Signing and predicting where the cursor will appear is impossible!


that kind of issue we are facing

**Comment by UziTech** [comment]
That sounds like a DPI issue. Your mac is probably higher DPI than your other devices. try https://github.com/szimek/signature_pad#handling-high-dpi-screens

**Comment by k2Sachin** [comment]
If there is any DPI issue then it does not work with macbook 12.6 and
safari 16.4.1. I am getting issues with older versions like safari 11.0.2.
