### ISSUE TITLE
Only Dots on Canvas

### ISSUE THREAD

**Issue by MarkusDeeken** [szimek/signature_pad#718]
Some of our users report problems while drawing a signature. Apperently there are only dots but not a connected line. It only happens on certain devices (IPad 9 Generation and Fujitsu Stylistic Q5010). We already implemented the code for handling high DPI screens but it didnt help. I'm afraid i cant give any more information since we cannot reproduce the issue with our test devices.

Do you have any idea what could be the problem?

**Comment by UziTech** [comment]
The only reason I can think of that happening is if the stylus they are using is malfunctioning. If it is sending multiple pointerdown and pointerup events it would create many dots instead of a line.

**Comment by kantivekariya** [comment]
I'm also facing the same issues to show dots on canvas 

![image](https://github.com/szimek/signature_pad/assets/29365336/0d2dc162-631c-442e-bf82-b2ff319d28a1)

**Comment by kantivekariya** [comment]
Hello, @UziTech this issue also occurred to me on the `Chrome` browser but it's working fine on the `Firefox` browser.

**Comment by MarkusDeeken** [comment]
Hi, sorry for the late response. We finally got a test device. A Fujitsu with Windows. 
Apparently whenever we try to swipe on the tablet, its activating the swipe back feature of the browser. Even if we swipe directly on the signatur pad. But the problem doesnt happen in our smaller test app, only in our actual app. Even though both are written in Angular and implement the signaturpad the same way. 
Any idea what could the cause fo this? Some setting maybe?

**Comment by MarkusDeeken** [comment]
Can be closed.

The error was in our own Framework which didnt updates dependencies correctly, so we where working with an older version of the signatur_pad. After a sucessfull update it works as expected.
