### ISSUE TITLE
Buttons unresponsive immediately after fast strokes in Chrome Android

### ISSUE THREAD

**Issue by basuneko** [szimek/signature_pad#723]
**Do you want to request a feature or report a bug?**

Bug

**What is the current behavior?**

I'm having a weirdly specific issue. After the user makes a fast gesture quickly lifting the finger, the captured pointer seems to not get released. This means that buttons etc won't react to clicks until the user clicks somewhere else. Unfortunately this seems to be the way users often draw their signatures.

I've created a [minimal reproduction example](https://codesandbox.io/s/cranky-ioana-hchq2z) but the issue occurs even in the official demo as well.

I've tried monitoring events on the canvas. This is what I'm seeing when the issue occurs:
```
pointerover        PointerEvent {isTrusted: true, pointerId: 49, width: 23, height: 23, pressure: 1, …}
pointerenter       PointerEvent {isTrusted: true, pointerId: 49, width: 23, height: 23, pressure: 1, …}
pointerdown        PointerEvent {isTrusted: true, pointerId: 49, width: 23, height: 23, pressure: 1, …}
touchstart         TouchEvent {isTrusted: true, touches: TouchList, targetTouches: TouchList, changedTouches: TouchList, altKey: false, …}
gotpointercapture  PointerEvent {isTrusted: true, pointerId: 49, width: 23, height: 23, pressure: 1, …}
pointermove        PointerEvent {isTrusted: true, pointerId: 49, width: 23, height: 23, pressure: 1, …}
pointermove        PointerEvent {isTrusted: true, pointerId: 49, width: 23, height: 23, pressure: 1, …}
touchmove          TouchEvent {isTrusted: true, touches: TouchList, targetTouches: TouchList, changedTouches: TouchList, altKey: false, …}
pointermove        PointerEvent {isTrusted: true, pointerId: 49, width: 23, height: 23, pressure: 1, …}
touchmove          TouchEvent {isTrusted: true, touches: TouchList, targetTouches: TouchList, changedTouches: TouchList, altKey: false, …}
pointermove        PointerEvent {isTrusted: true, pointerId: 49, width: 23, height: 23, pressure: 1, …}
touchmove          TouchEvent {isTrusted: true, touches: TouchList, targetTouches: TouchList, changedTouches: TouchList, altKey: false, …}
pointermove        PointerEvent {isTrusted: true, pointerId: 49, width: 23, height: 23, pressure: 1, …}
touchmove          TouchEvent {isTrusted: true, touches: TouchList, targetTouches: TouchList, changedTouches: TouchList, altKey: false, …}
pointermove        PointerEvent {isTrusted: true, pointerId: 49, width: 23, height: 23, pressure: 1, …}
touchmove          TouchEvent {isTrusted: true, touches: TouchList, targetTouches: TouchList, changedTouches: TouchList, altKey: false, …}
pointerup          PointerEvent {isTrusted: true, pointerId: 49, width: 1, height: 1, pressure: 0, …}
lostpointercapture PointerEvent {isTrusted: true, pointerId: 49, width: 1, height: 1, pressure: 0, …}
pointerout         PointerEvent {isTrusted: true, pointerId: 49, width: 1, height: 1, pressure: 0, …}
pointerleave       PointerEvent {isTrusted: true, pointerId: 49, width: 1, height: 1, pressure: 0, …}
touchend           TouchEvent {isTrusted: true, touches: TouchList, targetTouches: TouchList, changedTouches: TouchList, altKey: false, …}
```

I wonder if it's actually a bug in Chrome Android - it doesn't happen in Firefox Android. On iPad it doesn't seem to happen in neither Chrome nor Safari. But unfortunately I have not been able to find anything relevant.

**Reproduction**

It's hard to describe this with words so I've made a video as well.

https://github.com/szimek/signature_pad/assets/505411/87dc49ff-2e3c-4dd8-b129-9e33e757c6fa

1. Open the demo page
2. Draw a line quickly lifting the finger; make sure the finger doesn't leave the canvas
3. Click the clear button - the button doesn't react to the click
4. Click the clear button again - the signature pad gets cleared

**What is the expected behavior?**

The button reacts after the first click and clears the signature pad.

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**

The issue occurs with these:
Chrome Android 114.0.5735.130
Signature Pad 4.1.5, 3.0.0.beta4
I use Pixel 7 but we've had reports with other android devices

No issues:
* Android 
  * Firefox 114.1.1
* iPad OS 
  * Chrome 114.0.5735.124
  * Safari
* Desktop
  * Chrome 114.0.5735.133
  * Firefox 114.0.1

**Comment by basuneko** [comment]
Apologies, I see someone has reported a similar issue https://github.com/szimek/signature_pad/issues/635

I hope the extra details I have provided help to investigate the issue further

**Comment by UziTech** [comment]
Like I mentioned in the related issue. This seems to be intended behavior on Android trying to avoid accidental clicks. I don't see anything we can change in this library to fix that.

Your best bet is to report this bug to chrome.

**Comment by basuneko** [comment]
Thank you, I will raise a bug with Chrome 👍

**Comment by capc0** [comment]
@basuneko can you please link to the chrome bug ticket? I am also interested in a solution for this. Thank you.
