### ISSUE TITLE
TypeError: Cannot convert null value to object

### ISSUE THREAD

**Issue by davidasconsulting** [szimek/signature_pad#729]
After upgrading my Expo app to
"expo": "^49.0.0"
"react-native": "0.72.3",
"react-native-signature-pad-v2": "1.1.0"

I get the error:

TypeError: Cannot convert null value to object

This error is located at:
    in Unknown (created by SignaturePad)
    in SignaturePad (created by SignatureScreen)
    in RCTView (created by View)
    in View (created by SignatureScreen)
    in SignatureScreen (created by Connect(SignatureScreen))
    in Connect(SignatureScreen) (created by SceneView)
    in StaticContainer

When loading the signature pad.

How do I solve this?

**Comment by UziTech** [comment]
If you create a minimal reproduction repo I can try to help debug it.

**Comment by UziTech** [comment]
It looks like this might be hard for me to debug since react-native-signature-pad-v2 uses version 1.3.2 of signature_pad. You can create an issue on their repo.

https://github.com/iJimmyWei/react-native-signature-pad-v2/blob/master/injectedJavaScript/signaturePad.js

**Comment by davidasconsulting** [comment]
Hi,

Thank you for your response.  Are there any breaking changes between 1.3.2
and latest?  Or can I upgrade that library to use your latest code?

Thanks

David

**Comment by UziTech** [comment]
There are some breaking changes around events but for basic usage you should be able update without a problem. See the [changelog](https://github.com/szimek/signature_pad/blob/master/CHANGELOG.md#400) for more details.
