### ISSUE TITLE
Console error "Unable to preventDefault inside passive event listener invocation."

### ISSUE THREAD

**Issue by wslaghekke** [szimek/signature_pad#731]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**

- Use signature pad in Chrome 116
- Open the inspector
- After releasing the mouse button when drawing a line the console shows an error: `Unable to preventDefault inside passive event listener invocation.`

**What is the expected behavior?**
Warning should not occur, this happens because by default listeners are passive and passive listeners are not allowed to call `event.preventDefault()` inside their callbacks. 
A fix could be removing the preventDefault (if that is possible, i'm not sure why we are preventing the default), or marking the listener as not passive by passing `{passive: false}` as the second argument in the call to `addEventListener`

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**
Version 4.1.6 of SignaturePad, this issue will also affect earlier versions, it is caused by modern browsers defaulting to passive listeners.

**Comment by UziTech** [comment]
I don't see that error when I use chrome 116 on our [demo](https://szimek.github.io/signature_pad/).

If you want to create a PR to explicitly use passive: false on the event listeners, that would be very helpful. 😁👍

**Comment by ZhipengZeng** [comment]
@wslaghekke  Hi there, what's your workaround/solution for this issue? Thanks in advance
