### ISSUE TITLE
Loading fromDataUrl and fromData together?

### ISSUE THREAD

**Issue by tigrenok00** [szimek/signature_pad#732]
Hi, 
I have an image which should appear in the signature pad (like background) and **also be part of the export** to dataUrl after the drawing. I've transformed this jpg to dataUrl and load it initially into the component. The issue is that I also want to support undo action on the drawing, today what I do is:
```
undoDrawing() {
    let data = this.signaturePad?.toData();
    if (data) {
      data.pop();
       this.signaturePad.fromData(data);
      }
  }

```
The problem in this approach is that the initial image loaded with fromDataUrl will always be lost.
What can I do to support this? Is there a way to both apply load from dataUrl and then fromData on top of it?

**Comment by UziTech** [comment]
When you undo you will need to
- clear the canvas
- add the image back
- use `fromData(data, {clear: false})` to redraw the data without clearing the image

**Comment by smalljop** [comment]
Is there any specific code example?
