### ISSUE TITLE
Store signature data as data:image/svg+xml;base64

### ISSUE THREAD

**Issue by PSchreuder** [szimek/signature_pad#74]
I love this simple signature library! Thanks! There's one thing I really want to implement, and that's storing the signature data as svg / data:image/svg+xml;base64. So I can store the full-vector signature in my SQL database, and use it for high quality PDF's/print.

What's the best way to retrieve the signature in data:image/svg+xml;base64?

**Comment by yhurynovich** [comment]
Hi, I would like to sponsor SVG functionality (svg export). Can you please estimate cost of building of this function for me?

**Comment by BioPhoton** [comment]
I also need SVG export! 
@szimek are you interested in building this functionality?

**Comment by szimek** [comment]
I don't think I'll have enough time to do it. It shouldn't require that many changes though: 
1. store all points in memory, instead of just the 4 last ones
2. generate SVG from all these points using native Bézier curves (i.e. `<path d="Mx,y C...">`); I have no idea how one can draw Bézier curves with variable width in SVG :/

If anyone wants to prepare a PR, it would be awesome.

**Comment by BioPhoton** [comment]
Hi,
i guess an easy solution for implementing this feature would be to parse the canvas after drawing with a canvas to svg lib.

I did some quick tests with following libs:
- https://github.com/gliffy/canvas2svg
- https://github.com/kangax/fabric.js

With the canvas2svg lib i got propper output but the lines are not visible anymore

I replaced 
https://github.com/szimek/signature_pad/blob/master/signature_pad.js#L53
with
 this._ctx = new C2S(500,500);

With fabric i got also svg output but i guess i use it in a wrong way.

@szimek do you think this would be a good solotuin without much work.

**Comment by szimek** [comment]
It might be, but it would be awesome if somebody actually created a working prototype :) I'm afraid that the way I'm drawing lines (using filled circles) might not work very well with SVG unless some post-processing is used to smooth lines out.

If it doesn't work properly, it might be easier to prepare SVG by hand, but only if one assumes that all curves have the same width and just use the [C syntax](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d#Curveto).

**Comment by jackspirou** [comment]
@szimek I submitted a PR for saving as svg: https://github.com/szimek/signature_pad/pull/173

feedback welcome

**Comment by mhbu50** [comment]
1+

**Comment by BioPhoton** [comment]
THX to @jackspirou for this great pr!

**Comment by oliverjanik** [comment]
merge?

**Comment by szimek** [comment]
For anyone interested in SVG feature - I've just pushed a new version to [draw-signature-from-point-data branch](https://github.com/szimek/signature_pad/tree/draw-signature-from-point-data) (you can find built files in `dist` folder now) that supports generating SVG files when you pass `'image/svg+xml'` to `toDataURL` method. It would be awesome if you could check it out and see if there are any errors.

**Comment by jackspirou** [comment]
Thanks @szimek, I closed out my PR in favor of the draw-signature-from-point-data branch since it has some refactoring as well.

**Comment by szimek** [comment]
I've just release 1.6.0-beta.1 with this feature. This version is already used by https://szimek.github.io/signature_pad. Let me know if you find any issues.

**Comment by chitgoks** [comment]
i tried it but it still returns  data:image/png instead of svg

**Comment by muniom** [comment]
I seem to have an issue with SVG in IE.

Opening http://szimek.github.io/signature_pad/ in IE, and entering "signaturePad.toDataURL("image/svg+xml").length" into the console give me 186.

Drawing anything in the signature pad does not seem to generate a different output, always 186.

Chrome behaves as expected.

**Comment by szimek** [comment]
@muniom Which version of IE? Do you get any errors in dev console?

**Comment by chitgoks** [comment]
This only happens in IE11. Bing works ok

the reason why length is the same is that the path tags are undefined. this is the resulting string

<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 430 150">undefined</svg>

by the way. in Firefox it will not be visible because it requires the width and height attribute as well so i had to manually add the output svg.

**Comment by szimek** [comment]
@chitgoks Could you create a new issue for this IE and Firefox bug? It will be easier for me to handle it this way.

**Comment by chitgoks** [comment]
@szimek  will do
