### ISSUE TITLE
Can we have an indicator to know if the signature pad is pristine or dirty?

### ISSUE THREAD

**Issue by Nami2012** [szimek/signature_pad#748]
Requesting a feature

Right now we don't have any thing to know if the signature pad is pristine or touched. For my current use I can patch it with a variable but it would be cool to have a function for the same in signature pad as we have in angular formcontrol to know if the signature pad is dirty.

**Comment by Nami2012** [comment]
Yes, I am aware of the IsEmpty() function. But that function wouldn't  be able to tell apart if a signature-pad hasn't been touched by user and if its touched and deleted.
The specific use case for checking if the pad is pristine is when you have to show the empty validation for signature-pad. I have a specific use case where I have to check if the signature pad has not been touched by the user at all during validation. I didn't find any function for this. 
Let me know if you need more info on my use case.

**Comment by UziTech** [comment]
You could add a listener to the beginStroke event and set a Boolean.

**Comment by Nami2012** [comment]
Yes I have done the same for my use case. But I was wondering if we could have a isDirty variable inherently in the signature pad just like the one available in angular formcontrol. 
If this is not possible, Ill close my issue.

**Comment by UziTech** [comment]
Since this can easily be done with events I don't see a reason to add a method.

Honestly I don't understand why this is useful. If the user makes a mark than deletes it, it is the same thing as them never making a mark so isEmpty should work

**Comment by Nami2012** [comment]
Cool. Thanks for the clarification. Closing this thread.
