### ISSUE TITLE
The Troke drawing doesn't look good in the html canvas

### ISSUE THREAD

**Issue by nhonnh2** [szimek/signature_pad#754]
![signaturecanvas](https://github.com/szimek/signature_pad/assets/85781206/41fb7239-8ec0-49d2-91b2-605ebb63349d)

I have an option for getStroke but the resulting stroke doesn't feel smooth.

```
const options = {
  size: 3,
  thinning: 0.2,
  smoothing: 1,
  streamline: 0.1,
  easing: (t) => t,
  start: {
    taper: 0,
    easing: (t) => t,
    cap: true,
  },
  end: {
    taper: 10,
    easing: (t) => t,
    cap: true,
  },
};

```
My canvas have
width={440} ; height={220}

Can you help me make it more beautiful?

**Comment by UziTech** [comment]
What version of signature_pad are you using?

**Comment by nhonnh2** [comment]
Sorry, I got the wrong repository

**Comment by nhonnh2** [comment]
I will close issues

**Comment by nhonnh2** [comment]
I will close issues
