### ISSUE TITLE
Signature Pad Break if container element is rotated

### ISSUE THREAD

**Issue by optikool** [szimek/signature_pad#76]
Hi,

I'm trying to use Signature Pad in my app, but if the containing div, which is a modal dialog is rotated using CSS Signature Pad break. On mobile, the layout needs to be locked to Portrait because of the layout of the elements and because of design specs. When the signature capture is required, it is opened in a Modal box and the div container of this modal is rotated so that the signature capture is viewed in landscape mode so there is enough room for the signature. However once this is done, when I try to write a signature, the drawing begins either off screen or opposite of the input. And in some instance it draws in the opposite direction. Inspecting the element will show the canvas horizontal to the main app or if and am able to rotate the canvas, the signature still tries to draw horizontally instead of following the path that I am drawing which is vertically. Is there anything I can do to make this api follow the path I am drawing no matter what direction or is this a limitation that can't be solved.

I have tried rotating the canvas using CSS and also using context.rotate. 

Thanks

**Comment by bryanpotterdesign** [comment]
The .clear() method doesn't work after doing this. It will only clear a portion of the canvas. Any fix you can think of?

**Comment by pot-code** [comment]
> The .clear() method doesn't work after doing this. It will only clear a portion of the canvas. Any fix you can think of?

try clearing the canvas use canvas API:

```js
function onReset() {
  const ctx = canvas.getContext('2d')
  ctx.clearRect(0, 0, canvas.height, canvas.width) // swap the height and width
}
```
