### ISSUE TITLE
how to save image after editing from canvas to database in livewire?

### ISSUE THREAD

**Issue by Frman-Husein** [szimek/signature_pad#764]
how to save image after editing from canvas to database in livewire?

**Comment by UziTech** [comment]
not sure what livewire is but you should look at the docs at https://github.com/szimek/signature_pad#handling-data-uri-encoded-images-on-the-server-side

**Comment by Frman-Husein** [comment]
It is mean i using in laravel, in. Canvas i see image but how save this
image in database

**Comment by liamja** [comment]
Hey @Frman-Husein 

I found this great example of how to do achieve this with Alpine and Livewire:

https://gist.github.com/jonneroelofs/a4a372fe4b55c5f9c0679d432f2c0231

Basically, you can wrap signature_pad in an alpine.js instance, then you can wire:model the state of the canvas with Livewire.
