### ISSUE TITLE
Android app open Amap, can not get positioning, error information as follows, hope to get expert advice

### ISSUE THREAD

**Issue by yulili656** [szimek/signature_pad#779]
Android app open Amap, can not get positioning, error information as follows, hope to get expert advice：

[JS Framework] Failed to execute the callback function:
 TypeError: Cannot read property 'points' of undefined
10:14:06.314 reportJSException >>>> exception function:__WEEX_CALL_JAVASCRIPT__, exception:JavaScript execute error!Uncaught TypeError: Cannot read property 'points' of undefined
 at  (/__uniappchooselocation.js.nvue:1:28376)

**Comment by yulili656** [comment]
Thank you very much for your feedback

**Comment by UziTech** [comment]
What version of signature_pad?
