### ISSUE TITLE
moblie button issue

### ISSUE THREAD

**Issue by myucel8108** [szimek/signature_pad#783]
_If you have a question, please ask it on [StackOverflow](https://stackoverflow.com/questions/ask?tags=javascript+signature-pad) and use `signature-pad` tag instead of creating an issue._

**Do you want to request a feature or report a bug?**
report a bug

**What is the current behavior?**
When I turned on the https://stackoverflow.com/questions/ask?tags=javascript+signature-pad site on mobile and tested it, the click event didn't work at first, but next time I pressed it again, I found a behavior that works and I'm expecting to use the touch event as a solution, but I want to find an exact solution.

_If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via <https://jsfiddle.net> or similar (template: <https://jsfiddle.net/szimek/h80phxyr/>)._
@click event -> @touchend event

**What is the expected behavior?**

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**
There is a problem with the mobile device.

**Comment by UziTech** [comment]
Can you provide code so we can reproduce this?

**Comment by myucel8108** [comment]
I try this site
https://codesandbox.io/s/n5qjp3oqv4?resolutionWidth=320&resolutionHeight=675

**Comment by UziTech** [comment]
What is the problem? It seems to work perfectly for me

**Comment by UziTech** [comment]
It looks like you are using vue-signature-pad which is using an old version of signature_pad if you need help you should create an issue at https://github.com/neighborhood999/vue-signature-pad

**Comment by UziTech** [comment]
@gaetanlgce I noticed when you press the clear button the first couple of times the button changed color (slightly darker), but it didn't change after that. My guess is that it is your browser that is causing the debounce to prevent accidental clicks. If signature_pad doesn't actually receive a click event from the browser we can't know that the user clicked the button. 

Maybe there is a browser or phone setting that can help you.
