### ISSUE TITLE
Offset when second click

### ISSUE THREAD

**Issue by zyl54586** [szimek/signature_pad#791]
When I'm drawing on the canvas, the curve on the canvas follows the mouse perfectly when I click for the first time;but when I click for the second time, the curve produced on the canvas is offset from the mouse position. 
Why does this happen, and how can it be solved?

**Comment by UziTech** [comment]
can you create a [jsfiddle](https://jsfiddle.net) or [codepen](https://codepen.io) that can reproduce this?

**Comment by zyl54586** [comment]
I found it's caused by CSS:

```
#signature {
    width: 6.5rem;
    height: 2.5rem;
    margin-left: 0.25rem;
    margin-top: 0.3rem;
    background-color: #f3f3f4;
}
```

Why?

**Comment by UziTech** [comment]
If you can create a way for us to reproduce it we can try to help debug it. Can you try to create a div around the canvas an add the styles to that instead?

**Comment by UziTech** [comment]
Canvases have two widths and heights. They have CSS width and height and they have canvas width and height . If those are not the same, strange things can happen. See https://github.com/szimek/signature_pad#handling-high-dpi-screens

**Comment by zyl54586** [comment]
thanks for your reminder
