### ISSUE TITLE
We require the signature to not overflow and break, need a continuous signature, is it possible to give an option if we need a smooth signature or broken signature in case of overflow 

### ISSUE THREAD

**Issue by digioAbhi** [szimek/signature_pad#795]
_If you have a question, please ask it on [StackOverflow](https://stackoverflow.com/questions/ask?tags=javascript+signature-pad) and use `signature-pad` tag instead of creating an issue._

**Do you want to request a feature or report a bug?**

**What is the current behavior?**

_If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via <https://jsfiddle.net> or similar (template: <https://jsfiddle.net/szimek/h80phxyr/>)._

**What is the expected behavior?**

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**

**Comment by UziTech** [comment]
So you don't want the signature to look like how they drew it, you just want to add lines between marks for them?

**Comment by digioAbhi** [comment]
Yes, basically the behaviour before 5.0.1 
like 4.2.0 
overflow should be joined, consistent signatures 
https://github.com/szimek/signature_pad/pull/765

older behaviour is what is required by me

**Comment by UziTech** [comment]
Why would you want to save a signature that is not actually what they drew?

**Comment by UziTech** [comment]
I don't think we will be reintroducing that bug. https://xkcd.com/1172/

You can use v4 if you still want that bug, or you can change the data to be within the bounds of the canvas on endStroke if you want.

Something like:

```js
signaturePad.addEventListener("endStroke", () => {
  const data = signaturePad.toData();
  if (data && data.length > 0) {
    const width = canvas.offsetWidth;
    const height = canvas.offsetHeight;
    const lastPoints = data[data.length - 1].points;
    for (let i = 0; i < lastPoints.length; i++) {
      if (lastPoints[i].x < 0) {
        lastPoints[i].x = 0;
      }
      if (lastPoints[i].x > width) {
        lastPoints[i].x = width;
      }
      if (lastPoints[i].y < 0) {
        lastPoints[i].y = 0;
      }
      if (lastPoints[i].y > height) {
        lastPoints[i].y = height;
      }
    }
    data[data.length - 1].points = lastPoints;
  }
  signaturePad.fromData(data);
});
```

![signaturepad_bug](https://github.com/user-attachments/assets/cef5db0d-987f-4d48-959a-027f3f64b43d)

**Comment by digioAbhi** [comment]
Thank you 
works fine for me
