### ISSUE TITLE
Using .fromDataURL() sizing problem

### ISSUE THREAD

**Issue by MarcGodard** [szimek/signature_pad#81]
Hi When I use .fromDataURL() to load a signature that was created in the same sized canvas using this awesome library, the image dose not size correctly and is 1/4 of the size.

I am not sure if this is the library or not, but I resize the canvas before originally signing and before loading the signature in memory.

Is this some problem in my logic or has anyone seen this before?

**Comment by onelifemedia** [comment]
For anyone that happens to come across this issue, I figured out what I was doing wrong.

Before you put the data in, using `.fromDataURL(data)`, to need to make sure that you properly scale the canvas:

```javascript
      function resizeCanvas(canvas) {
        var ratio =  window.devicePixelRatio || 1;
        canvas.width = canvas.offsetWidth * ratio;
        canvas.height = canvas.offsetHeight * ratio;
        canvas.getContext('2d').scale(ratio, ratio);
      }

      resizeCanvas(canvas);
```

**Comment by demo-igor** [comment]
To make the same image size you can add options
`signaturePad.fromDataURL(data, {width: 100, height: 100})`
width, height should be the same as canvas size
More details:
https://github.com/szimek/signature_pad/blob/master/src/signature_pad.ts
