### ISSUE TITLE
signaturePad size problem when switching tablet orientation

### ISSUE THREAD

**Issue by danturi** [szimek/signature_pad#86]
I tested signature_pad  on a Samsung Galaxy Note Tablet (2014 edition) and here is what I have noticed. When I switch from landscape to portrait orientation everything is ok, but the problem is that when I return to landscape orientation the size is wrong and the canvas area goes out of the screen.

![screenshot_2014-12-28-13-20-50](https://cloud.githubusercontent.com/assets/8112673/5563912/0c4948be-8e9d-11e4-9bec-8b4561c33144.png)

**Comment by rdetert** [comment]
Try settings `.m-signature-pad` to `position: fixed` instead of `position: absolute`
