### ISSUE TITLE
The signature pad re-renders while changing portrait/landscape mode.

### ISSUE THREAD

**Issue by dahal** [szimek/signature_pad#91]
Hi,

I have a html5 mobile web app, trying to use this signature_pad. While I sign on portrait mode and change the orientation to landscape, or vice-versa, the signature clears. Any solution to this problem? 

![image1](http://s11.postimg.org/cb7omcf43/potrait.png)
![image2](http://s18.postimg.org/6r1ekuxzt/landscape.png)

**Comment by xypaul** [comment]
This is a big problem. Any suggestions would be appreciated.

**Comment by szimek** [comment]
This issue has been raised quite often - resizing canvas causes it to be cleared and I think there's no way around it. Probably the best solution is to force one of device orientations (most likely horizontal) - you could listen to orientation change event and show an overlay with some text in portrait mode. In this case you can either prevent canvas from resizing at all, or save image data, resize the canvas and load image data back into the canvas.

**Comment by ramaboo** [comment]
This is the solution we use:

```
  var wrapper = document.getElementById('signature-pad')
  var canvas = wrapper.querySelector('canvas')
  var signaturePad = new SignaturePad(canvas)

  var resizeCanvas = function() {
    var ratio =  window.devicePixelRatio || 1;
    canvas.width = canvas.offsetWidth * ratio;
    canvas.height = canvas.offsetHeight * ratio;
    canvas.getContext('2d').scale(ratio, ratio);
  };

  var orientationChange = function() {
    var dataURL = signaturePad.toDataURL();
    resizeCanvas();
    signaturePad.fromDataURL(dataURL);
  };
  
  window.addEventListener('orientationchange', function () { orientationChange(); });
  orientationChange();
```

Basically we save the image data then redraw it on the canvas after resize. It's not perfect as the image gets squished a little but it works good enough for our purposes until a better solution can be found.

**Comment by dahal** [comment]
:+1: @ramaboo

**Comment by plocket** [comment]
#32 is the same problem. The problem with the above solution is that the lines may go outside of the visible canvas, hiding some of the signature. I've posted a jsfiddle with a solution that works for me. See the comment at https://github.com/szimek/signature_pad/issues/32#issuecomment-1406826837.
