### ISSUE TITLE
Signature is not shown in Galaxy Tab 3 (10.1) 

### ISSUE THREAD

**Issue by kobruleht** [szimek/signature_pad#92]
Steps to reproduce:
1. From http://developer.samsung.com/remotetestlab/rtlDeviceList.action  select
   Galaxy Tab 3 (10.1)
2.  Open tab emulation and navigate to http://szimek.github.io/signature_pad/  page
3. Draw signature.
   Observed: signature is not drawn. If device orientation is changed from context menu, signatur flashes. It is not drawn in both orientations.
   It occurs in newest tab ( Samsung SM-T535 also called Galaxy Tab 4 10.1 LTE ) also.

It may be related to scrolling. If vertical scollbar is present, vertical lines appear. If both scrollbars are present, signature is drawn. If content is zoomed by double click, signature is not drawn.

![empty](https://cloud.githubusercontent.com/assets/1274923/6493833/1ae88580-c2c6-11e4-83f7-b5cfc26cdfd4.png)

**Comment by szimek** [comment]
Could you check if there are any errors in dev tools console?

**Comment by kobruleht** [comment]
I dont know how to open devtools in samsung. In my application I have windows.onerror handler whixh posts all errors to server. This code does not post any errors. If signature is placed after document and there are no scrollbars, signature works OK. If there is vertical scrollbar, only vertical lines will appear.
I tried <body style="overflow:hidden"> but this does not remove scrollbars in samsung tab.

Demo in http://thomasjbradley.ca/lab/signature-pad/accept/
works without any issues in Samsung tab.
You can create samsung developer account and try this emulator for free by selecting tab from Android tab.
