### ISSUE TITLE
Problem while clearing canvas with zoom in Chrome after refresh

### ISSUE THREAD

**Issue by dnadeau-quatral** [szimek/signature_pad#95]
How to reproduce:
1- Go to the demo page with Chrome
2- Zoom out  a little bit (IE: 70%)
3- Refresh the page
4- Draw on the lower right corner of the canvas
5- Try to clear the canvas

You will see that not all the canvas is cleared
![bug](https://cloud.githubusercontent.com/assets/4106750/6693274/16bf8f76-cca8-11e4-8140-78e1ac0e2b32.png)

**Comment by szimek** [comment]
I've just tried following these steps (zoom out to ~70%, refresh, draw something, clear the canvas) and it seems to work for me: http://quick.as/J9J2T9Jz4

**Comment by dnadeau-quatral** [comment]
I think this is because you are on a linux OS. It is possible ? I'm using
windows.

By the way, how the signature is so smooth when you do it? Mine, even in
your demo, is really not that smooth.

Thank you ! Awesome support !

On Tue, Mar 17, 2015 at 6:18 PM, Szymon Nowak <notifications@github.com>
wrote:

> I've just tried following these steps (zoom out to ~70%, refresh, draw
> something, clear the canvas) and it seems to work for me:
> http://quick.as/J9J2T9Jz4
>
> —
> Reply to this email directly or view it on GitHub.
>



-- 

Danny Nadeau, Analyste senior
Quatral Solutions Inc.
819.575.8080 x1092 / 514 227-8090 x1092
819.432.4482 Mobile
http://www.quatral.com

**Comment by dnadeau-quatral** [comment]
Hi,

My smooth problem comes from a settings from my mouse. Now it's fixed sorry
to have bothered you with that.

But i tried today at work with a linux computer and I still have the
problem.

Here a made a video for you
http://webmshare.com/jB50W

Thanks !

On Tue, Mar 17, 2015 at 11:50 PM, Danny Nadeau <dnadeau@quatral.com> wrote:

> I think this is because you are on a linux OS. It is possible ? I'm using
> windows.
>
> By the way, how the signature is so smooth when you do it? Mine, even in
> your demo, is really not that smooth.
>
> Thank you ! Awesome support !
>
> On Tue, Mar 17, 2015 at 6:18 PM, Szymon Nowak <notifications@github.com>
> wrote:
>
>> I've just tried following these steps (zoom out to ~70%, refresh, draw
>> something, clear the canvas) and it seems to work for me:
>> http://quick.as/J9J2T9Jz4
>>
>> —
>> Reply to this email directly or view it on GitHub.
>>
>
>
>
> --
>
> Danny Nadeau, Analyste senior
> Quatral Solutions Inc.
> 819.575.8080 x1092 / 514 227-8090 x1092
> 819.432.4482 Mobile
> http://www.quatral.com
>



-- 

Danny Nadeau, Analyste senior
Quatral Solutions Inc.
819.575.8080 x1092 / 514 227-8090 x1092
819.432.4482 Mobile
http://www.quatral.com

**Comment by szimek** [comment]
I was able to reproduce it with Chrome 40 on Windows using BrowserStack. I'll take a closer looks what's wrong when I have a bit more time.

**Comment by dnadeau-quatral** [comment]
Great !

Thanks have a nice day sir !

On Wed, Mar 18, 2015 at 12:37 PM, Szymon Nowak <notifications@github.com>
wrote:

> I was able to reproduce it with Chrome 40 on Windows using BrowserStack.
> I'll take a closer looks what's wrong when I have a bit more time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/szimek/signature_pad/issues/95#issuecomment-83050180>.
>



-- 

Danny Nadeau, Analyste senior
Quatral Solutions Inc.
819.575.8080 x1092 / 514 227-8090 x1092
819.432.4482 Mobile
http://www.quatral.com

**Comment by szimek** [comment]
Figured out what's wrong, but I'm not sure what's the best way to fix it. In this code: https://github.com/szimek/signature_pad/blob/gh-pages/js/app.js#L11-L13 when you zoom out, `devicePixelRatio` can be less than 0, thus after multiplying real canvas size by this less-than-1 ratio, the result is smaller than the displayed canvas. 

You could try changing line 11 to something like:

```javascript
var ratio =  Math.max(window.devicePixelRatio || 1, 1);
```

Maybe this will help.

**Comment by dnadeau-quatral** [comment]
I just tried it and it's working. 

Do you think this will interfere with anything else ?

**Comment by dnadeau-quatral** [comment]
I just tried it and it's working.

Do you think this will interfere with anything else ?

**Comment by szimek** [comment]
To be honest I have no idea. I don't think so, but this device pixel ratio stuff is tricky. I'll update the code in the demo and we'll see if anybody complains about it :)

**Comment by dnadeau-quatral** [comment]
Good, again awesome support from you !

**Comment by szimek** [comment]
I've just pushed this fix to the demo page, so it should work fine now.

**Comment by dnadeau-quatral** [comment]
It work in the demo
