### ISSUE TITLE
Possibility of reducing the Bezier curve ?

### ISSUE THREAD

**Issue by nishantvarma** [szimek/signature_pad#97]
Can I reduce the Bezier Curve approximation as a parameter? Sometimes the signature looks like ink pen spreading a bit more than a normal ball pen would. Is it possible to make the image more sharp by reducing the curve interpolations? I changed the minWidth and maxWidth but it still needs to be more sharp.Please let me know. As an example there is this http://willowsystems.github.io/jSignature/#/demo which is more sharp.

**Comment by szimek** [comment]
I'm not really sure what you mean by sharp, but have you tried setting `minWidth` and `maxWidth` to the same value, e.g. 1?

**Comment by nishantvarma** [comment]
Thanks for the prompt response, I will keep it 1 - 1.5 that looks fine. 
Can I actually make Bezier Curve approximation optional to see how that looks like ?
I wanted to see how the real stroke is vis-a-vis the approximated one.

**Comment by szimek** [comment]
Unfortunately not. But you could probably modify `SignaturePad.prototype._drawCurve` method and remove the interpolation. It takes Bezier curve as its input, so you could simply remove the whole code there and draw a straight line between its beginning and end.

**Comment by nishantvarma** [comment]
Thanks! I will just try that just to see how it looks like.

**Comment by szimek** [comment]
@nishantvarma I'm closing this issue. If you got any more questions, please reopen it.
