### ISSUE TITLE
canvas without width/height attributes -> off-scale drawing

### ISSUE THREAD

**Issue by hujhax** [szimek/signature_pad#99]
I made a pretty simple signature_pad example:
http://hujhax.austinimprov.com/code/SimpleSig/

Whenever I draw on it, it draws about 2x out of scale, with the new lines coming in out-of-sync with the cursor position.

I assume this is to do with not explicitly setting width and height attributes on the canvas -- I can fix it by adding these lines to the constructor:

        canvas.width = canvas.offsetWidth;
        canvas.height = canvas.offsetHeight;

... but I figured it was worth checking in about this, since  the "draw 2x out of scale" thing doesn't seem like intended behavior, right?

**Comment by szimek** [comment]
Please check out the [demo page](http://szimek.github.io/signature_pad/) and its [source code](https://github.com/szimek/signature_pad/blob/gh-pages/js/app.js#L14-L17) for an example how to set size of the canvas.

**Comment by hujhax** [comment]
Excellent -- I tried adding the resizeCanvas() call to that sample, and it worked correctly.  Thanks!

Q: are there cases where a signature_pad user would ٭not٭ want this resizing behavior?

**Comment by szimek** [comment]
I have no idea :) It's not part of the library, because some users might want to handle it differently.

**Comment by hujhax** [comment]
Fair enough :) -- thanks for the info!
